### ISSUE TITLE
Does Support net.Dial() or tls.Dial() for connect to nbio server?

### ISSUE THREAD

**Issue by chowyu08** [lesismal/nbio#1]

**Comment by lesismal** [comment]
net.Dial returns a blocking Conn, we need to use RawConn and dup it to get another non-blocking fd, I don't like a dup-way because I use an array to manage fd on *nix systems, dup-way needs a double size of that array, so syscall.Connect is a little more effective.

for tcp, you can use nbio.Dial like this:

```golang
g := nbio.NewGopher(nbio.Config{})
err := g.Start()
if err != nil {
	fmt.Printf("Start failed: %v\n", err)
}
defer g.Stop()

c, err := nbio.Dial("tcp", addr)
if err != nil {
	fmt.Printf("Dial failed: %v\n", err)
}
g.AddConn(c)
```

or refer to this demo:
https://github.com/lesismal/nbio/blob/master/examples/echo/client/client.go#L45

**Comment by lesismal** [comment]
I just spent the last few days copying and rewriting std's tls to support the non-blocking framework on the server-side, which took me a lot of effort. I am on the way to support the client-side

**Comment by lesismal** [comment]
net.Dial() and net.Listener has been supported, refer to this example:

- [std-net-echo-server](https://github.com/lesismal/nbio/blob/master/examples/netstd/server/server.go)
- [std-net-echo-client](https://github.com/lesismal/nbio/blob/master/examples/netstd/client/client.go)

**Comment by lesismal** [comment]
tls client-side has been supported, If you want to customize more by yourself, refer to this example:

https://github.com/lesismal/nbio/blob/master/examples/tls/client/client.go

**Comment by lesismal** [comment]
> tls client-side support has been done.
> If you want to use tls.Dial or customize more by yourself, refer to this example:
> 
> https://github.com/lesismal/nbio/blob/master/examples/tls/client/client.go

wait, I need do more test

**Comment by lesismal** [comment]
> > tls client-side support has been done.
> > If you want to use tls.Dial or customize more by yourself, refer to this example:
> > https://github.com/lesismal/nbio/blob/master/examples/tls/client/client.go
> 
> wait, client-side needs more test

all right, there's sth wrong with TLS1.0 of my clien-side implementation, TLS1.1-1.3 seems to be ok.

**Comment by lesismal** [comment]
if you mean just use std net.Dial() or tls.Dial() to connect to nbio server but no need to manage the connections by nbio server, 
of course, that's supported.

**Comment by chowyu08** [comment]
thank you for your reply
