### ISSUE TITLE
support tls and non-tls servers and clients with the same engine/mux

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#126]
not sure if all of these together are supported at the same time or if it's better to create multiple servers/engines.

currently my server is using nbio for the tls connection and the stock go http server for the non-tls connection and gorrilla for the outbound websocket connections.

I'm wondering if it is a good idea/possible to use a single common nbio engine for all these scenarios and share the mux for for the tls and non-tls servers.

**Comment by acgreek** [comment]
Is it ideal to share the taskpool between engines running in the same app?

**Comment by lesismal** [comment]
Now we can support all of these using the same Engine:
1. tls-server
2. non-tls-server
3. tls-client
4. non-tls-client

**Comment by acgreek** [comment]
If we go with your suggested approach, I suggest we get rid of NewEngineTLS, Config. AddrsNonTLS and Config.TLSConfig. We have just NewEngine method where Conf.Addrs will be for nonTLS and AddrsTLS will remain for TLS connection

**Comment by lesismal** [comment]
Different tls addr may have different tls.Config, so I didn't use []string for AddrsTLS.

**Comment by lesismal** [comment]
I think it's better now 😄
