### ISSUE TITLE
NewServer(TLS) c.SetReadDeadline(time.Now().Add(conf.KeepaliveTime))

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#13]
at end of the OnOpen handler, you call c.SetReadDeadline(time.Now().Add(conf.KeepaliveTime)), but on the OnData handler, you commented this line out. Why did you comment it out, and should OnOpen at least be consistent with OnData

**Comment by lesismal** [comment]
When OnOpen, we need to judge whether the connection comes with data to avoid being attacked by bot/zombie connection.
When OnData, the data we received is transported by a tcp streaming, it may not be a complete application layer protocol packet. For example, an attacker sends data to us byte by byte at a long interval which is less then a keepalive period, which will also cost lots of resources of our server. Therefore, SetReadDeadline should be called again when a complete application layer protocol package is parsed, but should not be called in OnData, such as each [http request](https://github.com/lesismal/nbio/blob/master/nbhttp/processor.go#L271), or a [message of websocket](https://github.com/lesismal/nbio/blob/master/examples/websocket_1m_tls/server/server.go#L33).

**Comment by lesismal** [comment]
try this example with the newest version:

```golang
package main

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"time"

	"github.com/lesismal/nbio/nbhttp"
)

var (
	addr = "localhost:8888"
)

func server(keepaliveTime time.Duration) {
	mux := &http.ServeMux{}
	mux.HandleFunc("/echo", func(w http.ResponseWriter, r *http.Request) {
		data := r.Body.(*nbhttp.BodyReader).RawBody()
		w.Write(data)
	})

	svr := nbhttp.NewServer(nbhttp.Config{
		Network:       "tcp",
		Addrs:         []string{addr},
		KeepaliveTime: keepaliveTime,
	}, mux, nil)
	err := svr.Start()
	if err != nil {
		log.Fatalf("server start failed: %v", err)
	}
}

func client(sendInterval time.Duration) {
	conn, err := net.Dial("tcp", addr)
	if err != nil {
		log.Fatalf("client dial failed: %v", err)
	}

	go func() {
		reqData := []byte(fmt.Sprintf("POST /echo HTTP/1.1\r\nHost: %v\r\nContent-Length: 5\r\nAccept-Encoding: gzip\r\n\r\nhello", addr))
		log.Printf("client begin to write %v bytes, 1 byte per %v seconds", len(reqData), sendInterval.Seconds())
		for i, b := range reqData {
			n, err := conn.Write([]byte{b})
			if err != nil || n < 1 {
				log.Fatalf("client write failed: %v, %v", n, err)
				return
			}
			log.Println("client send:", i)
			time.Sleep(sendInterval)
		}
	}()

	resData := make([]byte, 1024)
	n, err := conn.Read(resData)
	if err != nil || string(resData[n-5:n]) != "hello" {
		log.Fatalf("client read failed: %v, %v", n, err)
	}
}

func main() {
	keepaliveTime := time.Second * 5
	sendInterval := time.Second * 3
	server(keepaliveTime)
	time.Sleep(time.Second)
	client(sendInterval)
}
```

```sh
go run ./client.go  s
2021/05/19 12:04:01.365 [INF] Gopher[NB] start listen on: ["localhost:8888"]
2021/05/19 12:04:02 client begin to write 92 bytes, 1 byte per 3 seconds
2021/05/19 12:04:02 client send: 0
2021/05/19 12:04:05 client send: 1
2021/05/19 12:04:07 client read failed: 0, EOF
```

if we SetReadDeadline [here](https://github.com/lesismal/nbio/blob/master/nbhttp/server.go#L282), the zombie connection cannot be detected and closed quickly, we got:
```sh
go run ./client.go
2021/05/19 12:04:27.966 [INF] Gopher[NB] start listen on: ["localhost:8888"]
2021/05/19 12:04:28 client begin to write 92 bytes, 1 byte per 3 seconds
2021/05/19 12:04:28 client send: 0
2021/05/19 12:04:31 client send: 1
2021/05/19 12:04:34 client send: 2
2021/05/19 12:04:37 client send: 3
2021/05/19 12:04:40 client send: 4
2021/05/19 12:04:43 client send: 5
2021/05/19 12:04:46 client send: 6
2021/05/19 12:04:49 client send: 7
...
```

**Comment by acgreek** [comment]
Same behavior, I thought about it some more and it doesn't make sense to set the Deadline after the OnData event. 

The Conn in conn_*.go Read() and Write() functions could set the deadline before either operation. 

```
type Conn struct {
    .. .
    deadlineTimeout time.Duration
}

...
func (c * Conn) Read(in []byte) (int, error) {
    if c.deadlineTimeout != 0 {
         // c.SetDeadlineTimeout(c.deadlineTimeout)
    }
}

// same for Write function 

``` 

Sorry, this sort of ruff idea if I am missing something obvious.

**Comment by lesismal** [comment]
> func (c * Conn) Read(in []byte) (int, error) {
>     if c.deadlineTimeout != 0 {
>          // c.SetDeadlineTimeout(c.deadlineTimeout)
>     }
> }

This may be not correct for async-io frameworks.
Usually, for std, net.Conn will Block on Read, if you SetReadDeadline before net.Conn.Read, the deadline is set by your application logic.
But for nbio or other async-io frameworks, poller trigger Conn.Read, it is driven by io events but not your application logic.
We should leave it to the application layer who really need to decide the deadline.

**Comment by lesismal** [comment]
> Same behavior, I thought about it some more and it doesn't make sense to set the Deadline after the OnData event.
> 
> The Conn in conn_*.go Read() and Write() functions could set the deadline before either operation.
> 
> ```
> type Conn struct {
>     .. .
>     deadlineTimeout time.Duration
> }
> 
> ...
> func (c * Conn) Read(in []byte) (int, error) {
>     if c.deadlineTimeout != 0 {
>          // c.SetDeadlineTimeout(c.deadlineTimeout)
>     }
> }
> 
> // same for Write function 
> ```
> 
> Sorry, this sort of ruff idea if I am missing something obvious.

And it's obvious that SetReadDeadline before Read for async-io frameworks can not solve the problem in my previous demo.
It's even more worse than SetReadDeadline in OnData, think about that:
there's no data sent to our server after the new connection created, then there won't be a reading event, Conn.Read will never be called.

**Comment by lesismal** [comment]
> Same behavior, I thought about it some more and it doesn't make sense to set the Deadline after the OnData event.
> 
> The Conn in conn_*.go Read() and Write() functions could set the deadline before either operation.
> 
> ```
> type Conn struct {
>     .. .
>     deadlineTimeout time.Duration
> }
> 
> ...
> func (c * Conn) Read(in []byte) (int, error) {
>     if c.deadlineTimeout != 0 {
>          // c.SetDeadlineTimeout(c.deadlineTimeout)
>     }
> }
> 
> // same for Write function 
> ```
> 
> Sorry, this sort of ruff idea if I am missing something obvious.

Of course it's correct when we do this on a blocking Conn, such as the standard library:
https://github.com/golang/go/blob/master/src/net/http/server.go#L973

Or other websocket frameworks based on std:
https://github.com/olahol/melody/blob/master/session.go#L109

Or other tcp frameworks based on std, in my arpc:
should SetReadDeadline here:
https://github.com/lesismal/arpc/blob/047173ab150a07aaab482effc168f1ee7a8286c3/handler.go#L412
and should SetWriteDeadline here:
https://github.com/lesismal/arpc/blob/047173ab150a07aaab482effc168f1ee7a8286c3/handler.go#L436

**Comment by lesismal** [comment]
The timing of this timeout should be determined by the application layer (http, 7th layer) protocol, not by the transport layer (tcp, 4th layer)
