### ISSUE TITLE
很好奇这里为什么注释掉runtime.Gosched()

### ISSUE THREAD

**Issue by wubbalubbaaa** [lesismal/nbio#142]
首先谢谢您的开源框架
在这个地方：
https://github.com/lesismal/nbio/blob/db13c52634415bdd0f8b34dc25e16e000c7742d2/poller_epoll.go#L159
我看到代码中将runtime.Gosched()注释掉了
了gnet、gev、netpoll的代码， 都做了类似的处理， 动态地改变参数msec ，并且调用runtime.Gosched()主动让出时间片
字节的开发团队认为：
“当无事件触发，调整 msec=-1 时，直接 continue 会立即再次执行 EpollWait，而由于无事件，msec=-1，当前 goroutine 会 block 并被 P 切换。但是被动切换效率较低，如果我们在 continue 前主动为 P 切换 goroutine，则可以节约时间。”
很好奇为什么作者在这里注释掉了runtime.Gosched()，有什么其他的考虑吗？
（我在2核的服务器上做了benchmark，两者没有太多区别。但是2核的实验结果可能没有多大参考价值）

**Comment by lesismal** [comment]
> 字节的开发团队认为：
> “当无事件触发，调整 msec=-1 时，直接 continue 会立即再次执行 EpollWait，而由于无事件，msec=-1，当前 goroutine 会 block 并被 P 切换。但是被动切换效率较低，如果我们在 continue 前主动为 P 切换 goroutine，则可以节约时间。”

我最初也是看到字节同学帖子里你引用的这段，然后参考加上了
但我自己环境实测发现还不如不加，所以注释掉了

> （我在2核的服务器上做了benchmark，两者没有太多区别。但是2核的实验结果可能没有多大参考价值）

其他框架、benchmark仓库号称的一些数据由于软硬件环境可能存在差异，甚至可能存在为了KPI而你懂得的操作，所以benchmark尽量以自己跑代码为准更好，不要迷信任何三方的文章，尤其国内大厂

**Comment by lesismal** [comment]
参考字节的 [kitex-benchmark](https://github.com/cloudwego/kitex-benchmark) 也做了一份cpu带消耗的网络库压测，有兴趣可以对比下：
https://github.com/lesismal/go-net-benchmark

我的环境下nbio和gnet的性能在一个水平线，跑测试的先后顺序、两个框架各自测试时当时的系统运行差别可能细微差异对二者数据高低带来一些影响，但数据差距极小，其他框架的差距则较大：
https://github.com/lesismal/go-net-benchmark/issues/1

有兴趣可以在您自己的环境下实测下试试

**Comment by lesismal** [comment]
仔细想下，字节同学测试数据中得到的优势可能是特定压测场景下的其他协程（比如逻辑协程或者其他poller协程）优先被调度，而整个进程很多协程、调度顺序和优先级其实是个混沌系统，让其它优先、让本协成稍微慢一下下再EpollWait带来的提升可能也是玄学成分或者他们特定压测场景下导致的，但肉眼可见的是这里不管加不加runtime.Gosched()，都会继续执行EpollWait被动切换，加上反倒多浪费一下这个runtime.Gosched()的执行开销

不排除字节同学这样做在他们环境下确实能获得提升，因为我印象中他们之前的文章里还提到过他们内核部门提供了内核优化补丁。
但至少目前，这样做的优势没有在我自己环境中得到证实

**Comment by wubbalubbaaa** [comment]
谢谢回复🙌
