### ISSUE TITLE
compress after enable, not worked

### ISSUE THREAD

**Issue by rizzi37** [lesismal/nbio#143]
thanks for your work~

```
c.SetCompressionLevel(9)
c.EnableWriteCompression(true)
c.WriteMessage(messageType, data)
```

**Comment by lesismal** [comment]
Thanks for your feedback!
Please make sure both the server-side and the client-side have enabled compress, or provide me your full example code that can reproduce it will be better.

**Comment by rizzi37** [comment]
find,  i get it.

the last question, how can i send a close event ? use 4000~ 4999.

**Comment by lesismal** [comment]
try this:
```golang
var code uint16 = 5000
var codeBytes = make([]byte, 2)
binary.BigEndian.PutUint16(codeBytes, code)
c.WriteMessage(CloseMessage, codeBytes)
```

**Comment by rizzi37** [comment]
aha ~ some like make a protocol ~ thanks lot @lesismal

**Comment by lesismal** [comment]
> aha ~ some like make a protocol ~ thanks lot @lesismal

You are welcome!

**Comment by rizzi37** [comment]
the server has been success compress and write 

but chrome debugger still raw length by everyone frame ? 

the chrome has been auto decompress ? 

this is right ?

- server use websocket keeplive example code
- 

### header
```
map[Connection:[Upgrade] Host:[localhost:8888] Sec-Websocket-Extensions:[permessage-deflate; client_max_window_bits] Sec-Websocket-Key:[9pVw0mBa3XbI3hcb6VTNuQ==] Sec-Websocket-Version:[13] Upgrade:[websocket]]
```
### server: compressed data length
```
len(buf) 23488
```
### chrome client: the chrome monitor one frame 
```
length: 300000


```

**Comment by lesismal** [comment]
Do you mean that when your server sends (the 4th layer) 300000(which is compressed to 23488) bytes to chrome client, the client see 300000?

You application(the 7th layer) is  receiving the websocket body, so you should see the original length before compression.

If you want to see the compressed buffer size, you should debug the code around here:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L148

Or you can use wirshark/tcpdump to check the compressed payload in the 4th layer.
