### ISSUE TITLE
Why does nbio need to lock while reading and writing

### ISSUE THREAD

**Issue by wubbalubbaaa** [lesismal/nbio#144]
https://github.com/lesismal/nbio/blob/db13c52634415bdd0f8b34dc25e16e000c7742d2/conn_unix.go#L59
I think for one connetion, it  always works  in only one loop (one goroutine) after being put into epoll

**Comment by lesismal** [comment]
### First
Here is some comment:
https://github.com/lesismal/nbio/blob/db13c52634415bdd0f8b34dc25e16e000c7742d2/conn_unix.go#L58

The mutex can promise the Conn's state if there are concurrent Read/Write/Close.
Imagine:
```text
1. Conn A hold fd 1000;
2. Conn A enter Conn.Read but have not call syscall.Read
3. Conn A is closed by other goroutine
4. A new Conn B established and reuse fd 1000;
5. Conn A call syscall.Read which would steal Conn B's data
```

### Second
nbio use epoll LT by default which must be implemented to a `reactor`, that means we need to read all the data during each poller loop;
But nbio also supports the ET mod which can be used by the application layer to implement `proactor`, which means it would be decided by the application layer that when they `Read`, it's better to guarantee the concurrency of the state of Conn.

### Third
Mutex.Lock/Unlock cost only some atomic operations for most of the time, that's not too much cost and will not affect performance too much:
https://github.com/golang/go/blob/master/src/sync/mutex.go#74
https://github.com/golang/go/blob/master/src/sync/mutex.go#210

**Comment by lesismal** [comment]
Unlike other frameworks, nbio supports concurrency Read/Write/Close, which makes it more convenient for users.

**Comment by lesismal** [comment]
go encourage people to serialize operations by chan+goroutine, but that means single logic goroutine which may lead to low performance.
We should not limit user's design style, so nbio supports concurrent Write/Close.

Another thing, std also use lock for fd:
https://github.com/golang/go/blob/master/src/internal/poll/fd_unix.go#L370
...

**Comment by lesismal** [comment]
And you can compare with other frameworks which do not support concurrent Write/Close, it's really hard to use for some complex businesses such as game services, IM, maybe pushing systems, the users must wrap their code carefully.

**Comment by wubbalubbaaa** [comment]
thanks

**Comment by robertplanty** [comment]
> But nbio also supports the ET mod which can be used by the application layer to implement proactor, which means it would be decided by the application layer that when they Read, it's better to guarantee the concurrency of the state of Conn.

请问一下在nbio中如何配置为ET呢? 在文档和代码中没有找到相关的内容, 期待回复! 谢谢~

**Comment by lesismal** [comment]
> > But nbio also supports the ET mod which can be used by the application layer to implement proactor, which means it would be decided by the application layer that when they Read, it's better to guarantee the concurrency of the state of Conn.
> 
> 请问一下在nbio中如何配置为ET呢? 在文档和代码中没有找到相关的内容, 期待回复! 谢谢~

```golang
g := nbio.NewGopher(nbio.Config{
	Network:  "tcp",
	Addrs:    []string{":8888"},
	EpollMod: nbio.EPOLLET,
})
```

之前压测了下吞吐量，ET比LT略慢，某些场景可能需要ET，比如实现proactor，xtaci的gaio用的就是ET。

因为nbio的实现中LT略快，所以nbhttp里使用的仍然是LT并且没有导出为可配置的项。基于nbio.Gopher的其他自实现7层协议可以选择使用ET（因为我自己没用ET，所以只是进行了一些压测，没有做更全的测试，如果遇到bug，请issue给我）。

另外，可能是由于ET/LT的名字差别，导致很多人对于ET/LT性能存在误解，很多人以为ET比LT快，但实践对比中应该是得不出这个结论，通常情况两者应该是差不多的，如果我没记错的话，redis、skynet之类的用的也都是LT，陈硕在muduo的书中也说到过这些

**Comment by lesismal** [comment]
还需要补充一点，为了用户使用简单，nbio默认是直接把数据丢给用户的，而不是只丢事件给，ET模式下，需要框架层确保每次读完（设置循环读取次数无限大），所以每次可读都会读完本次数据：
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L145
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L182

如果需要自己订阅读事件自行定制读取方式，可以设置读方法：
```golang
g.OnRead(func(c *nbio.Conn) {
	/// ...
})
```

然后读取时就会用你设置的方法：
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L203

**Comment by robertplanty** [comment]
谢谢回复。
> xtaci的gaio用的就是ET。

可否问个基础问题😂我也有看到过xtaci写的gaio, 他在[知乎](https://zhuanlan.zhihu.com/p/102890337)上提到用ET的一大原因是ET可以不一次性全部读完底层buffer数据，利用TCP的流量控制将压力反向传到到客户端。
但是我注意到像nbio这种使用LT的reactor模型，每个连接在一个eventloop里串行读取和处理数据，也不需要一次性读完buffer。这是否也可以实现xtaci提到的“压力反向传导给发送端”呢？
谢谢您百忙中的回复！

**Comment by lesismal** [comment]
> 

xtaci可能是因为做kcp相关时，对流控各种考虑的比较多，因为kcp需要自己实现一套拥塞控制、流控调度相关的。

但在更多的非类传输层基础设施的、7层应用业务场景里，他提到的那种流控是没必要的，比如你做应用服务器，通常都是需要读完。应用层的流控，基本也只是限流，这个不管ET还是LT都可以做到，比如 g.OnRead 里，你可以统计流量，如果超过限流阈值直接close了，或者其他类似的统计、限制、控制逻辑。

另外话又说回来，xtaci说的反向传导，必要性也不大，因为不是尽早读取并且要多加一层反向传导的逻辑，本身也是对性能的一点损失。而且，什么时候去读、怎么去实现反向传导？又是一个复杂的事情，实现复杂度和性能损失都不划算，反向传导带来的提升，甚至无法弥补增加的成本损失。所以我之前压测gaio，相同的poller协程数，性能要比nbio、gnet差一档。即使是kcp-go类似的基础设施类场景，也是要追求性能的，proactor这个损失，目测gaio无法弥补回来

**Comment by lesismal** [comment]
> 但是我注意到像nbio这种使用LT的reactor模型，每个连接在一个eventloop里串行读取和处理数据，也不需要一次性读完buffer。这是否也可以实现xtaci提到的“压力反向传导给发送端”呢？

LT实现不了proactor，这个之前xtaci开始写gaio的时候就考虑到了并且大家聊过，因为LT你本次不读完，会一直可读并触发epoll循环，太浪费cpu了

**Comment by robertplanty** [comment]
了解了， 感谢❤
