### ISSUE TITLE
Can't get around race condition

### ISSUE THREAD

**Issue by Rambatino** [lesismal/nbio#149]
Hey, so this is in reference to this comment here:  https://github.com/lesismal/nbio/issues/145#issuecomment-985904989

I appreciate that it's a safe race condition as the pollers are indexed on the `fd` int, however, I'm unable to unit test because the race condition is derived entirely within the library. A slightly longer stack trace:

``` go
==================
==================
WARNING: DATA RACE
Read at 0x00c001188088 by goroutine 15:
  github.com/lesismal/nbio.(*poller).getConn()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/poller_epoll.go:73 +0x3ad
  github.com/lesismal/nbio.(*poller).readWriteLoop()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/poller_epoll.go:169 +0x34f
  github.com/lesismal/nbio.(*poller).start()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/poller_epoll.go:101 +0x489
  github.com/lesismal/nbio.(*Gopher).Start·dwrap·9()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/gopher_unix.go:54 +0x39

Previous write at 0x00c001188088 by goroutine 13:
  github.com/lesismal/nbio.(*poller).addConn()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/poller_epoll.go:62 +0x194
  github.com/lesismal/nbio.(*Gopher).AddConn()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/gopher.go:173 +0x104
  github.com/lesismal/nbio/nbhttp.(*Engine).AddConnNonTLS()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/nbhttp/engine.go:521 +0x56d
  github.com/lesismal/nbio/nbhttp.(*Engine).startListeners.func2()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/nbhttp/engine.go:305 +0x226

Goroutine 15 (running) created at:
  github.com/lesismal/nbio.(*Gopher).Start()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/gopher_unix.go:54 +0x28f
  github.com/lesismal/nbio/nbhttp.(*Engine).Start() <---------------------------#######################
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/nbhttp/engine.go:337 +0x71
  main.main()
      /usr/src/project/main.go:38 +0x184

Goroutine 13 (running) created at:
  github.com/lesismal/nbio/nbhttp.(*Engine).startListeners()
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/nbhttp/engine.go:297 +0x4bb
  github.com/lesismal/nbio/nbhttp.(*Engine).Start() <---------------------------########################
      /go/pkg/mod/github.com/lesismal/nbio@v1.2.8/nbhttp/engine.go:332 +0x30
  main.main()
      /usr/src/project/main.go:38 +0x184
==================
==================
```

An example of this occuring is when running the code from the previous example in docker.

``` bash
docker run -it -v ${PWD}:/usr/src/project golang:latest /bin/bash;
root@00f24d63eb03:/usr/src/project# cd /usr/src/project
root@00f24d63eb03:/usr/src/project# go run -race main.go
```

If you don't think the internals of the library should change to accommodate, is there a way round it in the unit test when running in a unix environment (apart from turning race off)?

**Comment by lesismal** [comment]
We can't avoid this race warning(g.connsUnix and g.pollers) unless we add some Mutex operations, but that means a waste of a performance.

There's a way that I think it can avoid this race condition, we support users to set the handlers to manage g.pollers and g.conns, and provide default handlers with the current implementation. Then in your unit test, you can custom the handlers with mutex for getPoller(idx)/setPoller(idx, poller) and getConn(fd)/setConn(fd, conn), but I think it's ugly:joy:

**Comment by Rambatino** [comment]
One last query though, is, why is it that this issue only happens on poller_epoll.go (inside docker) and not poller_kqueue.go (on a mac)? The code paths look very similar.

I've kinda struggled to get it passing inside docker and given we use -race on our sbx environments I can't see us being able to utilise this library properly :(

**Comment by lesismal** [comment]
It's not ` only happens on poller_epoll.go`, if you make some load test, it should easilly happen when there are concurrent operations on `g.connsUnix`(both `poller_epoll.go` and `poller_kqueue.go`)

**Comment by Rambatino** [comment]
Ahh okay thanks for the clarification @lesismal :)
