### ISSUE TITLE
支持kcp

### ISSUE THREAD

**Issue by symsimmy** [lesismal/nbio#150]
对延迟敏感的领域，使用RDUP比较多，其中应用较为广泛的是kcp，目前有一个go版本的实现，kcp-go：https://github.com/xtaci/kcp-go，想请问nbio如果需要支持kcp的话，方便么

**Comment by lesismal** [comment]
我之前有考虑过支持更多协议，比如 http2.0 http3.0/quic 以及 kcp，但：
http2.0 太渣了，单就接口类数据交互，ws足够了，对于文件服务，http2.0单链接在吞吐量大、链接不稳定比如丢包和窗口拥塞时，反倒不如1.x多个链接的表现，所以不打算支持http2.0

对于http3.0/quic 和 kcp 是基于 udp 的。
因为 go 的 udp 用起来非常简单，额外封装 poller 去支持 udp 相比于直接使用标准库反倒不够优雅、以及可能带来性能下降，需要 poller 的主要是基于 tcp 的领域，而且为了用户友好，nbio 提供了 OnOpen/OnClose 之类的各种包括但不限于 tcp 连接生命周期以及各种参数定制的便利性，所以其实 nbio 默认是没有支持 udp 的。

kcp-go 很棒，但一个痛点也是每个连接需要一个或多个协程，在高并发的场景内存、gc、调度开销不友好，但对于非海量并发的场景，这些开销不会达到阈值、硬件成本也可以接受，而且基于标准库其实数据传递过程中的内存局部亲和性、调度亲和性也都更友好、性能通常更好一些，反而是异步解析的亲和性低、逻辑复杂，所以在并发数量没超过阈值时性能不如标准库方式。

对于 kcp ，使用标准库也是可以做到可控的协程数量的，我之前有给傅大的 kcp-go 提过: 
https://github.com/xtaci/kcp-go/issues/201
这种方式来改造应该是最佳实践，但改造成本也是较大，傅大也未必有那么多时间。
我没有自己去改造或者PR的一个原因是这些可靠协议本身也相对复杂，一些细微的参数对性能的影响较大，现阶段我自己没有那么多精力去做。

**Comment by symsimmy** [comment]
了解了，感谢回复
