### ISSUE TITLE
请问这个组包得自己在OnData里面实现吗？

### ISSUE THREAD

**Issue by 1514louluo** [lesismal/nbio#151]

**Comment by lesismal** [comment]
对，网络库的部分只是4层数据的处理，除了nbhttp里的http和websocket，其他7层是用户自己的协议格式，只能用户自己处理

**Comment by 1514louluo** [comment]
ok，了解了。另外conn结构体里面的readbuf和writebuf，是否可以考虑使用ringbuffer？还有定时器可否可同时支持时间轮？ 😊😊

**Comment by 1514louluo** [comment]
dup新的fd加入事件驱动，复用net.conn思路很棒~~ tls的支持太重要了 并且客户端也支持事件驱动 👍

**Comment by lesismal** [comment]
> 

1. readbuf: conn_unix应该是已经不再使用readbuf了，这个过得有点久、记不清了，好像是一些中间版本的tls readbuf直接用的conn的这个、或者conn std有用到、为了兼容所以conn unix也带上了这个字段，搜了下最新的代码、最新的版本应该是不需要这个字段了但是暂时也没删掉，多一个字段即使百万在线内存影响也不大，后面版本我再看看，如果没问题conn unix也去掉它

2. writebuf: ring buf 并不是最优解。conn.Write 是直接syscall.Write的，失败了需要等待可写事件的情况才会把数据append到 write buf上，这个buf，在可写时、flush后会释放掉，这样才会整体内存占用最小。如果每个 conn 都自带 ring buf 并且持续持有，比如百万在线，百万个连接持有百万个 ring buf，这个内存占用量也是非常惊人的

数据结构要根据使用场景是否合理来做选择，我有看到其他一些库用了ring buf，但在海量并发场景（比如我这里解释到的）其实可能反倒拖后腿，所以不要只是看上去很美，要实践确实有用才行 😄 

3. 定时器: 最早的版本本身就是用时间轮的，根据读写的超时时间作为epoll wait的timeout参数，https://github.com/lesismal/nbio/commit/08fab465b597141a2e71089ce2fcd753ebbf1257。但实测下来效果并不划算，时间轮精度低、为了尽量让timeout触发准确，tick 间隔则应该小，配合poller时如果当前服务不活跃则空转相对浪费、时有cpu毛刺，如果tick间隔大了又太不精确。定时器领域小堆基本是最优解，而且log2N即使百万个元素一次fix操作成本也不，而且对于网络库读写超时的场景，通常是timeout参数固定、当前新增定时器的timeout基本就是最大值、不需要爬到堆顶，所以效率也是足够高了。标准库的time.AfterFunc超时触发时会在一个新的协程中进行回调，这个不太划算，所以nbio.Gopher里是自带一个协程来管理定时器。当然，如果场景需要更加自习定制时间轮性能，用户也可以不调用nbio.Conn的SetDeadline、而是自行管理比如用粗粒度的时间轮或者其他方案

**Comment by lesismal** [comment]
> dup新的fd加入事件驱动，复用net.conn思路很棒~~ tls的支持太重要了 并且客户端也支持事件驱动 👍

dup主要参考自 xtaci 的 [gaio](https://github.com/xtaci/gaio)

其实早期还是直接 syscall.Accept 的，直接 syscall.Accept 性能更好一点点。后来为了兼容直接把 std net.Conn 加入到 nbio.Gopher 来管理，所以也像 gaio 一样使用了 rawconn dup 的方案，这样用户很方便就能把 [net.Listen](https://github.com/lesismal/nbio-examples/blob/master/netstd/server/server.go) / [net.Dial](https://github.com/lesismal/nbio-examples/blob/master/netstd/client/client.go) 得到的 net.Conn 拿来放到 nbio 中使用，也为后来的 tls.Conn 相关的提供了不少便利
