### ISSUE TITLE
链接过早关闭，导致写入数据没有发送

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/nbio#155]
当前是把连接发送到另外的携程处理的，当调用write方法写入数据，并且同时调用close关闭连接时，数据并没有发送出去，有什么解决方法？

**Comment by lesismal** [comment]
如果close先于write，都关闭了确实不能再发。

如果是明确先write后close的（先后是指不管是在哪些协程，syscall或者nbio方法的先后时许），请提供下完整代码我看下

**Comment by lesismal** [comment]
是A协程close，B协程里write?

比如你的游戏服务器里，一个模块B的协程在给这个连接发消息，其他设备登录时登录模块A的协程把它关闭了，这时候B的Write就失败了

这种情况即使是std net.Conn也没法保证，而是需要框架或者业务上保证幂等性（如果需要）。go的指令没有c/cpp那么快，游戏服务器逻辑单协程的话高在线量就扛不住了，所以支持高并发高性能的go服务器仍然需要逻辑多协成，多协程也有很多不同的组合方式，但是想保证单个连接的完美close after write都是件难事，因为如果业务需要、则不通的协程随时都可能有write、框架本身无法限制业务，除非是业务固定，可以考虑把close串行化到所有wirte之后
从更高的协议层次考虑，即使syscall.Write成功，也只是写入内核缓冲区，之后的数据也不能保证送达，比如你close之前对方已经close只是你尚未收到FIN，甚至对方是掉电关机，或者网络链路不稳定导致数据不可达。
所以对于想保证完美时序、送达，其实是一件吃力不讨好的事情，往往成本大于收益。在业务层来考虑，如何保证断线以及断线重连等情况下的数据一致性与数据同步，才是真正必要的，有了业务交互上的一致性保证，不管是7层协议的Write失败、还是４层及以下的网络不可达，都不需要做额外的过多处理了

**Comment by lesismal** [comment]
如果只是相对简单的场景，可以把代码发出来看下，最简单的方式是应用层封装个：
```golang
func WriteWith(c *Conn, data []byte, f func()) {
    c.Write(data) // 如果刚好缓冲区满等情况，本次调用仍然无法完全写入，而是挂到c的buffer上，加入可写时间到epoll fd，异步等待可写时再写。抛开缓冲区满之类的，能保证绝大多数情况这句Write写入内核缓冲区
    f()
}
```

然后在write的协成里：
```golang
Write(c, data, func() {
    c.Close()
}
```

**Comment by liangmanlin** [comment]
是我搞错了，不过有宁外一个问题探讨，另外开一个issues
