### ISSUE TITLE
高频连接断开性能不佳

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/nbio#157]
使用apache的压测短连接请求，发现单线程瓶颈严重，是否可以给出选项，进行多线程accept

另外，nbio.Conn的读写锁是否可以分离，目前看是没有必要使用同一锁的，求教

**Comment by lesismal** [comment]
> 使用apache的压测短连接请求，发现单线程瓶颈严重，是否可以给出选项，进行多线程accept

有没有对比标准库、其他库？nbio的accept协程只是多做了一点std conn的转换，对于正常业务应该是足够用了，而且对于单个ip:port，即使是c/cpp netty那些，也是只有一个线程用于accept的。我刚看到accpet RawConn转换里的SetNonBlock倒是可以去掉，这个我提交下，但是这个对整体性能提升应该是不会太明显的。

另外还要对比下内核参数、瓶颈具体是指什么现象，比如大量timewait导致建连失败？或者压的频率太高backlog之类的也堵了？

> 另外，nbio.Conn的读写锁是否可以分离，目前看是没有必要使用同一锁的，求教
没必要，rwmutext比mutex代码指令更多些，并发竞争大时读写锁才有优势，对于单个非阻塞连接，触发竞争的时候应该是极少的，读写锁性能反倒浪费一点

**Comment by liangmanlin** [comment]
> 

比标准库慢一点点，不多，标准库也是单线程，所以想探讨，能不能多线程accept

> 没必要，rwmutext比mutex代码指令更多些，并发竞争大时读写锁才有优势，对于单个非阻塞连接，触发竞争的时候应该是极少的，读写锁性能反倒浪费一点

我的意思是，读写并不需要使用同一个锁，目前看是仅仅读取一个close标记，可以分离2个锁

http不会有锁冲突，因为肯定是先读后写

**Comment by lesismal** [comment]
SetNonblock 去掉了，省个syscall，可以试下这个，但是也不会快太多
https://github.com/lesismal/nbio/commit/cb5cd8a72ccddedd3ff2d65347828ef11c26d088

```sh
go get -u github.com/lesismal/nbio@cb5cd8a72ccddedd3ff2d65347828ef11c26d088
```

**Comment by lesismal** [comment]
> 我的意思是，读写并不需要使用同一个锁，目前看是仅仅读取一个close标记，可以分离2个锁
> 

用同一把锁是为了锁状态，如果已经close了，再去读，涉及到fd复用、窜号

> http不会有锁冲突，因为肯定是先读后写

读和写是不同协程，http1.1后支持pipeline，所以读和写还是有并发竞争的可能性，只是因为nonblocking，触发竞争竞争、冲突的情况很低、基本可以忽略

**Comment by lesismal** [comment]
读和写用锁，之前有人问过：
https://github.com/lesismal/nbio/issues/144

并且，如果按你说的这种用不同的锁，就相当于读不加锁了，是不行的

**Comment by liangmanlin** [comment]
> SetNonblock 去掉了，省个syscall，可以试下这个，但是也不会快太多 [cb5cd8a](https://github.com/lesismal/nbio/commit/cb5cd8a72ccddedd3ff2d65347828ef11c26d088)

> go get -u github.com/lesismal/nbio@cb5cd8a72ccddedd3ff2d65347828ef11c26d088

没有太多变化，大概4k次连接断开每秒

**Comment by liangmanlin** [comment]
> 用同一把锁是为了锁状态，如果已经close了，再去读，涉及到fd复用、窜号

这里是不是可以使用原子操作，因为真正读取的时候是没有锁的

**Comment by lesismal** [comment]
> 太多变化，大概4k次连接断开

正常业务的话足够了。而且纯短链接的请求应该没那么多，多数都keepalive。我这单机压下是5k以上

实在需要的话，反代多个端口（每个端口是一个listener协程，我压了下一秒能处理几万次）

**Comment by lesismal** [comment]
nbio的设计是给用户足够的自定制、扩展性，框架自己本身尽量减少三方依赖，如果还是特别想多协程listener，就用自己的listener吧：

```golang
package main

import (
	"fmt"
	"log"

	"github.com/lesismal/nbio"
	"github.com/libp2p/go-reuseport"
)

// func onData(c *nbio.Conn, data []byte) {
// 	c.Write(append([]byte{}, data...))
// }

func main() {
	g := nbio.NewGopher(nbio.Config{
		Network: "tcp",
		// Addrs:    []string{"localhost:8888"},
		EpollMod: nbio.EPOLLET,
	})

	for i := 0; i < 3; i++ {
		go func(idx int) {
			ln, err := reuseport.Listen("tcp", "localhost:8888")
			if err != nil {
				log.Fatal(err)
			}

			for {
				conn, err := ln.Accept()
				if err != nil {
					log.Println(err)
					return
				}
				g.AddConn(conn)
				// println("-- accept from listener", idx)
			}
		}(i)
	}

	// g.OnData(onData)
	g.OnRead(func(c *nbio.Conn) {
		buf := make([]byte, 1024)
		n, err := c.Read(buf)
		if err != nil {
			return
		}
		c.Write(buf[:n])
	})
	err := g.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}

	g.Wait()
}
```

**Comment by liangmanlin** [comment]
> nbio的设计是给用户足够的自定制、扩展性，框架自己本身尽量减少三方依赖，如果还是特别想多协程listener，就用自己的listener吧：
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 
> 	"github.com/lesismal/nbio"
> 	"github.com/libp2p/go-reuseport"
> )
> 
> func main() {
> 	g := nbio.NewGopher(nbio.Config{
> 		Network: "tcp",
> 		// Addrs:    []string{"localhost:8888"},
> 		EpollMod: nbio.EPOLLET,
> 	})
> 
> 	for i := 0; i < 3; i++ {
> 		go func(idx int) {
> 			ln, err := reuseport.Listen("tcp", "localhost:8888")
> 			if err != nil {
> 				log.Fatal(err)
> 			}
> 
> 			for {
> 				conn, err := ln.Accept()
> 				if err != nil {
> 					log.Println(err)
> 					return
> 				}
> 				g.AddConn(conn)
> 				// fmt.Printf("-- accept from listener[%v]\n", idx)
> 			}
> 		}(i)
> 	}
> 
> 	g.OnData(func(c *nbio.Conn, data []byte) {
> 		c.Write(append([]byte{}, data...))
> 	})
> 
> 	err := g.Start()
> 	if err != nil {
> 		fmt.Printf("nbio.Start failed: %v\n", err)
> 		return
> 	}
> 
> 	g.Wait()
> }

原来还可以这样操作，学习了

**Comment by lesismal** [comment]
> 

嗯呢，我俩主要项目（另一个arpc）都是很少依赖、核心基本只依赖标准库，剩下的都是可以用第三方各种扩展。。。
不像其他几个同类项目用着那么受限。。。

**Comment by lesismal** [comment]
别的poller库不支持的东西太多了，比如windows、并发写、tls、http1.x、websocket......
相比之下，nbio支持的功能有点多，epoll ET/ET也是都支持、可配置......

**Comment by liangmanlin** [comment]
是的，对比了gnet，我最后还是决定使用你的库从新开发一个httpd库，主要解决http handler的阻塞问题，基本是重复造轮子，当做学习

**Comment by lesismal** [comment]
我这个已经支持http相关的了、兼容标准库，自己开发的话，内存优化需要特别注意下
