### ISSUE TITLE
调用Gopher.Stop()时，OnClose回调没有执行

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/nbio#159]
调用Gopher.Stop()时，OnClose回调没有执行

**Comment by lesismal** [comment]
需要补充一下，https://github.com/lesismal/nbio/commit/2b860cf0cf0b0f4a903ab60ab33c1ebb2fdce7cb 的提交并不是一个强保证，没有对每个conn做wg.Add/Done相关、没有wg.Wait每个连接的onclose调用，可以做、但是没必要，原因如下：

1. 因为4层只负责数据传输、无法感知7层的业务、主动close所有conn时不能确保连接对于业务层的优雅退出，优雅退出应由应用层尽量保证
2. 需要对conn进行管理时，通常业务层也需要有自己的conn管理器，当应用层主动调用Gopher.Stop是明确知道这个时机并且可以自行对conn管理器进行相关处理的

**Comment by lesismal** [comment]
另外，7层的优雅退出，也都只是尽量保证，无法做到100%优雅，比如http pipeline的在途数据尚未抵达server就被关闭了，client端已经发出的调用仍然会失败，每一个层尽量保证自己层的服务就可以了

**Comment by lesismal** [comment]
提交了个新的，增加了每个conn的追踪，Stop时等待每个连接的onclose调用，但这里涉及较多的并发、时序一致性，需要多些测试再发布下个版本，临时版本可以先用着看看：https://github.com/lesismal/nbio/commit/a1a08d04dc84acc87b1ca93ed4b2f060a4a06b2d

```golang
go get -u github.com/lesismal/nbio@a1a08d04dc84acc87b1ca93ed4b2f060a4a06b2d
```

**Comment by liangmanlin** [comment]
好的，我先试试

**Comment by liangmanlin** [comment]
> 需要补充一下，[2b860cf](https://github.com/lesismal/nbio/commit/2b860cf0cf0b0f4a903ab60ab33c1ebb2fdce7cb) 的提交并不是一个强保证（只是sleep了200ms等待onclose被调用，仍可能没等到被调用Stop就返回了），没有对每个conn做wg.Add/Done相关、没有wg.Wait每个连接的onclose调用，可以做、但是没必要，原因如下：
> 
> 1. 因为4层只负责数据传输、无法感知7层的业务、主动close所有conn时不能确保连接对于业务层的优雅退出，优雅退出应由应用层尽量保证
> 2. 需要对conn进行管理时，通常业务层也需要有自己的conn管理器，当应用层主动调用Gopher.Stop是明确知道这个时机并且可以自行对conn管理器进行相关处理的

我是做websocket的时候发现的，理论上确实可以我自己先退出连接携程，再调用stop进行关闭，但是只有多少有一点点不顺手

**Comment by lesismal** [comment]
简单压测了些，暂时没遇到问题，以防万一，刚提交新增了Gopher.Shutdown()确保context超时或者取消后即使关闭遇到问题也能退出，可以试下最新版本。
原来的http server也有Shutdown但是没有包含等待每个连接退出的逻辑，业务服务尽量使用nbhttp.Server/Engine的Shutdown()、非http/ws用Gopher.Shutdown()进行优雅退出

如果应用层关闭server时就是程序退出，Shutdown就行了，如果程序不退出、继续执行其他逻辑，为了以防万一，应用层尽量在调用nbio相关的Stop/Shutdown之外自己处理每个连接来确保一致
