### ISSUE TITLE
请教一下为什么这里要复制一下fd然后再把原来的关闭掉

### ISSUE THREAD

**Issue by robertplanty** [lesismal/nbio#160]
https://github.com/lesismal/nbio/blob/a1a08d04dc84acc87b1ca93ed4b2f060a4a06b2d/net_unix.go#L30

为什么不直接使用这个fd呢?
```go
// 类似这样
errCtrl := rc.Control(func(fd uintptr) {
		newFd = int(fd)
	})
```
请问一下这样会有什么问题吗? 谢谢您

**Comment by lesismal** [comment]
调用 Control 获得的 syscall.RawConn 后不保障该文件描述符继续可用： https://github.com/golang/go/blob/master/src/syscall/net.go#L9

**Comment by lesismal** [comment]
TCPConn 的具体实现中：
https://github.com/golang/go/blob/master/src/net/tcpsock.go#L122
https://github.com/golang/go/blob/a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646/src/net/rawconn.go#L63
https://github.com/golang/go/blob/a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646/src/net/rawconn.go#L21
https://github.com/golang/go/blob/a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646/src/net/fd_posix.go#L18

回调 rawconn.Control传入的函数参数
https://github.com/golang/go/blob/a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646/src/internal/poll/fd_posix.go#L61 

defer时会destroy这个fd，所以后续不再可用：
https://github.com/golang/go/blob/a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646/src/internal/poll/fd_posix.go#L60 
https://github.com/golang/go/blob/a064a4f29a97a4fc7398d1ac9d7c53c5ba0bc646/src/internal/poll/fd_mutex.go#L213

用户获取RawConn本身就相当于接管fd，为了不泄露fd，用户获取的过程中回调用户传入的函数、而获取过程结束后就销毁了原来的fd，所以需要dup。
这与 http 的 Hijack 是类似的，用户接管了conn（比如websocket），则原来的read loop就退出了、不再继续原来的http解析：
https://github.com/golang/go/blob/master/src/net/http/server.go#L1969

**Comment by robertplanty** [comment]
谢谢您的耐心解答❤

**Comment by zhu121** [comment]
请问下，这边如果用unix.Socket()得到listen fd，用unix.Accept()得到连接fd，还需要dup处理吗

**Comment by lesismal** [comment]
> 请问下，这边如果用unix.Socket()得到listen fd，用unix.Accept()得到连接fd，还需要dup处理吗

标准库的Listner得到的net.Conn因为该fd已经由runtime的epoll管理了，没法从runtime epoll那切换到新的epoll，所以通过dup的方式。
用unix.Accept、syscall.Accept的方式应该是不需要dup的

**Comment by zhu121** [comment]
> > 请问下，这边如果用unix.Socket()得到listen fd，用unix.Accept()得到连接fd，还需要dup处理吗
> 
> 标准库的Listner得到的net.Conn因为该fd已经由runtime的epoll管理了，没法从runtime epoll那切换到新的epoll，所以通过dup的方式。 用unix.Accept、syscall.Accept的方式应该是不需要dup的

谢谢！
