### ISSUE TITLE
对端关闭时，会触发OnRead回调

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/nbio#161]
使用ET模式进行阻塞Read封装，发现在对端关闭时，也会触发一次可读，n=0,err=nil

实际测试，LT模式也一样

**Comment by lesismal** [comment]
试下最新：
https://github.com/lesismal/nbio/commit/36b68811404be1079ef7143ac25bce819f7cd85d

**Comment by liangmanlin** [comment]
ok了
