### ISSUE TITLE
有计划增加一些源码、框架解析的文档么？

### ISSUE THREAD

**Issue by betNevS** [lesismal/nbio#163]
项目的代码写的很好，但是感觉注释和解析的文档较少，希望作者能增加一些文档~

**Comment by lesismal** [comment]
感谢关注和支持！

一直琢磨这事，但是异步和内存优化相关的稍微有点复杂、比c/cpp那种还要复杂一些，不太容易解释清楚。如果以后有档期，我尽量写一些wiki，大致分几块：poller部分，异步流解析的部分（tls/http/websocket），内存池（与标准库一些模块或者fasthttp那种有区别），定制的协程池（跟传统的c/cpp逻辑线程池有区别，跟标准库或者fasthttp那种仍旧每个连接一个协程也不同）

**Comment by liangmanlin** [comment]
> 一直琢磨这事，但是异步和内存优化相关的稍微有点复杂、比c/cpp那种还要复杂一些，不太容易解释清楚。如果以后有档期，我尽量写一些wiki，大致分几块：poller部分，异步流解析的部分（tls/http/websocket），内存池（与标准库一些模块或者fasthttp那种有区别），定制的协程池（跟传统的c/cpp逻辑线程池有区别，跟标准库或者fasthttp那种仍旧每个连接一个协程也不同）

@lesismal http的逻辑部分我确实不认同放在poller里面处理的，gnet也是利用线程池，不过我不喜欢gnet的方式，所以我自己实现了异步处理库[httpd](https://github.com/liangmanlin/gootp/tree/master/httpd)，是基于nbio开发的,包括mempool也是使用sync.pool重写，还没完善，等落地项目验证

**Comment by lesismal** [comment]
> 

nbio的http是的协程池用法也跟其他协程池不太一样，主要是每个conn的执行队列可以保证有序然后使用无序协程池，协程池也是可以由用户自己配置，但是这块的性能差距不大，我默认协程池使用了有限数量的go+单个chan的队列。

nbio之上的http在一般并发量的情况下性能一般，跑不过标准库，因为是兼容标准库，异步流解析加上兼容标准库导致性能差一些、但是海量并发时候的低消耗和稳定性比标准库强太多了，如果不考虑兼容标准库，性能还有上升空间。如果主要是追求性能，httpd可以考虑下试试不兼容标准库的方案

mempool没有采用标准库一些模块或者fasthttp那种2^N方案，因为异步流解析的收发跨层次等各种情况，不如标准库那样容易复用，并且解析完一个request后需要把它丢给逻辑协程池去处理、剩下的半包需要切割、涉及半包缓存之类的，如果都固定使用2^N，mv+cp各种操作成本和内存占用都很高，实际上早期我也是用2^N方案，但性能拉跨并且内存占用比标准库还高，几番折腾换成了现在这种，其实类似于c/cpp malloc/realloc了，但是是交给sync.Pool和gc了。
nbio这个mempool其实也是可以由用户配置的，然后替换掉mempool的默认分配器就可以了·DefaultMemPool = yourImplementation`：
https://github.com/lesismal/nbio/blob/master/mempool/mempool.go#L22

另外，这个Allocator接口有个Realloc，其实早期的实现，需要buffer扩容的各个地方都是用了Realloc的，如果不想sync.Pool持有过量的内存导致高占用、想特别精确的分配释放、只持有当前半包缓存、当前在处理的请求响应中的相关内存，比如封装个cgo的实现替换掉就可以了。但是后来好多地方直接用append替换了Realloc，因为目前的mempool还算满意，所以也就没继续折腾Realloc给cgo那种精准分配释放留口子。但是说不定哪天真碰到需要精准控制的地方了，我再改一波把append的地方都改回Realloc、然后就可以继续精准打击了

异步库，io和逻辑跨协程了，所以buffer的生命周期也不太好管理，不像标准库或者fasthttp那种一个连接一个协程，循环中处理完一个才处理下一个、同一个buffer直接复用、生命周期也不跨协程，sync.Pool+gc也不像c/cpp那种可以精准释放内存，所以内存优化可能要更多细节，跨多个层（tcp/tls/http/ws）的内存的优化是我去年花费事件最多的地方了，难度倒是不算大，但是有点费体力，一不小心泄露了排查起来比较麻烦

你的httpd改造过程中有哪些好的思路或者约到问题欢迎多来交流下，我也把nbio再继续提高一些

**Comment by lesismal** [comment]
@liangmanlin 纯http parser的话也可以看看这个：
https://github.com/antlabs/httparser

这个只处理解析和[]byte性能好些，自己从头定制可能也还好。nbio的parser因为要兼容标准库，所以要很多[]byte转string、要缓存半包之类的没法去做极致性能

**Comment by liangmanlin** [comment]
> @liangmanlin 纯http parser的话也可以看看这个： https://github.com/antlabs/httparser
> 
> 这个只处理解析和[]byte性能好些，自己从头定制可能也还好。nbio的parser因为要兼容标准库，所以要很多[]byte转string、要缓存半包之类的没法去做极致性能

好的

**Comment by liangmanlin** [comment]
> 如果不想sync.Pool持有过量的内存导致高占用

这个问题确实没有考虑过，wrk压测是内存非常平稳，应该是pool的重用率非常高，性能也ok，90%的性能消耗在syscall中，基本上就是socket的读和写了，异步处理的性能损耗是5%左右，channel的2次转发

**Comment by lesismal** [comment]
nbio的http是默认使用协程池处理http和ws消息，协程池数量足够，用户的日常带有阻塞的业务也都没问题，整个进程的阻塞瓶颈通常在于数据库、缓存等的操作，但是协程池size远大于他们，所以虽然绝大多数情况不是每个连接一个协程，但也不至于因为某个连接上消息处理的阻塞操作导致其他cpu消耗也需要排队。

nbio的调用函数是用户可配置的，对于纯cpu消耗的场景，可以把执行函数配置成同步的调用、不需要传递给协程池，然后性能基本会高于标准库

**Comment by liangmanlin** [comment]
> 简单看了下httpd，http parser和ws conn读到完整消息后，框架内默认是没有丢给协程池去处理，如果有阻塞操作，会导致poller协程被阻塞、其他conn线头阻塞

是在异步协程执行的，只有当使用了ws的时候，拦截器会在poller协程执行，其他情况都会在worker线程执行，readme有说明

```golang
func (e *Engine) handler(conn *nbio.Conn, req *http.Request) {
	// 移交到队列处理
	// 根据fd hash
	r := newRequest(req, conn)
	e.manager[conn.Hash()%e.managerNum].Cast(r)
}
```

**Comment by liangmanlin** [comment]
其实主要是规避标准库的频繁创建销毁协程，不一定是最优的

**Comment by lesismal** [comment]
> 

只要不是同时存在大量goroutine，频繁创建销毁好像问题不大，可以benchmark试试看：
```golang
package pool

import (
	"log"
	"runtime"
	"sync"
	"testing"
	"time"
	"unsafe"

	"github.com/lesismal/nbio/taskpool"
	"github.com/panjf2000/ants/v2"
)

const testLoopNum = 1024
const sleepTime = time.Nanosecond * 10

func call(f func()) {
	defer func() {
		if err := recover(); err != nil {
			const size = 64 << 10
			buf := make([]byte, size)
			buf = buf[:runtime.Stack(buf, false)]
			log.Printf("taskpool call failed: %v\n%v\n", err, *(*string)(unsafe.Pointer(&buf)))
		}
	}()
	f()
}

func BenchmarkGo(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := sync.WaitGroup{}
		wg.Add(testLoopNum)
		for j := 0; j < testLoopNum; j++ {
			go call(func() {
				if sleepTime > 0 {
					time.Sleep(sleepTime)
				}
				wg.Done()
			})
		}
		wg.Wait()
	}
}

func BenchmarkAnts(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()

	p, _ := ants.NewPool(10000)
	defer p.Release()

	for i := 0; i < b.N; i++ {
		wg := sync.WaitGroup{}
		wg.Add(testLoopNum)
		for j := 0; j < testLoopNum; j++ {
			p.Submit(func() {
				if sleepTime > 0 {
					time.Sleep(sleepTime)
				}
				wg.Done()
			})
		}
		wg.Wait()
	}
}

func BenchmarkFixedPoolGo(b *testing.B) {
	p := taskpool.NewFixedPool(32, 512)
	defer p.Stop()

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := sync.WaitGroup{}
		wg.Add(testLoopNum)
		for j := 0; j < testLoopNum; j++ {
			p.Go(func() {
				if sleepTime > 0 {
					time.Sleep(sleepTime)
				}
				wg.Done()
			})
		}
		wg.Wait()
	}
}

func BenchmarkFixedPoolGoByIndex(b *testing.B) {
	p := taskpool.NewFixedPool(32, 512)
	defer p.Stop()

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := sync.WaitGroup{}
		wg.Add(testLoopNum)
		for j := 0; j < testLoopNum; j++ {
			p.GoByIndex(j, func() {
				if sleepTime > 0 {
					time.Sleep(sleepTime)
				}
				wg.Done()
			})
		}
		wg.Wait()
	}
}

func BenchmarkFixedNoOrderPool(b *testing.B) {
	p := taskpool.NewFixedNoOrderPool(32, 1024)
	defer p.Stop()

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := sync.WaitGroup{}
		wg.Add(testLoopNum)
		for j := 0; j < testLoopNum; j++ {
			p.Go(func() {
				if sleepTime > 0 {
					time.Sleep(sleepTime)
				}
				wg.Done()
			})
		}
		wg.Wait()
	}
}

func BenchmarkMixedPool(b *testing.B) {
	p := taskpool.NewMixedPool(32, 4, 1024)
	defer p.Stop()

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := sync.WaitGroup{}
		wg.Add(testLoopNum)
		for j := 0; j < testLoopNum; j++ {
			p.Go(func() {
				if sleepTime > 0 {
					time.Sleep(sleepTime)
				}
				wg.Done()
			})
		}
		wg.Wait()
	}
}

func BenchmarkTaskPool(b *testing.B) {
	p := taskpool.New(32, time.Second*10)
	defer p.Stop()

	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := sync.WaitGroup{}
		wg.Add(testLoopNum)
		for j := 0; j < testLoopNum; j++ {
			p.Go(func() {
				if sleepTime > 0 {
					time.Sleep(sleepTime)
				}
				wg.Done()
			})
		}
		wg.Wait()
	}
}
```

```sh
# go test  -bench . 
goos: linux
goarch: amd64
pkg: gopool
cpu: AMD Ryzen 7 5800H with Radeon Graphics         
BenchmarkGo-8                   	    4105	    257356 ns/op	  114925 B/op	    3075 allocs/op
BenchmarkAnts-8                 	    3378	    361650 ns/op	   16533 B/op	    1027 allocs/op
BenchmarkFixedPoolGo-8          	    3184	    341386 ns/op	   16402 B/op	    1025 allocs/op
BenchmarkFixedPoolGoByIndex-8   	    4023	    297420 ns/op	   16405 B/op	    1025 allocs/op
BenchmarkFixedNoOrderPool-8     	    6127	    205159 ns/op	   16400 B/op	    1025 allocs/op
BenchmarkMixedPool-8            	    3903	    300609 ns/op	  131268 B/op	    4097 allocs/op
BenchmarkTaskPool-8             	    3313	    381042 ns/op	   16408 B/op	    1025 allocs/op
PASS
ok  	gopool	8.503s
```

时间上，直接go比ants之类的还要略快，内存上虽然多一点，但是我这个benchmark里是每个op里循环1024次，除以1024后每op多的那一点点可以忽略。
直接用go的话，没法限制协程池数量，所以我用了MixedPool，时间比直接go略慢但是比其他的快，协程用完也能迅速回收

**Comment by liangmanlin** [comment]
之前与标准库的http测试，也是性能相当的

**Comment by lesismal** [comment]
> 之前与标准库的http测试，也是性能相当的

加上协程池异步处理后应该会慢一点，我这测是cpu消耗的接口不丢给协程池处理要比标准库快、加上协程池要慢，大概都是10-30%的范围，但只是小包测框架本身性能，正常的业务接口消耗更多一点这个差距就更小，都足够用了
