### ISSUE TITLE
NListener这个配置参数的作用

### ISSUE THREAD

**Issue by rwcoding** [lesismal/nbio#164]
NListener这个配置参数有什么作用，我在源码中似乎没有找到实际用途

**Comment by rwcoding** [comment]
NListener这个参数有什么作用，我在源码中似乎没有找到实际用途

**Comment by lesismal** [comment]
NListener没有用了，早期版本是sysacll.Listen，允许多个listener，后来直接用net.Listen就废弃了。
欢迎来pr下，或者后续版本整理的时候我再更新

**Comment by lesismal** [comment]
更新了，也清理了几个其他的废弃字段
