### ISSUE TITLE
管理不同协议的连接问题

### ISSUE THREAD

**Issue by rwcoding** [lesismal/nbio#169]
https://github.com/lesismal/nbio/blob/f673651490aa56c86ff51bbe26ec60930ad8a217/nbhttp/engine.go#L682
```go
c.MustExecute(func() {
			parser := c.Session().(*Parser)
			if parser == nil {
				logging.Error("nil parser")
			}
			parser.Close(err)
			engine._onClose(c, err)
			engine.mux.Lock()
			delete(engine.conns, c)
			engine.mux.Unlock()
		})
```

这里需要检测 session 中如果不是 `*Parser`，否则管理其他连接会panic

**Comment by lesismal** [comment]
感谢反馈！

merge的时候commit日志里有 #issue 被github自动关闭了，看下最新的代码可以了不，如果还不行，请提供个复现代码并重新打开issue我继续修复下

**Comment by liangmanlin** [comment]
我猜他是想表达这个意思

虽然不知道他出于什么考虑往http poller池中压入其他连接

不过按道理不应该修改

如果session中不是`*Parse`,会引发panic

```golang
c.MustExecute(func() {
			parser,ok := c.Session().(*Parser)
			if !ok {
				logging.Error("nil parser")
                                return
			}
			parser.Close(err)
			engine._onClose(c, err)
			engine.mux.Lock()
			delete(engine.conns, c)
			engine.mux.Unlock()
		})
```

**Comment by lesismal** [comment]
@liangmanlin 同一个Engine里管理不同协议的Conn是OK的，是我这里以前没考虑用户自定义协议的Conn加到里面来所以都按HTTP的处理了

应该是可以了： https://github.com/lesismal/nbio/pull/173

**Comment by lesismal** [comment]
用户自定义连接与http共用Engine还需要注意一点，tls/http/websocket为了优化内存，打通了几层的内存池，nbio.Write内会释放上层传入的由mempool.Malloc分配的[]byte，用户自定义的协议的Conn写入的数据，要么也使用mempool分配，要么释放的回调里区别对待下：
```golang
userData := mempool.Malloc(...)
userConn.Write(userData)
```
或者释放回调里判断下
```golang
g.OnWriteBufferRelease(func(c *nbio.Conn, buffer []byte) {
	parser, ok := c.Session().(*nbhttp.Parser)
	if ok && parser != nil {
		mempool.Free(buffer)
	}
})
```

**Comment by liangmanlin** [comment]
我对这个使用不是很认同，如果允许不同类型网络协议交由统一poller（`Engine`）处理，那么应该为每一个fd单独注册回调，或者是不同的fd引用不同的`Engine`回调，目前nbio是没有这样做的,实际调用的是poller的回调函数

以onCLose为例
https://github.com/lesismal/nbio/blob/5ed8498d46765fbc1bd4f5a1785ad23c7bc71c2e/engine.go#L190-L197

https://github.com/lesismal/nbio/blob/5ed8498d46765fbc1bd4f5a1785ad23c7bc71c2e/poller_epoll.go#L72-L82

应该修改为类似api
```golang
func (g *Engine) AddConn(conn net.Conn,connFather *Engine) (*Conn, error) {
	c, err := NBConn(conn)
        c.g = connFather 
	if err != nil {
		return nil, err
	}
	g.pollers[uint32(c.Hash())%uint32(g.pollerNum)].addConn(c)
	return c, nil
}

 func (p *poller) deleteConn(c *Conn) { 
 	if c == nil { 
 		return 
 	} 
 	fd := c.fd 
 	if c == p.g.connsUnix[fd] { 
 		p.g.connsUnix[fd] = nil 
 		p.deleteEvent(fd) 
 	} 
        if c.g != nil {
 	    c.g.onClose(c, c.closeErr) 
        }else{
            p.g.onClose(c, c.closeErr)
        }
 } 
```

**Comment by lesismal** [comment]
@liangmanlin 
nbhttp.Engine是之前有人想要http/ws client、serverdou能在同一个engine里处理，后来实现的时候，就全支持扩展了，步骤相当于：
1. nbio.Conn 支持自定义自己的OnData handler: https://github.com/lesismal/nbio/blob/master/conn.go#L17
2. nbhttp.Engine 包装一下 nbio.Gopher/Engine.OnData、调用nbio.Conn的OnData handler: https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L692

所以不需要再修改接口了

**Comment by liangmanlin** [comment]
我截取的代码段是想说明
1.如果我有多个应用层协议，例如websocket，2字节大端头部tcp包（这个比较流行），那么我的nbio.Conn.session大概率不一样，虽然我可以通过switch去判断，但是这样不优雅，事实上我目前我只能只有做

https://github.com/liangmanlin/gootp/blob/90df988e452732250bcd81cdb5871b58535bfd48/httpd/httpd.go#L69-L74
```golang
g.OnClose(func(c *nbio.Conn, err error) {
			if s, ok := c.Session().(*websocket.Conn); ok {
				kernel.DebugLog("websocket closed: %s", c.RemoteAddr())
				s.OnClose()
			}
		})
```

2.目前nbio只提供onData的conn handler，这样就说明，其实对于每个连接，都应该可以执行不同的回调函数

3.目前nbio.Conn结构已经有Engine的引用，只不过默认是指向poller的g

**Comment by lesismal** [comment]
> 例如websocket，2字节大端头部tcp包（这个比较流行），那么我的nbio.Conn.session大概率不一样，虽然我可以通过switch去判断，但是这样不优雅，事实上我目前我只能只有做
> 2.目前nbio只提供onData的conn handler，这样就说明，其实对于每个连接，都应该可以执行不同的回调函数
> 3.目前nbio.Conn结构已经有Engine的引用，只不过默认是指向poller的g

对于OnClose，虽然不优雅，但是可以实现功能，并且这种统一封装的地方，即使不优雅，也不会浪费太多代码。
没给OnClose弄成nbio.Conn的字段支持每个nbio.Conn自己的OnClose回调的原因是要多加个func字段浪费字节，虽然百万也才8M，但因为OnClose不像OnData那样是必需品，所以能省还是省一点


websocket的实现，其实已经提供了upgrader.OnClose的回调中就传递了websocket.Conn给用户，各层处理好自己的事情就好了

**Comment by rwcoding** [comment]
框架中 WebSocket 的 onMessage 回调是在单独的协程或协程池中的，还是在 poller 协程中的，如果在poller中，我需要自己再做处理

**Comment by lesismal** [comment]
> 

默认是在单独的协程池处理的，一些相关的初始化：
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L476
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L516
https://github.com/lesismal/nbio/blob/master/conn.go#L75
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L604
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L647
