### ISSUE TITLE
Close status code

### ISSUE THREAD

**Issue by IceflowRE** [lesismal/nbio#177]
Is it possible to send a custom close status code?
And is it possible to get the status code sent by the client when `onClose` is called.

**Comment by lesismal** [comment]
I don't understand what kind of status code you want, would you please provide some examples?

**Comment by lesismal** [comment]
Do you mean websocket's close code? If you mean websocket, can do it like this:
```golang
var code uint16 = 1000
var codeBytes = make([]byte, 2)
binary.BigEndian.PutUint16(codeBytes, code)
// codeBytes = append(codeBytes, "your reason text if you need"...)
c.WriteMessage(websocket.CloseMessage, codeBytes)
c.Close()
```

**Comment by IceflowRE** [comment]
Oooh, thank you! Exactly what i needed.

**Comment by lesismal** [comment]
You are welcome!
