### ISSUE TITLE
Support `PATCH` method.

### ISSUE THREAD

**Issue by qioalice** [lesismal/nbio#178]
https://github.com/lesismal/nbio/blob/2457f390e664c0b86488a9a4d3c2771f31ac1fa0/nbhttp/table.go#L10

Hi. Could you add an HTTP `PATCH` method support? It wasn't a part of the RFC2616 HTTP/1.1 standard, but it became a part of that in 2010. https://datatracker.ietf.org/doc/html/rfc5789

An attempt to use it now will lead to `ErrInvalidMethod` as `parser.Read failed: invalid HTTP method`.
Honestly, I barely want to change an API and replace PATCHes everywhere :)

**Comment by lesismal** [comment]
Thank you for your feedback!

Please try the latest: https://github.com/lesismal/nbio/pull/179

**Comment by qioalice** [comment]
Thank you very much, that works. 
When do you plan to release the next version?

**Comment by lesismal** [comment]
> PS. When do you plan to release the next version?

published already: https://github.com/lesismal/nbio/releases/tag/v1.2.15
