### ISSUE TITLE
How to set keep_alive related parameters for TCP connections?

### ISSUE THREAD

**Issue by seymourtang** [lesismal/nbio#186]
I found the relevant source code,but `SetKeepAlivePeriod` function has been commented.
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L258
```go
// SetKeepAlive implements SetKeepAlive.
func (c *Conn) SetKeepAlive(keepalive bool) error {
	if keepalive {
		return syscall.SetsockoptInt(c.fd, syscall.SOL_SOCKET, syscall.SO_KEEPALIVE, 1)
	}
	return syscall.SetsockoptInt(c.fd, syscall.SOL_SOCKET, syscall.SO_KEEPALIVE, 0)
}

// SetKeepAlivePeriod implements SetKeepAlivePeriod.
func (c *Conn) SetKeepAlivePeriod(d time.Duration) error {
	return errors.New("not supported")
	// d += (time.Second - time.Nanosecond)
	// secs := int(d.Seconds())
	// if err := syscall.SetsockoptInt(c.fd, syscall.IPPROTO_TCP, syscall.TCP_KEEPINTVL, secs); err != nil {
	// 	return err
	// }
	// return syscall.SetsockoptInt(c.fd, syscall.IPPROTO_TCP, syscall.TCP_KEEPIDLE, secs)
}
```
Also I can't get to the FD from the `*nbio.Conn`.Please tell me how to set keep_alive related parameters for TCP connections?

**Comment by seymourtang** [comment]
@lesismal

**Comment by seymourtang** [comment]
Updated:
I can get to the FD from the `hash` function.
```go
// Hash returns a hash code.
func (c *Conn) Hash() int {
	return c.fd
}
```

**Comment by lesismal** [comment]
I have uncommented `SetKeepAlivePeriod`.
Please try the latest: https://github.com/lesismal/nbio/releases/tag/v1.2.18

BTW, I think TCP-Keepalive is not very useful: 
```text
It can only detect Layer-4's state, but we always need to detect zombie connections in Layer-7.
If we already do it in Layer-7, we don't need TCP-Keepalive anymore. 
```

**Comment by seymourtang** [comment]
> I have uncommented `SetKeepAlivePeriod`. Please try the latest: https://github.com/lesismal/nbio/releases/tag/v1.2.18
> 
> BTW, I think TCP-Keepalive is not very useful:
> 
> ```
> It can only detect Layer-4's state, but we always need to detect zombie connections in Layer-7.
> If we already do it in Layer-7, we don't need TCP-Keepalive anymore. 
> ```

Thank you, I'll try it later.
