### ISSUE TITLE
Is it better to use Readv(2) than Read(2) in loop?

### ISSUE THREAD

**Issue by irying** [lesismal/nbio#187]
还需要补充一点，为了用户使用简单，nbio默认处理方式是直接把数据丢给用户的，而不是只丢事件给用户，这种情况下，需要框架层确保每次读完（设置循环读取次数无限大），所以每次可读都会读完本次数据：
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L145
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L182

如果需要自己订阅读事件自行定制读取方式，可以设置读方法：
```golang
g.OnRead(func(c *nbio.Conn) {
	/// ...
})
```

然后读取时就会用你设置的方法：
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L203

_Originally posted by @lesismal in https://github.com/lesismal/nbio/issues/144#issuecomment-1042708834_

**Comment by irying** [comment]
@lesismal 这个是否可以换成readv(2)一次性读完，就不用循环读

**Comment by lesismal** [comment]
> @lesismal 这个是否可以换成readv(2)一次性读完，就不用循环读

readv可能不会有提升，多数情况可能还不如read：
1. 默认使用的poller协程内的一个固定read buffer，所以如果实际场景每次交互的数据较大，就把对应的这个默认的read buffer也设置大了就可以保证单次read尽量读完到这个buffer里了，可以通过 `conf.ReadBufferSize` 来设置这个size。因为每个poller的io协程只对应一个buffer，所以即使这个size调大些、但数量少并且只分配一次，所以内存消耗也不会太多。
2. writev的实现也是先创建一个大buf然后把几段buf copy到大buf里去，然后只需要write一次、通过节省syscall来提高性能，但相比单次其实多出了copy成本。readv也是类似的，在单个buffer size不够的时候可以通过用copy来减少read syscall来提高性能。但readv与writev不同，writev你可以提前判断当前是不是有多段buf要写入，如果多段buf并且size在某个阈值（copy消耗成本对比多次syscall成本的阈值）范围内，那么writev划算，但是readv的使用场景，你没有提前预知读缓冲区内的数据是否大于你所准备的buf size。

**Comment by lesismal** [comment]
ps: writev的c内部实现就是我上面说的那种，但是直接使用内核的，是消耗内核态更多，而且没法跟应用层的buffer pool结合来优化，实际性能还不如应用层自己拼接，所以nbio.Conn提供的Writev是自己拼接buffer后再调用write而不是writev

**Comment by irying** [comment]
> > @lesismal 这个是否可以换成readv(2)一次性读完，就不用循环读
> 
> readv可能不会有提升，多数情况可能还不如read：
> 
> 1. 默认使用的poller协程内的一个固定read buffer，所以如果实际场景每次交互的数据较大，就把对应的这个默认的read buffer也设置大了就可以保证单次read尽量读完到这个buffer里了，可以通过 `conf.ReadBufferSize` 来设置这个size。因为每个poller的io协程只对应一个buffer，所以即使这个size调大些、但数量少并且只分配一次，所以内存消耗也不会太多。
> 2. writev的实现也是先创建一个大buf然后把几段buf copy到大buf里去，然后只需要write一次、通过节省syscall来提高性能，但相比单次其实多出了copy成本。再单个读buffer不够时，readv减少了syscall次数提高了性能，但多段buffer的代码仍然比读到单个buffer的循环和空间亲和性要消耗多。而且readv与writev不同，writev你可以提前判断当前是不是有多段buf要写入，如果多段buf并且size在某个阈值（copy消耗成本对比多次syscall成本的阈值）范围内，那么writev划算，但是readv的使用场景，你没有提前预知读缓冲区内的数据是否大于你所准备的buf size。

如果用readv的话，我可以设置一个临时buf（c），大小足够大，比如65536；
1）当读缓冲区的数据（a）大于我所准备的buf size（b），即a>b时，n = readv(fd, []iov{a, c})，这时我把读出来的n和b的差值append给b，一同返回给应用层；
2）当缓冲区的数据（a）不大于我所准备的buf size（b），即a<=b，n = readv(fd, []iov{a, c})，只把读出来的n返回给应用层

**Comment by lesismal** [comment]
> 比如65536；
> 1）当读缓冲区的数据（a）大于我所准备的buf size（b），即a>b时，n = readv(fd, []iov{a, c})，这时我把读出来的n和b的差值append给b，一同返回给应用层；

你还是没理解我说的１。直接把１中说的buffer调大，就完全可以避免readv了

另外，你想获取socket当前可读数据量，你有没有想过，这本身也消耗一次syscall，并且获取之前你无法知道这次是否是大量数据，所以你只能每次获取，每次浪费一个syscall，整体的性能下降损失已经很大了

**Comment by lesismal** [comment]
在某种情况下，比如你的内网环境稳定，每次协议交互都是固定的几段buffer，并且这几段buffer是离散的无法用单独一个大buffer优化的时候，或许用readv可以带来非常非常少许的吞吐量提升。如果确实有这种场景并且你的性能需求非常极端，可以考虑readv，并且nbio你只要用g.OnRead自己定制这个读就可以了，nbio设计了OnRead接口就是为了给用户尽量留下充足的定制空间，预留了这个定制的机制，就不需要框架本身再去额外支持各种细节了

其他绝大部分现实场景，比如公网服务，大包被路由选路和分片丢包各种线路波动的情况，无法保证你本次读事件到来时，缓冲区内就是有你每个协议交互的完整包数据，所以你想获取当前缓冲区数据size的额外的ioctl就没有通用方法来优化掉，简单调整我前面的１中说的buffer size差不多就是最优解了

**Comment by irying** [comment]
> > 倒是你说的那个调大buffer去read，也可以一次性read完，那为什么代码还有遍历呢？
> 
> 哦，你这里的“遍历”是指我代码里的for循环多次读取吧？其他框架有的是传递事件，有的是单次读完传递数据，nbio在默认LT模式下这个循环是支持可配置读取次数的，主要有以下目的： 一是为了通常情况下尽量本次读完，比如你设置成无限大或者大于读缓冲区，基本就是每次都能读完当前数据，默认是LT模式，这样就不必导致单次数据抵达还得下一次event loop重复触发了，重复触发有点浪费 二是为了支持业务层限流，比如为了防止某个连接数据量大，导致单次读取时间长影响其他连接，可以把那个每次event loop读取次数配置较小比如3次，让所有连接尽量公平及时地获得读取机会的时间

精彩，没想到还有限流这个
