### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by ckcfcc** [lesismal/nbio#188]
很棒的库。而且对协议支持也很完善。

一点小建议：可以考虑将engine监听后自动适配所有基于TCP的协议，例如支持普通tcp、tls、ws、wss、http、https等，提供通用的回调和协议专用的回调。

比如：连接建立就都用onOpen，关闭就都是onClose，额外的，向http https这种，就增加一个专用回调。比如onWeb(conn, req, resp) 类似这种的。

git上看了一下，目前有基于std库的实现
https://github.com/soheilhy/cmux
大概阅读了一下，好像就是通过头部内容来确认一下协议

**Comment by ckcfcc** [comment]
在补充一些，之前看了一些issue，建议提供一下类似限流或者熔断的选项或基址。

看到有个issue中，好像提到他们无限制怼发送数据，把环形缓冲区撑到非常大的情况。

**Comment by lesismal** [comment]
感谢关注与反馈！

> 一点小建议：可以考虑将engine监听后自动适配所有基于TCP的协议，例如支持普通tcp、tls、ws、wss、http、https等，提供通用的回调和协议专用的回调。

这个实现起来不难，但应该归属于应用层自己去定制，nbio支持的tcp/tls/http1.x/websocket这些都是相当于支持网络传输载体而不是去侵入应用层的业务，分层应该明确，每一层处理好自己的事情，否则其他协议也都来让支持，那基础设施就做的杂而丑了，并且伴随着一点性能损失。

而且多数公司的业务，并不需要同一个端口去处理所有不同协议，分开不同的port对于监控也好日志也好，逻辑也好，都更清晰。有时候复用并不是更优解，因为复用并兼容不同的东西意味着这块的逻辑更复杂，要懂得具体问题具体分析。

如果哪家公司的项目应用层确实需要这种，自己定制下就可以了，不应该来反向入侵框架实现。

**Comment by lesismal** [comment]
> 比如：连接建立就都用onOpen，关闭就都是onClose，额外的，向http https这种，就增加一个专用回调。比如onWeb(conn, req, resp) 类似这种的。

同样的，业务层的框架自己在公共的地方wrap一下，提供给业务的应用层一些自己想要的接口就可以了，这点代码量没什么复杂的，也不应该来反向入侵基础框架的实现

**Comment by lesismal** [comment]
> 在补充一些，之前看了一些issue，建议提供一下类似限流或者熔断的选项或基址。
> 看到有个issue中，好像提到他们无限制怼发送数据，把环形缓冲区撑到非常大的情况。

这个应该是在其他框架中的issue吧，nbio没有使用环形缓冲区，对于异步框架，目标是节省内存，每个conn上再挂载一个buffer不管是环形还是普通buffer，都是要消耗更大的内存总量的，更合理的方案是如果发送失败需要等待可写时缓存起来，可写并flush成功后就释放掉，而写缓冲阻塞的情况是属于少数情况，所以用普通的buffer+append反倒比环形队列更简单高效

至于限流，具体的限流应该由业务层自己实现，框架层应该做的是提供限流的基础手段，nbio提供一些选项，用户可以配合使用来实现限流，比如 `conf.ReadBufferSize`，`MaxConnReadTimesPerEventLoop`，或者自己定制 `g.OnRead`，然后配合 OnData 用户自己统计分析即可

**Comment by lesismal** [comment]
nbio专注基础框架层，否则比如音视频流媒体或者其他各种协议也都要搞，单个仓库就有点大而乱了。
自带了tls/http/websocket是绝大多数人的硬性需求，所以框架内自带了，并且也能对标标准库的基础结构（tls放到外部的单独仓库了，因为tls是直接copy标准哭的代码魔改的，而标准哭的开元协议是BSD，我想保持nbio的MIT协议，所以tls放外部单独了）。
其他的，比如哪天想再支持流媒体，则会单独开仓库来做，这样层次是分明的，各个库处理好自己的事情，低耦合

**Comment by liangmanlin** [comment]
> nbio专注基础框架层，否则比如音视频流媒体或者其他各种协议也都要搞，单个仓库就有点大而乱了。 自带了tls/http/websocket是绝大多数人的硬性需求，所以框架内自带了，并且也能对标标准库的基础结构（tls放到外部的单独仓库了，因为tls是直接copy标准哭的代码魔改的，而标准哭的开元协议是BSD，我想保持nbio的MIT协议，所以tls放外部单独了）。 其他的，比如哪天想再支持流媒体，则会单独开仓库来做，这样层次是分明的，各个库处理好自己的事情，低耦合

确实，目前的http支持应该单独开一个仓库
