### ISSUE TITLE
Question about conn lock

### ISSUE THREAD

**Issue by irying** [lesismal/nbio#189]
### First
Here is some comment:
https://github.com/lesismal/nbio/blob/db13c52634415bdd0f8b34dc25e16e000c7742d2/conn_unix.go#L58

The mutex can promise the Conn's state if there are concurrent Read/Write/Close.
Imagine:
```text
1. Conn A hold fd 1000;
2. Conn A enter Conn.Read but have not call syscall.Read
3. Conn A is closed by other goroutine
4. A new Conn B established and reuse fd 1000;
5. Conn A call syscall.Read which would steal Conn B's data
```

### Second
nbio use epoll LT by default which must be implemented to a `reactor`, that means we need to read all the data during each poller loop;
But nbio also supports the ET mod which can be used by the application layer to implement `proactor`, which means it would be decided by the application layer that when they `Read`, it's better to guarantee the concurrency of the state of Conn.

### Third
Mutex.Lock/Unlock cost only some atomic operations for most of the time, that's not too much cost and will not affect performance too much:
https://github.com/golang/go/blob/master/src/sync/mutex.go#74
https://github.com/golang/go/blob/master/src/sync/mutex.go#210

_Originally posted by @lesismal in https://github.com/lesismal/nbio/issues/144#issuecomment-985487362_

**Comment by irying** [comment]
@lesismal 看这评论，应该是fd的读写锁才对吧

1. Conn A hold fd 1000;
2. Conn A enter Conn.Read but have not call syscall.Read
3. Conn A is closed by other goroutine
4. A new Conn B established and reuse fd 1000;
5. Conn A call syscall.Read which would steal Conn B's data

还有这个第3步已经关了ConnA，为啥第5步还可以调用syscall.Read，是说临界情况吗？比如刚锁到，准备Read，但还没Read就被close了。

**Comment by lesismal** [comment]
默认情况下read是发生在poller event loop协程，accept不是在poller event loop协程，close的发生很可能也不是在poller event loop协程里。除了对方close然后poller读失败或者可写事件触发poller循环内的写并且写失败，其他基本都是在poller之外的协程close的：比如应用层协程池处理一个连接的数据判定它非法把它关闭，或者SetReadDeadline后被timer协程关闭，这些都是poller之外的协程关闭的。
所以read与close，很可能是在不同的并发流。然后就可能发生临界情况。Conn结构体如果不用锁，比如在poller循环里刚收到一个fd读事件并且进入了旧的Conn.Read但是尚未调用syscall.Read，这时这个fd被其他协程关闭了，并且新的连接进来重新hold了这个fd，因为协程的调度无法保证poller loop里的Conn.Read执行完syscall.Read之后才能执行其他协程的读，所以这时候旧的连接持有的fd其实已经被关闭、fd的值不变但已经是应该归属于新的Conn的，这就是串号了。然后旧Conn调用到syscall.Read了，读到了数据，但是这个数据本该属于新的Conn，然后两个Conn对应的读取解析就都乱了。
每个Conn加上锁后，能够保证fd syscall的整个临界区操作，比如旧的被Close了，就不会执行syscall.Read了也就不会把新Conn的数据偷走，或者旧连接自己先Lock了，其他地方要等它执行完syscall并且Unlock后才会进入close，这样也不会导致fd被先关闭并且重新被其他Conn获得和数据错乱

**Comment by lesismal** [comment]
虽然函数名字是读写关闭，但这个读写并不是读写锁的读写的意思，使用读写锁的场景是依赖于对数据更新与否的逻辑，而这里除了更新Conn状态的这个变量数据、还需要保护整个临界区的syscall操作。

另外，对于很多场景也是没必要用读写锁的，很多时候是Mutex优于RWMutex，比如这里的Conn，对于单个Conn来说，发生并发竞争的概率极低。而RWMutex的代码调用要比Mutex多一些，长久下来，RWMutex的额外消耗多数会是大于它从并发竞争上带来的收益。所以除非明确知晓会有大量并发读的场景可能导致锁竞争，否则Mutex更优

**Comment by irying** [comment]
thx 🙏 @lesismal

**Comment by irying** [comment]
@lesismal 我今天看了https://github.com/lesismal/nbio/issues/190 这个issue，想了下，conn的fd是怎么重用的，代码里conn的fd是Go一波accept之后的netFD，netFD不会相同吧

**Comment by lesismal** [comment]
可以看下APUE, v2 3.3 open函数的介绍中有一句：
"由open返回的文件描述符一定是最小的未用描述符数字"

fd是File Descriptor的缩写，其他各种文件类型也是跟open函数一样的，accpet、pipe、epoll_create之类的得到的fd，也都是当前最小的未使用的。
当你close一个fd后，这个fd的值（比如5）就是未使用的，下次有相关函数得到一个fd时就会返回5

应该是因为内核、进程也都是用的文件描述符表，就是个数组，所以用这种策略是最高效的吧

**Comment by lesismal** [comment]
APUE CSAPP这些经典书挺好的，可以多读几遍

**Comment by irying** [comment]
@lesismal 再次感谢🙏🙏，我昨晚也翻了下，之前一直觉得一直往后找fd，但真实是：在程序运行起来后打开其他文件时，系统会返回**文件描述符表中最小可用**的文件描述符，并将此文件描述符记录在表中。
