### ISSUE TITLE
关于conn_unix.go的Read()的疑问

### ISSUE THREAD

**Issue by zhu121** [lesismal/nbio#190]
问题：Conn的Read()函数为什么需要加互斥锁，注释“use lock to prevent multiple conn data confusion when fd is reused on unix”不大理解，因为：
* 连接fd在Engine的[]*Conn中是不重复的
* syscall.EpollWait()返回的可读事件得到的fd也是独立的

**Comment by lesismal** [comment]
之前也有相关issue可供参考:
https://github.com/lesismal/nbio/issues/144
https://github.com/lesismal/nbio/issues/189

**Comment by lesismal** [comment]
另外，其实不只是读，写也是同样的道理。如果不加锁，应用层协成跟poller不在同一个并发流，不加锁并判断状态的话，多个并发流都是存在窜号的可能性的。
有些框架是串行化单个fd的IO，用close列表+epoll trriger的方式，然后让同一个conn的操作串行化，他们可能会提供直接写那么这个写不在poller协程内进行也不是穿行的，还可能提供异步写来保证穿行。但这只是框架层，处于性能考量，应用层通常是另外的协程池，所以你不加锁，就可能乱。我看到一些其他框架的issue列表里可能会有数据错乱的问题，我没有亲自去尝试，但估计可能跟我说到的这些原因类似。
标准库的封装，poll.Fd也都是加了锁的，只是一般开发者直接拿net.Conn来用了、并没有去看标准库源码的实现。总体上来讲，除非c++的一些逻辑单线程的框架，因为逻辑单线程、close和write都是可控的，那种比较容易实现fd不需要加锁并能保证close后不会再有原来的持有fd的地方再对已经close的fd有io操作导致窜号。其他业务层有多个并发流的，很难实现真正的无锁且避免窜号的问题。

**Comment by zhu121** [comment]
一个poller由一个goroutine运行事件循环，一个Conn在连接期间是绑定在某个poller的，如果使用runtime.LockOSThread()将协程绑定到专用的系统线程，是不是可以在read/write时不用加锁

**Comment by lesismal** [comment]
> 一个poller由一个goroutine运行事件循环，一个Conn在连接期间是绑定在某个poller的，如果使用runtime.LockOSThread()将协程绑定到专用的系统线程，是不是可以在read/write时不用加锁

LockOSThread 只是保证这个协程不用切换到其他线程去调度、保障这个协程自己的性能，但对于其他协程，他们之间仍然是并发的关系，所以并发流跟是否 LockOSThread 没有关系。
