### ISSUE TITLE
Auto-closing WS in 2min

### ISSUE THREAD

**Issue by qioalice** [lesismal/nbio#191]
Hi.

Just got an issue during with websocket automatically closes itself in 2 min after connection was established. An error message tells me: `websocket conn is closed [::1]:33776 read timeout`. So, it looks like the `net.Conn.SetReadDeadline(2min)` call made somewhere inside and never been called again after message is received. 

Maybe it's my responsibility to call this method after message was received, but I guess it should be more clear whether should I call or not. Moreover, my thoughts are simple: "If I didn't make the first call, why should I make the next ones?". 

The example is simple. 
Just open the connection and wait. You will get your connection been closed in 2 min.

<details>
<summary>Example</summary>

	```golang
	package main

	import (
		"context"
		"fmt"
		"log"
		"net/http"
		"os"
		"os/signal"
		"sync"
		"syscall"
		"time"

		"github.com/lesismal/nbio/nbhttp"
		"github.com/lesismal/nbio/nbhttp/websocket"
	)

	func OnWebsocket(w http.ResponseWriter, r *http.Request) {
		upgrader := websocket.NewUpgrader()
		upgrader.CheckOrigin = func(_ *http.Request) bool {
			return true
		}
		upgrader.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
			fmt.Println(time.Now().String(), "websocket:", messageType, string(data), len(data))
			c.WriteMessage(messageType, data)
		})
		upgrader.OnOpen(func(c *websocket.Conn) {
			fmt.Println(time.Now().String(), "websocket conn is open", c.RemoteAddr().String())
		})
		upgrader.OnClose(func(c *websocket.Conn, err error) {
			fmt.Println(time.Now().String(), "websocket conn is closed", c.RemoteAddr().String(), err)
		})

		conn, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			panic(err)
		}
		wsConn := conn.(*websocket.Conn)
		_ = wsConn
	}

	func main() {

		ctx, cancelFunc := context.WithCancel(context.Background())
		wg := new(sync.WaitGroup)

		sig := make(chan os.Signal, 1)
		defer close(sig)
		signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)

		srv1 := nbhttp.NewServer(nbhttp.Config{
			Addrs: []string{":13000"},
			Handler: http.HandlerFunc(OnWebsocket),
		})

		if err := srv1.Start(); err != nil {
			log.Fatalln("Failed to start server 1", err)
		}

		wg.Add(1)
		go func() {
			defer wg.Done()
			<-ctx.Done()

			ctx, cancelFunc := context.WithTimeout(context.Background(), 5 * time.Second)
			defer cancelFunc()

			if err := srv1.Shutdown(ctx); err != nil {
				log.Println("Failed to shutdown server 1", err)
			}
		}()

		<-sig
		cancelFunc()

		wg.Wait()
	}
	```
</details>

**Comment by lesismal** [comment]
> Maybe it's my responsibility to call this method after message was received

Yes, usually we should update the deadline time when we received a message.

Because `SetReadDeadline` is called by `nbio` by default, to avoid zombie connections:
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L531
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L566

If you don't want to update the deadline time, you should `SetReadDeadline(time.Time{})` after `upbrader.Upgrade` to cancel the timeout timer

related:
https://github.com/lesismal/nbio/issues/181#issuecomment-1080367781

**Comment by qioalice** [comment]
> Because `SetReadDeadline` is called by `nbio` by default, to avoid zombie connections:
> https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L531
> https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L566

Ok. You provided a code that references to the engine of `nbhttp`. How it works there? An engine automatically updates read op deadline after each message is received? Or once the connection is established there's no way to make its keep-alive status more than 2min? 

> If you don't care about zombie connections and don't want to update the deadline time, you can `SetReadDeadline(time.Time{})` after `upbrader.Upgrade` to cancel the timeout timer, but that's not suggested.

Maybe this should be a part of `nbio` itself since the first call is made by them? And manage TTL in a declarative way? Like changing a value in `Upgrader`?

**Comment by lesismal** [comment]
The `KeepaliveTime` is used for HTTP, `nbio` `SetReadDeadline(KeepaliveTime)` automatically when a new connection is established because the connection is treated as an HTTP connection by default we are running the HTTP service.
After `Upgrade`, users Hijack the connection from HTTP, and then the connection is not an HTTP  connection any longer.
So, after the `Upgrade/Hijack`, users should manage the read deadline themselves.

**Comment by lesismal** [comment]
`nbio` doesn't provide a new configuration like `WebsocketKeepaliveTime`, because `WebSocket` is not included in `nbhttp`, it's another subpackage.
And it's easy for users to wrap a handler to implement auto-SetReadDeadline like this:
```golang
func YourWsMessageHandler(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
	// your implementation...
}

u.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
	YourWsMessageHandler(c, messageType, data)
	c.SetReadDeadline(time.Now().Add(YourWsKeepaliveTime))
})
```

**Comment by qioalice** [comment]
Ok, thanks. This issue is over, I guess, so I am closing it. But let me ask the last question.

How `nbio` will handle a regular HTTP keep-alive connection? I understand the first call `SetReadDeadline()` when connection is established. Will it be invoked again when new message is received to prolong keep-alive TTL?

**Comment by lesismal** [comment]
> How nbio handles a regular HTTP keep-alive connection? I understand that the first call SetReadDeadline() is invoked when a connection is established. Will it be invoked again when new message is received to prolong keep-alive TTL?

Yes it will be invoked again if it's a keep-alive connection:
https://github.com/lesismal/nbio/blob/master/nbhttp/processor.go#L281

**Comment by lesismal** [comment]
I'm considering not setting `nbhttp.KeepaliveTime` to `120s` as default value, if it's 0, nbio doesn't `SetReadDeadline`.
What do you think about it?

**Comment by qioalice** [comment]
> How do you think about it?

I don't mind. If we're in the WS context, there's a problem. As a user I do not call the first `SetReadDeadline` but I have to call the next ones. That's quite vaguely. It's not a problem for me to write wrappers and call them each time I receive a message but it'd be better if this call would be also under the hood like the first one. With an ability to change this TTL at the connect establishing.

Or, if you want to force users to call `SetReadDeadline` by themselves, then the first call should be also performed by the user. In `OnOpen` callback, I guess?

**Comment by lesismal** [comment]
As I've mentioned, it's not suitable for `nbhttp` to `SetReadDeadline` for `Websocket`.

We can provide a new configuration field in `Upgrader`, `Upgrader.KeepaliveTime`, then we can handle the deadline automatically by `nbio`.

**Comment by lesismal** [comment]
Commited: https://github.com/lesismal/nbio/commit/8e9086aa7cab1c0669cb1f4692023a833fe92433

Then we can use it like this:
```golang
u := websocket.NewUpgrader()

// set keepalive time, then nbio will call SetReadDeadline automatically
u.KeepaliveTime = time.Second * 120
```

If it's fine to you, I'll merge it to master and publish a new version.

**Comment by qioalice** [comment]
> If it's fine to you, I'll merge it to master and publish a new version.

Excellent. That's exactly what I want. 
Will you set the default value for this new configuration field?

**Comment by lesismal** [comment]
> 

I haven't set a default value for it.
Because if I do, other users' original `SetReadDeadline` logic will fail. Without setting the default value can keep forward compatible

**Comment by qioalice** [comment]
> I haven't set a default value for it.
> Because if I do, other users' original `SetReadDeadline` logic will fail. Without setting the default value can keep forward compatible

But then for now you don't have a first 2m TTL when connection is established. And it also breaks a backward compatibility, since some users may rely on it.

**Comment by lesismal** [comment]
> But then for now you don't have a first 2m TTL when connection is established. And it also breaks a backward compatibility, since some users may rely on it.

I think it doesn't matter.
Because if users have relied on it, the users should also have `SetReadDeadline` in their `OnMessage` handler, else their connections will be closed in 2min. So it's still compatible. 😄

**Comment by qioalice** [comment]
> I think it doesn't matter.
> Because if users have relied on it, the users should also have `SetReadDeadline` in their `OnMessage` handler, else their connections will be closed in 2min. So it's still compatible. 😄

Ok. Let's assume user has their own `SetReadDeadline` call in `OnMessage` handler and in the current version you don't have first `SetReadDeadline` call under the hood when connection is established.

In that case the connection will live forever until first message is received. And when first message is received, `SetReadDeadline` is called first time. Am I wrong?

**Comment by lesismal** [comment]
> In that case the connection will live forever until first message is received. And when first message is received, SetReadDeadline is called for the first time. Am I wrong?

Yes, you are right. 
So, maybe we need to throw this compatibility problem to go mod and version control. Have you any better idea?

**Comment by lesismal** [comment]
> > But then for now you don't have a first 2m TTL when connection is established. And it also breaks a backward compatibility, since some users may rely on it.
> 
> I think it doesn't matter. Because if users have relied on it, the users should also have `SetReadDeadline` in their `OnMessage` handler, else their connections will be closed in 2min. So it's still compatible. 😄

I think a little more, users should have `SetReadDeadline` right after `Upgrade`, like this:
```golang
func onWebsocket(w http.ResponseWriter, r *http.Request) {
	upgrader := newUpgrader()
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		panic(err)
	}
	c.SetDeadline(...)
}
```

**Comment by qioalice** [comment]
> I think a little more, users should have `SetReadDeadline` right after `Upgrade`, like this:

Why do they need to do so if you've had a 2m default call until you made a new version based on this issue? I think there was only one reason - a default 2m value is not suitable for them. 

So, I guess it'd better if you'd just add a default value for new upgrader parameter. 2m, like it was before.

**Comment by lesismal** [comment]
>  a default 2m value is not suitable for them

Yes, for `Websocket`, 2m is too long, so users usually have their own config. For example, it's 30-60s in most of my services.

> So, I guess it'd be better if you'd just add a default value for new upgrader parameter. 2m, like it was before.

Ok, I'll commit it later.

**Comment by lesismal** [comment]
done: https://github.com/lesismal/nbio/commit/614794ce3ebcca47cf4a992bba7ec9478117bb84

**Comment by qioalice** [comment]
Thank you.
Waiting for next release.

**Comment by lesismal** [comment]
published: https://github.com/lesismal/nbio/releases/tag/v1.2.19

**Comment by qioalice** [comment]
> I mentioned above:
> "Because if I do, other users' original SetReadDeadline logic will fail"

You're right. I forgot about it. Again.
Thank you for publishing new version. I appreciate your efforts.

**Comment by lesismal** [comment]
Thank you all the same for your feedback and your idea to make this repo better, appreciate it very much!
