### ISSUE TITLE
关于Nbio做纯转发时的一点疑问

### ISSUE THREAD

**Issue by ffcdn** [lesismal/nbio#197]
你好，大佬，想问下 如果用nbio来实现纯转发性能会比rust实现的差很多吗？rust有一个https://github.com/zhboner/realm，主要提到零拷贝技术的应用

**Comment by lesismal** [comment]
兄弟是想用splice这种吧？

纯转发的话，用标准库好些，没必要用nbio，标准库比如TCPConn，自己就有ReadFrom的方法、会判断是否支持splice，支持的话就直接用splice了也就是zero copy，具体的可以看下TCPConn.ReadFrom实现，然后两个TCPConn时互相ReadFrom就可以了

用标准库实现起来很简单，俩协程就可以。如果不是单个service节点有海量连接数，协程数量压力不大，标准库足够好了。

如果是海量连接数，用nbio时用ET模式并且，g.OnRead自定制读事件的handler，然后在handler内自己用syscall.Splice应该也是可以实现的，但是逻辑要比标准库多许多

**Comment by lesismal** [comment]
如果是应用层需要做一些额外的逻辑，zero copy就没法用了，而且go的指令比c/cpp/rust要慢比较多，性能肯定就上不去了。
如果只是纯转发，语言本身的逻辑不是特别多、主要是syscall，那与rust的差距应该不会太大。

**Comment by ffcdn** [comment]
谢谢大佬，受益良多！！太喜欢您的解答了，客观公正又专业

**Comment by lesismal** [comment]
> 谢谢大佬，受益良多！！太喜欢您的解答了，客观公正又专业

过奖了，欢迎多多交流:smile:

**Comment by Yajun312890225** [comment]
> 兄弟是想用splice这种吧？
> 
> 纯转发的话，用标准库好些，没必要用nbio，标准库比如TCPConn，自己就有ReadFrom的方法、会判断是否支持splice，支持的话就直接用splice了也就是zero copy，具体的可以看下TCPConn.ReadFrom实现，然后两个TCPConn时互相ReadFrom就可以了
> 
> 用标准库实现起来很简单，俩协程就可以。如果不是单个service节点有海量连接数，协程数量压力不大，标准库足够好了。
> 
> 如果是海量连接数，用nbio时用ET模式并且，g.OnRead自定制读事件的handler，然后在handler内自己用syscall.Splice应该也是可以实现的，但是逻辑要比标准库多

兄弟有可能不太行吧，两个TCPConn 互相ReadFrom，这个方法是阻塞的，不能每次接受到数据后SetDeadline，超时就自动关闭了
