### ISSUE TITLE
关于社区联系方式

### ISSUE THREAD

**Issue by cexll** [lesismal/nbio#198]
halo大佬 有qq/wx 群聊吗 或者能加上大佬微信  
但是我更希望搞一个群聊 平时分享一下技术 书籍 聊聊天都是非常不错的

**Comment by lesismal** [comment]
感谢关注，qq/wx zz太敏感了，容易连带着遭殃，所以不打算用 qq/wx 。

有 slack 频道，也还算方便：
https://join.slack.com/t/arpcnbio/shared_invite/zt-1d3m133y9-ASG_hPzTyX~Njox_MDd9OQ

**Comment by yeyuqiu** [comment]
> 感谢关注，qq/wx zz太敏感了，容易连带着遭殃，所以不打算用 qq/wx 。
> 
> 有 slack 频道，也还算方便： https://join.slack.com/t/arpcnbio/shared_invite/zt-1d3m133y9-ASG_hPzTyX~Njox_MDd9OQ

slack失效了，麻烦给个新的吧

**Comment by lesismal** [comment]
这里：
https://join.slack.com/t/lesismal/shared_invite/zt-1pdth2fld-qqgcgFjdinaCPv_p~w3MVA
