### ISSUE TITLE
希望大佬能开一个异步IO的讨论帖

### ISSUE THREAD

**Issue by dengchengchao** [lesismal/nbio#200]
RT:
slack实在有点不习惯。有一些项目的细节想要咨询一下

**Comment by lesismal** [comment]
可以的，这个issue里就可以聊，或者不同的主题开不同主题的issue

**Comment by dengchengchao** [comment]
嗯嗯，这个issue我先关了哈，我再看看源码先。

**Comment by lesismal** [comment]
其实我觉得github issue比论坛、技术群更适合讨论技术

国内几个go论坛，几年前还好些，现在都是广告、公众号、卖课、招聘之类的赚钱运营为主了，已经很少有人论坛上认真讨论技术了，而且这些论坛的稳定性也不够好

技术群聊天内容多了内容就淹没了、还得额外做笔记整理，而且人多杂乱聊啥的都有、难专注，slack清净干净得多，至少不至于满屏段子开车黄图。各种群里聊多了，反倒浪费很多时间
