### ISSUE TITLE
关于tls支持

### ISSUE THREAD

**Issue by dengchengchao** [lesismal/nbio#201]
想把异步IO用在项目里面，目前项目的背景是面向外网的一个类似websocket项目。由于安全原因必须通过TLS加密。
这里没有详细对比nbio的TLS库的代码。想问下tls代码的改动多吗？如果以后tls升级到更高的版本是不是依赖于这个库的升级？如果改动比较大，感觉这一块也是一个强依赖。

**Comment by lesismal** [comment]
nbio依赖的tls是取自go1.6源码的tls进行的魔改，只是把同步解析改成了支持异步、tls协议本身的逻辑与标准库1.6相同、它支持的nbio也支持、它不支持的nbio也不支持，应该是覆盖了tls1.0-1.3了。

这里有一些基础测试可以参考验证下，包括了tls不同版本、"粘包"测试。
https://github.com/lesismal/nbio-examples/blob/master/tls_sticky_packet/client/client.go#L22

由于标准库是同步阻塞读写，改成异步后是事件、通知或者回调数据事件，解析器的改动是挺大的。nbio依赖的tls由于是直接在标准库源码上魔改，而go是BSD-3，所以tls我单独开了个BSD-3的仓库里了：[llib](https://github.com/lesismal/llib)

**Comment by dengchengchao** [comment]
嗯嗯，简单看了下。但是不太建议修改太多，目前我们遇到的麻烦也是之前为了优化tls+业务鉴权握手，修改了TLS的代码导致现在升级TLS都比较麻烦。
我简单研究了下，如果只支持TLS1.3，是不是修改比较少，毕竟1RTT就可以交换秘钥。 TLS可以修改为服务端accept连接之后，等完全收到客户端的clientHello包之后再回调用OnData()进行handshake。这样加上你dup出来的conn，可以最大程度的复用go原本的tls

**Comment by lesismal** [comment]
> 嗯嗯，简单看了下。但是不太建议修改太多

做的修改都是异步相关的，这个不是能不能修改太多的问题，而是必须修改，因为标准库默认的同步模式，比如一个tls包头拿到了、解析出body长度1024，标准库的net.Conn直接去阻塞读直到读完整1024再去继续解析就行了，但是异步库是不能允许这种阻塞的，当前读到的数据不足1024，只能缓存起来、等下次读到数据了再append拼接起来看是否达到1024了，达到或者超过了可以解析body、否则还得继续等下次数据到来。另外对于buffer部分还做了深度定制的内存优化，否则内存占用比标准库还高

**Comment by lesismal** [comment]
> 我简单研究了下，如果只支持TLS1.3，是不是修改比较少，毕竟1RTT就可以交换秘钥。 

1.3本身就是1RTT的吧？
标准库原有的tls的流程我没有去改变，所以如果1.3本来就是1RTT，那么nbio里面应该也是1RTT的。


> TLS可以修改为服务端accept连接之后，等完全收到客户端的clientHello包之后再回调用OnData()进行handshake。这样加上你dup出来的conn，可以最大程度的复用go原本的tls

不管是标准库阻塞读的模式，还是异步库异步数据回调的模式，首先都得有数据后去解析协议才能知道当前是否收到了对方一个完整的TLS Packet，所以 “等完全收到客户端的clientHello包之后再回调用OnData()” 这个说法就是不准确的，应该是先有 OnData 的逻辑然后才能知道是否收到了完整的cleintHello，而且收到数据就去OnData也并不影响tcp层面的1RTT，因为如果当前没有读到完整的clientHello、即使调用了OnData也并不会去发送Key Exchange、Server Params那些数据出去

**Comment by lesismal** [comment]
[data.pcap.zip](https://github.com/lesismal/nbio/files/9309168/data.pcap.zip)

我这里简单测试了下 TLS1.3，tcpdump抓包看了下，大概看了下，没有太详细分析，你看下分析的对不：
<img width="1280" alt="1660226013371" src="https://user-images.githubusercontent.com/40462947/184149593-b6ed78a0-09db-40b1-9736-06365649a0a9.png">

zip里的pcap文件，或者你自己也可以抓包分析下看看还需要优化不

**Comment by lesismal** [comment]
> 目前我们遇到的麻烦也是之前为了优化tls+业务鉴权握手，修改了TLS的代码导致现在升级TLS都比较麻烦。

你们之前也是自己改了一下标准库？升级是指升级TLS版本还是你们自己修改的TLS库？是修改了哪些部分的代码导致升级困难？

**Comment by dengchengchao** [comment]
> > 我简单研究了下，如果只支持TLS1.3，是不是修改比较少，毕竟1RTT就可以交换秘钥。
> 
> 1.3本身就是1RTT的吧？ 标准库原有的tls的流程我没有去改变，所以如果1.3本来就是1RTT，那么nbio里面应该也是1RTT的。
> 
> > TLS可以修改为服务端accept连接之后，等完全收到客户端的clientHello包之后再回调用OnData()进行handshake。这样加上你dup出来的conn，可以最大程度的复用go原本的tls
> 
> 不管是标准库阻塞读的模式，还是异步库异步数据回调的模式，首先都得有数据后去解析协议才能知道当前是否收到了对方一个完整的TLS Packet，所以 “等完全收到客户端的clientHello包之后再回调用OnData()” 这个说法就是不准确的，应该是先有 OnData 的逻辑然后才能知道是否收到了完整的cleintHello，而且收到数据就去OnData也并不影响tcp层面的1RTT，因为如果当前没有读到完整的clientHello、即使调用了OnData也并不会去发送Key Exchange、Server Params那些数据出去

嗯，TLS1.3 是1RTT的，我的意思是在网络库和TLS加一个中间层，这个中间层先缓存clientHello的数据，等clientHello接受完毕再调用TLS的handshake，不过从抓包来看，似乎不止一次RTT，明天我有空详细研究下

**Comment by dengchengchao** [comment]
> > 目前我们遇到的麻烦也是之前为了优化tls+业务鉴权握手，修改了TLS的代码导致现在升级TLS都比较麻烦。
> 
> 你们之前也是自己改了一下标准库？升级是指升级TLS版本还是你们自己修改的TLS库？是修改了哪些部分的代码导致升级困难？

这个涉及到项目的一些细节，不太方便细说，要是大佬不介意的话，可以加个微信吗

**Comment by dengchengchao** [comment]
> 嗯，TLS1.3 是1RTT的，我的意思是在网络库和TLS加一个中间层，这个中间层先缓存clientHello的数据，等clientHello接受完毕再调用TLS的handshake，不过从抓包来看，似乎不止一次RTT，明天我有空详细研究下

因为只有一个RTT，所以可以这样实现，因为服务端只用等待接受一次数据

**Comment by lesismal** [comment]
> 嗯，TLS1.3 是1RTT的，我的意思是在网络库和TLS加一个中间层，这个中间层先缓存clientHello的数据，等clientHello接受完毕再调用TLS的handshake，不过从抓包来看，似乎不止一次RTT，明天我有空详细研究下

都是一样的道理，不先解析、就无法知道是否已经收到完整的clientHello

**Comment by lesismal** [comment]
> 这个涉及到项目的一些细节，不太方便细说，要是大佬不介意的话，可以加个微信吗

鹅家的软件都太吵闹了，可以的话slack吧：
https://join.slack.com/t/arpcnbio/shared_invite/zt-1d3m133y9-ASG_hPzTyX~Njox_MDd9OQ
