### ISSUE TITLE
Webtransport

### ISSUE THREAD

**Issue by nicoroy2561** [lesismal/nbio#204]
Hi,
I've been using nbio for a while now and I love the package.
Thank you for building it :)

I've been looking into Webtransport as a replacement for websockets.
I understand that, with nbio, your goal was to implement a truly "non-blocking io", and I think the library perfectly reaches this goal.

I was wondering if you were following the development of Webtransport (over http/3 - quic), as that seems a likely replacement for websocket moving forward, and what your thoughts were on implementing the protocol itself within nbio (or an nbio version that uses webtransport in place of websockets).

**Comment by lesismal** [comment]
Thank you @nicoroy2561  and I really appreciate your trying on `nbio` and your affirmation!

`http/3 - quic` is based on `udp`, `nbio` doesn't support `udp` by now because std's `udp` is simple enough and easier to implement non-blocking interface.
I have thought aoubt supportting HTTP/2 and HTTP/3 many times, but each of them is a big project for me. I think it will cost me at least 3-6 months for each, but I don't have that much time, so there's no schedule by now.

**Comment by nicoroy2561** [comment]
Thank you @lesismal for the quick answer!

I would definitely avoid "supporting" http/2 as it doesn't make much sense (websocket uses http/1.1 as far as I know and there's no standard that relies on http/2). If your tests have even shown it performs worse than http/1.1 then it's probably not worth pursuing.

As per Webtransport, there's an implementation at https://github.com/adriancable/webtransport-go and another at https://github.com/marten-seemann/webtransport-go (this latter one also supporting client connections).
It might be worth trying to integrate either as a test, perhaps.
Having those implementations available might also prove good for understanding the protocol itself.

I definitely think it'd be good to have both Websocket and Webtransport support in the future, to fall back to the first in case the latter has any issues.
I personally have no experience in working on a network stack, but in case am willing to try help out in my spare time :)

**Comment by lesismal** [comment]
> As per Webtransport, there's an implementation at https://github.com/adriancable/webtransport-go and another at https://github.com/marten-seemann/webtransport-go (this latter one also supporting client connections).
It might be worth trying to integrate either as a test, perhaps.
Having those implementations available might also prove good for understanding the protocol itself.

Thanks, I'll read these libs' code, I think `webtransport` is simple.
But `quic` is more complex, we need more effort on it.

> I personally have no experience in working on a network stack, but in case am willing to try help out in my spare time :)

That's great! Welcome to communicate!

**Comment by nicoroy2561** [comment]
After spending some time reading through the libraries, I think I now understand your concerns.

As you noted, the webtransport implementation itself seems to be rather straightforward.
The issue is the http/3 implementation which seems to be quite complex overall.

I think the key would be seeing if quic-go (https://github.com/lucas-clemente/quic-go) has a low-level enough implementation exposed that would allow you to use it with Epoll.
If it did, you'd likely be able to leverage most of the work you've done with nbio and the way it handles connections.

An alternative could be creating a fork of quic-go that exposes the low-level API to integrate it with nbio - with the http/3 spec being finalized I don't think that implementation will change much.
Would you be open to base a Webtransport support over quic-go (MIT license seems permissive) or would you only consider fully implementing http/3 separately?

**Comment by lesismal** [comment]
> As you noted, the webtransport implementation itself seems to be rather straightforward.
The issue is the http/3 implementation which seems to be quite complex overall.

Yes, you're right!

> I think the key would be seeing if quic-go (https://github.com/lucas-clemente/quic-go) has a low-level enough implementation exposed that would allow you to use it with Epoll.
If it did, you'd likely be able to leverage most of the work you've done with nbio and the way it handles connections.

That's not easy. There have been some go implementation for quic, but there are same problems like the std's net that it cost no less than 1 goroutine for each quic-connection. Then, if there are a lot of udp sessions, there will be a huge num of goroutines and the process comes into the unhealthy state.

> An alternative could be creating a fork of quic-go that exposes the low-level API to integrate it with nbio - with the http/3 spec being finalized I don't think that implementation will change much.
Would you be open to base a Webtransport support over quic-go (MIT license seems permissive) or would you only consider fully implementing http/3 separately?

We need to implement async-parser for nbio, can not easily reuse quic-go or other lib's code, that cost lots of time.

**Comment by lesismal** [comment]
I aim to reduce the huge resource cost when there are lots of connections, if there are not too many connections, libs like quic-go will work fine.

**Comment by nicoroy2561** [comment]
> I aim to reduce the huge resource cost when there are lots of connections, if there are not too many connections, libs like quic-go will work fine.

That's what I thought. And that's honestly why I appreciate nbio as much, so I wouldn't want to suggest giving up on that.

> That's not easy. There have been some go implementation for quic, but there are same problems like the std's net that it cost no less than 1 goroutine for each quic-connection. Then, if there are a lot of udp sessions, there will be a huge num of goroutines and the process comes into the unhealthy state.
> 
> ....
>
> We need to implement async-parser for nbio, can not easily reuse quic-go or other lib's code, that cost lots of time.

I'll be forking quic-go and see where the goroutine/conn is spawned and if we can intercept that while keeping the same underlying structure otherwise :)

**Comment by lesismal** [comment]
> I'll be forking quic-go and see where the goroutine/conn is spawned and if we can intercept that while keeping the same underlying structure otherwise :)

That's a good start!
I am considering supporting udp in nbio, and keeping compatibility.

**Comment by nicoroy2561** [comment]
I just came across this:
https://github.com/lucas-clemente/quic-go/issues/3474
Which is basically asking for what we're looking into.

Seems there's little interest from the library contributor; will have to look deeper into the code and see whether a fork is feasible.

**Comment by nicoroy2561** [comment]
I noticed the latest release adds support for UDP traffic.
Amazing job as usual! Thanks for the hard work.

**Comment by lesismal** [comment]
Thank you for your attention!

The UDP implementation wraps the conn session between multi messages from the same client address, examples:
[server](https://github.com/lesismal/nbio-examples/blob/master/udp/server/server.go)
[client](https://github.com/lesismal/nbio-examples/blob/master/udp/client/client.go)

the server log in the examples would be like this:
```sh
ubuntu@ubuntu:~/dev/gopath/src/github.com/lesismal/nbio_examples/udp$ go run ./server/
2022/09/09 15:26:51.342 [INF] NBIO[NB] start listen on: ["udp@127.0.0.1:8888"]
2022/09/09 15:26:54 onData: [0xc000108000, 127.0.0.1:59016], hello 0
2022/09/09 15:26:54 onData: [0xc000108000, 127.0.0.1:59016], hello 1
2022/09/09 15:26:54 onData: [0xc000108000, 127.0.0.1:59016], hello 2
2022/09/09 15:26:55 onClose: [127.0.0.1:59016], read timeout
``` 

There's the convenience that we can use the *Conn directly(as showed in the log: 0xc000108000 is the same *Conn pointer), just manage the session by timeout, because SetDeadline interfaces are also supported by nbio 😄.

But QUIC is still a huge project, hahaha, hope one day we can make it!

**Comment by lesismal** [comment]
There's a related issue about udp io optimization: https://github.com/golang/go/issues/45886#issuecomment-1240728221

We can implement it without std syscall's support for [recvmmsg](https://man7.org/linux/man-pages/man2/recvmmsg.2.html)  but need to add multi files for different platforms' struct typedef.

So I prefer to support [recvmmsg](https://man7.org/linux/man-pages/man2/recvmmsg.2.html) in the future when std provides syscall.RecvMMsg.

**Comment by nicoroy2561** [comment]
> There's the convenience that we can use the *Conn directly(as showed in the log: 0xc0000a2320 is the same *Conn pointer), just manage the session by timeout, because udp SetDeadline interfaces are also supported by nbio.

Amazing work. Will try it out in the coming days!

> But QUIC is still a huge project, hahaha, hope one day we can make it!

Indeed. I'll keep looking into the quic-go implementation, see what I can come up with.


>There's a related issue about udp io optimization: https://github.com/golang/go/issues/45886#issuecomment-1240728221
We can implement it without std syscall's support for [recvmmsg](https://man7.org/linux/man-pages/man2/recvmmsg.2.html) but need to add multi files for different platforms' struct typedef.
So I prefer to support [recvmmsg](https://man7.org/linux/man-pages/man2/recvmmsg.2.html) in the future when std provides syscall.RecvMMsg.

That's quite interesting. It seems things are moving now with that proposal, so it might not be too much further down the line.

Since you already implemented UDP support in nbio though, we could start with finding a way to implement quic and later upgrade to recvmmsg once it becomes available.

**Comment by nicoroy2561** [comment]
I've been looking into the quic-go implementation a bit more, and I think there are 2 possibilities:

1) A fork that exposes a modified server which takes in a function to call for storing new connections outside of quic-go (onAccept) and an onMessage callback to handle it within quic-go, as well as another callback to send message on a connection stored outside.
This would allow us to use epoll with quic-go but not nbio itself - as we'd be forced to use the quic-go server implementation.

2) A fork that exposes functions to decode and return Quic messages (onMessage), open streams and basically implement a whole server separately (would have to look into congestion control and other stuff too I suppose).
This would allow us to use nbio while relying on quic-go for decoding and everything else.
 
I think 2) is what we're after, but it does seem like it might take a while.
I also think quic-go is quite complex overall as an implementation. We might want to consider

3) rewriting (a fork of) quic-go in a more streamlined way, exposing its useful internals while getting rid of what's not needed (e.g. the server implementation itself, exposing only internals necessary to implement it)


The main issue with 2) and 3) is that they would likely (2) and definitely (3) end up resulting in a different repo. Meaning we'd have to maintain a separate quic implementation ourselves (though we could still try and integrate relevant quic-go upstream changes).

I'd like to hear your thoughts on this. How do you think we should proceed?

**Comment by lesismal** [comment]
I think it's better to implement a new one, or else we can't keep the code clean.

**Comment by nicoroy2561** [comment]
> I think it's better to implement a new one, or else we can't keep the code clean.

Fair enough. Do you want help with that?
If you make a new repo and give me collaborator access, we can get started on it :)
In case you have time, that is.

**Comment by lesismal** [comment]
> 

I don't have too much time this year, you can create the project.

**Comment by nicoroy2561** [comment]
I'll have a go at it then :) letting you know once things start getting somewhere!

**Comment by nicoroy2561** [comment]
I'll go ahead and close this for the time being - I'll eventually open a new issue if I get anything done.
Worthy of note is that the UDP change liked above has been accepted by the golang team.

Thank you as usual both for the hard work and the consideration :)
