### ISSUE TITLE
eventfd 用来干嘛了

### ISSUE THREAD

**Issue by buffge** [lesismal/nbio#206]
看见你代码里有evtfd 但是没有地方用到

**Comment by lesismal** [comment]
你用的mac吧？kqueue好像确实没用到，后面版本我清理掉
linux主要是退出的时候用于触发循环

**Comment by buffge** [comment]
我用的linux,我的锅 没仔细看代码 是为了退出rwLoop循环
还有个问题 代码中很多 //go:norace 是为了减少编译时间吗

**Comment by lesismal** [comment]
> 我用的linux,我的锅 没仔细看代码 是为了退出rwLoop循环 还有个问题 代码中很多 //go:norace 是为了减少编译时间吗

norace是为了消除race test时的告警，这些原本的代码为了性能不适合使用锁、原子之类的并且是已知的安全，前阵子 @zbh255 pr了这些来消除告警。

相关:
https://github.com/lesismal/nbio/issues/145
https://github.com/lesismal/nbio/issues/149
https://github.com/lesismal/nbio/pull/195
https://github.com/lesismal/nbio/pull/196

**Comment by buffge** [comment]
谢谢
