### ISSUE TITLE
当发送“大量消息体积比较大“的消息时，会出现消息不完整的情况

### ISSUE THREAD

**Issue by Sinclair-Ni** [lesismal/nbio#217]
单条消息体积在 64kb 以内大概 55kb 左右，会被切割，好像内部默认 32kb 被切割一次，然后当一直发送（300客户端，消息每秒10次左右）这种 大容量消息 的时候，大概率会出现消息不被完整拼接后发送出去的情况。client 端接收到的不完整消息大小依旧是 55kb 左右，但是是那种明显被切割过两段不完整的情况。

**Comment by lesismal** [comment]
首先，如果只是TCP的OnData中这是正常的，因为TCP本来就是流。应用层自己的协议包应该由用户自己来维护。

其次，32k被切割一次是因为nbio的默认read bufer size是32k:
https://github.com/lesismal/nbio/blob/master/engine.go#L19

如果你们的业务需要更大的ReadBuffer，可以通过配置修改这个值：
```golang
server = nbio.NewEngine(nbhttp.Config{
	// other params

	ReadBufferSize: 1024 * N,
})
```

但ReadBufferSize只是单次最大读取，而TCP协议本身是不能保证你的一端发送的包都同时到达对端的，所以如同我在"首先"中说的，你们应用层自己仍然需要负责协议包完整性的逻辑

**Comment by lesismal** [comment]
如果也需要发送大包，也可以设置TCP发送缓冲区大小来提高写效率：`c.SetWriteBuffer(N)`

**Comment by Sinclair-Ni** [comment]
好的，顺序问一下，nbhttp 里面的  Engin 和外面的 nbio.Engin 有什么区别吗？我目前用的是 nbhttp 包里的内容

**Comment by lesismal** [comment]
> 好的，顺序问一下，nbhttp 里面的 Engin 和外面的 nbio.Engin 有什么区别吗？我目前用的是 nbhttp 包里的内容

区别就是分别处理4层和7层，其实这本身是网络协议栈的区别。网络协议栈的知识，建议系统学习下，前期可以看《图解tcp/ip》、比较容易读懂的，进阶可以看《tcp/ip详解》。计算机网络的教材之类的也可以

如果有兴趣深入研究，也可以读下源码，但还是先学协议栈基础知识做铺垫好些
