### ISSUE TITLE
BeforeWrite阻塞

### ISSUE THREAD

**Issue by Kotodian** [lesismal/nbio#220]
我在Write里打印了各种日志 发现有BeforeWrite的时候,在linux中调用Write会阻塞死,用demo没有复现,有时间完善下问题

**Comment by lesismal** [comment]
请提供个能够复现的代码我试下

**Comment by lesismal** [comment]
我看了下源码，好像是有这个问题，如果调用了SetDeadline之类的应该是可能导致死锁，我复现下、确认的话发个修复

**Comment by Kotodian** [comment]
> 我看了下源码，好像是有这个问题，如果调用了SetDeadline之类的应该是可能导致死锁，我复现下、确认的话发个修复

是的 我的BeforeWrite是设置WriteDeadline, 在windows下应该是走系统调用(不确定), linux下应该有用锁

**Comment by lesismal** [comment]
Windows下是封装的std，直接用了net.TCPConn自带的SetDeadline，所以不需要加锁、不会导致这个问题。

发了个版本：https://github.com/lesismal/nbio/releases/tag/v1.3.2

感谢反馈！
