### ISSUE TITLE
"invalid HTTP method" while trying to read websocket message

### ISSUE THREAD

**Issue by susuper** [lesismal/nbio#225]
Hello.
I am trying to use your module to implement simple websocket client.
In the example below I am getting "invalid HTTP method" error at the most times I try to run the code.
According to debugger, the error happens at line 239 of nbhttp/parser.go (v1.3.3).
Sometimes the code starts to read and send websocket messages, but can't find any dependency.
I would like to ask if I am doing something wrong?) 
Thank you!

```
package main

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/url"
	"os"
	"os/signal"
	"time"

	"github.com/lesismal/nbio/nbhttp"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

func newUpgrader() *websocket.Upgrader {
	u := websocket.NewUpgrader()

	u.OnOpen(func(c *websocket.Conn) {
		log.Println("OnOpen:")
	})

	u.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
		log.Println("OnMessage:", string(data))

		c.WriteMessage(websocket.TextMessage, []byte("{\"event\":\"ping\"}"))
	})

	u.OnClose(func(c *websocket.Conn, err error) {
		fmt.Println("OnClose:", c.RemoteAddr().String(), err)
	})

	return u
}

func main() {
	engine := nbhttp.NewEngine(nbhttp.Config{})
	err := engine.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}

	go func() {
		u := url.URL{Scheme: "wss", Host: "ws.kraken.com", Path: ""}
		dialer := &websocket.Dialer{
			Engine:            engine,
			Upgrader:          newUpgrader(),
			DialTimeout:       time.Second * 10,
			EnableCompression: true,
		}
		_, res, dErr := dialer.Dial(u.String(), nil)
		if dErr != nil {
			var bReason []byte
			if res != nil && res.Body != nil {
				bReason, _ = io.ReadAll(res.Body)
			}
			fmt.Printf("dial: %v; reason: %s; code: %d\n", dErr, string(bReason), res.StatusCode)

			return
		}
	}()

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()
	engine.Shutdown(ctx)
}
```

**Comment by lesismal** [comment]
I tried a simple server with `localhost` and `InsecureSkipVerify: true`, then use your client code to test, but it is running fine.
Would you please provide the server code that can reproduce it?

**Comment by susuper** [comment]
> I tried a simple server with `localhost` and `InsecureSkipVerify: true`, then use your client code to test, but it is running fine. Would you please provide the server code that can reproduce it?
Thank you for quick response.
So basically you see no errors at my implementation of websocket client?
Unfortunately the server code is out of my reach. I will try to catch the situation where incoming messages are handling properly by my client.

**Comment by lesismal** [comment]
This is my test code: [test.zip](https://github.com/lesismal/nbio/files/9780060/test.zip)

**Comment by susuper** [comment]
Also my code seems to work fine after commenting line 241 at nbhttp\parser.go:
```
		case stateClientProtoBefore:
			if c == 'H' {
				start = i
				p.nextState(stateClientProto)
				continue
			}
			//return ErrInvalidMethod
```

**Comment by lesismal** [comment]
I tried your code that connects to `ws.kraken.com` and reproduced it, working on it now.

**Comment by lesismal** [comment]
I made a new commit, please try it: https://github.com/lesismal/nbio/commit/b324cd76ecbbfdb3338c7aff698e677c8e536825
I tried many times with this commit version and it runs fine. If it also works for you, I'll publish a new version.

The reason for this issue should be like this comment here: 
https://github.com/lesismal/nbio/blob/master/nbhttp/processor.go#L402

**Comment by susuper** [comment]
Thank you, the latest [d168827](https://github.com/lesismal/nbio/commit/d168827e1138b02afa9b016bc2b410b1aae8e109) works like a charm!

**Comment by lesismal** [comment]
Published: https://github.com/lesismal/nbio/releases/tag/v1.3.4

Thank you for your feedback!

**Comment by stepan-romankov** [comment]
This is back in v1.5.12 and version 1.6.1 crashes with 
`
goroutine 50 [running]:
github.com/lesismal/nbio/nbhttp.(*ClientConn).Do.func1()
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/nbio@v1.6.1/nbhttp/client_conn.go:171 +0xa4
panic({0x104fca400?, 0x1051e1ed0?})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:785 +0x124
github.com/lesismal/llib/std/crypto/tls.(*Conn).readFromUntil(0x1051e3e30?, {0x12be7d998?, 0x14001526008?}, 0x104d5d35c?, 0x14000282000?)
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/llib@v1.2.0/std/crypto/tls/conn.go:970 +0x28
github.com/lesismal/llib/std/crypto/tls.(*Conn).readRecordOrCCS(0x1400010a008, 0x0)
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/llib@v1.2.0/std/crypto/tls/conn.go:754 +0x25c
github.com/lesismal/llib/std/crypto/tls.(*Conn).readRecord(...)
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/llib@v1.2.0/std/crypto/tls/conn.go:678
github.com/lesismal/llib/std/crypto/tls.(*Conn).readHandshake(0x1400010a008)
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/llib@v1.2.0/std/crypto/tls/conn.go:1211 +0x9c
github.com/lesismal/llib/std/crypto/tls.(*Conn).clientHandshake(0x1400010a008)
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/llib@v1.2.0/std/crypto/tls/handshake_client.go:171 +0x1a4
github.com/lesismal/llib/std/crypto/tls.(*Conn).Handshake(0x1400010a008)
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/llib@v1.2.0/std/crypto/tls/conn.go:1737 +0x44
github.com/lesismal/nbio/nbhttp.(*ClientConn).Do(0x14001696090, 0x1400169a000, 0x140016a0000)
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/nbio@v1.6.1/nbhttp/client_conn.go:306 +0xc90
github.com/lesismal/nbio/nbhttp/websocket.(*Dialer).DialContext(0x14001684000, {0x10501efb0, 0x14001684070}, {0x1400168e000, 0x24}, 0x0, {0x0, 0x0, 0x30?})
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/nbio@v1.6.1/nbhttp/websocket/dialer.go:170 +0xdcc
github.com/lesismal/nbio/nbhttp/websocket.(*Dialer).Dial(0x14001684000?, {0x1400168e000?, 0x24?}, 0x0?, {0x0?, 0x0?, 0x0?})
	/Users/stepan_romankov/go/pkg/mod/github.com/lesismal/nbio@v1.6.1/nbhttp/websocket/dialer.go:59 +0x100
main.main.func1()

`
