### ISSUE TITLE
Documention about internals 

### ISSUE THREAD

**Issue by Narasimha1997** [lesismal/nbio#229]
Is there any document/article that describes how this is different from traditional web server/ I/O frameworks in go and details of internal architecture and design decisions?

**Comment by lesismal** [comment]
It's more like c/cpp's event-driven frameworks, the main points:
1. async-io(reactor by default, user can custom handlers to implement proactor), poller/pollers run in one or a few io goroutines(configurable)
2. async-parser
3. logic goroutine pool with size limited
4. buffer pool

For more details, please read the code.
