### ISSUE TITLE
runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by nickolastone** [lesismal/nbio#239]
env
mac os,  m1 cpu
nbio version . 1.3.5 

start run will got

`panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/lesismal/nbio.NewEngine({{0x1050e5527, 0x2}, {0x0, 0x0}, {0x0, 0x0, 0x0}, 0xa, 0x8000, 0x0, ...})
        /Users/nickolast/code/nickolastone/nerv/vendor/github.com/lesismal/nbio/engine_unix.go:131 +0x128
github.com/lesismal/nbio/nbhttp.NewEngine({{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...})
        /Users/nickolast/code/nickolastone/nerv/vendor/github.com/lesismal/nbio/nbhttp/engine.go:871 +0x538
github.com/lesismal/nbio/nbhttp/websocket.init()
        /Users/nickolast/code/nickolastone/nerv/vendor/github.com/lesismal/nbio/nbhttp/websocket/upgrader.go:35 +0x7b4`

i think it's wrong at github.com/lesismal/nbio/net_unix.go

`func init() {
	var limit syscall.Rlimit
	if err := syscall.Getrlimit(syscall.RLIMIT_NOFILE, &limit); err ==nil {
		if n := int(limit.Max); n > 0 {
			MaxOpenFiles = n
		}
	}
} `

MaxOpenFiles is too big like 9223372036854775807

**Comment by lesismal** [comment]
Thank you for your feedback!

It's the same as https://github.com/lesismal/nbio/issues/238#issuecomment-1300766454

You can set a suitable `MaxOpenFiles` to solve this or wait for my next release.

**Comment by lesismal** [comment]
Please try the latest commit:
```sh
go get -u github.com/lesismal/nbio@76daa64
```

**Comment by lesismal** [comment]
Fixed by [v1.3.6](https://github.com/lesismal/nbio/releases/tag/v1.3.6).
