### ISSUE TITLE
客户端建立连接后循环发送多个包，服务端只读取到一个

### ISSUE THREAD

**Issue by soukengo** [lesismal/nbio#243]
客户端建立连接后循环发10个包，服务端通过注册的OnData回调里只收到1个包，而在OnRead回调中循环读取，则会报错“panic: bufio: reader returned negative count from Read”

https://github.com/soukengo/gnettest/blob/main/pkg/server/socket/network/nbio/server.go

**Comment by lesismal** [comment]
nbio提供的是非阻塞读写接口，不适合像用标准库那样当成阻塞的读写接口用 bufio 之类的在标准库加工过的 Conn 基础上来处理的。
nbio这个Read我看了下，uni*下应该是返回的 syscall.Read 的值，我扫了下你的测试代码，给nbio加了日志看，nbio.Conn.Read 应该是返回 -1, EAGAIN 了。EAGAIN 的意思就是当前没有可读数据、应用层应该结束本次读取了，等待下次可读事件再触发OnRead时再读。
而bufio这个Reader里面的逻辑判断-1直接panic了。

如果一定要自己定制，可以参考下 nbio poller 部分实际读取的代码的逻辑，否则建议直接用OnData好些。或者像 gnet 那样，自己定制一个类似 bufio 这样的来处理与异步库共同使用时的细节。

**Comment by lesismal** [comment]
即使 nbio 封装 syscall.Read 不返回 -1，用 bufio Reader 也还有其他问题。
异步库，你直接把 bufio Reader 里 buf 的一段返回给应用层了，而应用层解析到一个包后，通常是要丢个逻辑协程去处理逻辑，应用层就可能持有这段 buf，而下次 IO 的时候，bufio Reader.fill 的时候，可能就重新把数据移动到它的 buf 头部，也就是说覆盖了原来的前段，当前正被你的应用层持有的那段 buf 就可能被 IO 协程的 Read 给覆盖了:
https://github.com/golang/go/blob/master/src/bufio/bufio.go#L190
https://github.com/golang/go/blob/master/src/bufio/bufio.go#L94

**Comment by lesismal** [comment]
golang异步库真正和应用层结合起来要多考虑些细节，我在gnet的issue里也有提到一些，nbio合理使用都能解决（在tls/http/websocket都已经搞定了），但是其他一些框架目前的处理方式是很难解决的

**Comment by soukengo** [comment]
感谢大佬回复，如果直接用OnData，但是目前测试只收到一个包呢

**Comment by lesismal** [comment]
> 感谢大佬回复，但是直接使用OnData，目前测试只收到一个包呢

client连续写多个，server可能一次可读事件时就已经收到了多个，nbio默认的read buffer是32k，所以一次读取可能就是读出了多个包、比如十个全读到了。
TCP是流，咱不能确保单次正好读到一个完整包，所以解析一段buf的逻辑应该是循环解析的，但你这里好像只解析了一次，也就是10个包的buf你只解析到一个就返回了：
https://github.com/soukengo/gnettest/blob/main/pkg/server/socket/packet/parser.go#L17

你可以在这里加个日志看看OnData的data长度是多少、你解析出来的包的长度是多少，然后就好定位了

**Comment by soukengo** [comment]
明白了，感谢

**Comment by lesismal** [comment]
循环解析后，也是可能有剩余数据的，比如本次OnData是8.5个包，你循环解析出8个，剩下的0.5个，要缓存起来跟下次到达的数据拼接起来。如果想简单，就nbioConn里对应一个bytes.Reader，每次OnData，先往这个reader.Write，再把reader传给你的packet去解析，不过这可能不是性能和内存占用的最佳实践，就像我在gnet那个issue里说的，这种每个conn对应一个buffer，高在线量时的开销甚至可能比标准库更大，因为还涉及消息的跨协程处理。
所以针对高在线量场景，nbio自带的http/websocket或者tls，都是定制了内存使用的。

而普通在线量，poller的吞吐并不比标准库有优势，反而是异步、流解析器，跨协程的buffer和各种变量逃逸以及生命周期、调度亲和性劣势。
基于这些客观情况，综合下来，标准库方案的每个连接至少一个协程的方式可能更适合普通在线量的业务。

过去的一年多里，性能难以赶上标准库这个问题一直困扰我，直到最近我放弃了基于异步接口的性能赶超标准库，而是支持了不同的IO模式来实现不同在线时的性能诉求与开销的平衡，详情在这里：
https://github.com/lesismal/nbio/releases/tag/v1.3.5

**Comment by soukengo** [comment]
> 循环解析后，也是可能有剩余数据的，比如本次OnData是8.5个包，你循环解析出8个，剩下的0.5个，要缓存起来跟下次到达的数据拼接起来。如果想简单，就nbioConn里对应一个bytes.Reader（而不是每次OnData创建一个），每次OnData，先往这个reader.Write，再把reader传给你的packet去解析，不过这可能不是性能和内存占用的最佳实践，就像我在gnet那个issue里说的，这种每个conn对应一个buffer，高在线量时的开销甚至可能比标准库更大，因为还涉及消息的跨协程处理。 所以针对高在线量场景，nbio自带的http/websocket或者tls，都是定制了内存使用的。
> 
> 而普通在线量，poller的吞吐并不比标准库有优势，反而是异步、流解析器，跨协程的buffer和各种变量逃逸以及生命周期、调度亲和性劣势。 基于这些客观情况，综合下来，标准库方案的每个连接至少一个协程的方式可能更适合普通在线量的业务。
> 
> 过去的一年多里，性能难以赶上标准库这个问题一直困扰我，直到最近我放弃了基于异步接口的性能赶超标准库，而是支持了不同的IO模式来实现不同在线时的性能诉求与开销的平衡，详情在这里： https://github.com/lesismal/nbio/releases/tag/v1.3.5

我先简单使用bytes.Reader来处理，每个conn对应一个buffer。我再研究一下如何解决内存开销的问题。

目前前面的问题解决了，感谢大佬耐心的回复，麻烦你帮我把这个issue关闭了哈。
