### ISSUE TITLE
req.Body 是否可以不强制复用,与其他库冲突,有些库会包装req.Body

### ISSUE THREAD

**Issue by buffge** [lesismal/nbio#248]
[file nbhttp.processor.go:42](https://github.com/lesismal/nbio/blob/master/nbhttp/processor.go#L42)
```go
func releaseRequest(req *http.Request) {
	if req != nil {
		if req.Body != nil {
// 这里是否可以改为 req.Body.Close()  如果body 是 BodyReader再put呢
			br := req.Body.(*BodyReader)
			br.Close()
			bodyReaderPool.Put(br)
		}
		// fast gc for fields
		*req = emptyRequest
		requestPool.Put(req)
	}
}
```
有一个非常常用的库 sentry 它会记录req.Body 会把req.Body包装为一个 io.TeeReader 所以到上面那行类型转换直接就panic了.
sentry的文件: https://github.com/getsentry/sentry-go/blob/master/scope.go#L113

**Comment by lesismal** [comment]
感谢反馈！
我看下，加个配置项，允许不自动Close

**Comment by lesismal** [comment]
[dev](https://github.com/lesismal/nbio/tree/dev)已经加上配置项来设置不自动复用body：
```sh
go get -u github.com/lesismal/nbio@cf9d24c
```

可以这样设置：
```golang
mux := &http.ServeMux{}
mux.HandleFunc("/echo", onEcho)
svr := nbhttp.NewEngine(nbhttp.Config{
	Network:        "tcp",
	Addrs:          []string{"localhost:8080"},
	Handler:        mux,
	RetainHTTPBody: true, // 不自动释放body
})
```

也把主动关闭server的Accept error日志去掉了。

我本地简单测了下这两个应该是都可以了，您闲了试下看看能行不，可以的话我合并到主分支、发布个版本。

**Comment by buffge** [comment]
我先用着dev,用问题再报给你. 用"你"就行 咱俩差不多大

**Comment by buffge** [comment]
你可以理解错我昨天的意思了,我是说 br := req.Body.(*BodyReader)  这个强制断言panic了. body close是没问题的.
我觉得应该应该改成
```
ori:
br := req.Body.(*BodyReader)
br.Close()
bodyReaderPool.Put(br)
curr:
req.Body.Close()
if br,ok := req.Body.(*BodyReader);ok{
   bodyReaderPool.Put(br)
}
```

**Comment by lesismal** [comment]
又提交了下，试试行了不：
```sh
go get -u github.com/lesismal/nbio@2723a1b
```

> 咱俩差不多大

哈哈哈，你多大 😂

**Comment by buffge** [comment]
> 又提交了下，试试行了不：
> 
> ```shell
> go get -u github.com/lesismal/nbio@2723a1b
> ```
> 
> > 咱俩差不多大
> 
> 哈哈哈，你多大 😂
感谢  95年

**Comment by lesismal** [comment]
那还是很羡慕你年轻有朝气的 :joy:

**Comment by lesismal** [comment]
released: https://github.com/lesismal/nbio/releases/tag/v1.3.8
