### ISSUE TITLE
如何不停机的情况添加或变更http/wss的域名

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/nbio#252]
目前查看例子，发现似乎不太可行，如何可以做到nginx那样，不停机的情况下，添加一个server配置呢

**Comment by lesismal** [comment]
这看上去应该是不同层的需求。

nginx域名配置是指作为反代的功能吧？
nbio或者标准库这些主要是http server，还不涉及域名吧。
tls的话，如果证书需要热更，可以稍微改一下这里，用二级指针之类的：
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L318
然后fsnotify或者命令方式重新加载配置后，代码里修改engine的tls配置。或者扩展多一点字段去做，都可以。

但热更配置，也是应该由业务方自己完成，nbio的定位是框架，并非正反代的产品。
