### ISSUE TITLE
Websocket server large memory usage with very few active connections 

### ISSUE THREAD

**Issue by GavinClarke0** [lesismal/nbio#255]
First off, thank you for creating and releasing this. It has been very valuable. 

I have a WebSocket server (server configuration below) which after running for a few minutes rapidly increases in memory usage until the os kills the process. This server never has more than 5 Websocket connections at once. 

Profiling the server shows the memory usage is almost entirely used by the nbio/mempool as shown by this profiling graph below. Given the low tps and connection count of the service this appears to me to possibly be a memory leak (which is likely due to some misconfiguration on my end).

From my monitoring of the service it appears that memory usage just grows until the os kills the process. A graph of memory usage is attached below. The sudden drop is when the process is killed. 

I am hoping you could help me to find an appropriate configuration that avoids the excess memory usage and or diagnose the cause if it is an actual issue. 

**Note:**
- I have `ReleaseWebsocketPayload` set to true as indicated in other similar issues 
 
### Heap Profile
 
![profile001](https://user-images.githubusercontent.com/38338229/210926557-abbb412d-98ee-464f-a07b-ea44446cf28d.png)

### Server Configuration 

```
	svr := nbhttp.NewServer(nbhttp.Config{
		Network:                      "tcp",
		Addrs:                        []string{address},
		MaxLoad:                      10000,
		MessageHandlerPoolSize:       500,
		ReleaseWebsocketPayload:      true,
		NPoller:                      runtime.NumCPU() * 8,
		Handler:                      mux, // standard  http mux
		KeepaliveTime:                time.Second * 60,
		ReadBufferSize:               1024 * 4,
	})
```

### Memory Monitoring Graph
<img width="682" alt="Screen Shot 2023-01-05 at 7 56 55 PM" src="https://user-images.githubusercontent.com/38338229/210927143-7d693f7f-85a9-4565-b8d0-c77d15f544be.png">

**Comment by lesismal** [comment]
Thank you for your feedback.
Would you please provide a demo(server/client) that can reproduce the problem, then I will try to find it.

**Comment by lesismal** [comment]
And, what's the version used in your project?

**Comment by lesismal** [comment]
I see that there're a lot of Malloc during nbio.Conn.flush, is the size of the data written to the conn very huge or another side didn't read it in time? That may be because the tcp write buffer has been full and blocked. If so, please try to set the tcp write buffer to a larger size after `upgrader.Upgrade`:
```golang
if nbc, ok := wsConn.Conn.(*nbio.Conn); ok {
	nbc.SetWriteBuffer(yourSize)
}
```

Demo that can reproduce the problem will be better for troubleshooting.

**Comment by GavinClarke0** [comment]
The version I am using was `v1.3.4`.

What can I do about slow clients or not reading the data in time ? Aggressively drop them ? 

When Clients are closed I notice memory is not reclaimed from the mempool. Is this by design ? 

I will try and to put together a demo server and client quickly. The server is used in fanout manner where we send "subscribed" clients messages from a proprietary source via the Websocket so I do not have a demo example laying around and create one. 

For additional context we are a write heavy workload with very few client reads. Around 200 small messages a seconds written to clients (I may have misspoke when I said low tps). The data is not individually huge on a per message basis but all together may be large. This aligns with with your comment on `nbio.Conn.flush`.

**Comment by lesismal** [comment]
> What can I do about slow clients or not reading the data in time ? Aggressively drop them ?

The speed between producer and consumer should keep balanced.
Usually, the consumer should be able to consume the message in time, else the server should limit the speed of sending. if not allowed to limit the speed of sending, we should allow the consumer to drop some of the messages then we can keep the TCP window in a healthy state.

If it's allowed to limit the speed of sending, it may be better to use std-based solutions if there're not too many connections. The WebSocket connection based on std's net.TCPConn would blocking on Write when the TCP write buffer is full, then it automatically limits the speed of sending. That's much easier to implement the code than a reactor mod framework like nbio, but need to take care of Blocking problems if there is broadcast logic.

> When Clients are closed I notice memory is not reclaimed from the mempool. Is this by design ?

When the Conn is closed, it will free the buffer to mempool:
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L553

But it doesn't mean returning the buffer to the system, because of sync.Pool will still keep the buffer to be reused until there's no buffer request for some moment, it will return the buffer to the system.

If we want to return the buffer to the system as soon as possible after the conn is closed, we can implement another `mempool.Allocator` and replace it: `mempool.DefaultMemPool = yourAllocatorImplementation`.
But I think the real problem is not this, it may be the unhealthy speed between producer and consumer.

> I will try and to put together a demo server and client quickly. The server is used in fanout manner where we send "subscribed" clients messages from a proprietary source via the Websocket so I do not have a demo example laying around and create one.

That would help a lot, I'll be glad to wait for your demo.

> For additional context we are a write heavy workload with very few client reads. Around 200 small messages a seconds written to clients (I may have misspoke when I said low tps). The data is not individually huge on a per message basis but all together may be large. This aligns with with your comment on nbio.Conn.flush.

Let me guess, whether you implement the client-side logic like this:
```golang
for {
    msg, err := client.Read()
    if err != nil {
        ...
    }
    // There may be blocking logic, then Reading will be very slow and block the server-side's TCP Writing.
    // If this is the point, we can try to handle the msg async, in another goroutine, then we won't block Reading.
    handle(msg) 
}
```

**Comment by GavinClarke0** [comment]
> Let me guess, whether you implement the client-side logic like this:

Unfortunately I have zero control over the clients. We are sensitive to their network and client quality.

 Keeping that in mind it appears your hypothesis around slow clients being the root cause is likely correct. This is also supported by my own testing, where using my own clients under consistent network conditions, I have no issues going to 2k clients and beyond. 

> When the Conn is closed, it will free the buffer to mempool:
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L553

Apologies I should of looked into the code. Reusing buffers via a sync pool makes sense.

**Comment by lesismal** [comment]
BTW, when the TCP write buffer is full and blocked, the data is cached wait for a writable event then to flush the data. Before the old cached data has been flushed, new data written to the Conn will be appended to the cache, that may cause your OOM.
If needed, we can set the `MaxWriteBufferSize` with a suitable value, then if the size of the cached data is bigger than it, the Conn will be closed, then avoid OOM.

**Comment by GavinClarke0** [comment]
I am going to close the issue as with your suggestions above and some other modifications I am now able to handle significantly more "slow" clients. I very much appreciate your guidance on this. 

Further profiling after modification now shows that at peak load of 1k slow connections the `mempool` was now only using 1gb of memory which is more than reasonable. The remaining memory was the found to be taken up by the kernel buffers which confirms your hypothesis even further.  

I was unable to create a demo which accurately recreated the issue locally and given the strong evidence for the currently hypothesized root cause I will not spend much more time attempting to create one. 

Thank you for the assistance and the great library!

**Comment by lesismal** [comment]
You are welcome!

**Comment by GavinClarke0** [comment]
Apologies for reopening, I wanted to add a quick question about the mempool and didn't want to lose the context of the issue. Limiting the WriteBuffer has worked to prevent OOM errors so thank you for that solution. 

However, I am now seeing consistent growth in the Mempool during AppendString. I have attached the profile png below. I am curious what behaviour would cause the mempool to consistently grow with no real increase in connections. 

I looked at the code [here](https://github.com/lesismal/nbio/blob/master/mempool/mempool.go). It appears the allocation is held by the Connection object so I imagine that if I am holding reference to the connection I am still holding reference to the buffer which would prevent it from being GC'd. However looking through by allocations in pprof I cannot reference to old connections. 

I am wondering if this is something you have observed before and may have a hypothesis on ? 


### Heap Profile Yesterday
![profile007](https://user-images.githubusercontent.com/38338229/214632175-49be8b77-f4d8-4c9d-ae87-fe32f116f596.png)


### Heap Profile Today 
![profile008](https://user-images.githubusercontent.com/38338229/214631950-2a96a0c2-f7f6-42ee-8dc8-ba9d1c873b8c.png)

**Comment by lesismal** [comment]
If your connections keep sending big buffer and beyond the TCP window's speed, the buffer will be cached/hold by nbio.Conn and waiting for the writable event:
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L394
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L410

Please refer this comment again:
https://github.com/lesismal/nbio/issues/255#issuecomment-1373891838

Also, if want to gc as soon as possible, can implement another `mempool.Allocator` which is not based on `sync.Pool`.

If there aren't a lot of connections, better using std-based solution or `nbhttp.IOModBlocking`, then we gain the automatic limitation of the sending speed and keep a balance.

**Comment by lesismal** [comment]
If possible, you can provide the full examples(server and client), then I'll try it and customize some details for your real service situation.

**Comment by lesismal** [comment]
Here's another example to limit buffer usage: 
https://github.com/lesismal/nbio-examples/blob/master/websocket_tls/server_manual_frame_assembly/server.go

It imeplements a user layer buffer manager to limit both buffer usage, it‘s token bucket rate limiting, as a result, qps/tps speed will be limited automatically. 

This can not solve TCP layer's cache at 
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L394
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L410
But we can implement a mempool.Allocator like this to replace mempool.DefaultMempool

**Comment by GavinClarke0** [comment]
>  However looking through by allocations in pprof I cannot reference to old connections.

My comment above turned out to be wrong. Further analysis did find a reference to the connection which prevent its `writebuffer` from ever being garbage collected. Even after a sync pool is gc'd. This explained the consistent increase of memory usage I was observing . Removing this reference fixed my memory issue.  The default mem-allocator is otherwise working very well. 

Thanks for putting more time into this and apologies for not making sure to ensure my initial conclusion were correct.

**Comment by lesismal** [comment]
> Thanks for putting more time into this and apologies for not making sure to ensure my initial conclusion were correct.

You are welcome! Just feel free to communicate:smile:
