### ISSUE TITLE
OnClose回调遗漏

### ISSUE THREAD

**Issue by suconghou** [lesismal/nbio#256]
由1.2.21升级到1.3.8 ， 代码未做变动，发现onclose 回调有很多遗漏，

例如：
在Chrome控制台new 5个 ws, 刷新后， 1.2.21 将会打印5个链接断开， 1.3.8 只有一个

代码复用了Upgrader，全局都使用一个；  是1.3.8不能复用了吗，还是bug

**Comment by lesismal** [comment]
Upgrader是与每个Conn对应的，它上面有一些状态是与Conn相关的。以前的版本也是不应该共用的，没遇到bug可能只是运气好每次完整包交互并且并发量不大没触发并发的临界问题。否则比如Conn A Upgrade一半，另一个Conn B也Upgrade了，本来Upgrader设置给了A的变量被B重置了。

**Comment by suconghou** [comment]
可以了， 感谢纠正

**Comment by lesismal** [comment]
> 可以了， 感谢纠正

不客气，那这个我先关闭了。
