### ISSUE TITLE
MacOS上跑WebSocket压测挂了

### ISSUE THREAD

**Issue by lxzan** [lesismal/nbio#257]
OS: macOS 13.1 22C65 arm64
go version go1.19.3 darwin/arm64
tcpkali -c 200 -r 20000 -T 20s -f body.json --ws 127.0.0.1:8888/ws
https://github.com/lesismal/nbio-examples/blob/master/websocket/server/server.go

错误堆栈
[ERR] conn execute failed: conn closed
goroutine 17155 [running]:
github.com/lesismal/nbio.(*Conn).Execute.func1.1.1()
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio@v1.2.22-0.20220909121643-7eba463da3a6/conn.go:102 +0x60
panic({0x1022de220, 0x14000110d80})
	/usr/local/go/src/runtime/panic.go:884 +0x204
main.onWebsocket({0x10231fb50, 0x140024b4580}, 0x0?)
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio-examples@v0.0.0-20221027111559-0682cc6cf218/websocket/server/server.go:51 +0x1a0
net/http.HandlerFunc.ServeHTTP(0x14000a8e360?, {0x10231fb50?, 0x140024b4580?}, 0x102223cb8?)
	/usr/local/go/src/net/http/server.go:2109 +0x38
net/http.(*ServeMux).ServeHTTP(0x14000166240?, {0x10231fb50, 0x140024b4580}, 0x14002913f00)
	/usr/local/go/src/net/http/server.go:2487 +0x140
github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio@v1.2.22-0.20220909121643-7eba463da3a6/nbhttp/processor.go:258 +0x44
github.com/lesismal/nbio.(*Conn).Execute.func1.1(0x0?)
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio@v1.2.22-0.20220909121643-7eba463da3a6/conn.go:106 +0x40
github.com/lesismal/nbio.(*Conn).Execute.func1()
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio@v1.2.22-0.20220909121643-7eba463da3a6/conn.go:107 +0x40
github.com/lesismal/nbio/taskpool.(*MixedPool).callWitoutRecover(0x0?, 0x0?)
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio@v1.2.22-0.20220909121643-7eba463da3a6/taskpool/mixedpool.go:38 +0x58
github.com/lesismal/nbio/taskpool.(*MixedPool).Go.func1()
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio@v1.2.22-0.20220909121643-7eba463da3a6/taskpool/mixedpool.go:45 +0x38
created by github.com/lesismal/nbio/taskpool.(*MixedPool).Go
	/Users/caster/go/pkg/mod/github.com/lesismal/nbio@v1.2.22-0.20220909121643-7eba463da3a6/taskpool/mixedpool.go:44 +0x158

**Comment by lesismal** [comment]
嗯嗯，只是示例里的server加了panic，应该是高并发压测、client不停发起新连接的过程中client端关闭了，导致server端Upgrade一半就失败了。
正常业务不会这样直接写panic。

**Comment by lxzan** [comment]
> 嗯嗯，只是示例里的server加了panic，应该是高并发压测、client不停发起新连接的过程中client端关闭了，导致server端Upgrade一半就失败了。 正常业务不会这样直接写panic。

我后面意识到了这不是bug, 赶紧关闭了issue🤣

**Comment by lesismal** [comment]
昨天看到你的 gws，也star了。

跑了下压测，比gorilla要快，nbio的IOModMixed或者IOModBlocking时每个连接至少一个协程的性能也基本持平。

内存消耗方式不一样，nbio的内存消耗是更偏基于qps，并发度需要的buffer数量在pool里共用，每个连接上不自带一个固定的buffer；gws或者其他一些基于标准库的框架多数是每个连接上挂一个bufio.Reader/Writer之类的、是持续占用。
所以当连接数不大但qps很高时，nbio的内存消耗会大于gws或者gorilla之类的但是在可控范围内，qps不高的话可能差不太多；但是连接数很大时，nbio的内存会保持在更低的水准，除非极端情况每个连接都tcp窗口满了之类的导致待发送的cache会占用多，但是这个值是可配置的，超过一定size当做不健康的连接自动断开连接就可以了。
另外就是IOModMixed、IOModNonBlocking，能承载更大的连接数，标准库每个连接一个协程的方式毕竟对协程数量巨大的场景还是扛不住。

看到readme里有这个描述：`zero extra goroutine to manage connection`。
但对于涉及广播的场景，其实还是需要为每个连接开一个写协成用chan default这种，避免单个连接tcp窗口拥塞导致Write阻塞，从而导致广播的循环中其他连接也被阻塞的问题。

**Comment by lxzan** [comment]
可以开协程去广播

**Comment by lxzan** [comment]
我是真的不喜欢用channel 😆

**Comment by lesismal** [comment]
> 可以开协程去广播

如果不是每个连接一个协程，只是一个协程去广播，还是有延迟的问题。
因为是循环中，一个连接阻塞了、其他连接就都等待。

如果是每次广播都对每个连接新开一个协程、新的消息广播又开新的，就太浪费协程数量了

**Comment by lesismal** [comment]
可以参考下 melody:
https://github.com/olahol/melody/blob/master/melody.go#L190

或者nbio里也自带了每个连接开启写协程的功能:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L350

**Comment by lxzan** [comment]
> > 可以开协程去广播
> 
> 如果不是每个连接一个协程，只是一个协程去广播，还是有延迟的问题。 因为是循环中，一个连接阻塞了、其他连接就都等待。
> 
> 如果是每次广播都对每个连接新开一个协程、新的消息广播又开新的，就太浪费协程数量了

控制下协程上限嘛，比如说64个

**Comment by lesismal** [comment]
我把 gws 也加到我那个百万连接测试里了，也加上了tinyws，性能都差不多：
https://github.com/lesismal/nbio-examples/tree/master/websocket_1m

比较失望的是基于fasthttp那个fastws，那个不是fasthttp作者自己实现的，性能和消耗比较跨

**Comment by lxzan** [comment]
> 我把 gws 也加到我那个百万连接测试里了，也加上了tinyws，性能都差不多： https://github.com/lesismal/nbio-examples/tree/master/websocket_1m
> 
> 比较失望的是基于fasthttp那个fastws，那个不是fasthttp作者自己实现的，性能和消耗比较跨

我可以适配下，接入fasthttp

**Comment by lesismal** [comment]
> 控制下协程上限嘛，比如说64个

不是，你可能还没理解这个点。
你想一下，如果你的协程只有64或者N个，那比如刚好当前连续广播了大于64个消息，每次广播里都有这个慢连接，那它自己就把这个size 64的协程池占满了，要等到它超时被踢掉了之类的才会释放协程资源。在它被踢掉之前，其他连接的广播就都等待了。
这只是举例64和一个慢连接，实际场景，可能是多个慢连接，比如你1w个协程，100个慢连接，只要100个广播消息，也就协成池短期被占满了。
在性能、响应敏感的服务里，这样肯定是不行的。

**Comment by lxzan** [comment]
> > 控制下协程上限嘛，比如说64个
> 
> 不是，你可能还没理解这个点。 你想一下，如果你的协程只有64或者N个，那比如刚好当前连续广播了大于64个消息，每次广播里都有这个慢连接，那它自己就把这个size 64的协程池占满了，要等到它超时被踢掉了之类的才会释放协程资源。在它被踢掉之前，其他连接的广播就都等待了。 这只是举例64和一个慢连接，实际场景，可能是多个慢连接，比如你1w个协程，100个慢连接，只要100个广播消息，也就协成池短期被占满了。 在性能、响应敏感的服务里，这样肯定是不行的。

它只会占一个的容量，我指的是最大64的并发度. 可以参考下 https://github.com/lxzan/concurrency ，用了有锁队列和递归调度任务.

**Comment by lesismal** [comment]
> 我可以适配下，接入fasthttp

没太大必要，一旦Upgrade、conn被Hijack了，剩下的性能就完全是ws库自己的部分了、跟fasthttp已经没关系了。所以如果有人需要ws服务和性能，根本不必依赖fasthttp。当然，想http+ws的，还是可以考虑。
但其实实际应用中，fasthttp的优势不会那么大、反倒为了避免bug需要额外注意一些东西，比如它的[]byte如果作为参数传递给其他模块在handler结束后仍然被使用的，fiber好像有个配置项是会开启把header之类的都弄成新的string而不是直接使用fasthttp的read buffer里的一段，所以我个人觉得没必要使用fasthttp。

之前我想把nbio的http也做个适配fasthttp来着，但是它的Context很多字段没有办法修改，我就放弃了

**Comment by lesismal** [comment]
> 锁队列和递

这不是容量的问题，而是阻塞的问题，会造成消息延迟、客户端收消息慢了，你再想想 :joy:

**Comment by lxzan** [comment]
> 昨天看到你的 gws，也star了。
> 
> 跑了下压测，比gorilla要快，nbio的IOModMixed或者IOModBlocking时每个连接至少一个协程的性能也基本持平。
> 
> 内存消耗方式不一样，nbio的内存消耗是更偏基于qps，并发度需要的buffer数量在pool里共用，每个连接上不自带一个固定的buffer；gws或者其他一些基于标准库的框架多数是每个连接上挂一个bufio.Reader/Writer之类的、是持续占用。 所以当连接数不大但qps很高时，nbio的内存消耗会大于gws或者gorilla之类的但是在可控范围内，qps不高的话可能差不太多；但是连接数很大时，nbio的内存会保持在更低的水准，除非极端情况每个连接都tcp窗口满了之类的导致待发送的cache会占用多，但是这个值是可配置的，超过一定size当做不健康的连接自动断开连接就可以了。 另外就是IOModMixed、IOModNonBlocking，能承载更大的连接数，标准库每个连接一个协程的方式毕竟对协程数量巨大的场景还是扛不住。
> 
> 看到readme里有这个描述：`zero extra goroutine to manage connection`。 但对于涉及广播的场景，其实还是需要为每个连接开一个写协成用chan default这种，避免单个连接tcp窗口拥塞导致Write阻塞，从而导致广播的循环中其他连接也被阻塞的问题。


考虑到兼容性，gws使用了std net, 适合在那种最多几千到一万连接的场景下工作。

最近看了1m-go-websocket，大受启发，后续我会为gws加上epoll支持的开关。kqueue懒得搞了，线上大家都是linux。

**Comment by lesismal** [comment]
单就协程池，我这里弄了好几种：
https://github.com/lesismal/nbio/tree/master/taskpool

最后选的Mixed的，因为压测似乎比ants和字节的效果要好一点

**Comment by lxzan** [comment]
我压测过ants，似乎直接go性能更好。比协程池更有意义的是控制并发上限。我感觉runtime里面有优化。

**Comment by lesismal** [comment]
> poll支持的开关。

1m-go-websocket 那个库的实现方式是有问题的，也是涉及这里我说的，for的时候，它遇到单个连接慢了，其他连接就得跟着等待。我之前有给1m-go-websocket提issue指出它的问题，但是可惜这个库关闭了列表所以查不到了。

gobwas/ws和它的examples就是基于1m-go-websocket的方式实现的，我有在那里提issue讲这些，有兴趣的话可以去看下。和这里提到的问题都是for循环中单个连接的阻塞导致其他连接等待的问题，但他们那个是更偏于poller io层面的

**Comment by lesismal** [comment]
> 发上限。我感觉runtime里

对，直接go性能最好，但数量不可控。所以需要协程池，但新版go里，ants相比于其他实现方式没明显优势甚至劣势了

**Comment by lxzan** [comment]
1m-go-websocket 只是个demo, 很多细节都可以优化

**Comment by lesismal** [comment]
> 1m-go-websocket 只是个demo, 很多细节都可以优化

虽然只是demo，但它所讲到的实现方式，没办法解决我说的问题。

要解决，必须要支持异步解析器，比如读到半包要缓存起来等到下次数据来了拼接一起再解析，而不是都像标准库那样阻塞读知道解析出完整包；因为只要你是阻塞读完整包，你的for循环中这个连接就可能卡住，其他连接即使有数据可读也得等你这阻塞读结束。所以不能阻塞读完整包，而是每次读都把数据交给异步解析器去处理、得到完整消息就处理消息、读不到就继续读，如果当前没数据了就出让协程让for循环里的其他连接继续读，否则其他连接就被慢连接坑死了

1m-go-websocket、gobwas/ws都只做了io的event driven，没有做异步解析器，所以它们目前的方案，解决不了我说的这个问题，如果想更进一步，你就不能只按它们的方式去做

**Comment by lesismal** [comment]
![image](https://user-images.githubusercontent.com/40462947/212530401-bc303914-6380-4627-ac30-bfba125bf048.png)

这里真实遇到的问题，就是我说的这个原因

**Comment by lxzan** [comment]
> > 1m-go-websocket 只是个demo, 很多细节都可以优化
> 
> 虽然只是demo，但它所讲到的实现方式，没办法解决我说的问题。
> 
> 要解决，必须要支持异步解析器，比如读到半包要缓存起来等到下次数据来了拼接一起再解析，而不是都像标准库那样阻塞读知道解析出完整包；因为只要你是阻塞读完整包，你的for循环中这个连接就可能卡住，其他连接即使有数据可读也得等你这阻塞读结束。所以不能阻塞读完整包，而是每次读都把数据交给异步解析器去处理、得到完整消息就处理消息、读不到就继续读，如果当前没数据了就出让协程让for循环里的其他连接继续读，否则其他连接就被慢连接坑死了
> 
> 1m-go-websocket、gobwas/ws都只做了io的event driven，没有做异步解析器，所以它们目前的方案，解决不了我说的这个问题，如果想更进一步，你就不能只按它们的方式去做

fork nbio 学习下.
我也担心过你说的问题, 但看到demo效果是极好的(迁移成本低), 就开辟分支写epoll支持了.

**Comment by lxzan** [comment]
也层考虑过依赖 gnet , 自己解析完整的WebSocket Frame比较麻烦, 又缺乏TLS, 遂放弃.
最大缺乏动力的点还是写自己公司的业务用不上海量长连接的支持.

**Comment by lesismal** [comment]
gnet没有实现net.Conn，做各种实现、扩展太不友好了，所以写了这个库。
但目前我支持了tls/http1.x/ws这些，http2.0和quic/http3.0，工作量有点过大，暂时撸不动

**Comment by lxzan** [comment]
已经很厉害了, 那么大的工作量

**Comment by lesismal** [comment]
> 已经很厉害了, 那么大的工作量

主要也是本身还有事情要做，不能全身心铺到开源上，国内要是有好点的开源基金会就好了，项目捐出去组织起来大家一块搞，可惜没有

**Comment by lesismal** [comment]
gorilla都停止维护了，挺可惜的

**Comment by lxzan** [comment]
> gorilla都停止维护了，挺可惜的

大概后面那个维护者感到厌倦了吧, 不是自己的亲儿子, 也没有报酬

**Comment by lxzan** [comment]
支持的特性越多, 维护起来越麻烦

**Comment by lesismal** [comment]
是啊，为爱发电，难以为继

**Comment by lxzan** [comment]
跑测试又跪了, 忽然想起自己是MacOS
:(

下班再试试用linux nbio/http非阻塞模式接入gws, 没问题的话就太方便了

**Comment by lesismal** [comment]
> 跑测试又跪了, 忽然想起自己是MacOS :(
> 


哈哈哈，或者你把那个panic去掉再跑试试

> 下班再试试用linux nbio/http非阻塞模式接入gws, 没问题的话就太方便了

应该是需要你的websocket parser支持异步模式，比如本次只读到half-packet，这比阻塞模式的解析要复杂一些，而且内存可能需要特殊优化、否则有可能比阻塞模式的内存消耗更大

**Comment by lxzan** [comment]
要自己解析半包的话就很复杂了，和gnet差不多

**Comment by lesismal** [comment]
> 要自己解析半包的话就很复杂了，和gnet差不多

nbio目前就是这样实现的，gnet，太难弄了

**Comment by lxzan** [comment]
> > 要自己解析半包的话就很复杂了，和gnet差不多
> 
> nbio目前就是这样实现的，gnet，太难弄了

使用链式buffer，分阶段解析websocket协议吗？

**Comment by lesismal** [comment]
> 

跟链式buffer没直接关系，nbio没那么用，看自己选择的实现策略。
“分阶段解析websocket协议” 以往人们管这叫 "TCP粘包“，虽然这个词不准确，但大概就是这个意思。因为数据是stream过来的，你没法保证每次都读到自己想要的一个完整包。
阻塞模式的IO、buffer接口，提供了一些便利而已，但阻塞读就要持续占用goroutine，海量连接就扛不住了，GC压力大容易STW，如果硬件配置低系统可用内存少容易OOM

**Comment by lxzan** [comment]
> 可以事件驱动websocket读操作，读到所需的字节数就进入下一个状态，否则等待下一次事件。

这都是我对gnet的想法，改天参考下nbio的实现。

**Comment by lesismal** [comment]
其实就是更像写C/C++之类的方式，只是golang自带gc，可能更像java自己撸NIO。但java通常设计模式太重了、很不喜欢
