### ISSUE TITLE
invalid write calling, should call WriteMessage instead

### ISSUE THREAD

**Issue by pippozq** [lesismal/nbio#258]
目前我用websocket构建了一个代理通道，在这个通道中发起http请求，现在是用gorilla实现的，但是是阻塞模式，我考虑用nbio替换，client端代理是可以正常建立连接了，目前遇见一个问题

type TunnelQueue struct {
	// ID
	ID       uint64
       // 这个已经更换为 nbio的了
	conn     *websocket.Conn
}
// 这里是转发http request 
func (t *TunnelQueue)Send(req *http.Request) error {
	_ = t.conn.SetWriteDeadline(time.Now().Add(writeWait))
	req.URL.Path = t.subPath(req.URL.Path) // 处理path前缀 可忽略这个

	if writeErr := req.Write(t.conn); writeErr != nil {
		return fmt.Errorf("request error:%s", writeErr.Error())   
	}
	return nil
}

这里返回了invalid write calling, should call WriteMessage instead

我查看了源码，这里没有实现io.Writer的接口，是考虑到什么问题所有没有实现呢？
// Write overwrites nbio.Conn.Write.
func (c *Conn) Write(data []byte) (int, error) {
	return -1, ErrInvalidWriteCalling
}

**Comment by lesismal** [comment]
Websocket的Message是有多种类型的（Text/Binary/Ping/Pong），直接Write不包括类型信息，框架如果默认使用某个类型是不合理的。
error信息已经表述比较明确了，请使用 WriteMessage

**Comment by lesismal** [comment]
如果代理转发目标server也是websocket、握手后只需要透传数据，还可以参考这里的方式减少websocket协议的解析与组装来提高转发效率：
https://github.com/lesismal/nbio/issues/205

**Comment by lesismal** [comment]
这段代码，是想把req发送给一个Websocket.Conn？这本身就不合理吧。
完整一点的代码或者功能描述给出来才能明白OP你具体想做什么。

如果是想req去send websocket握手请求，不是非要这样做的，可以直接用nbio的websocket.Dial，这里有例子：
https://github.com/lesismal/nbio-examples/blob/master/websocket/nbioclient/client.go

**Comment by pippozq** [comment]
我只是想问问没有实现Writer 接口的考虑,现在知道你的考虑点了，我就用writeMessage方法吧

**Comment by pippozq** [comment]
我看了下，那两个链接的代码，因为目前我已经用

**Comment by pippozq** [comment]
我看了下那两个链接的代码，对于我现有代码改动比较大吧，因为我是替换gorilla的websocket，我现在直接用WriteMessage的话，dump一次request就行，没啥大的改动。把req发送给websocket.conn ，比如远端集群禁入，但是出网可以通过白名单，那我就可以在远端启动一个client，然后到中心建立一个websocket,中心端访问远端集群的服务HTTP接口就通过这个隧道了，也只是转发http的请求不转发其他流量，所以是这么来考虑的，这个问题我先关闭了哟，后续有问题再请教
