### ISSUE TITLE
TLS corruption when using macos foundation websocket client

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#26]
sample code:
https://github.com/lesismal/nbio/pull/25

I know you don't have a mac so not sure how you can reproduce. If can attach a tcpdump

**Comment by acgreek** [comment]
also confirmed no issue with gobwas/ws tls echo server

**Comment by lesismal** [comment]
Is the server on Linux, else are the client and server both on mac?

Is there error log help to tell where it failed, for example: tls handshake or websocket frame parsing

**Comment by lesismal** [comment]
> If can attach a tcpdump

maybe helpful, plz attach one.

**Comment by acgreek** [comment]
I've tried with a linux build (in docker) and running locally on my mac host

**Comment by acgreek** [comment]
I can also confirm that the server finishes the http request-response.

[macfoundationclient.pcapng.gz](https://github.com/lesismal/nbio/files/6718051/macfoundationclient.pcapng.gz)

**Comment by acgreek** [comment]
confirmed this is fixed
