### ISSUE TITLE
想问下跟字节的netpoll有做过性能比较吗

### ISSUE THREAD

**Issue by Kotodian** [lesismal/nbio#260]
https://github.com/cloudwego/netpoll

**Comment by lesismal** [comment]
单就网络收发，之前有做过几个库、标准库对比，有兴趣可以在你自己的环境下跑下这个代码，顺便帮我看看测试代码是否有问题，如果有问题请帮我指出、pr更好：
https://github.com/lesismal/go-net-benchmark/issues/1

但从实际角度看，似乎字节netpoll的定位是不太一样的。netpoll主要用于他们内部框架，比如kitex，并且是以响应性为目标、内存消耗可能反倒更高。
我没有完整阅读netpoll代码，但似乎他们处理连接时仍然是事件来了先阻塞读的方式或者类似的方式，所以高在线的场景需要占用大量协程、加上他们自己的一些buffer算法，我去年在压测时发现他们内存消耗更大，后面没再关注了，不知道他们当前版本是否有优化到更好的水准。
但去年跟他们交流过程中，他们也明确表示过，他们不是为了处理海量连接的场景。而nbio对于性能、易用性、资源消耗的可控性各方面都是狠注重的，所以nbio能处理百万级连接数量。对于http1x/websocket，在1.3.5版本后，nbio支持多种io模式，如果使用Mixed或者Blocking模式能实现阻塞读模式的连接性能好于标准库http、gorilla/websocket，Mixed模式下高在线承载海量链接性能与稳定性兼顾，而其他方案可能就STW变得明显甚至OOM了。

netpoll实际的应用好像中主要是kitex，字节自己有个kitex benchmark，但他们仓库下面列出的数据与我在自己环境跑出的数据差别较大。鸟窝老师每年也有一些rpc框架的压测对比，可以参考：
https://colobu.com/2022/07/31/2022-rpc-frameworks-benchmarks

字节的herz我没太关注，不知道是不是也基于netpoll的，从他们自己提供的benchmark数据看，与fasthttp性能差不多。
nbio的http除了性能，主要注重了对标准库的兼容，这样已有的那些基于标准库的方案比如gin、echo、iris、chi等框架，都能轻松把网络层替换成nbio，从而处理更多业务场景。但为了兼容标准库，性能有所牺牲。如果不考虑兼容标准库，可以实现与fasthttp、herz相同的性能水平，但我个人精力和推广能力有限，没法像字节那样团队运营及维护，也不像fasthttp那样出生于golang早期大家瓜分天下的时代容易吸引用户，兼容标准库或许还能多些用户。而且毕竟，目前也只有nbio能在处理百万链接这种场景时保持较低的内存开销、不至于明显的STW从而比较稳定。

**Comment by Kotodian** [comment]
> 



> lesismal/go-net-benchmark#1

好，我到时候自己测试看看
