### ISSUE TITLE
Cant send large response.

### ISSUE THREAD

**Issue by DeadInside1985** [lesismal/nbio#263]
Hello. I try to replace net/http in gin framework by your example.
But when I replace I have error in this part, about CloseNotifier interface.
`
                          
                    c.Stream(func(w io.Writer) bool {
			n, err := data.Read(vbuf)
			if err != nil && err != io.EOF {
				fmt.Println("read error", err)
				return false
			}
			if n > 0 {
				if _, err := w.Write(vbuf[:n]); err == nil {
					return true
				}
			}
			return false)
`

When I try to write data without check conn state  like `io.Copy(c.Writer,dataReader)` but get error `invalid write result` in case if data size reach around 500kb. When I try to write by one part `c.Writer.Write(io.ReadAll(dataReader)` limit increase to 4mb.

Versions:
github.com/gin-gonic/gin v1.8.2
github.com/lesismal/nbio v1.3.9

Sorry, my bad english.

**Comment by lesismal** [comment]
Please provide the full examples that can reproduce this problem, including both the server and client side, I'll try it.

**Comment by DeadInside1985** [comment]
As client I use browser chrome.
1. First problem with stream 
```
package main

import (
 "bytes"
 "context"
 "fmt"
 "github.com/gin-gonic/gin"
 "github.com/lesismal/nbio/nbhttp"
 "io"
 "log"
 "math/rand"
 "os"
 "os/signal"
 "time"
)

func onHello(c *gin.Context) {
 data := make([]byte, 1000*1024)
 rand.Read(data)

 reader := bytes.NewReader(data)

 buffer := make([]byte, 4096)

 c.Stream(func(w io.Writer) bool {
  n, err := reader.Read(buffer)
  if err != nil && err != io.EOF {
   fmt.Println("read error", err)
   return false
  }
  if n > 0 {
   if _, err := w.Write(buffer[:n]); err == nil {
    return true
   }
  }
  return false
 })
}

func main() {
 router := gin.New()

 router.GET("/hello", onHello)

 svr := nbhttp.NewServer(nbhttp.Config{
  Network: "tcp",
  Addrs:   []string{"0.0.0.0:8080"},
 }, router, nil)

 err := svr.Start()
 if err != nil {
  log.Fatalf("nbio.Start failed: %v\n", err)
 }

 log.Println("serving [gin-gonic/gin] on [nbio]")

 interrupt := make(chan os.Signal, 1)
 signal.Notify(interrupt, os.Interrupt)
 <-interrupt

 ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
 defer cancel()
 svr.Shutdown(ctx)
}
```
Error 
2023/01/23 11:58:00.708 [ERR] conn execute failed: interface conversion: *nbhttp.Response is not http.CloseNotifier: missing method CloseNotify
goroutine 24 [running]:
github.com/lesismal/nbio.(*Conn).Execute.func1.1.1()
 /root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/conn.go:123 +0x72
panic({0x76e920, 0xc00024c0f0})
 /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/gin-gonic/gin.(*responseWriter).CloseNotify(0xc001f00000?)
 /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/response_writer.go:112 +0x2c
github.com/gin-gonic/gin.(*Context).Stream(0x6?, 0xc0004ebcb8)
 /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:1060 +0x35
main.onHello(0xc0004ebd30?)
 /var/www/go/src/nbio/main.go:25 +0xf9
github.com/gin-gonic/gin.(*Context).Next(...)
 /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0004ca1a0, 0xc0000c6000)
 /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616 +0x671
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0004ca1a0, {0x876b40?, 0xc0004f0100}, 0xc000494300)
 /root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572 +0x1dd
github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
 /root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/nbhttp/processor.go:265 +0x3f
github.com/lesismal/nbio.(*Conn).Execute.func1.1(0x0?)
 /root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/conn.go:127 +0x3e
github.com/lesismal/nbio.(*Conn).Execute.func1()
 /root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/conn.go:128 +0x3b
github.com/lesismal/nbio/taskpool.(*MixedPool).callWitoutRecover(0xc0000122a0?, 0x0?)
 /root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/taskpool/mixedpool.go:38 +0x59
github.com/lesismal/nbio/taskpool.(*MixedPool).Go.func1()
 /root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/taskpool/mixedpool.go:45 +0x36
created by github.com/lesismal/nbio/taskpool.(*MixedPool).Go
 /root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/taskpool/mixedpool.go:44 +0xcd

2. I test this code and this work without proxy but then I use nginx as proxy I get error in nginx log `upstream prematurely closed connection while sending to client`
```
package main

import (
	"bytes"
	"context"
	"github.com/gin-gonic/gin"
	"github.com/lesismal/nbio/nbhttp"
	"io"
	"log"
	"math/rand"
	"net/http"
	"os"
	"os/signal"
	"time"
)

func onHello(c *gin.Context) {
	data := make([]byte, 10*1000*1024)
	rand.Read(data)

	reader := bytes.NewReader(data)
	buffer := make([]byte, 512*1024)

	_, err := io.CopyBuffer(c.Writer, reader, buffer)
	if err != nil {
		c.Status(http.StatusInternalServerError)
		return
	}
	c.Status(http.StatusOK)
}

func main() {
	router := gin.New()

	router.GET("/hello", onHello)

	svr := nbhttp.NewServer(nbhttp.Config{
		Network: "tcp",
		Addrs:   []string{"0.0.0.0:8080"},
	}, router, nil)

	err := svr.Start()
	if err != nil {
		log.Fatalf("nbio.Start failed: %v\n", err)
	}

	log.Println("serving [gin-gonic/gin] on [nbio]")

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
	defer cancel()
	svr.Shutdown(ctx)
}
```

**Comment by DeadInside1985** [comment]
Nginx part 
```
location / {
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_pass http://127.0.0.1:8080;
}
```

**Comment by lesismal** [comment]
nbio.Conn.Write is non-blocking, don't use it like net.Conn.Write, please try to Write directly rather than using c.Stream or io.Copy.

**Comment by DeadInside1985** [comment]
Like this ?
```
	data := make([]byte, 10*1000*1024)
	rand.Read(data)

	_, err := c.Writer.Write(data)
	if err != nil {
		c.Status(http.StatusInternalServerError)
		return
	}
	c.Status(http.StatusOK)
```
Yes this is working, but this need to read all data in memory, my service serve files from disk.
Its possible to avoid this?

**Comment by lesismal** [comment]
Yes, like this.

> but this need to read all data in memory, my service serve files from disk

Do you mean you want `Zero Copy/Sendfile`? `sendfile` is enabled by default in nbhttp.

**Comment by lesismal** [comment]
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L542
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L572
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L614
https://github.com/lesismal/nbio/blob/master/nbhttp/engine.go#L651

https://github.com/lesismal/nbio/blob/master/nbhttp/response.go#L198

**Comment by lesismal** [comment]
nbhttp.Response 实现了 io.ReaderFrom，直接用标准库 http servefile这些都是会触发 sendfile 的。
但是我试了下gin的没有触发，看了下，gin.Context.Writer断言 io.ReaderFrom 失败，所以直接用 c.ServeFile 或者 io.Copy 都会失败，手动强转下类型就可以触发了：
```golang
func onHello(c *gin.Context) {
	f, err := os.Open(`./test.txt`)
	if err != nil {
		panic(err)
	}
	res := *(**nbhttp.Response)(unsafe.Pointer(&c.Writer))
	io.Copy(res, f)
}
```

**Comment by lesismal** [comment]
gin.ResponseWriter接口没有包括io.ReaderFrom，所以从这个来看，gin作为file server都不会使用sendfile。我刚又去gin的issue列表查看了一番，确实还没有支持，但是有人PR：
![image](https://user-images.githubusercontent.com/40462947/214116185-6c08841a-c887-47af-a399-523eaac21eba.png)

gin竟然没有支持sendfile，有点意外。。

**Comment by lesismal** [comment]
related:
https://github.com/gin-gonic/gin/pull/1610
https://github.com/gin-gonic/gin/issues/1344

@DeadInside1985 
If this pr for gin is merged in the future, then we should not need the type conversion any longer:
https://github.com/gin-gonic/gin/pull/3197

**Comment by DeadInside1985** [comment]
I make fork and merge this PR.
In some cases than data not on disk I need to download it from upstream and send to client (like proxy).
It possible to send data zero allocation?

**Comment by DeadInside1985** [comment]
I try your code and get this error:
github.com/lesismal/nbio.(*Conn).Execute.func1.1.1()
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/conn.go:123 +0x72
panic({0x76b920, 0xa9b1f0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/lesismal/nbio/nbhttp.(*Response).Write(0x879458, {0xc001f00000, 0x9c4000, 0x9c4000})
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/nbhttp/response.go:96 +0x51
bytes.(*Reader).WriteTo(0xc0003ea1e0, {0x874c60?, 0x879458?})
	/usr/local/go/src/bytes/reader.go:143 +0x87
io.copyBuffer({0x874c60, 0x879458}, {0x874aa0, 0xc0003ea1e0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:409 +0x16e
io.Copy(...)
	/usr/local/go/src/io/io.go:386
main.onHello(0xc00015a100)
	/var/www/go/src/nbio/main.go:24 +0xc7
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/context.go:173
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000082820, 0xc00015a100)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:616 +0x671
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000082820, {0x876940?, 0xc000e9a200}, 0xc000e94400)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.8.2/gin.go:572 +0x1dd
github.com/lesismal/nbio/nbhttp.(*ServerProcessor).OnComplete.func1()
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/nbhttp/processor.go:265 +0x3f
github.com/lesismal/nbio.(*Conn).Execute.func1.1(0x0?)
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/conn.go:127 +0x3e
github.com/lesismal/nbio.(*Conn).Execute.func1()
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/conn.go:128 +0x3b
github.com/lesismal/nbio/taskpool.(*MixedPool).callWitoutRecover(0x0?, 0x0?)
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/taskpool/mixedpool.go:38 +0x59
github.com/lesismal/nbio/taskpool.(*MixedPool).Go.func1()
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/taskpool/mixedpool.go:45 +0x36
created by github.com/lesismal/nbio/taskpool.(*MixedPool).Go
	/root/go/pkg/mod/github.com/lesismal/nbio@v1.3.9/taskpool/mixedpool.go:44 +0xcd

**Comment by lesismal** [comment]
> If this pr for gin is merged in the future

Provide the full examples, I'll try it tomorrow.

**Comment by DeadInside1985** [comment]
```
package main

import (
	"bytes"
	"context"
	"github.com/gin-gonic/gin"
	"github.com/lesismal/nbio/nbhttp"
	"io"
	"log"
	"math/rand"
	"net/http"
	"os"
	"os/signal"
	"time"
	"unsafe"
)

func onHello(c *gin.Context) {
	data := make([]byte, 10*1000*1024)
	rand.Read(data)
	reader := bytes.NewReader(data)

	res := *(**nbhttp.Response)(unsafe.Pointer(&c.Writer))
	res.WriteHeader(http.StatusOK)
	io.Copy(res, reader)
}

func main() {
	router := gin.New()

	router.GET("/hello", onHello)

	svr := nbhttp.NewServer(nbhttp.Config{
		Network: "tcp",
		Addrs:   []string{"0.0.0.0:8080"},
	}, router, nil)

	err := svr.Start()
	if err != nil {
		log.Fatalf("nbio.Start failed: %v\n", err)
	}

	log.Println("serving [gin-gonic/gin] on [nbio]")

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
	defer cancel()
	svr.Shutdown(ctx)
}
```

**Comment by lesismal** [comment]
Well, sorry, I used the wrong code(net/http server) when I test Sendfile.
gin.Context has itself HTTP process steps, it seems can't use nbhttp's Sendfile.

**Comment by lesismal** [comment]
Need to hack like this, then it works:
```golang
func nbhttpResponse(c *gin.Context) *nbhttp.Response {
	type GinContext struct {
		Writer struct {
			http.ResponseWriter
			size   int
			status int
		}
	}
	return (*(**GinContext)(unsafe.Pointer(&c))).Writer.ResponseWriter.(*nbhttp.Response)
}

func onHello(c *gin.Context) {
	// if you have write status code using c, should call WriteHeaderNow() before using nbhttp.Response
	// c.Writer.WriteHeaderNow()

	w := nbhttpResponse(c)
	http.ServeFile(w, c.Request, `./test.txt`)
}
```

**Comment by DeadInside1985** [comment]
Yes its working. Thank you.

**Comment by lesismal** [comment]
You are welcome!

**Comment by lesismal** [comment]
`labstack/echo` 也有同样的问题，但是它的 Response 定义是暴露出来的，相对好处理些，这里也记录下：

```golang
func onHello(c echo.Context) error {
	w := c.Response().Writer.(*nbhttp.Response)
	http.ServeFile(w, c.Request(), `./test.txt`)
	return nil
}
```
