### ISSUE TITLE
您好，支持在web框架fiber下使用吗？

### ISSUE THREAD

**Issue by feng99** [lesismal/nbio#268]
支持在web框架fiber下使用吗？
它是基于fasthttp的。

我有一个websocket的广播的功能需求。
谢谢

**Comment by lesismal** [comment]
感谢关注！
不支持fasthttp系的，以前想支持fasthttp但因为fasthttp相关的类型字段没有导出，而且fasthttp基于兼容性、没法修改相关:
https://github.com/valyala/fasthttp/issues/1239

而且就性能来说，不管是基于fasthttp系还是基于标准库，Upgrade后、Conn都是被websocket接管、读写和逻辑都是由websocket库本身处理的了，所以后续的性能与fasthttp或者标准库已经无关了。

倒是可以修改websocket一些内容、单独package去支持fasthttp系的，但是无法有效利用nbio的更多功能、比如不同的IO模式的优势：
https://github.com/lesismal/nbio/releases/tag/v1.3.5
所以修改的意愿不是特别强，我过阵子不忙了看下大概要修改多少，如果修改不大，也可以考虑单开个repo去支持fasthttp websocket

**Comment by lesismal** [comment]
如果你们的websocket是单独的服务、没有与http接口用同一个服务，直接用nbio的就可以了，如果是与http接口一起的，我再想能不能Hijack的方式hack一下，但是需要业务自己去处理一部分Upgrade逻辑，代码也是不太美观

**Comment by feng99** [comment]
感谢回复，再请教两个问题
1.gorilla的websocket支持在fiber框架里使用吗？
2.fiber有办法把请求转换为net/http，转换以后，可以用您这个项目吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月25日 20:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lesismal/nbio] 您好，支持在web框架fiber下使用吗？ (Issue #268) |

感谢关注！
不支持fasthttp系的，以前想支持fasthttp但因为fasthttp相关的类型字段没有导出，而且fasthttp基于兼容性、没法修改相关:
valyala/fasthttp#1239

而且就性能来说，不管是基于fasthttp系还是基于标准库，Upgrade后、Conn都是被websocket接管、读写和逻辑都是由websocket库本身处理的了，所以后续的性能与fasthttp或者标准库已经无关了。

倒是可以修改websocket一些内容、单独package去支持fasthttp系的，但是无法有效利用nbio的更多功能、比如不同的IO模式的优势：
https://github.com/lesismal/nbio/releases/tag/v1.3.5
所以修改的意愿不是特别强，我过阵子不忙了看下大概要修改多少，如果修改不大，也可以考虑单开个repo去支持fasthttp websocket

**Comment by lesismal** [comment]
这是fasthttp基于gorilla改造的基于fasthttp的，fiber只要拿到fasthttp.RequestCtx应该就可以直接用了：
https://github.com/fasthttp/websocket

fibber的请求转换为net/http我还没试过，ws这块主要是Upgrade流程+接管conn就可以了

**Comment by lesismal** [comment]
看了下，fasthttp Upgrade直接回调把conn传递给用户的handler了，所以好像可以搞：
https://github.com/fasthttp/websocket/blob/417207d494e8a883b46ae3193fce4c6e9c3d80d5/server_fasthttp.go#L184

**Comment by feng99** [comment]
net/http 处理程序与 Fiber 请求处理程序之间的转换器https://github.com/gofiber/adaptor
是不是把fiber请求转换为net/http请求后，就可以接入您的项目了呢？

fiber自带的那个websocket我看了，
但是不敢用，一个是功能不够全，
 还有两年前的issue。😳





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月25日 21:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lesismal/nbio] 您好，支持在web框架fiber下使用吗？ (Issue #268) |

这是fasthttp基于gorilla改造的基于fasthttp的，fiber只要拿到fasthttp.RequestCtx应该就可以直接用了：
https://github.com/fasthttp/websocket

fibber的请求转换为net/http我还没试过，ws这块主要是Upgrade流程+接管conn就可以了

**Comment by lesismal** [comment]
> 看了下，fasthttp Upgrade直接回调把conn传递给用户的handler了，所以好像可以搞： https://github.com/fasthttp/websocket/blob/417207d494e8a883b46ae3193fce4c6e9c3d80d5/server_fasthttp.go#L184

nbio的想精简还是要做下单独裁剪。直接从 fasthttp/websocket的Upgrade后的Conn里取出conn给nbio的websocket用也可以，类似这里：
https://github.com/lesismal/nbio/issues/240#issuecomment-1304804444
但是多整了一道就有点别扭

**Comment by lesismal** [comment]
> 

如果转换器ok，那应该就可以，这个adaptor我收藏了，感谢，哈哈哈
咱试试这个转换器能不能拉通

**Comment by feng99** [comment]
好的，感谢，
其实我不想用fiber，
但是，大领导选定了fiber框架，
这些细节他又不参与。

明天我也研究下那个转换器。

如果您有相关结果，也请告知。
十分感谢。😍

issue我会在有进一步结果后关闭。




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月25日 22:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lesismal/nbio] 您好，支持在web框架fiber下使用吗？ (Issue #268) |

如果转换器ok，那应该就可以，这个adaptor我收藏了，感谢，哈哈哈
咱试试这个转换器能不能拉通

**Comment by lesismal** [comment]
试了下，好像是不行，这个adaptor、fasthttp没有实现 http.Hijacker：
```sh
2023/02/25 22:16:35 Upgrade failed: websocket: response does not implement http.Hijacker
```

**Comment by lesismal** [comment]
如果想省事，可以直接用这个：
https://github.com/fasthttp/websocket

**Comment by feng99** [comment]
感谢您的回复  
这个demo符合我的基本需求   略微改了改    搞定了.  
https://github.com/gofiber/recipes/tree/master/websocket-chat

**Comment by lesismal** [comment]
好的，它这个就是用的  github.com/fasthttp/websocket ，在gorilla基础上改的，够用了
