### ISSUE TITLE
作为udp的客户端使用时，与web框架fiber兼容吗？

### ISSUE THREAD

**Issue by feng99** [lesismal/nbio#269]
您好

作为udp的客户端使用时，与web框架fiber兼容吗？

场景是
go代码作为客户端   向硬件设备发送数据。  

同时，go代码  也作为服务端  接收设备定时上报的数据

使用的是udp协议，这个场景下
您的项目与web框架fiber兼容吗？

谢谢

**Comment by lesismal** [comment]
感谢关注！

但是兄弟，fiber是基于fasthttp的，fasthttp好像还没支持http2.0/3.0，http3.0是基于quic(udp)的，所以fiber是基于tcp的，你们项目是怎么做到用udp client访问fiber的服务的，我有点懵逼:joy:

**Comment by lesismal** [comment]
我猜你想表达的是不是这样：
1. 你们的go udp client向其他设备发送数据
2. 你们的这个go进程同时也想用fiber做server、接收设备定时上报的数据

如果是这样的话，那这udp与fiber没什么关系的，udp的逻辑和fiber的逻辑各自写就可以了

**Comment by feng99** [comment]
嘿嘿，不是您理解的这样啦，
我是要实现两个功能
1.go代码作为udp的服务端，接收设备的上报数据
2.go代码作为udp的客户端，向设备发送udp请求

我看您的项目的readme.md里写支持udp协议。

因为我的代码是继续fiber框架下的

我再加一个main.go是不是就可以了。
udp与tcp没有关系，
共用操作mysql那块的代码就行。





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月27日 21:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lesismal/nbio] 作为udp的客户端使用时，与web框架fiber兼容吗？ (Issue #269) |

感谢关注！

但是兄弟，fiber是基于fasthttp的，fasthttp好像还没支持http2.0/3.0，http3.0是基于quic(udp)的，所以fiber是基于tcp的，你们项目是怎么做到用udp client访问fiber的服务的，我有点懵逼😂

**Comment by lesismal** [comment]
那这个udp就是跟fiber没关系了，只是一个进程里的不同模块，你用不同的方法或者分不同的包都可以

估计兄弟是其他语言临时接任务来写go吧，其实你这个issue我估计是跟nbio和fiber都没关系，就是go的package、方法这些基础语法只要你再熟悉下就清楚了

**Comment by feng99** [comment]
我没有写过udp的，
以前都是http协议的请求与相应。
好的。
新的package，新的main.go
见笑了。嘿嘿




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月27日 21:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lesismal/nbio] 作为udp的客户端使用时，与web框架fiber兼容吗？ (Issue #269) |

那这个udp就是跟fiber没关系了，只是一个进程里的不同模块，你用不同的方法或者分不同的包都可以

估计兄弟是其他语言临时接任务来写go吧，其实你这个issue我估计是跟nbio和fiber都没关系，就是go的package、方法这些基础语法只要你再熟悉下就清楚了

**Comment by lesismal** [comment]
加油

**Comment by lesismal** [comment]
main.go不是必需品，不是每个包都需要main.go，即使是main包也可以没有main.go只要有func main()。。。
兄弟加油

**Comment by feng99** [comment]
好哒   书我是看了不少   项目练得太少了   感谢解惑
