### ISSUE TITLE
a lot of failures when tested again autobahn test suite

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#27]
Test the websocket_tls server 

https://github.com/crossbario/autobahn-testsuite

unzip and open index.html 

[autobahn-testreport.zip](https://github.com/lesismal/nbio/files/6717474/autobahn-testreport.zip)

**Comment by lesismal** [comment]
a little busy recently but will handle it as soon

**Comment by acgreek** [comment]
I have another guy working on a pull-request to make it easy to rerun the test suite

**Comment by lesismal** [comment]
> I have another guy working on a pull-request to make it easy to rerun the test suite

that's great!

I take a look at the index.html, need to fix some edge condition, such as 0 payloads you pr just now, and ping/pong's handling.

**Comment by lesismal** [comment]
fix bug for parsing message with payload 0/65535/65536, and add CheckUtf8.
that should have reduced the num of autobahn test suite errors, but that's not all, still working on it.

it's indeed hard for me to reproduce https://github.com/lesismal/nbio/issues/26 without a mac env, I'm not sure whether it was affected by these new commits.
so, please try https://github.com/lesismal/nbio/issues/26 with the newest version.

**Comment by acgreek** [comment]
I fixed a lot of the easier issues, but there are some major issues with the framing. We need to make sure all framing/fragment code works correctly before we can expect anyone to use this.

**Comment by acgreek** [comment]
With my latest patch, almost everything is green, except for some handling of close

[report.tar.gz](https://github.com/lesismal/nbio/files/6720909/report.tar.gz)

**Comment by acgreek** [comment]
I fixed all the close issues. Now everything is green

**Comment by lesismal** [comment]
> I fixed all the close issues. Now everything is green

great, thanks a lot!

**Comment by acgreek** [comment]
I ran the autobahn against the TLS websocket echo server and it seems the server is sending duplicate pongs messages. It like TLS sometimes sends the same messages twice to the websocket OnMessage method

specifically test 2.1
```
Case Outcome

Actual events differ from any expected.

Expected:
{'OK': [('pong', u'')]}

Observed:
[('pong', u''), ('pong', u'')]
```

[report-tls.tar.gz](https://github.com/lesismal/nbio/files/6721763/report-tls.tar.gz)

**Comment by lesismal** [comment]
> websocket

this should work, try the latest:
https://github.com/lesismal/nbio/commit/15b21f1757d77f7bf84d598fa9da5a4ab399e235#diff-2c79faedadc15a44e52b4c0f800eb989f1b27f517c4799a9c0ac3540412458df

**Comment by acgreek** [comment]
yep, that fixed it. Thank you 

Also it seems the the mac foundation client works. I'll do some more testing tomorrow to confirm.
