### ISSUE TITLE
关于写超时的疑惑

### ISSUE THREAD

**Issue by buexplain** [lesismal/nbio#270]
哈喽，我有一个关于写超时的疑惑，还望解答，谢谢。
下面是个往客户端写数据的方法，里面有一把锁。
https://github.com/lesismal/nbio/blob/45fe2ecca807df6f3893d169a2c60b12c939a842/nbhttp/websocket/conn.go#L142-L145
我的问题：当我在调用这个方法前设定写超时，当方法拿到这把锁的时候，有可能超时时间已经到达了，我应该如何避免这个情况？
示例代码：
```go
//这行代码设置写超时是5秒
_ = conn.SetWriteDeadline(time.Now().Add(time.Second*5))
//这行代码有可能在等待锁，当方法拿到锁的时候，有可能已经是5秒之后了
_ = conn.WriteMessage(websocket.TextMessage, []byte("test"))
```

**Comment by lesismal** [comment]
websocket如果使用默认的IOModNonblocking模式，则写入的fd是非阻塞的，每个写都是迅速完成的，所以不会等待那么久。
如果使用IOModBlocking则使用标准库连接，或者使用IOModMixed新连接到达时如果当前在线低于配置的MaxBlockingOnline则也是使用标准库连接这种情况有可能写阻塞比较久，可以设置 upgrader.BlockingModAsyncWrite=true，这样会为该连接启动一个单独的协程+chan处理写，就不会阻塞了
