### ISSUE TITLE
Engine 停止后内存泄漏

### ISSUE THREAD

**Issue by isletnet** [lesismal/nbio#271]
linux平台，成员connsUnix申请的内存没释放

**Comment by lesismal** [comment]
已经停止后，就交给GC自动处理了，不需要手动再去清理了的

**Comment by isletnet** [comment]
实测内存占用会越来越多，加上这两行才GC才会清理

**Comment by lesismal** [comment]
> 实测内存占用会越来越多，加上这两行才GC才会清理

engine不是都退出了嘛，占用越来越多还是engine自己的问题吗？。。。
请提供一个复现的完整示例我看下是不是什么bug导致的

**Comment by isletnet** [comment]
> 

有道理，是我代码问题
