### ISSUE TITLE
Can't render HTML

### ISSUE THREAD

**Issue by ansharcreative** [lesismal/nbio#273]
Hello, I start to migrate a new engine to my service but there is a requirement to render Swagger Page for testing purposes. when I try to open Swagger Page using the NBIO engine that only renders HTML text. Do you have any solution for this? Thanks

<img width="1440" alt="Screen Shot 2023-03-05 at 21 45 27" src="https://user-images.githubusercontent.com/127035808/222968005-ae263c6d-2253-4831-a574-b49fda6272a9.png">

Notes:
I using `net/http` with [chi](https://github.com/go-chi/chi) as a mux handler

**Comment by lesismal** [comment]
Please provide the full example that can reproduce this problem, I'll try it.

**Comment by ansharcreative** [comment]
@lesismal here is the full example :

```go
package main

import (
	"context"
	"os"
	"os/signal"
	"runtime"
	"time"

	"github.com/go-chi/chi"
	"github.com/lesismal/nbio/nbhttp"
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	mux := chi.NewRouter()
	mux.Mount("/swagger", httpSwagger.WrapHandler)
	server := nbhttp.NewServer(nbhttp.Config{
		Addrs:   []string{":8080"},
		Network: "tcp",
		NPoller: runtime.NumCPU() * 2,
		Handler: mux,
	})
	err := server.Start()
	if err != nil {
		panic(err)
	}

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()

	server.Shutdown(ctx)
}
```

**Comment by lesismal** [comment]
I tried with std server, but got the same error:
```
mux := chi.NewRouter()
mux.Mount("/swagger", httpSwagger.WrapHandler)
server := http.Server{
	Addr:    "localhost:8080",
	Handler: mux,
}
server.ListenAndServe()
```

I'm not familiar with "github.com/swaggo/http-swagger", would you please try the right example using this repo?

**Comment by ansharcreative** [comment]
here is an example to use swagger. then visit with URL `http://localhost:8080/swagger/index.html`

```
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	mux := chi.NewRouter()
	mux.Mount("/swagger", httpSwagger.WrapHandler)
	server := http.Server{
		Handler: mux,
		Addr:    ":8080",
	}
	server.ListenAndServe()
}
```

should be rendered page like the below : 
<img width="1430" alt="Screen Shot 2023-03-05 at 22 48 15" src="https://user-images.githubusercontent.com/127035808/222970858-6f2d4b0a-036b-44fc-a60e-a6bcab334b04.png">

**Comment by lesismal** [comment]
I follow the steps of the official example, then get the successful result.
![image](https://user-images.githubusercontent.com/40462947/222971228-6f28df5b-d300-49ae-a477-fb65b59e4b1e.png)

Before you run this server, you need to do it step by step as the README siad(see https://github.com/swaggo/http-swagger):
1. Add comments to your API source code
2. Install swag by `go get github.com/swaggo/swag/cmd/swag` `go install github.com/swaggo/swag/cmd/swag`
3. Generate the doc resources by `swag init` in your root dir including main.go
4. Run the main.go `go run main.go`

main.go
```golang
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/swaggo/http-swagger"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	r := chi.NewRouter()

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/doc.json"), //The url pointing to API definition
	))

	http.ListenAndServe(":1323", r)
}
```

**Comment by lesismal** [comment]
After you run `swag init`, it will generate doc resources including go code:
![image](https://user-images.githubusercontent.com/40462947/222971561-411ac3b3-67a2-46b2-b771-c7f7bf95c38f.png)

doc dir:
![image](https://user-images.githubusercontent.com/40462947/222971581-e6de3689-b076-456a-94f6-d50d48a23c5b.png)


If you didn't generate these resources, it can't be rendered of course.

**Comment by ansharcreative** [comment]
oh, I'm sorry, I forgot to give a full example of to install swag 🙏 . but, when I change the base server from HTTP to Nbio I just only render a text, how I could solve this problem?

**Comment by lesismal** [comment]
> oh, I'm sorry, I forgot to give a full example of to install swag 🙏 . but, when I change the base server from HTTP to Nbio I just only render a text, how I could solve this problem?

Is it working correctly when using the std server?

**Comment by ansharcreative** [comment]
yups when I use the std server that works correctly, but when I change with the Nbio engine that page only renders an HTML text.

**Comment by lesismal** [comment]
But I get the rendered page also when using nbio:

```golang
package main

import (
	"context"
	"os"
	"os/signal"
	"runtime"
	"time"

	"github.com/go-chi/chi"
	"github.com/lesismal/nbio/nbhttp"
	httpSwagger "github.com/swaggo/http-swagger"
	_ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	r := chi.NewRouter()

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/doc.json"), //The url pointing to API definition
	))

	// http.ListenAndServe(":1323", r)

	server := nbhttp.NewServer(nbhttp.Config{
		Addrs:   []string{"localhost:1323"},
		Network: "tcp",
		NPoller: runtime.NumCPU() * 2,
		Handler: r,
	})
	err := server.Start()
	if err != nil {
		panic(err)
	}

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*5)
	defer cancel()

	server.Shutdown(ctx)
}
```

**Comment by lesismal** [comment]
Can you provide the full examples including resources? No need to provide the doc of your real project but just a simply generated doc that can reproduce the problem.

**Comment by ansharcreative** [comment]
@lesismal sorry I forgot to set the config, now it's working perfectly. thanks for the great support!

**Comment by lesismal** [comment]
You are welcome! Thank you for your attention to nbio!

**Comment by successor1** [comment]
Hi, i got a similar issue. 

```golang
func UserPanelHandler(w http.ResponseWriter, r *http.Request) {
	sess := session.Ss.GetSessionFromCtx(r)
	if sess.Role != "User" {
		http.Error(w, "", http.StatusForbidden)
		return
	}
	params := models.Session{Role: sess.Role, Username: sess.Username}
	chatTemplate, err := template.ParseFiles("contacts.html")
	if err != nil {
		fmt.Println(err)
	}
	err = chatTemplate.Execute(w, params)
	if err != nil {
		fmt.Println(err)
	}
	return
}
```

This doesn't render.

**Comment by lesismal** [comment]
> Do we continue the conversation here, as it's a similar issue or do i create a new issue?

@successor1 
Please check all the previous conversations, it was not an issue...

You can provide a full example that can reproduce your problem, it will be better to open another issue, and I will try it.

**Comment by successor1** [comment]
> > Do we continue the conversation here, as it's a similar issue or do i create a new issue?
> 
> @successor1 Please check all the previous conversations, it was not an issue...
> 
> You can provide a full example that can reproduce your problem, it will be better to open another issue, and I will try it.

Ok, got it. I'll open an issue later with full example.
