### ISSUE TITLE
Use Epoll in linux

### ISSUE THREAD

**Issue by centratelemedia** [lesismal/nbio#274]
If implementing NBIO on Linux, does it automatically use epoll?

**Comment by lesismal** [comment]
Yes, nbio use epoll on Linux by default.

But there are some more features for HTTP/Websocket, if you set IOMod to IOModBlocking or IOModMixed, there would be some differences, for more details, please refer to v1.3.5 release doc:
https://github.com/lesismal/nbio/releases/tag/v1.3.5

Of course, even use std's net.TCPConn, it also uses epoll but provides blocking interfaces.

**Comment by centratelemedia** [comment]
@lesismal 

Thank you very much...
