### ISSUE TITLE
Memory usage increases every day

### ISSUE THREAD

**Issue by om26er** [lesismal/nbio#283]
The number of clients in my case is more or less the same, however, I see everyday the memory usage of my node keeps increasing, here is the output of pprof. Its clear most of allocations are happening in `AppendString` -- So how do we limit that ? 
```
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top 100
Showing nodes accounting for 77.81MB, 100% of 77.81MB total
      flat  flat%   sum%        cum   cum%
   41.24MB 53.00% 53.00%    41.24MB 53.00%  github.com/lesismal/nbio/mempool.(*MemPool).AppendString
      16MB 20.56% 73.56%       16MB 20.56%  github.com/lesismal/nbio.NewEngine
      16MB 20.56% 94.13%       16MB 20.56%  github.com/lesismal/nbio/taskpool.NewFixedNoOrderPool
    3.07MB  3.95% 98.07%     3.07MB  3.95%  github.com/lesismal/nbio/mempool.(*MemPool).Malloc
    0.50MB  0.64% 98.71%     0.50MB  0.64%  github.com/jackc/pgx/v5/pgconn.connect
    0.50MB  0.64% 99.36%     0.50MB  0.64%  runtime.malg
    0.50MB  0.64%   100%     0.50MB  0.64%  github.com/lesismal/nbio/nbhttp/websocket.newConn
```

**Comment by lesismal** [comment]
Would you please provide the origin pprof file?
Is this your production pprof? I think 77.81MB is not a huge amount. If the hardware specification is really low, maybe it's better change to c/cpp/rust.
And it would be better to provide full code that can reproduce the problem, else I don't have the env and would be difficult for me to try and optimize the code.
