### ISSUE TITLE
How to actively close the user connection?

### ISSUE THREAD

**Issue by changyl** [lesismal/nbio#284]
How to actively close user connection in server if elegant, see no examples

**Comment by lesismal** [comment]
Thanks for your attention!

You can just call:
```golang
nbio.Conn.Close()
nbio/nbhttp/websocket.Conn.Close()
```

**Comment by changyl** [comment]
After I close the connection, when I stop the service through the method engine.Shudwon(), the service panic

`^C2023/04/14 20:18:57.747 [ERR] Timer[NB] exec call failed: sync: negative WaitGroup counter
goroutine 71 [running]:
github.com/lesismal/nbio/timer.(*Timer).loop.func1.1()
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:175 +0x78
panic({0x16f3a20, 0x1914eb0})
     /usr/local/go/src/runtime/panic.go:884 +0x212
sync.(*WaitGroup).Add(0x103b876?, 0xc000436d88?)
     /usr/local/go/src/sync/waitgroup.go:83 +0xda
sync.(*WaitGroup).Done(0xc0002c00d0?)
     /usr/local/go/src/sync/waitgroup.go:108 +0x25
github.com/lesismal/nbio.(*Engine).OnClose.func1(0xc0003c48c0?, {0x0?, 0x0?})
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/engine.go:236 +0x7b
github.com/lesismal/nbio.(*poller).deleteConn(0xc0003c48c0?, 0xc0002c00d0?)
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/poller_kqueue.go:87 +0xba
github.com/lesismal/nbio.(*Conn).closeWithErrorWithoutLock(0xc0002c00d0, {0x0?, 0x0})
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn_unix.go:565 +0xf6
github.com/lesismal/nbio.(*Conn).closeWithError(0xc0002c00d0, {0x0, 0x0})
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn_unix.go:543 +0x15c
github.com/lesismal/nbio.(*Conn).Close(...)
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn_unix.go:232
github.com/lesismal/nbio.(*Engine).Stop.func2()
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/engine.go:167 +0x25
github.com/lesismal/nbio/timer.(*Timer).loop.func1(0xc000436f78?, 0xc000436f14?)
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:179 +0x53
github.com/lesismal/nbio/timer.(*Timer).loop(0xc00015a000)
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:180 +0x507
created by github.com/lesismal/nbio/timer.(*Timer).Start
     /Users/didi/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:57 +0x6a

`

**Comment by changyl** [comment]
^C2023/04/14 20:18:57.747 [ERR] Timer[NB] exec call failed: sync: negative WaitGroup counter
goroutine 71 [running]:
github.com/lesismal/nbio/timer.(*Timer).loop.func1.1()
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:175 +0x78
panic({0x16f3a20, 0x1914eb0})
     /usr/local/go/src/runtime/panic.go:884 +0x212
sync.(*WaitGroup).Add(0x103b876?, 0xc000436d88?)
     /usr/local/go/src/sync/waitgroup.go:83 +0xda
sync.(*WaitGroup).Done(0xc0002c00d0?)
     /usr/local/go/src/sync/waitgroup.go:108 +0x25
github.com/lesismal/nbio.(*Engine).OnClose.func1(0xc0003c48c0?, {0x0?, 0x0?})
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/engine.go:236 +0x7b
github.com/lesismal/nbio.(*poller).deleteConn(0xc0003c48c0?, 0xc0002c00d0?)
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/poller_kqueue.go:87 +0xba
github.com/lesismal/nbio.(*Conn).closeWithErrorWithoutLock(0xc0002c00d0, {0x0?, 0x0})
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn_unix.go:565 +0xf6
github.com/lesismal/nbio.(*Conn).closeWithError(0xc0002c00d0, {0x0, 0x0})
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn_unix.go:543 +0x15c
github.com/lesismal/nbio.(*Conn).Close(...)
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/conn_unix.go:232
github.com/lesismal/nbio.(*Engine).Stop.func2()
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/engine.go:167 +0x25
github.com/lesismal/nbio/timer.(*Timer).loop.func1(0xc000436f78?, 0xc000436f14?)
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:179 +0x53
github.com/lesismal/nbio/timer.(*Timer).loop(0xc00015a000)
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:180 +0x507
created by github.com/lesismal/nbio/timer.(*Timer).Start
     /Users/eden/go/pkg/mod/github.com/lesismal/nbio@v1.3.10/timer/timer.go:57 +0x6a



>

**Comment by lesismal** [comment]
Please provide the full examples that can reproduce the problem, including server and client code, I'll try it.

**Comment by changyl** [comment]
> 

Thank you, because the link closing operation is closed through the copy of the connection, so panic
