### ISSUE TITLE
我想问下nbio能够开启端口复用吗

### ISSUE THREAD

**Issue by Kotodian** [lesismal/nbio#285]

**Comment by lesismal** [comment]
nbio默认的listener没有支持reuseport，因为不想依赖三方库，并且三方的reuseport也很工整、不想copy一份放到nbio里。
但是nbio支持用户自定义listener，Accept得到的Conn通过AddConn相关方法添加到nbio的Engine里。

TCP的例子:
https://github.com/lesismal/nbio/issues/157#issuecomment-1047563475

HTTP的Engine支持自定义Listen函数和通过NListener设置每个addr的listener协程数量：
```golang
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/lesismal/nbio/nbhttp"
	reuseport "github.com/libp2p/go-reuseport"
)

func onEcho(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte(time.Now().Format("20060102 15:04:05")))
}

func main() {
	mux := &http.ServeMux{}
	mux.HandleFunc("/", onEcho)

	engine := nbhttp.NewServer(nbhttp.Config{
		Network: "tcp",
		Addrs:   []string{"localhost:8080"},
		Listen:  reuseport.Listen,
		// NListener: 2,//启动NListener个协程进行Accept loop，如果不设置，默认为1
		Handler: mux,
	})

	err := engine.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}
	defer engine.Stop()

	<-make(chan int)
}
```

用户也可以自己进行Listen，Accept的Conn用 AddConnNonTLSBlocking/AddConnNonTLSNonBlocking/AddConnTLSBlocking/AddConnTLSNonBlocking 系列函数添加到 Engine里进行管理，这几个函数涉及不同的IOMod，具体使用方式可以根据自己的需要参考下相关代码

**Comment by Kotodian** [comment]
原来可以这样,感谢

**Comment by lesismal** [comment]
不客气，感谢使用和支持！
