### ISSUE TITLE
协议解析怎么使用，怎么才能让OnData()的数据是一个协议的完整的数据包

### ISSUE THREAD

**Issue by chowyu08** [lesismal/nbio#3]

**Comment by lesismal** [comment]
nbio 已经支持 http 1.x，例子在这里：
https://github.com/lesismal/nbio/tree/master/examples/http

tcp之上的其他自定制应用层协议，通常需要应用层自己处理包的解析，大致流程是：
1. OnData 中判断数据是否足够数据头或标识包体长度的部分，如果足够，则解析包体长度，否则数据缓存起来，下次有数据和之前的数据append到一起，再进行判断
2. 已有包头、计算出包体大小后，跟判断包头长度是类似的逻辑，判断当前已有数据是否足够整个包，够则解析包并传递给应用层，不够则缓存数据、待下次数据到来再进行判断

arpc 使用 nbio 做网络层这里有个例子，仅供参考：
https://github.com/lesismal/arpc/blob/master/examples/nbio/server/server.go

**Comment by lesismal** [comment]
通常应在 OnOpen 中设置应用层的 Session，可能包括你们用于包解析、Connection或者其他所需信息的数据结构，比如 arpc 例子中的这里：
https://github.com/lesismal/arpc/blob/master/examples/nbio/server/server.go#L28

在 OnData 中取出你之前设置的 nbio.Conn.Session ，并用这个 Session 相关的组件进行你们的完整包解析、消息处理等：
https://github.com/lesismal/arpc/blob/master/examples/nbio/server/server.go#L42
