### ISSUE TITLE
nbio实现网关的一些问题

### ISSUE THREAD

**Issue by liwnn** [lesismal/nbio#303]
首先，感谢大佬开源这个项目，对我帮助很大。

我用nbio开发的是一个网关，接收几十万客户端连接（tcp、websocket同时支持），网关把消息做简单的逻辑处理，然后转发到客户端指定的服务器（只有几千台，tcp连接），服务器处理消息后再通过网关转发回客户端

现在方案是：用nbio启动两个server分别支持tcp跟websocket客户端连接；启动一个tcp server支持服务器连接

问题是：
1. 在issue中看您说过，连接少的时候，标准库性能较高。所以我针对服务器的连接（只有几千连接）是不是应该用标准库实现以获取更高性能？我看websocket可以设置阻塞模式，而tcp没有此选项
2. 我应该尝试往哪个方向设置参数，能让nbio发挥最大性能？

**Comment by lesismal** [comment]
感谢关注和支持！

> 在issue中看您说过，连接少的时候，标准库性能较高。所以我针对服务器的连接（只有几千连接）是不是应该用标准库实现以获取更高性能？

到服务器只有几千连接的话可以用标准库的，但是要注意要尽量避免单个Conn.Write可能阻塞而造成client转发数据阻塞：
到服务端的连接，最好是异步写，比如单独一个协程+chan做队列，或者动态协程执行异步写入类似这里： https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L613

> 我看websocket可以设置阻塞模式，而tcp没有此选项

这个是指nbhttp Engine这个server端的，IOModBlocking阻塞模式的连接会为每个连接分配至少一个协程处理读，如果你们连接数很大不适合用这种模式、内存和GC压力大、服务不稳定。
IOModMixed是适合：低峰场景让设置的连接数采用阻塞模式获取更好的相应性能，高峰时段能承载大量连接。
但如果持续高在线、没有低峰时段，其实只保证少量连接的响应性意义不是特别大，但设置这种也只是为那少量连接数采用Blocking模式、每个连接至少一个协程，所以消耗也不至于很大，使用这种也可以

`而tcp没有此选项`：其实http/websocket的阻塞、非阻塞Conn的分流是通过这里的 lmux 实现的：
https://github.com/lesismal/nbio/blob/master/lmux/lmux.go
原理比较简单，就是把Listener封装一层，并且用chan分流给两个自实现的Listener A B，加上计数，当前A处理的阻塞连接数小于设置的阈值时，把连接分发给A去用阻塞模式处理，并且计数+1，该连接断开时计数-1；当A处理的阻塞连接数达到设置的阈值时，把新连接分发给B去加入到nbio的poller作为非阻塞连接进行管理。如果你们需要实现tcp的这种类似模式，稍微封装下也比较容易


> 我应该尝试往哪个方向设置参数，能让nbio发挥最大性能？

在线量这么大，通常每个连接上的交互频率不会特别高，如果每个连接都很高频交互、其实已经超过了硬件响应能力。nbio主要优势是与标准库方案相比，不需要为每个连接固定使用至少一个常驻协程、减少内存和GC压力、让服务稳定。
如果交互频率不是特别高，如果业务没有太特殊的需要，默认参数比如逻辑协程数量这些基本能够均衡。如果你们服务有特殊要求，得结合实际业务特点才能做瓶颈热点分析和针对优化，这个我目前不知道你们是否有特殊情况，也不好确定哪里需要优化

**Comment by liwnn** [comment]
感谢这么晚了还花时间解答

我们服务每个连接发包频率不大，平均几秒一个，会对连接限流，最多每秒10个。

后面参考您的建议用标准库实现server端的连接，测试下性能。如果跟nbio差距不大的话，就选nbio，毕竟nbio简单易用。

另外还有个问题：
客户端收到消息，需要转发服务器。每个消息都是copy一遍的，这部分[]byte怎么去回收？如果目标Conn有buff的，应该是可以立即回收的，否则需要等待网络写完回收？

**Comment by lesismal** [comment]
> 客户端收到消息，需要转发服务器。每个消息都是copy一遍的，这部分[]byte怎么去回收？如果目标Conn有buff的，应该是可以立即回收的，否则需要等待网络写完回收？

这个能提供下你们具体实现的示例吗？

**Comment by liwnn** [comment]
> > 客户端收到消息，需要转发服务器。每个消息都是copy一遍的，这部分[]byte怎么去回收？如果目标Conn有buff的，应该是可以立即回收的，否则需要等待网络写完回收？
> 
> 这个能提供下你们具体实现的示例吗？

// 客户端的TCP消息
func (s *ClientTcp) OnRead(c *nbio.Conn, data []byte) {
	// 这个是客户端连接
	session, _ := c.Session().(*ClientSession)
	for {
		// 解析一个包
		size, ok := parsePacketLen(data)
		if !ok {
			// 增加到buffer...
			return
		}
		// 这个packet怎么回收?
		packet := make([]byte, size)
		copy(packet, data[:size])
		data = data[size:]

		// 取出目标服务器的连接，发送网络数据
		serverConn := GetServerConn(session.serverID)
		serverConn.Write(packet)
	}
}

**Comment by lesismal** [comment]
简单写了下大概，没有调试，不敢保证正确性，大概是这个意思，仅供参考：
```golang
package main

import (
	"context"
	"encoding/binary"
	"fmt"
	_ "net/http/pprof"
	"os"
	"os/signal"
	"sync"
	"time"

	"github.com/lesismal/nbio"
)

// 绝大多数包的长度，如果都不是特别大的包，就设置为最长长度
const mostPacketLength = 1024

var bufferPool = sync.Pool{
	New: func() interface{} {
		b := make([]byte, mostPacketLength)
		return &b
	},
}

func getBuffer(n int) []byte {
	pbuf := bufferPool.Get().(*[]byte)
	if cap(*pbuf) < n {
		*pbuf = append((*pbuf)[:cap(*pbuf)], make([]byte, n-cap(*pbuf))...)
	}
	*pbuf = (*pbuf)[:n]
	return *pbuf
}

func putBuffer(buf []byte) {
	bufferPool.Put(&buf)
}

// 表示整个packet长度的字节数。
// 假设0、1两个字节的uint16表示整个packet长度，则body为这个uint16-2，字节序是大端还是小端、其他协议细节以你们实际为准
const packetLenBytes = 2

type ClientTcp struct {
	buf      []byte
	serverID string
}

// 客户端的TCP消息
func (client *ClientTcp) OnRead(c *nbio.Conn, data []byte) {
	if client.buf == nil {
		// 如果之前没有缓存packet数据，直接消费data
		consumed, err := client.parseAndForwardMessage(c, data)
		if err != nil {
			// 如果不需要close client，需要把未消费完的buffer缓存起来
			c.Close()
			return
		}
		// 消费的data字节数少于data总字节数、还有剩余，需要缓存起来，与下次数据拼接
		if consumed < len(data) {
			client.buf = getBuffer(len(client.buf) - consumed)
			copy(client.buf, data[consumed:])
		}
	} else {
		// 如果之前有缓存的部分packet数据，data append到之前数据再消费
		client.buf = append(client.buf, data...)
		consumed, err := client.parseAndForwardMessage(c, client.buf)
		if err != nil {
			// 如果不需要close client，需要把未消费完的buffer缓存起来
			c.Close()
			return
		}
		if consumed < len(data) {
			// 消费的data字节数少于data总字节数、还有剩余，把数据从尾部挪到头部继续缓存
			copy(client.buf, client.buf[consumed:])
			client.buf = client.buf[:len(client.buf)-consumed]
		} else {
			// 刚好消费完，归还buffer，避免每个conn都长期持有buffer占用内存高
			putBuffer(client.buf)
			client.buf = nil
		}
	}
}

func (client *ClientTcp) parseAndForwardMessage(c *nbio.Conn, data []byte) (consumed int, err error) {
	var nwrite int
	for len(data) > packetLenBytes {
		packetLen := int(binary.LittleEndian.Uint16(data[:2]))
		if len(data) < packetLen {
			return consumed, nil
		}
		packet := getBuffer(packetLen)
		serverConn := GetServerConn(client.serverID)
		// 可以先尝试不用buffer pool看看你们线上服务内存有压力没，通常非高频、非大包，runtime自己GC那些就足够了;
		// 这里示例用了buffer pool，如果是同步写，写成功后就可以归还packet的buffer，如果是异步写，要等异步写完后再归还；
		// 如果确实需要用pool但仍然压力大，内存池这块就还需要考虑其他优化方案，比如加chan限流器，SetMaxMemory，手动GC，或者用cgo配合c malloc/free、jemalloc之类的
		nwrite, err = serverConn.Write(packet)
		putBuffer(packet)
		if err != nil {
			return consumed, err
		}
		consumed += packetLen
		data = data[packetLen:]
	}
	return
}

func main() {
	engine := nbio.NewEngine(nbio.Config{
		Network: "tcp",
		Addrs:   []string{":8000"},
	})
	engine.OnOpen(func(c *nbio.Conn) {
		client := &ClientTcp{}
		c.SetSession(client)
	})
	engine.OnData(func(c *nbio.Conn, data []byte) {
		session := c.Session()
		if client, ok := session.(*ClientTcp); ok {
			client.OnRead(c, data)
		} else {
			c.Close()
		}
	})
	engine.OnClose(func(c *nbio.Conn, err error) {
		// ...
	})

	err := engine.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}
	defer engine.Stop()

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
	defer cancel()
	engine.Shutdown(ctx)
}
```

**Comment by liwnn** [comment]
明白了，再次感谢，非常好的项目。现在时间比较紧，后面有时间了，要仔细看下nbio的代码

**Comment by lesismal** [comment]
好的，感谢支持！

**Comment by liwnn** [comment]
不好意思，再打扰下。因为serverConn是nbio.Conn，如果用pool的话，现在write需要等待回掉，nbio是没有回掉的吧？

```
		serverConn := GetServerConn(client.serverID)
		// 可以先尝试不用buffer pool看看你们线上服务内存有压力没，通常非高频、非大包，runtime自己GC那些就足够了;
		// 这里示例用了buffer pool，如果是同步写，写成功后就可以归还packet的buffer，如果是异步写，要等异步写完后再归还；
		// 如果确实需要用pool但仍然压力大，内存池这块就还需要考虑其他优化方案，比如加chan限流器，SetMaxMemory，手动GC，或者用cgo配合c malloc/free、jemalloc之类的
		nwrite, err = serverConn.Write(packet)
```

**Comment by lesismal** [comment]
serverConn如果是nbio.Conn，直接写就行，写完就可以释放，不需要等待回调。
