### ISSUE TITLE
Reduce the number of calls to time.Now in setdeadline

### ISSUE THREAD

**Issue by liwnn** [lesismal/nbio#310]
函数setDeadline，参数已经是最终时间了。但是为了使用Timer中的AfterFunc，会调用time.Now()计算差值，Timer中的AfterFunc也会再执行time.Now，计算最终时间。相当于多调用了两个time.Now，连接数量大了，还是有些开销的。

是否可以给Timer中添加直接设置最终时间的函数解决此问题？

```go
func (c *Conn) setDeadline(timer **timer.Item, returnErr error, t time.Time) error {
	c.mux.Lock()
	defer c.mux.Unlock()
	if c.closed {
		return nil
	}
	if !t.IsZero() {
		now := time.Now()
		if *timer == nil {
			*timer = c.p.g.AfterFunc(t.Sub(now), func() { c.closeWithError(returnErr) })
		} else {
			(*timer).Reset(t.Sub(now))
		}
	} else if *timer != nil {
		(*timer).Stop()
		(*timer) = nil
	}
	return nil
}
```

**Comment by lesismal** [comment]
有道理，加个 UntilFunc() ?

用户SetDeadline的时候就是取now.Add了一次，nbio里又两次取now

**Comment by liwnn** [comment]
> 有道理，加个 UntilFunc() ?
> 
> 用户SetDeadline的时候就是取now.Add了一次，nbio里又两次取now

AddFunc? 增加计时器。AfterFunc把时间算一下，也调用AddFunc？

**Comment by lesismal** [comment]
`AddFunc` 这个名字的意义不好理解。

实现`net.Conn`接口，用户应用层自己`time.Now().Add`那个是没法省略了

**Comment by liwnn** [comment]
是的，用户层肯定是最终时间

**Comment by lesismal** [comment]
time包里有 `Until`，参数也是 `time.Time`，叫 `UntilFunc` 可能会好些，而且用户用 `SetDeadline(time.Now().Add(...))`的时候，直接把这个 setDeadline 的 `time.Time` 参数传递给 `UntilFunc` 作为 `timer` 的 `expire` 就可以了

**Comment by lesismal** [comment]
哦也不是完全能省，如果需要reset trigger，还是要取timeout，还是得取now、sub一下

**Comment by lesismal** [comment]
不管是用 `time.Duration` 还是 `time.Time` 做参数，鱼和熊掌不可兼得了好像，但是多数场景设置超时的时间都是堆尾、不需要reset trigger，就可以省掉一些

再想想

**Comment by liwnn** [comment]
> 不管是用 `time.Duration` 还是 `time.Time` 做参数，鱼和熊掌不可兼得了好像，但是多数场景设置超时的时间都是堆尾、不需要reset trigger，就可以省掉一些
> 
> 再想想

是的，针对setDeadline场景，理论上每次都是堆尾；其他场景 ，堆顶的可能性也很小，reset trigger的消耗可以忽略不计了。

**Comment by lesismal** [comment]
```golang
// UntilFunc call f when time expire.
func (t *Timer) UntilFunc(expire time.Time, f func()) *Item {
	t.mux.Lock()

	it := &Item{
		index:  len(t.items),
		expire: expire,
		f:      f,
		parent: t,
	}

	heap.Push(&t.items, it)
	if t.items[0] == it {
		t.trigger.Reset(time.Now().Sub(it.expire))
	}

	t.mux.Unlock()

	return it
}
```
