### ISSUE TITLE
Using nbhttp for server-sent events

### ISSUE THREAD

**Issue by c1llo** [lesismal/nbio#312]
I am using nbio with the echo framework followuing the example, with websockets it works perfectly!

The only thing I am having trouble with is that there is not an exposed Flusher interface implemented by nbio.Response.
https://pkg.go.dev/net/http#Flusher
https://github.com/lesismal/nbio/blob/master/nbhttp/response.go

Here is some code just for an example (using server-sent events requires the buffer to be flushed):

```
func (a *ApiHandlers) LiveEvents(c echo.Context) error {
	userId := c.Get("userId").(uuid.UUID)

	topic := fmt.Sprintf("events:%s", userId.String())

	eventsSub := a.EventService.EventBus.Subscribe(topic)
	defer eventsSub.Unsubscribe()

	c.Response().Header().Set(echo.HeaderContentType, "text/event-stream")
	c.Response().Header().Set(echo.HeaderCacheControl, "no-cache")
	c.Response().Header().Set(echo.HeaderConnection, "keep-alive")
	c.Response().Header().Set("X-Accel-Buffering", "no")

	w := c.Response().Writer.(*nbhttp.Response)

	_, err := w.Write([]byte("data:connected to aurora\n\n"))
	if err != nil {
		return err
	}

	//previously able to do c.Response().Flush(), Flush() is not available on nbhttp.Response
	// c.Response().Flush()

	for {
		select {
		case <-c.Request().Context().Done():
			// User closed the connection. We are out of here.
			return nil
		case ev := <-eventsSub.Channel:
			_, err := fmt.Fprint(c.Response(), "event:event\n")
			if err != nil {
				return err
			}

			publishedEvent := ev.(publishedEvent)

			_, err = fmt.Fprintf(c.Response(), "data:%s\n\n", publishedEvent.ID.String())
			if err != nil {
				return err
			}
		}
	}
}
```

**Comment by lesismal** [comment]
Thank you for your feedback!

I think this means it will hold this goroutine for a long time, 
but nbio aims to avoid continues goroutine usage for each connection.
If your service use http only, I think it's better to use std http.Server for this logic:
```golang
for {
	select {
	case <-c.Request().Context().Done():
		// User closed the connection. We are out of here.
		return nil
	case ev := <-eventsSub.Channel:
		_, err := fmt.Fprint(c.Response(), "event:event\n")
		if err != nil {
			return err
		}

		publishedEvent := ev.(publishedEvent)

		_, err = fmt.Fprintf(c.Response(), "data:%s\n\n", publishedEvent.ID.String())
		if err != nil {
			return err
		}
	}
}
```

> I am using nbio with the echo framework followuing the example, with websockets it works perfectly!

But it seems your service also supports websocket. Then I think it should be better to use websocket and push subscribed message async.

**Comment by c1llo** [comment]
Thanks I decided to use websockets. I'm not sure how to push subscribed message async with nbio while consuming a channel? I just created a new goroutine:

```
	userId := c.Get("userId").(uuid.UUID)

	topic := fmt.Sprintf("events:%s", userId.String())

	eventsSub := a.EventService.EventBus.Subscribe(topic)

	upgrader := websocket.NewUpgrader()
	upgrader.CheckOrigin = func(r *http.Request) bool {
		return true
	}

	conn, err := upgrader.Upgrade(c.Response(), c.Request(), nil)
	if err != nil {
		return err
	}

	go func(){
		for ev := range eventsSub.Channel {
			publishedEvent := ev.(publishedEvent)

			err := conn.WriteMessage(websocket.TextMessage, []byte(publishedEvent.ID.String()))
			if err != nil {
				c.Logger().Error(err)
				break
			}
		}
	}()

	return nil
```

**Comment by lesismal** [comment]
I think your `eventsSub` should support async push after `Subscribe`.
```golang
wsConn, err := upgrader.Upgrade()
if err != nil {
    // ...
}
Subscribe(topic, func(topic, data) {
    wsConn.WriteMessage(MessageType, topic and data)
}
```

But in your example, I only found Blocking Subscribe, which means you must use a goroutine to handle events.
Maybe you can refer to your implementation of EventBus and find out whether there is a way to receive publish async.

**Comment by c1llo** [comment]
perfect I managed to do it:

https://github.com/c1llo/aurora/blob/main/api/realtime_websocket_handlers.go#L160

**Comment by lesismal** [comment]
Yes, perfect, congratulations! :smile:
