### ISSUE TITLE
Use cases of MaxLoad and MaxBlockingOnline configurations

### ISSUE THREAD

**Issue by WeiquanWa** [lesismal/nbio#315]
> 	// MaxLoad represents the max online num, it's set to 10k by default.
>	MaxLoad int

>	// MaxBlockingOnline represents max blocking conn's online num.
>	MaxBlockingOnline int

They are from Config struct. Seems they're similar to each other. Please describe the use cases of them.

**Comment by WeiquanWa** [comment]
Please describe use cases of `ReadBufferSize` and `BlockingReadBufferSize` as well

**Comment by lesismal** [comment]
`MaxLoad` limits each `Engine`'s max online connection num

`MaxBlockingOnline` limits the connection num that uses blocking mod(based on blocking net.Conn such as net.TCPConn, std tls.Conn and llib tls.Conn).

For example:
```golang
MaxLoad=100
MaxBlockingOnline=50
```

The Engine can manage at most 100 connections, if more connections come, they will be closed right after being Accepted.
And at most 50 connections are running in blocking mod, the other connections running on non-blocking mod and managed by nbio's poller.

**Comment by WeiquanWa** [comment]
it means at most 50 connections can run in blocking mod and the rest of connections(100-50) can run on non-blocking mod. right?

**Comment by lesismal** [comment]
> it means at most 50 connections can run in blocking mod and the rest of connections(100-50=50) can run on non-blocking mod. right?

Yes, correct.

**Comment by WeiquanWa** [comment]
> Please describe use cases of `ReadBufferSize` and `BlockingReadBufferSize` as well

what about this?

**Comment by lesismal** [comment]
For `IOModBlocking` and the blocking mod connections in `IOModMixed`, we need 1 read buffer to for-loop read each connection's data, `BlockingReadBufferSize` is the read buffer size of this.

**Comment by WeiquanWa** [comment]
then `IOModMixed` will use both `ReadBufferSize` and `BlockingReadBufferSize`?

**Comment by WeiquanWa** [comment]
got you. 

Finally we've decided to move forward with nbio/websocket for our system. FYI,  I closely checked lxzan/gws too, but it has a potential issue that uses single buffer pool for reading and writing across all connections. This is not realistic for our system and also other enterprise systems. Would you let me know the memory management method being used?

**Comment by lesismal** [comment]
> Finally we've decided to move forward with nbio/websocket for our system. FYI, I closely checked lxzan/gws too, but it has a potential issue that uses single buffer pool for reading and writing across all connections. This is not realistic for our system and also other enterprise systems. 

> Would you let me know the memory management method being used?

That's a long long story, I'm not native English speaker, it's difficult for me to describe it clearly by now.
But the default buffer pool's implementation is not too complex, you can read the source code here:
https://github.com/lesismal/nbio/blob/master/mempool/mempool.go

To control memory usage and make your service healthy as much as possible, I suggest to `SetMemoryLimit` like this:
https://github.com/lesismal/go-websocket-benchmark/blob/main/frameworks/nbio_mod_mixed/server.go#L31

Here is some 1m-connections benchmark report on my ubuntu vm, the nbio non-blocking server use cpu 0-3 and `SetMemoryLimit(2G)`, benchmark with 1k payload:
```sh
--------------------------------
os:

Ubuntu 20.04.6 LTS \n \l

--------------------------------
cpu model:

model name	: AMD Ryzen 7 5800H with Radeon Graphics
--------------------------------
              total        used        free      shared  buff/cache   available
Mem:       16362568      396988    15151676        1636      813904    15656380
Swap:             0           0           0
--------------------------------
2023/05/30 14:27:01.747 [INF] NBIO[Benchmark-Client] start
2023/05/30 14:27:01 1000000 clients start connecting
2023/05/30 14:27:02 29006 clients connected
2023/05/30 14:27:03 65988 clients connected
......
2023/05/30 14:27:33 999988 clients connected
2023/05/30 14:27:33 1000000 clients connected
-------------------------
BENCHMARK: nbio_mod_nonblocking
TOTAL    : 5000000 times
SUCCESS  : 5000000, 100.00%
FAILED   : 0, 0.00%
TPS      : 126575
TIME USED: 39.50s
MIN USED : 59.06ms
MAX USED : 237.44us
AVG USED : 15.80us
TP50     : 14.35us
TP75     : 19.70us
TP90     : 25.88us
TP95     : 30.52us
TP99     : 42.36us
CPU MIN  : 0.00%
CPU MIN  : 365.01%
CPU MIN  : 430.50%
MEM MIN  : 1.60G
MEM MIN  : 1.95G
MEM MIN  : 2.09G
-------------------------
```

For more details about 1m-connections benchmark, please refer to:
https://github.com/lesismal/go-websocket-benchmark#1m-connections-benchmark-for-nbio

**Comment by lxzan** [comment]
What do you think are the potential problems with using a single buffer pool ? If there is indeed a flaw, it would be helpful for me to improve gws
