### ISSUE TITLE
请教几个参数的问题

### ISSUE THREAD

**Issue by liwnn** [lesismal/nbio#318]
1. ReadBufferSize是跟poller绑定的，所以说理论上越大越好？
```go
	// ReadBufferSize represents buffer size for reading, it's set to 16k by default.
	ReadBufferSize int
```
(注释说默认16K，实际上似乎是64K)
2. MaxWebsocketFramePayloadSize 看代码只有write时用到了，read是用不到的？
```go
	// MaxWebsocketFramePayloadSize represents max payload size of websocket frame.
	MaxWebsocketFramePayloadSize int
```

**Comment by lesismal** [comment]
> ReadBufferSize是跟poller绑定的，所以说理论上越大越好？

压测了一些数据，好像64k比较好，当然，得看不同节点配置的具体情况，但是单就各个poller框架而言，这个数值在同一个软硬环境下应该是差不多的。

早期配置的16k，后来改为64k，注释忘了更新，下次更新上去

> 2. MaxWebsocketFramePayloadSize 看代码只有write时用到了，read是用不到的？

这个主要是用来限制大buffer使用，而且单次写入太大对syscall write也不友好，所以应用层写大buffer时自动拆成小帧

**Comment by lesismal** [comment]
注释这个先顺手改了：
https://github.com/lesismal/nbio/commit/a3f0a1ef87e59226046511c80290cf46da69050b

你看得好仔细，发现问题，欢迎来PR啊

**Comment by liwnn** [comment]
> 注释这个先顺手改了： [a3f0a1e](https://github.com/lesismal/nbio/commit/a3f0a1ef87e59226046511c80290cf46da69050b)
> 
> 你看得好仔细，发现问题，欢迎来PR啊

最近在研究参数怎么调优。另外websocket的ReadBufferSize注释也得改下。

**Comment by lesismal** [comment]
内核缓冲区size、当前缓冲数据这些相互影响的，如果当前缓冲区数据多，应用层buffer小就要读多次，大一点就可以省一些syscall。
具体多少划算是个玄学，搜一下对应的内核参数也设置上不同的值，然后应用层也多配置不同的参数压测试试

**Comment by liwnn** [comment]
好的，感谢解答
