### ISSUE TITLE
What happens when multiple goroutines send a message to single websocket connection?

### ISSUE THREAD

**Issue by WeiquanWa** [lesismal/nbio#319]
Let's say there are multiple goroutines that sends own messages to single websocket connection. What happens under IOModBlocking and IOModMixed?

**Comment by lesismal** [comment]
The WriteMessage/Close is concurrent safe.
The message will be sent one by one.
No matter which IOMod it is, It's the same for users.

For more details, please read the code.

**Comment by WeiquanWa** [comment]
cool. then what happens if I attempt to re-close an already closed websocket connection?

**Comment by lesismal** [comment]
> cool. then what happens if I attempt to re-close an already closed websocket connection?

It's also concurrent safe.
nbhttp/websocket.Conn.Close just closes the underlayer net.Conn, such as net.TCPConn/nbio.Conn/tls.Conn/llib tls.Conn/..., as far as I know, all these net.Conn are implemented with Lock and are concurrent safe.
For OnClose callback, nbhttp/websocket will call it only once too:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L548
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L569

So, no need worrying about calling Write/Close concurrently, that's safe and `Just Do It`

**Comment by WeiquanWa** [comment]
> https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L548
Do I have to call `CloseAndClean` instead of `Close` for a connection?

**Comment by lesismal** [comment]
> > https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L548
> 
> Do I have to call `CloseAndClean` instead of `Close` for a connection?

No need, it will be automatically called by nbio if it's blocking-mod connection:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L761

CloseAndClean may be used to deeply customize some features but rarely need to do it, so, it also may be deprecated in future versions.

**Comment by WeiquanWa** [comment]
Let me describe my use case.  I'm going to send ping frames from server side, not client side inside another goroutine. When writing the ping frame is failed, I'm going to close the connection at the point.  The following is the relevant code.
```
// sendPing sends a ping frame to a client periodically
func (c *Client) sendPing(pingMsg string) {
	ticker := time.NewTicker(cfg.WSSettingsVal.PingInterval)
	defer func() {
		ticker.Stop()
		// Graceful close if this triggers a closing
		_ = c.connection.Close()
		c.manager.removeClient(c)
	}()
	for {
		select {
		case <-ticker.C:
			if err := c.connection.WriteMessage(websocket.PingMessage, []byte(pingMsg)); err != nil {
				slog.Error(cfg.LOG_ID_GLOBAL, err)
				return
			}

		}
	}

}
```
I have a concern  the attempt to re-close the connection that was already closed by nbio  will cause a panic

**Comment by lesismal** [comment]
I think that's not a good way to close zombie connections as I said before:
It's better to let client-side to send the message, and the server-side just set `upgrader.KeepaliveTime = YourTimeout`

In your implementation, you use 1 goroutine to do it every connection during the whole life time of the connection.

If you must to do it that sending ping message in your server-side, I will suggest like this:
```golang
// nbio automatically reset ReadDeadline when receiving a message
upgrader.KeepaliveTime = time.Second * 30

// use time.AfterFunc, it only cost 1 goroutine during sending ping message then exit,
// and reset the timer to do it again if sending success, else never set it again
upgrader.OnOpen(func(c *websocket.Conn) {
	var aliveFn func()
	aliveFn = func() {
		if err := c.WriteMessage(websocket.PingMessage, []byte(pingMsg)); err != nil {
			slog.Error(cfg.LOG_ID_GLOBAL, err)
			return
		}
		time.AfterFunc(cfg.WSSettingsVal.PingInterval, aliveFn)
	}
	time.AfterFunc(cfg.WSSettingsVal.PingInterval, aliveFn)
})
```

**Comment by WeiquanWa** [comment]
>It's better to let client-side to send the message,

Browsers (where our clients will play) cannot send ping frames to a websocket server. That's why I'm going to send ping from a server. 

> If you must to do it that sending ping message in your server-side, I will suggest like this:

Thank you for your code sample, however, there is no logic to close the connection when failed to writing a ping frame in your code?

**Comment by lesismal** [comment]
> Browsers (where our clients will play) cannot send ping frames to a websocket server. That's why I'm going to send ping from a server.

But Browsers can send User-Defined-Message, such as a Binary/Text message. That also works for updating ReadDeadline and Keepalive.

> however, there is no logic to close the connection when failed to writing a ping frame in your code? Without it, how to close the zombie connection?

Of course you can call Close.

**Comment by WeiquanWa** [comment]
>Of course you can call Close.

Well, I think the logic to call `Close` function outside nbio will cause a panic in the case that nbio already closed the connection in its own logic?

**Comment by lesismal** [comment]
> > Of course you can call Close.
> 
> Well, I think the logic to call `Close` function outside nbio will cause a panic in the case that nbio already closed the connection in its own logic?

no.

please spend a little time reading the code:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/conn.go#L88

or just try it

**Comment by WeiquanWa** [comment]
I'm wondering how the upstream code of `Close` function is different from my downloaded local code (v1.3.16).  Have you updated the code recently?  The following image is what I'm seeing 
![image](https://github.com/lesismal/nbio/assets/88868948/b962b87c-9b33-4913-b804-945d2ba5b4a2)

**Comment by WeiquanWa** [comment]
hmm, I'm right.  you've upgraded the close function in upstream. when will the new version be released?

**Comment by lesismal** [comment]
> hmm, I'm right. you've upgraded the close function in upstream. when will the new version be released?

It's just a nil checking, but the websocket.Conn.Conn is never set to nil by nbio, unless user set it to nil.
So, the Close func is not different.
