### ISSUE TITLE
日志打印建议

### ISSUE THREAD

**Issue by buexplain** [lesismal/nbio#320]
https://github.com/lesismal/nbio/blob/9f947279faa0995b5bea36c9f8119032d0ababfe/nbhttp/engine.go#L567
建议打印一下这个错误日志，因为这里有可能出现：`too many open files`错误，如果没有提示，根本想不到连接为什么被拒绝了。

**Comment by lesismal** [comment]
有道理，要加下

**Comment by lesismal** [comment]
已经加了一些:
https://github.com/lesismal/nbio/commit/18db583eca3a9e252f013907c48086b3b8502857

可以先试试 dev :
```sh
go get -u github.com/lesismal/nbio@18db583eca3a9e252f013907c48086b3b8502857
```

**Comment by buexplain** [comment]
> 

好的
