### ISSUE TITLE
Question: writeBuffer

### ISSUE THREAD

**Issue by wuqinqiang** [lesismal/nbio#322]
[writeBuffer](https://github.com/lesismal/nbio/blob/master/conn_unix.go#L409)

<img width="639" alt="截屏2023-06-03 10 34 56" src="https://github.com/lesismal/nbio/assets/36129334/b54ef12e-836c-4609-af57-599beea0f3d4">

这里对writeBuffer 操作不加锁没并发bug吗？

走到这里，说明上次writeBuffer是没写完的，conn对应所属的epoll可写事件会持续触发，在flush也会对writeBuffer操作，尽管flush操作是加锁的。

**Comment by lesismal** [comment]
这些地方是小写的包内 private func，是由大写的 public func 调用的，public func 都有锁的：
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L149
https://github.com/lesismal/nbio/blob/master/conn_unix.go#L180

**Comment by wuqinqiang** [comment]
> 这些地方是小写的包内 private func，是由大写的 public func 调用的，public func 都有锁的： https://github.com/lesismal/nbio/blob/master/conn_unix.go#L149 https://github.com/lesismal/nbio/blob/master/conn_unix.go#L180

是我看错了😂，感谢。

**Comment by lesismal** [comment]
> 是我看错了，感谢。

不客气，能多些人来关注和认真研究交流是好事情，如果有兴趣来一起维护的话更好了

**Comment by wuqinqiang** [comment]
> > 是我看错了，感谢。
> 
> 不客气，能多些人来关注和认真研究交流是好事情，如果有兴趣来一起开发和维护的话就更好了

哈哈 我是看你们项目代码，然后想实现(模仿)一个最小化netpoll，达到学习的效果，要是能在过程中发现bug, 俺就pr，哈哈。

https://github.com/wuqinqiang/easyio

**Comment by lesismal** [comment]
> https://github.com/wuqinqiang/easyio

![image](https://github.com/lesismal/nbio/assets/40462947/f5beb9c7-2f4d-49c0-a341-32815926c743)

刚好上周看到了你写的nbio的文章，写得挺好的：
https://zhuanlan.zhihu.com/p/617184143

因为你github名字和文章署名Remember不一样，我还不知道是你写的。
刚好今天看邮箱，发件人的名字Remember，才知道是你，哈哈哈

**Comment by wuqinqiang** [comment]
> > https://github.com/wuqinqiang/easyio
> 
> ![image](https://user-images.githubusercontent.com/40462947/243151651-f5beb9c7-2f4d-49c0-a341-32815926c743.png)
> 
> 刚好上周看到了你写的nbio的文章，写得挺好的： https://zhuanlan.zhihu.com/p/617184143
> 
> 因为你github名字和文章署名Remember不一样，我还不知道是你写的。 刚好今天看邮箱，发件人的名字Remember，才知道是你，哈哈哈

好东西值得被学习和文字记录。
另外再分享之前的一个趣事，我第一次看到nbio的时候，理解成 NB IO😂。后面才反应过来，应该是Non-Blocking IO,哈哈

一语双关嘛～～

**Comment by lesismal** [comment]
> 另外再分享之前的一个趣事，我第一次看到nbio的时候，理解成 NB IOjoy。后面才反应过来，应该是Non-Blocking IO,哈哈
> 一语双关嘛～～

你没看错啊，哈哈哈：
https://github.com/lesismal/nbio/commit/c5122cc157bf098a4354eb75773c672233fb41de
https://www.v2ex.com/t/761727#reply5

![image](https://github.com/lesismal/nbio/assets/40462947/214684b0-4ffd-4f53-88b0-70b5c5af4464)
![image](https://github.com/lesismal/nbio/assets/40462947/5ed3ae4b-d43d-4be0-8dc6-ae0298067f69)
