### ISSUE TITLE
ondata

### ISSUE THREAD

**Issue by cjf621** [lesismal/nbio#323]
ondata接受的是conn指针，这个能改吗，不然没法给conn继承加字段了

**Comment by lesismal** [comment]
可以通过 nbio.Conn.SetSession( UserData ) 来保存用户层信息，或者 map[*nbio.Conn]UserData 之类的。需要加字段之类的都由用户层自己的 UserData 里处理即可。使用标准库也是一样的道理

**Comment by cjf621** [comment]
> 可以通过 nbio.Conn.SetSession( UserData ) 、websocket.Conn.SetSession( UserData ) 来保存用户层信息，或者 map[*nbio.Conn]UserData 之类的。需要加字段之类的都由用户层自己的 UserData 里处理即可。使用标准库也是一样的道理

这样不错，我之前是用继承结构体实现，避免全局map的锁持有
