### ISSUE TITLE
what's the config of LockPoller and LockPoller use for ?

### ISSUE THREAD

**Issue by byene0923** [lesismal/nbio#324]
谢谢作者开源，在学习nbio源码，请问下 LockPoller和 LockListener 这两个配置的作用和使用场景

**Comment by lesismal** [comment]
主要是用单独的线程处理Accept或者Read，减少一点调度，可能对相应的消耗密集场景效率略有提升，但普通压测比较难比较出差异：
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L125
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L157

xtaci/gaio 还进一步绑定了cpu：
https://github.com/xtaci/gaio/blob/master/affinity_linux.go#L28

但nbio支持配置多addr、每个addr也支持多listener、每个listener一个协程，nbio也支持多poller，这种不确定的协程数量不太好均匀分配cpu的绑定，绑定cpu后反倒可能使cpu上对应的绑定了线程的协程数的不均匀，所以nbio这里没有对绑定cpu做支持。
