### ISSUE TITLE
wss的发包问题

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/nbio#325]
程序控制每个链接每秒发送10个包，但是使用vnstat查看网卡流量发现pps是2倍，是不是有什么地方write了2次

**Comment by lxzan** [comment]
每秒发送10个websocket frame ?

**Comment by lesismal** [comment]
有无echo回包，pps是统计单向还是双向，包体多少是否超过tls里默认单帧大小？

**Comment by liangmanlin** [comment]
> 有无echo回包，pps是统计单向还是双向，包体多少是否超过tls里默认单帧大小？

echo是回包的，pps是单向的，包最大72字节

是wss代理，直连的tcp后端的pps是对的，但是客户端和代理之间的pps就是双倍，这个pps是统计客户端的机器，不是代理，所以是单向统计

**Comment by lxzan** [comment]
使用代理跑一下 `autobahn` 试试

**Comment by liangmanlin** [comment]
tcpdump发现应该是ack包，是我疏忽了，但是有个机器没有发送ack，这个比较诡异，有待研究
