### ISSUE TITLE
wss运行一段时间后无法关闭

### ISSUE THREAD

**Issue by liangmanlin** [lesismal/nbio#326]
是调用server.stop()进行关闭的，看日志是只打印了POLLER stop... 没有输出stopped

使用lsof 查看进程所有tcp连接已经关闭，仅仅打开了一个文件

并且关闭钱，wss链接也是失败的，tcp连接正常，但是无法接受数据，个人怀疑是poller卡死了

**Comment by liangmanlin** [comment]
没有使用taskpool，直接在poller里面进行了一次nbiotcp.Write,按道理不会卡死？

**Comment by lesismal** [comment]
用Shutdown试试。

**Comment by lesismal** [comment]
提供下可复现的代码

**Comment by lesismal** [comment]
我最近有点忙，闲了看

**Comment by liangmanlin** [comment]
复现代码可能要等下周，目前已知就是在nbhttp.Parser.Read里面触发了Parser.Close,导致了死锁，nbhttp默认是用taskpool工作，可能平时不会发生，我是直接在poller里面执行函数

复现过程就是，大量新建wss连接，然后突然关闭客户端

**Comment by lesismal** [comment]
我想想要不要给bio.Conn多加个mutex给Execute队列单独使用，否则这种io协程上不跨协程直接执行逻辑队列onclose确实不好弄。但poller协程上直接进行逻辑处理要注意避免阻塞比如请求下游http或者rpc或者数据库等其他阻塞操作

**Comment by liangmanlin** [comment]
目前看只有onclose会这样，我认为可以把onclose放入taskpool运行，一般来说不会有问题，这样改的比较少

**Comment by lesismal** [comment]
Onclose也要保证顺序，所以是用nbio.Conn.Execute放到Conn队列里去执行，这里默认就是用的taskpool但你定制后没有走协程池了

**Comment by lesismal** [comment]
直接在engine调用onclose的地方go去执行倒是可以解决onclose本身，但可能还会有其他死锁

**Comment by lesismal** [comment]
可以测下试试

**Comment by lesismal** [comment]
你本地在这里加个go试试：
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L103

**Comment by liangmanlin** [comment]
好，我试试

**Comment by liangmanlin** [comment]
> 你本地在这里加个go试试： https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L103

这样改没有出现问题了

**Comment by liangmanlin** [comment]
跑了几天，问题依旧，可能还有别的地方触发

**Comment by liangmanlin** [comment]
在websocket.Conn.handleProtocolMessage也会触发close

**Comment by lesismal** [comment]
还是用协程池吧，如果不想协程数量太多，把协程池size设小点就行了

**Comment by liangmanlin** [comment]
https://github.com/lesismal/nbio/blob/9d2ae1dbb9b59b183a56d949359bc11f16e3aefa/nbhttp/websocket/conn.go#L240

把这个改成

`go c.Conn.Close() `

应该可以解决，考虑到可能破坏原来的设计思想，看能不能加一个配置，用户选择是否异步执行？

**Comment by liangmanlin** [comment]
业务只是非常薄的一次wss->tcp转发，用异步处理感觉不划算

**Comment by lesismal** [comment]
就用默认的协程池可以的不

**Comment by lesismal** [comment]
如果在线量不是非常大，标准库同步方案延迟更低

**Comment by liangmanlin** [comment]
嗯，我考虑一下
