### ISSUE TITLE
Windows: Based on std net, for debugging only，请问这是表明在windows下不能用嘛？我们的程序是在windows下运行的

### ISSUE THREAD

**Issue by zhuqiyun** [lesismal/nbio#331]
Windows: Based on std net, for debugging only，请问这是表明在windows下不能用嘛？我们的程序是在windows下运行的

**Comment by lesismal** [comment]
Windows主要用于调试，Windows下使用nbio性能和消耗不如直接使用标准库

**Comment by zhuqiyun** [comment]
我这边对性能要求不高，还是继续使用吧 ，也是为了兼容跨平台

**Comment by zhuqiyun** [comment]
为啥不能跟java一样搞个netty那种，所有平台都性能很好的，非要单独区分windows，有个类似的库gnet也是只能在windows下测试使用

**Comment by lesismal** [comment]
iocp不熟，工作量不小，开源用爱发电，本职工作忙起来更没那么多档期投入到windows上

**Comment by lxzan** [comment]
> 为啥不能跟java一样搞个netty那种，所有平台都性能很好的，非要单独区分windows，有个类似的库gnet也是只能在windows下测试使用

用标准网络库喽, `epoll/kqueue/iocp` 都支持得很好
