### ISSUE TITLE
taskpool 可否延迟回收？

### ISSUE THREAD

**Issue by FJSDS** [lesismal/nbio#335]
目前从测试来看。 taskpool  里面 goroutine 频繁创建销毁。
请问一下 goroutine不延迟退出的原因是什么呢？

**Comment by FJSDS** [comment]
是觉得timer的消耗比较大吗？

**Comment by lesismal** [comment]
早期版本创建goroutine成本较高，用协程池复用可能比较划算。较新版本runtime协程退出后并不是直接回收资源，在go关键字创建协程时会先从旧的已退出的协程队列中去取来实现复用。

常驻协程池的方案主要是使用chan或者cond_t，相比于runtime自己的协程复用，使用chan或者cond_t的方案的性能更差，所以没必要担心频繁重复创建。所以也可以看到ants等早期协程池实现其实跑benchmark性能并没有什么优势。

协程池的主要作用是限制协程数量，避免数量太大后OOM、STW这些问题。

字节的gopool实现没有使用chan或者cond_t，而是list+go，循环从list取直到没有任务就退出、不常驻等待；
nbio/taskpool自带了个常驻协程+chan，跟字节的list+协程方案的主要区别是：
1. nbio/taskpool可以实现自动反向流控（比如创建任务的地方很多，任务队列满了就阻塞等待，整个系统自然均衡）、避免list过大
2. 对于绝大多数时间，pool size没跑满，nbio/taskpool创建协程的逻辑更简单所以实际场景性能也可能更好一点点

**Comment by lesismal** [comment]
runtime复用可以看下这里：
https://github.com/golang/go/blob/master/src/runtime/proc.go#L4477
https://github.com/golang/go/blob/master/src/runtime/proc.go#L4502
https://github.com/golang/go/blob/master/src/runtime/proc.go#L4667

**Comment by FJSDS** [comment]
你好，感谢你的回答。
