### ISSUE TITLE
Websockets getting closed in around 10 mins

### ISSUE THREAD

**Issue by sdoshidensity** [lesismal/nbio#343]
Post 10 mins I starts to get Pong timeout on all the websocket connections with error "websocket: close code=1008 and reason=\"Pong timeout\"". But same websocket connections works perfectly on gorilla. Let mw know is there is some config for this? 

I've created one engine which has ~400 websocket connections concurrently.

**Comment by sdoshidensity** [comment]
`package main

import (
	"context"
	"fmt"
	"time"

	"github.com/density-exchange/density-api/pkg/log"
	"github.com/lesismal/nbio/extension/tls"
	"github.com/lesismal/nbio/nbhttp"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

func main() {
	ctx := context.Background()
	engine := nbhttp.NewEngine(nbhttp.Config{Name: "engine"})

	logger := log.NewExample()
	err := engine.Start()
	if err != nil {
		fmt.Println("engine.Start failed:", err)
		return
	}
	engine.NPoller = 20
	engine.NListener = 20

	defer engine.Shutdown(ctx)

	for i := 0; i < 300; i++ {
		go func() {
			connection(engine, ctx, logger)
		}()
	}

	ticker := time.NewTicker(time.Minute * 1)
	for {
		select {
		case <-ctx.Done():
			fmt.Println("ctx.Done")
			return
		case <-ticker.C:
			logger.Info("ticker", log.Any("len", engine.Online()))
		}
	}
}

func connection(engine *nbhttp.Engine, ctx context.Context, logger log.Logger) {

	url := "wss://stream.binancefuture.com/ws/6SlFwzcBxKzwBV4TPe1Laf4EPOtx7U2H6KDqBi2sWMx2tqoWVW538GBqs4xPpshe"

	upgrader := websocket.NewUpgrader()
	dialer := &websocket.Dialer{
		Engine:      engine,
		Upgrader:    upgrader,
		DialTimeout: time.Second * 5,
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}
	conn, _, err := dialer.Dial(url, nil)
	if err != nil {
		logger.Error("Dial failed", log.Error(err))
		return
	}
	conn.SetPingHandler(func(conn *websocket.Conn, s string) {
		//if err := u.heartBeat.HeartBeat(ctx, u.StreamID); err != nil {
		//	u.logger.Error("error in updating heartbeat for user stream", zap.Error(err))
		//}
		logger.Info("PingHandler")
	})
	conn.SetPongHandler(func(conn *websocket.Conn, s string) {
		//if err := u.heartBeat.HeartBeat(ctx, u.StreamID); err != nil {
		//	u.logger.Error("error in updating heartbeat for user stream", zap.Error(err))
		//}
		logger.Info("PongHandler")
	})
	conn.OnClose(func(c *websocket.Conn, err error) {
		logger.Info("OnClose", log.Error(err))
		ctx.Done()
	})
	conn.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
		logger.Info("OnMessage", log.Any("data", string(data)))
	})
}
`



{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}
{"level":"info","msg":"OnClose","error":"websocket: close code=1008 and reason=\"Pong timeout\""}

**Comment by lesismal** [comment]
I guess it's because you set your own `Ping Handler` but doesn't reply to the `Ping Message`.
I suggest that you don't set your own `Ping Handler` but just use nbio's default Ping Handler and try it again. Or you can reply the Ping Message in your own `Ping Handler`.
