### ISSUE TITLE
CloseMessage missing if called directly before Close

### ISSUE THREAD

**Issue by elnappo** [lesismal/nbio#347]
If I do this on the server side (in SetCloseHandler):
```go
conn.WriteClose(code, "")
conn.Close()
```
the client never receives the close message and the Read returns EOF

But if I add a very small sleep like this:
```go
conn.WriteClose(code, "")
time.Sleep(1 * time.Microsecond)
conn.Close()
```
the client receives the close message. I confirmed this behavior via Wireshark. I have no idea whats happening here, but sound like a bug to me? With gorilla this works like I would expect it. Do you have an idea what's the problem here?

Thank you!

**Comment by lesismal** [comment]
I'm not sure of the exact reason, would you please provide the full example and nbio version, then I'll try it.

Currently, I guess it's because the `websocket.Conn.Close` calls `net.Conn.Close` directly, if you are using `BlockingModAsyncWrite`, the `conn.WriteClose` will write the close message frame async in another goroutine, and the conn.Close() may exec before that, and the close message frame has never been sent.
I'll consider implementing the `websocket.Conn.Close` async with delay.

**Comment by elnappo** [comment]
I was able to reproduce this issue with `net/http`:
```go
package main

import (
	"fmt"
	"net/http"
	"time"

	gorilla "github.com/gorilla/websocket"
	"github.com/lesismal/nbio/nbhttp/websocket"
)

func main() {
	u := websocket.NewUpgrader()
	u.SetCloseHandler(func(conn *websocket.Conn, i int, _ string) {
		conn.WriteClose(i, "")
		//time.Sleep(1 * time.Microsecond)
		conn.Close()
	})

	http.HandleFunc("/ws", func(w http.ResponseWriter, r *http.Request) {
		u.Upgrade(w, r, nil)
	})
	go http.ListenAndServe("localhost:8888", nil)

	conn, _, _ := gorilla.DefaultDialer.Dial("ws://localhost:8888/ws", nil)
	conn.WriteControl(gorilla.CloseMessage, gorilla.FormatCloseMessage(1001, ""), time.Now().Add(time.Second))
	_, _, err := conn.ReadMessage()
	fmt.Println(err)
}
```
when using your HTTP server the problem does not occur.

If you wouldn't mind I would like to take this opportunity to ask a few questions:
* Can I use `SetSession` and `Session` to add a reference to my custom connection metadata?
* Is it fine to use a single upgrader instance for all connections? It seams like you are creating a new one on every upgrade request in your examples.

Furthermore it would be awesome if you could add more comments and documentation to the code. Sometimes it's hard to understand what exactly a functions does an how it should be used and more importantly how it should not be used.

Thank you!

**Comment by lesismal** [comment]
Please try this commit:
```sh
go get -u github.com/lesismal/nbio@eb810299cbc621a46f86b175d892630758060c5c
```

> Can I use SetSession and Session to add a reference to my custom connection metadata?

Yes, you can.

> Is it fine to use a single upgrader instance for all connections? It seams like you are creating a new one on every upgrade

Must create a new upgrader for each new connection In some old versions, but in the latest, can use the same upgrader.

> Furthermore it would be awesome if you could add more comments and documentation to the code. Sometimes it's hard to understand what exactly a functions does an how it should be used and more importantly how it should not be used.

Sorry about the poor comments and documents. Maybe do it in the future, but it's complex many where and a little hard to describe it clearly(because of different IOMod).

**Comment by elnappo** [comment]
Thank you! This solves the problem. But I'm not sure if I like the solution. It's a little bit weird that the connection is closed after a one second wait. If I call Close I assume the connection is closed almost instantly. I set `BlockingModAsyncWrite` to false to migrate that issue. Are there any downsides of using sync writes? Why are async writes the default? Whats the advantages of it?

**Comment by lesismal** [comment]
I'll change the delay of async close to a smaller duration, maybe make it configurable.

You can also try to set `BlockingModAsyncWrite` to `true`:
```golang
u := websocket.NewUpgrader()
u.BlockingModAsyncWrite = false
```

Then `WriteClose` will be sent directly(before close).
But the `WriteClose` maybe blocks if the connection's TCP send buffer is full, so if you have broadcast logic, the connection may blocks and other connections need to wait in the same for-loop. Please take good care of this.

**Comment by lesismal** [comment]
I changed the async close delay time to 0.1s as default:
https://github.com/lesismal/nbio/commit/5ca5456d79cea7e0b5b28d7af00fe70f4bee5265
