### ISSUE TITLE
OnClose vs SetCloseHandler

### ISSUE THREAD

**Issue by danwt** [lesismal/nbio#349]
Hi,

Please what's the intended usage of the functions and their difference?
Thanks

**Comment by lesismal** [comment]
Hi,

OnClose registers callback for the connection's close event, it will be called when the connection is closed.

SetCloseHandler registers callback for websocket protocol's close message, it will be called when receive a websocket close message.

**Comment by danwt** [comment]
Thanks!

So all CloseHandler calls imply a followup OnClose call
But not all OnClose calls imply a corresponding CloseHandler call?

**Comment by lesismal** [comment]
> So all CloseHandler calls imply a followup OnClose call
> But not all OnClose calls imply a corresponding CloseHandler call?

Yes, nearly that.
Because the other side can just close the connection without sending a websocket close message.
