### ISSUE TITLE
Memory leak on MacOS

### ISSUE THREAD

**Issue by rockflying** [lesismal/nbio#355]
When I run the nbio-examples/server_nbio/server.go, the program always gets killed by the OS due to too much memory usage.
<img width="1113" alt="Screenshot 2023-10-09 at 14 03 46" src="https://github.com/lesismal/nbio/assets/7097318/2abdce7f-ad11-44d7-a758-012342062a8d">

**Comment by rockflying** [comment]
Server config is:	
`svr := nbhttp.NewServer(nbhttp.Config{
		Network:                 "tcp",
		Addrs:                   []string{"localhost:8888"},
		Handler:                 mux,
		MaxLoad:                 100,
		ReleaseWebsocketPayload: true,
		ReadBufferSize:          1024 * 4,
		IOMod:                   nbhttp.IOModMixed,
		MaxBlockingOnline:       100,
	})`

**Comment by lesismal** [comment]
Thank you for your feedback!

Do you mean [websocket_1m/server_nbio](https://github.com/lesismal/nbio-examples/tree/master/websocket_1m/server_nbio) or [websocket_1m_tls/server_nbio](https://github.com/lesismal/nbio-examples/tree/master/websocket_1m_tls/server_nbio) ?

MacOS only used for debugging, but I'll try it.

**Comment by rockflying** [comment]
Server config is:

svr := nbhttp.NewServer(nbhttp.Config{
		Network:                 "tcp",
		Addrs:                   []string{"localhost:8888"},
		Handler:                 mux,
		MaxLoad:                 100,
		ReleaseWebsocketPayload: true,
		ReadBufferSize:          1024 * 4,
		IOMod:                   nbhttp.IOModMixed,
		MaxBlockingOnline:       100,
	})

**Comment by lesismal** [comment]
Please tell me the exact code url, coz there isn't a `nbio-examples/server_nbio/server.go`.
Or provide the full code including both server and client.

**Comment by rockflying** [comment]
Sorry for the late reply. Yes, I run the coe in the nbio-example: https://github.com/lesismal/nbio-examples/tree/master/websocket_1m/server_nbio

**Comment by lesismal** [comment]
Got it, thank you! I'll try it when I have time.

And BTW, here are some commits to kqueue since you opened this issue, those did not aim to fix the problem you have mentioned but may be related, you can also try the latest version.
