### ISSUE TITLE
websocket: reading loop conflict with 3rd frameworks that implement http.ResponseWriter themselves

### ISSUE THREAD

**Issue by lesismal** [lesismal/nbio#357]
related: https://github.com/lesismal/nbio/issues/353#issuecomment-1767699771

tks @z-ab , 试下这个提交吧

```sh
go get -u github.com/lesismal/nbio@eec98322147b6333c705d7b113c223d830ec5a8b
```

**Comment by z-ab** [comment]
@lesismal 收到，我试试，谢谢

**Comment by z-ab** [comment]
```
# github.com/lesismal/nbio
../../../../pkg/mod/github.com/lesismal/nbio@v0.0.0-20231018144555-eec98322147b/conn_unix.go:377:5: p.resetRead undefined (type *poller has no field or method resetRead)
```

```
go get -u github.com/lesismal/nbio@eec98322147b6333c705d7b113c223d830ec5a8b
```
利用这个分支报这个错误

**Comment by lesismal** [comment]
请试下这个：
```sh
go get -u github.com/lesismal/nbio@6a21497
```

**Comment by z-ab** [comment]
<img width="528" alt="image" src="https://github.com/lesismal/nbio/assets/1701441/eee8d0e0-8b3e-4eca-8ac9-a4ea5cd0f015">

1000客户端连接，只有282个链接啦，其他都失败啦。当前测试在mac下测试

**Comment by z-ab** [comment]
> ulimit -n

65536

**Comment by z-ab** [comment]
<img width="401" alt="image" src="https://github.com/lesismal/nbio/assets/1701441/4354c59b-d2a0-444f-9d5b-de8ba811e988">
在测试环境进行测试的结果

**Comment by z-ab** [comment]
<img width="427" alt="image" src="https://github.com/lesismal/nbio/assets/1701441/ce286104-2d41-4066-9bda-51a9e9f7b1a8">

在测试环境测试的结果，限定5000

**Comment by lesismal** [comment]
@z-ab 并发dial那块的sleep只有0和500的sleep了，其他的都没sleep，所以相当于同时发起了998个dial，mac下估计backlog打满了，1000连接这种测试，把dial那块的go协程去掉，挨个连接就行了，我试了下是可以成功的，不去掉的话确实被reset了

**Comment by lesismal** [comment]
我是了下1w连接，跑了500秒没有断开

**Comment by z-ab** [comment]
OnClose: 127.0.0.1:8081 read timeout
我去掉批量建联，for单独循环，在mac和测试环境(2H4C)大概在2~3k的时候就报上边的错误

**Comment by z-ab** [comment]
> @z-ab 并发dial那块的sleep只有0和500的sleep了，其他的都没sleep，所以相当于同时发起了998个dial，mac下估计backlog打满了，1000连接这种测试，把dial那块的go协程去掉，挨个连接就行了，我试了下是可以成功的，不去掉的话确实被reset了

在websocket服务端重启的时候，这个时候客户端会批量连接，这个和go协程并发场景很像。如果客户端在几十万的时候，很容易出现并发建联。及时通过随机打散可能也无法打的太散

**Comment by lesismal** [comment]
> > @z-ab 并发dial那块的sleep只有0和500的sleep了，其他的都没sleep，所以相当于同时发起了998个dial，mac下估计backlog打满了，1000连接这种测试，把dial那块的go协程去掉，挨个连接就行了，我试了下是可以成功的，不去掉的话确实被reset了
> 
> 在websocket服务端重启的时候，这个时候客户端会批量连接，这个和go协程并发场景很像。如果客户端在几十万的时候，很容易出现并发建联。即时通过随机打散可能也无法打的太散

mac不是做专业的服务器的，而且没调内核参数
linux服务器Acceptor几千上万/秒建立连接都还好
而且你这个是测试程序localhost，来的太快了，如果是公网服务，公网链路本身就会比这个离散一些
如果确实是内网之类的有这么多连接数，应该在client端使用 limiter 限制频率、而不是这种随机打散，随机打散并不能保证控制这个重连频率

**Comment by lesismal** [comment]
> OnClose: 127.0.0.1:8081 read timeout OnClose: xxx.xx.xx.xx EOF 我去掉批量建联，for单独循环，在mac和测试环境(2H4C)大概在2~3k的时候就报上边的错误

这个2H4C是指什么？
2-3k是指建立连接2-3k后报错？报的是read timeout 还是报reset by peear？

**Comment by z-ab** [comment]
> > OnClose: 127.0.0.1:8081 read timeout OnClose: xxx.xx.xx.xx EOF 我去掉批量建联，for单独循环，在mac和测试环境(2H4C)大概在2~3k的时候就报上边的错误
> 
> 这个2H4C是指什么？ 2-3k是指建立连接2-3k后报错？报的是read timeout 还是报reset by peear？

写错了，2cpu4G内存。报的read timeout

**Comment by z-ab** [comment]
> > > @z-ab 并发dial那块的sleep只有0和500的sleep了，其他的都没sleep，所以相当于同时发起了998个dial，mac下估计backlog打满了，1000连接这种测试，把dial那块的go协程去掉，挨个连接就行了，我试了下是可以成功的，不去掉的话确实被reset了
> > 
> > 
> > 在websocket服务端重启的时候，这个时候客户端会批量连接，这个和go协程并发场景很像。如果客户端在几十万的时候，很容易出现并发建联。即时通过随机打散可能也无法打的太散
> 
> mac不是做专业的服务器的，而且没调内核参数 linux服务器Acceptor几千上万/秒建立连接都还好 而且你这个是测试程序localhost，来的太快了，如果是公网服务，公网链路本身就会比这个离散一些 如果确实是内网之类的有这么多连接数，应该在client端使用 limiter 或者有限数量的协程池 限制频率、而不是这种随机打散，随机打散并不能保证控制这个重连频率

这个client可能是android中app，这个client就没法做控制，服务器重启，客户端就会重连，如果有50万客户端app，可能到服务器同时建联的还是比较多的

**Comment by lesismal** [comment]
> 这个client可能是android中app，这个client就没法做控制，服务器重启，客户端就会重连，如果有50万客户端app，可能到服务器同时建联的还是比较多的

那可以在客户端里每个连接自己随机sleep下，公网可以离散一些，linux服务器tcp backlog那些参数调大些。
reuseport多开几个listener我不确定效果好不，需要实测
或者如果可以你们多开几个端口，如果client到server之间有中转的反代、均衡器之类的可以均衡连到go上，或者client根据自己的信息做下hash连接到不同的端口上也可以试试

**Comment by lesismal** [comment]
> 报的read timeout

我又跑了几轮较长时间的，1w连接，都没有遇到read timeout。你那边用 https://github.com/lesismal/nbio/commit/6a214973e2898cadf1f65bb864d903372086acf1 还有read timeout的问题吗？

**Comment by z-ab** [comment]
@lesismal 有遇到，在docker中跑，大概1.5万左右出现timeout和close EOF错误。gorilla和gws基本也在1.5万左右出现timeout。用了一个rust框架大概在2.2万左右。测试环境没再测试

**Comment by lesismal** [comment]
> @lesismal 有遇到，在docker中跑，大概1.5万左右出现timeout和close EOF错误。gorilla和gws基本也在1.5万左右出现timeout。用了一个rust框架大概在2.2万左右。测试环境没再测试

doker什么规格，是不是配置瓶颈了

**Comment by z-ab** [comment]
> > @lesismal 有遇到，在docker中跑，大概1.5万左右出现timeout和close EOF错误。gorilla和gws基本也在1.5万左右出现timeout。用了一个rust框架大概在2.2万左右。测试环境没再测试
> 
> docker什么规格，是不是配置瓶颈了

8cpu 8G内存

**Comment by lxzan** [comment]
> gorilla和gws基本也在1.5万左右出现timeout。用了一个rust框架大概在2.2万左右。

用wsbench测试下, 看看会不会timeout

```bash
go install -v github.com/lxzan/wsbench@v1.0.13
wsbench  broadcast -c 20000 -p 100 -i 5  -n 1 -u ws://127.0.0.1:9000
```
