### ISSUE TITLE
请教一下 nbhttp.engine shutdown问题

### ISSUE THREAD

**Issue by gosun163** [lesismal/nbio#361]
nbhttp.engine shutdown之后，再start无效，看代码应该engine.shutdown没有置为false

另外shutdown有时会出现错误
![1698567085104](https://github.com/lesismal/nbio/assets/52063598/a05308a9-6729-4f0a-9591-d9dc0407dca5)

**Comment by lesismal** [comment]
感谢关注和反馈！

> nbhttp.engine shutdown之后，再start无效，看代码应该engine.shutdown没有置为false

因为Engine内部的东西比较多，shutdown清理状态也相对麻烦、怕有遗漏。如果业务上需要重启，可以把创建、启动Engine的地方单独封装个工厂方法，每次新创建一个、旧的释放就可以了

shutdown报错的有比较容易复现代码吗？我试下。另外，windows主要是用于调试，性能不如直接使用标准库，你们生产服务器是部署在什么系统？
