### ISSUE TITLE
Upgrader 是否可复用？

### ISSUE THREAD

**Issue by TelephoneTan** [lesismal/nbio#363]
对于每一个传入的 HTTP 请求，如果所需的 WebSocket 配置一样，是否能够将 `websocket.NewUpgrader()` 返回的 `Upgrader` 实例共享复用？

**Comment by lesismal** [comment]
感谢关注！

较早版本不能复用，较新的版本都是可以复用的，考虑到可能有老用户使用旧版本的兼容性所以没更新，目前应该还好，刚更新了文档和examples：
https://github.com/lesismal/nbio#using-websocket-with-std-server
https://github.com/lesismal/nbio-examples/blob/master/websocket/server/server.go
