### ISSUE TITLE
对标netty的nio吗?

### ISSUE THREAD

**Issue by qinguoyi** [lesismal/nbio#368]
对项目很感兴趣，请问是对标netty的nio吗?

**Comment by lesismal** [comment]
异步非阻塞IO、epoll这些不是netty独有的、而是比编程语言更加基础的编程模式或系统接口，nio也只是异步非阻塞、对epoll这些的一种封装、框架。
nbio是异步非阻塞IO的框架，没有对标其他库或者框架，都是按照我自己的代码风格实现的、比较偏面向过程，我个人喜欢直观、不喜欢层层封装，所以除了因为底层复杂而所需的一些复杂实现，并没有什么不必要的设计模式，跟netty、java肯定也是相去甚远。
因为我对设计模式学不太会（层层封装太恶心人了、看十几秒就看不下去所以没有花足够时间去学）、也没怎么研究过netty，好像gnet那些库的代码风格有参考netty吧、具体不太清楚，但是其他的golang epoll库的功能相对比较少、对TLS、HTTP、Websocket这些的支持比较弱

欢迎来体验nbio

**Comment by qinguoyi** [comment]
好的，感谢
