### ISSUE TITLE
請教關於TLS websocket的連線問題

### ISSUE THREAD

**Issue by akang026** [lesismal/nbio#370]
您好，我目前於client端嘗試與nbio的server端建立TLS websocket連線
在TLS認證完成後，websocket upgrade封包如下：
```
GET /path HTTP/1.1
  Pragma: no-cache
  Host: example.com:443
  Cache-Control: no-cache
  Origin: https://example.com:443
  Upgrade: websocket
  Connection: Upgrade
  Sec-WebSocket-Key: XXXXXXXXXX==
  Sec-WebSocket-Protocol: test
  Sec-WebSocket-Version: 13
```
我Client端在嘗試連線時，收到Server回覆HTTP 403
想請教您關於Origin的格式是否有誤?
Server端拒絕連線是否與origin內容中為https開頭有關?

**Comment by lesismal** [comment]
感谢关注、使用nbio和反馈！

请问有跨域吗？默认会进行跨域检查：
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L449

如果是跨域的，可以配置您自己的跨域检查规则方法，返回true即为放行：
```golang
upgrader.CheckOrigin = func(r *http.Request) bool {
    // 您自己的跨域安全规则
}
```

**Comment by akang026** [comment]
感謝您的回覆，請問能使用下列的function嗎?
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L592
會造成前述的websocket請求失敗嗎?

**Comment by lesismal** [comment]
> 感謝您的回覆，請問能使用下列的function嗎? https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L592 會造成前述的websocket請求失敗嗎?

这个就是默认的检查，对比请求头的Origin的host与request host是否相同，如果确实是因为跨域导致403并且既然之前已经被403、用这个默认的肯定是不行了。
如果你们对建立ws连接是不需要安全策略、可以统一放行，那么该function直接返回true即可：
```golang
upgrader.CheckOrigin = func(r *http.Request) bool {
    return true
}
```

如果需要安全策略、就需要自行判断，比如你们允许哪些域名来建立ws连接，则检查Origin的host与你们允许的host列表是否匹配，有匹配到则放行、否则拒绝。

**Comment by akang026** [comment]
不好意思再確認、釐清一下，默認的檢查中 "对比请求头的Origin的host与request host是否相同" 是否為封包中下列兩個欄位
1. Host: example.com:443
2. Origin: https://example.com:443
而只要example.com由我們自行判斷，是在允許的host列表中，則我們可於CheckOrigin中放行

感謝您的回覆！

**Comment by lesismal** [comment]
具体细节请代码调试或者加日志确认下，或者看下源码标准库url解析的实现。因为我不一直在电脑前，不敢确认自己回答这些细节的准确性
