### ISSUE TITLE
Write errors after 65k web socket connections writing every 2 sec

### ISSUE THREAD

**Issue by BigBoulard** [lesismal/nbio#371]
Hi,

I want to know how many web socket TLS connections a single instance could handle, and how much resource is needed in terms of CPU and RAM. So, I've created a repo to test this out.

## Algorithm
- Each `client` instance tries to make 25 000 web socket creation requests
- Once a Web Socket connection is established, a write is performed every 2 sec by the client
- The `server` reads the message and just echoes it.
- The `server` stops (`fatal`) when there's any web socket creation or any read/write error

The server prints how many connections have been created every 100 connections.
I'm testing on Docker Desktop on macOS (M2 > arm64) and Compose.

There are 2 versions of the server (`gorilla-server` and `nbio-server`) and the client (`gorilla-server` and `nbio-server`) but we can abstract this.

When I test the `nbio-server` once it reaches around 67,400 connections, the server stops.
On the client side, after reaching at least 10,000 connections, I can see errors when the client tries to write on a web socket.

```sh
2023-11-22 11:07:03 2023/11/22 10:07:03 connection count: 12979
2023-11-22 11:07:03 2023/11/22 10:07:03 writeMessage error: write tcp 192.168.32.5:54092->192.168.32.2:8090: write: broken pipe
```

I saw that some test that are just creating web sockets without writing to it can reach way more connections.
So, I doubt that I'm reaching the limit of the machine. Do you see anything wrong?

## Server Code

`nbio/server/cmd/main.go`
```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/lesismal/llib/std/crypto/tls"

	"github.com/BigBoulard/go-chat-test/nbio/server/internal/client"
	"github.com/gin-gonic/gin"
	"github.com/lesismal/nbio/nbhttp"
)

const (
	HttpServerPort = "8090"
	HttpServerMode = gin.DebugMode
)

var (
	HttpServerHost = "localhost"
	server         *nbhttp.Server
	router         *gin.Engine
	count          int
)

func main() {
	if os.Getenv("HOST") == "docker" {
		HttpServerHost = "nbio-server"
	}

	// setup router
	gin.SetMode(HttpServerMode)
	router = gin.New()
	router.Use(gin.Recovery())
	router.GET("/ws", serveWS)

	// get SSL cert
	sslFolder := getSSLFolder()
	cert, err := tls.LoadX509KeyPair(
		filepath.Join(sslFolder, "cert.pem"),
		filepath.Join(sslFolder, "key.pem"),
	)
	if err != nil {
		log.Fatalf("can't load SSL files %s or %s: %v ",
			getSSLFolder()+"cert.pem", getSSLFolder()+"key.pem", err,
		)
	}

	// setup http server
	server = nbhttp.NewServer(
		nbhttp.Config{
			Network:  "tcp",
			AddrsTLS: []string{fmt.Sprintf("%s:%s", HttpServerHost, HttpServerPort)},
			TLSConfig: &tls.Config{
				Certificates:       []tls.Certificate{cert},
				InsecureSkipVerify: true,
			},
			Handler: router,
			IOMod:   getIOMod(os.Getenv("IOMod")), //  nbhttp.IOModNonBlocking |  nbhttp.IOModBlocking | nbhttp.IOModMixed
		},
		router,
		nil,
	)

	// start HTTP Server
	go func() {
		log.Printf("Listening and serving  on https://%s:%s in %s mode", HttpServerHost, HttpServerPort, HttpServerMode)

		if err := server.Start(); err != nil {
			log.Fatalf("server.Start failed %v", err)
		}
	}()

	handleShutdown()
}

func getIOMod(IOMode string) int {
	switch IOMode {
	case "IOModNonBlocking":
		return nbhttp.IOModNonBlocking
	case "IOModBlocking":
		return nbhttp.IOModBlocking
	case "IOModMixed":
		return nbhttp.IOModMixed
	default:
		return nbhttp.IOModNonBlocking
	}
}

func serveWS(c *gin.Context) {
	// client
	err := client.NewWSClient(c)
	if err != nil {
		log.Fatalf("NewWSClient(c) error: %v", err)
		return
	}

	// connection count
	count += 1
	if count%100 == 0 {
		log.Printf("connection count: %d", count)
	}
}

func getSSLFolder() string {
	wd, err := os.Getwd()
	if err != nil {
		log.Fatalf("getEnvFilePath error: %v", err)
	}
	return filepath.Join(wd, "./cert/ssl")
}

func handleShutdown() {
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	<-quit
	log.Println("Shutting down http server ...")

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := server.Shutdown(ctx); err != nil {
		log.Fatal("server shutdown error")
	}
	log.Println("Server shut down")
}
```

`nbio/server/internal/client/client.go`
```go
package client

import (
	"fmt"
	"log"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/lesismal/nbio/nbhttp/websocket"
)

var (
	AllowedHosts = []string{"https://localhost:8080", "https://localhost:5173"}
)

// a websocket client, basically a frontend visitor
type WSClient struct {
	upgrader *websocket.Upgrader
	ws       *websocket.Conn // Web Socket conn
}

// used to initialize a new Client with all required values initialized
func NewWSClient(ginCtx *gin.Context) error {
	// create a WSClient instance
	c := &WSClient{
		upgrader: websocket.NewUpgrader(),
	}

	// create ws
	var err error
	c.ws, err = c.createWS(ginCtx)
	if err != nil {
		return fmt.Errorf("wsclient.ConfigureWSConn: c.createWS error: %w", err)
	}

	return nil
}

func (c *WSClient) createWS(ginCtx *gin.Context) (*websocket.Conn, error) {
	// onMessage handler
	c.upgrader.OnMessage(
		func(conn *websocket.Conn, messageType websocket.MessageType, data []byte) {
			// log.Printf("New message from %s", conn.RemoteAddr().String())

			// echo
			if err := c.ws.WriteMessage(websocket.TextMessage, data); err != nil {
				log.Fatalf("OnMessage: WriteMessage error: %v", err)
			}

		},
	)

	// upgrade the connection
	conn, err := c.upgrader.Upgrade(ginCtx.Writer, ginCtx.Request, nil)
	if err != nil {
		return nil, fmt.Errorf("c.Upgrade: upgrader.Upgrade error: %w", err)
	}

	// WARN IMPORTANT otherwise limits is about 16,900 ws
	conn.KeepaliveTime = time.Second * 30

	return conn, nil
}
```

## Client Code

`gorilla/client/cmd/main.go`
```go
package main

import (
	"crypto/tls"
	"flag"
	"fmt"
	"io"
	"log"
	"net/url"
	"os"
	"os/signal"
	"syscall"
	"time"

	// _ "net/http/pprof" // set up a webserver for getting Go profiles

	"github.com/gorilla/websocket"
)

const (
	HttpServerPort = "8090"

	pauseAfterWrite        = time.Millisecond * 2000
	pauseBetweenWSCreation = time.Millisecond * 30
)

var (
	HttpServerHost = "localhost"
	n              = flag.Int("n", 20000, "number of connections")
	activeConns    = 0 // active conn
)

func main() {
	if os.Getenv("SERVER_HOST") != "" {
		HttpServerHost = os.Getenv("SERVER_HOST")
	}

	// flags
	flag.Usage = func() {
		_, _ = io.WriteString(os.Stderr, `Websockets client generator
Example usage: go run gorilla/test/cmd/main.go -n=10000
`)
		flag.PrintDefaults()
	}
	flag.Parse()

	// Enable pprof hooks
	// go func() {
	// 	if err := http.ListenAndServe("localhost:6060", nil); err != nil {
	// 		log.Fatalf("pprof failed: %v", err)
	// 	}
	// }()

	// Launch Goroutines
	for i := 0; i < *n; i++ {
		go func() {
			// create ws conns
			conn, err := getWSConn()
			if err != nil {
				log.Printf("connection count: %d", activeConns)
				log.Fatalf("getWSConn error: %v", err)
				return
			}

			// close connection on exit
			defer func() {
				conn.Close()
			}()

			// writes to ws, the server will echo it
			for {
				if err := conn.WriteMessage(websocket.TextMessage, []byte("Hello from user 1")); err != nil {
					log.Printf("connection count: %d", activeConns)
					log.Fatalf("writeMessage error: %v", err)
					return
				}
				time.Sleep(pauseAfterWrite)
			}

		}()
		activeConns++
		time.Sleep(pauseBetweenWSCreation)
	}

	log.Printf("successfully handled %d connections", activeConns)

	handleShutdown()
}

func getWSConn() (*websocket.Conn, error) {
	dialer := &websocket.Dialer{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
	}

	url := url.URL{
		Scheme: "wss",
		Host:   HttpServerHost + ":" + HttpServerPort,
		Path:   "/ws",
	}
	conn, res, err := dialer.Dial(url.String(), nil)
	if err != nil {
		if res != nil && res.Body != nil {
			bReason, err := io.ReadAll(res.Body)
			if err != nil {
				log.Fatalf("RealAll error: %v", err)
			}
			log.Printf("dial: %v, reason: %v\n", err, string(bReason))
		}
		return nil, fmt.Errorf("can't connect to %s %w", url.String(), err)
	}

	return conn, err
}

func handleShutdown() {
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	<-quit
	log.Println("Shutting down server ...")
}
```

Below is the repository if you want to test this out

<https://github.com/BigBoulard/go-chat-test>

Thank you so much.

**Comment by lesismal** [comment]
> There are 2 versions of the server (gorilla-server and nbio-server) and the client (gorilla-server and nbio-server) but we can abstract this.

[I have said that, please use the same client to ](https://github.com/lesismal/nbio-examples/issues/13#issuecomment-1821323671)

Please notice that:
```text
If you want to test the server's ability, I think it's better to use the same gorilla client to test both servers.
```

Use the same client to different servers, that will be fair to different servers.

**Comment by lesismal** [comment]
It's just a test, I think it would be better to make the examples simple.
I ran your repo when the old issue was opend in `nbio-examples` but docker failed, I don't have much time to fix the errors myself. There are also some ENV, and I need to spend a little more time to read the code and README.

**Comment by lesismal** [comment]
For similar stress test, I used to use these, multi ports to support more than 64k connections and just `go run` them:
https://github.com/lesismal/nbio-examples/blob/master/websocket_1m_tls/server_net/server.go
https://github.com/lesismal/nbio-examples/blob/master/websocket_1m_tls/server_nbio/server.go
https://github.com/lesismal/nbio-examples/blob/master/websocket_1m_tls/client/client.go

**Comment by BigBoulard** [comment]
> > There are 2 versions of the server (gorilla-server and nbio-server) and the client (gorilla-server and nbio-server) but we can abstract this.
> 
> [I have said that, please use the same client to ](https://github.com/lesismal/nbio-examples/issues/13#issuecomment-1821323671)
> 
> Please notice that:
> 
> ```
> If you want to test the server's ability, I think it's better to use the same gorilla client to test both servers.
> ```
> 
> Use the same client to different servers, that will be fair to different servers.

I took you advice into account and it's actually the case: <https://github.com/BigBoulard/go-chat-test/blob/main/nbio/compose-nbio-with-gorilla-client.yml>

**Comment by BigBoulard** [comment]
> It's just a test, I think it would be better to make the examples simple. I ran your repo when the old issue was opend in `nbio-examples` but docker failed, I don't have much time to fix the errors myself. There are also some ENV, and I need to spend a little more time to read the code and README.

Sure, I understand. This morning, I performed the same test stripping out the write performed every 2 seconds by the clients and removed the 2 goroutines spawn by the server for echoing the write performed by the clients. The result is that we can create as many WS as we want up to 1M I guess, I just stopped at about 750M.

**Comment by BigBoulard** [comment]
It seems like the write operation from the client, plus the read and then write from the server (the echo) comes at a normal cost that makes the number of web socket clients drop from around 1M to 70k-90k. I can see that the resource consumption is much higher (CPU + RAM).

**Comment by lesismal** [comment]
Yes, high online num is mainly limited by hardware specifications and kernel configurations.
Usually, nbio is fine to handle as many as 1m connections or high num if using nbio poller to serve the connections and cost not as much as std net's lots of goroutines cost. 
For nbio serving non-blocing connections, It's the high qps/tps that mainly consume lots of cpu/mem resources.
