### ISSUE TITLE
请教下，这个库可以进行TLS双向验证吗？

### ISSUE THREAD

**Issue by ericjing83** [lesismal/nbio#373]
您好，
请教下，这个库可以进行TLS双向验证吗？服务端要验证客户端是否是黑客伪造的，客户端也要验证服务端是否是黑客伪造的。

**Comment by lesismal** [comment]
可以。
nbio依赖的tls是llib里在标准库1.16 tls基础上魔改的，只是修改支持了非阻塞、流解析，功能性基本与标准库保持了一致，所以标准库1.16 tls支持的，llib tls也支持（如果遇到bug、欢迎issue）。
