### ISSUE TITLE
tcp raw 有没有办法只保留部分数据，其他数据不进缓冲区

### ISSUE THREAD

**Issue by joyanhui** [lesismal/nbio#375]
```go
engine.OnData(func(c *nbio.Conn, data []byte) {
		c.Write(append([]byte{}, data...))
	})
```
怎么限制 每个客户端 发送的data 长度，比如限制在 1k以内，超过部分直接丢掉。
自己在OnData里面截取自然是可以的，有没有办法不让数据到缓冲区呢？
MaxWriteBufferSize 是全局不是针对每一个请求的对吗？

**Comment by lesismal** [comment]
`MaxWriteBufferSize` 是单个连接的，每个连接的发送缓冲区最多缓存这么大、超过了再 `Write` 就返回 `errOverflow`，所以可以设置这个为1k实现丢弃，但前提是应用层使用 nbio.Conn.Write 返回 error 后不去close这个conn。

但是TCP可以丢弃数据这种需求看上去有点奇怪，通常没有这样设计的。
我能想到的可以丢弃数据的场景有一些，比如voip通话、游戏帧同步之类的，但用UDP效率更佳。追求速度和当前、不保证必达、不追求高质量

**Comment by joyanhui** [comment]
@lesismal 非常感谢大佬解答！

我这边是一个 客户端设备是否在线 并顺带收集设备采集的数据 ，2-5秒采集一次。每次只有几百个字节的数据。
之前是udp不太理想  所以用了tcp短连接。

可否继续赐教：如果返回err后  主动关闭conn 会出现什么情况？通常在什么场景下应该主动关闭conn？

**Comment by lesismal** [comment]
> 如果返回err后 主动关闭conn 会出现什么情况？通常在什么场景下应该主动关闭conn？

主动关闭、缓存的数据也就不会继续发送了。
用tcp短链接这个我有点没get到点，如果是需要保持在线通常是长连接，如果不需要保持在线，那close就无所谓了。但你又说需要tls，我有点更懵了。

确定是短链接吗？tcp建立连接后一次request、response流程后就关掉这种？

**Comment by joyanhui** [comment]
我上面的描述有误，tls不是在这个场景里面使用的。

这里描述的 客户端是MCU单片机物联网设备，服务端是nbio tcp  echo，没有走tls。

我也不清楚用短链接和长连接哪个方式更好一些。自己对比测试也没有感觉太大的差距。自己感觉 因客户端间隔2-5秒才发送一次数据，加上最早是用的http方式，所以就延续用了短连接 ： 每次处理完成客户端请求后就从服务端主动关闭了连接。

> 主动关闭、缓存的数据也就不会继续发送了。

是不是意味着：我限制了MaxWriteBufferSize，实际是从server端限制每个客户端的连接发送过来的数据大小，如果当前连接客户端新发送过来的数据+已经缓存 >  MaxWriteBufferSize大小`len(c.writeBuffer)+n > g.maxWriteBufferSize`，那么后面的数据就不会被继续写入到缓存(不会继续占用服务端的内存)。

再谢！

**Comment by lesismal** [comment]
> 是不是意味着：我限制了MaxWriteBufferSize，实际是从server端限制每个客户端的连接发送过来的数据大小，如果当前连接客户端新发送过来的数据+已经缓存 > MaxWriteBufferSize大小len(c.writeBuffer)+n > g.maxWriteBufferSize，那么后面的数据就不会被继续写入到缓存(不会继续占用服务端的内存)。

不是从server段限制每个客户端发送过来的数据，是限制server发送给client的数据在syscall Write遇到tcp缓冲区满时为这个连接缓存起来的数据的size。你的低频交互并且交互数据size不大、通常都会直接写入到内核的tcp缓冲区成功，除非网络链路不好、tcp缓冲区堆积满了导致失败，但你使用短链接、一个request+response、buffer size又不大，所以基本上不会触发这个缓冲区满的情况，所以也没必要为你提出的这个问题担心。

**Comment by joyanhui** [comment]
@lesismal  感谢，这次明白应该怎么做了！！

**Comment by lesismal** [comment]
不客气，欢迎随时交流！
