### ISSUE TITLE
大佬，很感谢分享，我在使用的时候有一些问题，是否可以请教下

### ISSUE THREAD

**Issue by cowpeatechnology** [lesismal/nbio#379]
我也是刚看到这个库，准备使用的场景想用来做一个游戏服，设定是4个人在一个房间，用帧同步模式，通讯协议是websocket，为了减少服务器下发的数据，我在服务器做了个定时器，50ms下发一次这期间收到的比如位置更改等信息。我写了个客户端模拟，发现在大概1000个客户端的时候性能好像下降的就很厉害了，想请教下配置细节，不知可否。 v: yiclubs

**Comment by guonaihong** [comment]
可以把profile dump出来看下。

**Comment by lesismal** [comment]
猜测是单个协程广播？多分几组多几个协程去并发广播，避免单个循环里发送的多导致慢。
其他的就得看细节了，元素多少、广播的元素数量、元素对应的数据计算量，各种细节，这个得展开了说才能知道。

我不怎么用微信社交，可以就在这里聊

**Comment by lxzan** [comment]
发送如此频繁，应该采用标准库IO模式并开启TCP Delay

**Comment by lesismal** [comment]
> 发送如此频繁，应该采用标准库IO模式并开启TCP Delay

实时性高的游戏类型不太适合延迟发送，单个玩家连接的吞吐量也不会像rpc那种非常大非常高频，延迟发送可能影响玩家体验。to c和to b的业务侧重点不太一样
