### ISSUE TITLE
How to use proxy for websocket connection

### ISSUE THREAD

**Issue by sdoshidensity** [lesismal/nbio#383]
Hi,

How to use proxies for websocket connection. 

What does this function should contain?

`func(*http.Request) (*url.URL, error)`

**Comment by lesismal** [comment]
What kind of proxy?

**Comment by lesismal** [comment]
nbio suports only the basic tcp/udp/http/websocket protocol, doesn't support protocols based on these basic protocols.
You can implement the proxy yourself.
