### ISSUE TITLE
Can this library be used as a websocket client?

### ISSUE THREAD

**Issue by Andrey36652** [lesismal/nbio#384]
I have such a question, because both client examples use gorilla/websocket
https://github.com/lesismal/nbio-examples/blob/master/websocket/client/client.go
https://github.com/lesismal/nbio-examples/blob/master/websocket_tls/client/client.go

**Comment by canselcik** [comment]
It used to be. I used it extensively for it a while ago. I am not sure what happened but yes the examples now surprisingly use gorilla/websocket.

**Comment by lesismal** [comment]
Hi Bros, thank you for your attention and feedback!

At the beginning, nbio didn't implement websocket clien, so I used gorilla client for examples. 
After nbio has supported websocket, I didn't remove the old gorilla examples.

Some of the differences/points:
1. nbio websocket client is driven by nbio's poller, it may be a little slower than gorilla client(based on std conn) when there are not a huge num of connections
2. nbio websocket client is non-blocking, uses callbacks to handle events/message, many users may not be used to use a client in that style in golang.
3. most of the scenarios, we don't need too many websocket client in a golang Proc, gorilla client wouldn't cost too much

If you are sure you want to use nbio websocket client, please just refer to the examples in a different sub dir:
https://github.com/lesismal/nbio-examples/blob/master/websocket/nbioclient/client.go
https://github.com/lesismal/nbio-examples/tree/master/websocket_tls/nbioclient

**Comment by canselcik** [comment]
I appreciate the reply @lesismal.

In my experience the gorilla client has some issues in certain situations that I am yet to be able to narrow down on. For example when connecting to Bybit's Websocket endpoint, under very high market trading volume gorilla websocket fails with `panic: runtime error: slice bounds out of range [:5472] with capacity 4096` while the nbio websocket client stopped invoking the callbacks but did not panic.

After a while I switched back to Gorilla and the panic came back. While gorilla is great, it is still not perfect and alternatives are nice. nbio wsclient was definitely the only serious alternative I had come across.

**Comment by lesismal** [comment]
Thank you @canselcik , I appreciate your experience and share, glad if nbio could help.

Is there a full example that can reproduce the problem when communicating with Bybit's Websocket? I'd like to take a look into it.
