### ISSUE TITLE
[advice]建议再多一层上层的封装（独立一个package，依赖这个库）

### ISSUE THREAD

**Issue by hafung** [lesismal/nbio#388]
类似 php生态里 workerman => gatewayworker 的关系;

gatewayworker的架构支持分布式部署，自动绑定连接到用户，整合了各种方便的业务回调和方法（比如发送到用户、群组、离开群组等等）

这样可以更新专注业务，不关心底层实现

**Comment by hafung** [comment]
这个库本身真的很好，但要立马上手写业务，以及日后的扩展，需要做一些额外的工作

**Comment by lesismal** [comment]
感谢关注。

这个库本身定位是基础设施、对标标准库TCP、UDP，以及Websocket这些。
以前考虑过出一些业务相关的框架，但个人精力有限，目前没有档期去做这些。
