### ISSUE TITLE
How to run a worker that sends ping/pong as a text message like pingHandler and pongHandler upgrader

### ISSUE THREAD

**Issue by AnirudhDensityIntern** [lesismal/nbio#394]

**Comment by lesismal** [comment]
What do you want to implement exactly? Is it for keepalive?

**Comment by AnirudhDensityIntern** [comment]
yes

**Comment by lesismal** [comment]
I think the best practice is:
1. server side: SetReadDeadline and reply a pong message to a ping message
2. client side: send a ping message every interval

In nbio, you need just set `upgrader.KeepaliveTime = yourKeepaliveInterval` then nbio will update ReadDeadline itself when receiving a message, nbio also replies a pong message to a ping message automatically. 
So, maybe that's all you need to do except ask the client side to send the keepalive ping messages themselves.

**Comment by lesismal** [comment]
Although sending ping msg on the server-side can do that keepalive things and many people design their code like that, it's a little waste. server-side check read deadline would be better for server-side cost.

But if you want to do that:

`upgrader.SetPongHandler(yourPingHandler)`
of course you should update read deadline by `wsConn.SetReadDeadline(time.Now().Add(...))` in yourPongHandler or 
set `upgrader.KeepaliveTime=...`

and 

`wsConn.WriteMessage(PingMessage, []byte("your text"))` in your self timer

**Comment by AnirudhDensityIntern** [comment]
we are set the conn.SetDeadline to 10 second and then we send the pong message inside the ping handler we getting the ping timeout in this case.
when we write the message there is no error but still get the pong message timeout.
this we get in close handler`"reason\\\":\\\"read timeout\\\"`

`func (u *userStreamImpl) pingHandler(userID uuid.UUID) func(conn *websocket.Conn, s string) {
	return func(conn *websocket.Conn, s string) {
		u.logger.Debug("websocket ping received", log.Any("userID", userID))
		err := conn.SetDeadline(time.Now().Add(10 * time.Second))
		fmt.Println(err)
		err = conn.WriteMessage(websocket.PongMessage, []byte{})
		fmt.Println(err)
		time.Sleep(8 * time.Second)
		err = conn.SetDeadline(time.Time{})
		//err = conn.WriteMessage(websocket.TextMessage, []byte("{\"hello dude\": \"jhehd\"}"))
		if err != nil {
			u.logger.Error("websocket ping handler failed", log.Error(err), log.Any("userID", userID))
			u.publishCloseMessage(userID, "websocket ping handler failed")
		}
	}
}`

**Comment by lesismal** [comment]
1st, you should reply to the ping message as soon as you receive it
2nd, you shouldn't `time.Sleep(8 * time.Second)` in a message handler, that will make the goroutine blocking for long, and may use out the goroutine pool.

**Comment by AnirudhDensityIntern** [comment]
we are replying that without time.sleep

**Comment by lesismal** [comment]
<img width="309" alt="image" src="https://github.com/lesismal/nbio/assets/40462947/d1eff1d3-0fc4-4810-8d8b-23107d566391">

**Comment by lesismal** [comment]
Show me the full examples including both client and server sides that can reproduce it!

Your previous example is the wrong implementation.

**Comment by AnirudhDensityIntern** [comment]
```
func (u *userStreamImpl) pingHandler(userID uuid.UUID) func(conn *websocket.Conn, s string) {
	      return func(conn *websocket.Conn, s string) {
		      u.logger.Debug("websocket ping received", log.Any("userID", userID))
		      err := conn.SetDeadline(time.Now().Add(10 * time.Second))
		      err = conn.WriteMessage(websocket.PongMessage, []byte{})
		      if err != nil {
			      u.logger.Error("websocket ping handler failed", log.Error(err), log.Any("userID", userID))
			      u.publishCloseMessage(userID, "websocket ping handler failed")
		      }
	      }
      }

```

**Comment by AnirudhDensityIntern** [comment]
we are managing only on server side to call different backend services

**Comment by lesismal** [comment]
> ```
> func (u *userStreamImpl) pingHandler(userID uuid.UUID) func(conn *websocket.Conn, s string) {
> 	      return func(conn *websocket.Conn, s string) {
> 		      u.logger.Debug("websocket ping received", log.Any("userID", userID))
> 		      err = conn.WriteMessage(websocket.PongMessage, []byte{})
> 		      if err != nil {
> 			      u.logger.Error("websocket ping handler failed", log.Error(err), log.Any("userID", userID))
> 			      u.publishCloseMessage(userID, "websocket ping handler failed")
> 		      }
> 	      }
>       }
> ```

Please provide the full example that I can run directly. That's not all the details.
