### ISSUE TITLE
请问多个包合并读取应该如何处理？

### ISSUE THREAD

**Issue by joyanhui** [lesismal/nbio#395]
在esp32单片机上发送消息到nbio的tcp server的时候，有tcp mss的1440的限制，超过1440字节后会拆分成多个DAT包。 

在nbio这边应该如何处理呢。我根据nbio-examples 试了下 在客户端发送了一个1440 + 一个100 字节的两个包的情况徐敖 为什么for会循环几百上千次 

```go
package main

import (
	"fmt"
	"log"
	"github.com/lesismal/nbio"
)

func main() {
	g := nbio.NewGopher(nbio.Config{
		Network: "tcp",
		Addrs:   []string{":18007"},
		//EpollMod: nbio.EPOLLET,
	})

	g.OnRead(func(c *nbio.Conn) {
		buf := make([]byte, 512)
		clientInfo := []byte{}
		i := 0
		iErr := 0
		for {
			i++
			n, err := c.Read(buf[0:])
			if n > 0 {
				clientInfo = append(clientInfo, buf[0:n]...)
				if clientInfo[len(clientInfo)-1] == '#' {
					c.Close()
					break
				}
			}
			if err != nil {
				iErr++
				log.Println(err)
			}
		}
		log.Println("循环了", i, "次")
		log.Println("读取错误", iErr, "次")
		log.Println(string(clientInfo))

	})
	err := g.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}

	g.Wait()
}

```

```sh
2024/02/08 18:40:21 resource temporarily unavailable
2024/02/08 18:40:21 resource temporarily unavailable
2024/02/08 18:40:21 resource temporarily unavailable
2024/02/08 18:40:21 resource temporarily unavailable
2024/02/08 18:40:21 resource temporarily unavailable
2024/02/08 18:40:21 resource temporarily unavailable
2024/02/08 18:40:21 循环了 458 次
2024/02/08 18:40:21 读取错误 454 次
2024/02/08 18:40:21 v1Set!xl:4827e25702c4!16!0a484b5c79ddb3c933c67a97194501a1!760532712!Sr5sLSyfjqUR8LBp0DHM6HfnYDLR09vmxwLNlM_fn7fa6Psm-4vWjEvooi6OsT5b8a_k7w-wOuGB2PHPUPMse2zj9YxYOyEDQejFDf_ESqe3ESDa_evh8rnZWF7j3jsYjB-BsCF1jWS41M2UI7UjDX_3QZGZ9EScMmMOZykAkWN8AJUbjsEbc_gofOmxjAabmSvKcHh1zhK3IQcomP3s5oBj2T32oV098jR3IqZsPkaAOcvr-LHSETaTmwKmjd-Qb00haPiuuTWxVqm0gPJ3nz-JzWTh8_9H8Jv9IMWbH0mh2T-KuzcHFGevPGqNM-5GdGo4iISCkx10Sekj1TDb1YHyS6G1A6MZCWHcjml5iQ0Ull-Wynp1EOqZHInbOl0h4JDEyFEk4UAGGr705_FwB_6R6WRJd1Ma6UFfP2HtbU0BsMoHLcTlhdsuURRdHY33KAJCD4pdduuGKeCqtRVLFa4furAjbsqnvivg44FIVyxDmxFSKf9SkgMJ3OiwpVn9bWTiuKlJu1ezb5L68JkNGcOEf94hC34XKCBI6uTA0pKZg6bTAru5ZknCa3-PeSmJAP7mznL3lLPinMIEhuoF0y09qGTVIIleM9wCsmZHa5Gdw8YndeVzlHKA9BBO5GMMuUFMBH4bbCj0onuiJ7vlYxO7PMQF-pEIk0TcZyjL__XqhAA07xg-L-xF4tfvHI-MBgJNrfjCPayIfYsjxtQ23V5uXhfoAeluzZNxPjr3f857VPxagTU4VgAUlZYC7qH0LqoKHsngAnEV38QIOFC4H3T3KOykT-Vf-z8xbZQ2u-0h2GAb4h1blmg9li9zmRXhoE88q9_H8PUP3d1CklPtP6Mqi0b2f3GPM9YqSAvEF-IfZ4nepn9dRmKg18Wnz8IC0_7gaOXX_C-OcSuR60Qk9WwRw0pyjig75VwY6ZFQ0MyuGM_1T8nIeIt84Ks272LWFHpIPt7s9uFcM0AtGbeg_SK4NkjRg6F1DrXKLqtFXZfszK19_WWvG2bEpsByvmjcuu_4Sye6OxBgpkyS1yxMsBQKCwoa4kaPtdXCxFHBLT6wLw4uS11Ym_Z5d36X035j6v5W9l9dst5hzsnUq1C2ZOLAuptiKkRTt-O-jzZTPGaJc-K79xtT8dyUn0CuRylRCbl1XFCSu2ZgEeebpJ8s-zEiNA3wZq9ZsEMQsNmD_433XUY4FAdQTFRAD-iQvFcUuKb2yhJ4zu1diw_pIstvrOZy04CNdxLtKswNYFN3CaiGVU-egu_r-Ao-SIUXgFi-G7ARsnNBpUKeL3NXjcStEa_b-ldZrzSZc2fTca_kH7CykR47q-x-pAVj9CxCMMZK10i1rCeHyMWqfWRFmKmztb9kW8xI0x7aUZwLosHs52ljg8dvwHyZQGEU2rYNehGvbvaz1M-Y1qaRZIym9w9M-qlmQc7ymnIjr3TKBDpq8UcoNT6wQj12l5TdcrtmzOWX#

```

**Comment by lesismal** [comment]
可以直接使用 OnData ，nbio会传data给你，但这个data是用poller上公共的buffer进行读取，所以如果你在OnData注册的handler之外仍然要使用传递给你的data需要自己另行拷贝

如果一定要自己定制OnRead，可以参考下nbio的默认实现：
https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L199

`resource temporarily unavailable` 是 `EAGAIN`，说明当前没有数据可读，这时候你应该结束本次读取、等待下次可读再读

**Comment by joyanhui** [comment]
@lesismal  大佬春节快乐，感谢！

**Comment by lesismal** [comment]
新年快乐🚀

**Comment by ruimya** [comment]
> 可以直接使用 OnData ，nbio会传data给你，但这个data是用poller上公共的buffer进行读取，所以如果你在OnData注册的handler之外仍然要使用传递给你的data需要自己另行拷贝
> 
> 如果一定要自己定制OnRead，可以参考下nbio的默认实现： https://github.com/lesismal/nbio/blob/master/poller_epoll.go#L199
> 
> `resource temporarily unavailable` 是 `EAGAIN`，说明当前没有数据可读，这时候你应该结束本次读取、等待下次可读再读

可以考虑给 ondata 函数一个返回值，通过返回值决定是否留到下次再读取

**Comment by lesismal** [comment]
框架不会提供上层数据的缓存，因为这直接涉及到buffer的使用，由应用层自己定制自己想要的数据结构来处理更好。

例如，这个用于存数据的buffer是否直接用于syscall read、是否涉及后续跨协程或者持续使用：
1. 目前默认配置是每个poller上固定buffer、poller的eventloop里读到这个buffer、ondata回调给应用层，如果跨协程、后续持续使用则需要自行拷贝之后再后续使用
2. 框架提供了定制onReadBufferAlloc/onReadBufferFree，用户可以自己定制如何使用buffer、以及后续buffer的拼接使用

而且，框架提供了OnRead、给用户足够的定制自由。

例如，是否用常驻buffer：
1. 如果常驻，海量连接，常驻的内存总量就大
2. 如果不常驻、每次解析完就放回pool那么内存总量就小

例如，使用什么buffer结构：
1. 使用单个buffer、每次append，可能单个包size大、造成大buffer的压力
2. 像字节那种使用linkedbuffer，多段小buffer、避免1的问题


这些点，涉及到很多不同的组合方式，不同的方式可能适用于不同的业务场景，如果框架提供了一种固定的，有些场景你想针对业务定制就不方便了。

应用层协议buffer的缓存逻辑并不复杂，比如你每次append一下然后判断长度是否足够一个packet、够则进行循环解析、不够则继续等待、下次再来数据继续append之类的。这个逻辑太简单了、没什么成本的。很多人纠结框架提供而不是自己做这几行代码的实现，没什么必要的，因小失大。


nbio的设计针对更通用的场景，字节家的netpoll是针对他们的rpc设计的、并不适用于其他通用场景，gnet提供的封装太简单了，而且无锁这种看上去好听实际上没有带来性能提升、而且不可能所有逻辑都在少量的几个eventloop协程里处理、还是需要异步协程池，然后用户就需要做更多额外的封装，buffer的方式也无法满足我上面描述的这些点的自由定制需求。
所以nbio不会考虑gnet和字节netpoll的方案。

另外，对于性能，gnet和netpoll官方宣称的比别人都高，我和一些小伙伴都没有复现出来：
https://github.com/guonaihong/bench-tcp
https://github.com/lesismal/go-net-benchmark/issues/1
对于benchmark性能，建议自己亲自跑一些压测代码看看自己环境的实际效果
