### ISSUE TITLE
How to check that websocket conn is open or closed? can we export the internal variable of isClosed?  

### ISSUE THREAD

**Issue by AnirudhDensityIntern** [lesismal/nbio#396]

**Comment by lesismal** [comment]
### For opening:
```golang
wsc, err := upgrader.Upgrade(...)
if err !=nil {
    ...
    return
}
// on open here
```

or register open handler by `upgrader.OnOpen`

### For closing:
register close handler by `upgrader.OnClose`

You don't need to check the state of the ws conn when you use it everytime.

**Comment by AnirudhDensityIntern** [comment]
I want to make new connection and insure the websocket Should be closed when I renew the older websocket thats why I need to check the webscocket is closed or not. 

If you are not exporting isclosed Variable can you please make a function that exports the boolean value for the websocket

**Comment by lesismal** [comment]
I think your way is not correct, that's useless to export isClosed coz:
1. before OnClose is called it's healthy
2. when OnClose is called, you know that it's closed now

That's why I said you don't need to check it's state.

**Comment by AnirudhDensityIntern** [comment]
I know when we call conn.close it closes the stream but in order to renew the websocket I will again do conn.close on the closed channel but in that case i will get error, So I need to ensure the websocket is closed or not before closing the channel also I dont want to make 2 same stream at any moment.

**Comment by lesismal** [comment]
You don't need to re-create it when it's healthy!
You should re-create a new conn when OnClose.

Why do you want to re-create it when it's healthy?

**Comment by AnirudhDensityIntern** [comment]
can we connect?
