### ISSUE TITLE
Comparison with other event based network libs

### ISSUE THREAD

**Issue by derkan** [lesismal/nbio#4]
Thanks for this lib. Do you have any performance comparison with other frameworks? 

Frameworks like:
- [evio](https://github.com/tidwall/evio)
- [gnet](https://github.com/panjf2000/gnet)

this may help:
[example gnet-benchmarks](https://github.com/gnet-io/gnet-benchmarks)

**Comment by lesismal** [comment]
Thank you for your feedback！

I did some test to compare with other frameworks, check the code here:
https://github.com/lesismal/go_network_benchmark

gnet used to be the fastest non-blocking framework written in golang, so I test and compared nbio with gnet, see the result here:
https://github.com/lesismal/go_network_benchmark/issues/2

To be honest, different env and hardware may lead to different results, so try yourself by this code or the code like [gnet-benchmarks](https://github.com/gnet-io/gnet-benchmarks)

In addition, unlike other frameworks such as evio/gnet, nbio implements net.Conn and has already supported tls and http 1.x. Today I just basically completed the support for websocket. 
Plz rrefer to the examples, including tcp sticky bytes, http 1m-connections test 、and websocket 1m-connections test and other samples:
https://github.com/lesismal/nbio/tree/master/examples

By the way, there was a blog and repo about 1m-go-websockets, but its code seems not correct. That repo's optimization just add event of conn's FD to a poller but without setting the FD to NON-BLOCKING mode, then read the FD when it's readable, if some connections are blocked, the other connections would be blocked and have to wait.

**Comment by derkan** [comment]
Thank you for detail info. Results show that this project is really promising. This repo got my ⭐ :). Issue can be closed. Thanks again.

**Comment by lesismal** [comment]
> Thank you for detail info. Results show that this project is really promising. This repo got my ⭐ :). Issue can be closed. Thanks again.

Thank you for your support 😄😄
