### ISSUE TITLE
AsyncRead 代码疑惑

### ISSUE THREAD

**Issue by yicixin** [lesismal/nbio#401]
https://github.com/lesismal/nbio/blob/5bf91e67b31f0d6587adc3ecbda9956a2d788990/conn_unix.go#L133
这里是不是应该return了呢？如果继续执行可能会在https://github.com/lesismal/nbio/blob/5bf91e67b31f0d6587adc3ecbda9956a2d788990/conn_unix.go#L145
处创建出第二个异步读的协程吧

**Comment by lesismal** [comment]
对的，感谢指正！要不要来个PR？

**Comment by yicixin** [comment]
我对下面这部分代码有些不太理解，希望作者能解答一下

在非oneShot的情况下，cnt最大值会是2，且为2时直接return，已经执行的c.readEvents+=1需要在下面的g.IOExecute中减掉。

但什么时候会有cnt为2的情况呢， AsyncRead只有在ET模式下使用，ET模式在本次未处理完数据前不会进行第二次事件触发吧。 
是为了兜底 "本次处理的协程刚好处理完数据还未退出，第二次事件立马触发"这种场景吗？

```go
func (c *Conn) AsyncRead() {
	...
	cnt := atomic.AddInt32(&c.readEvents, 1)
	if cnt > 2 {
		atomic.AddInt32(&c.readEvents, -1)
		return
	}
	if cnt > 1 {
		return
	}

	g.IOExecute(func(buffer []byte) {
		for {
			for i := 0; i < g.MaxConnReadTimesPerEventLoop; i++ {
				rc, n, err := c.ReadAndGetConn(buffer)
				if n > 0 {
					g.onData(rc, buffer[:n])
				}
				if errors.Is(err, syscall.EINTR) {
					continue
				}
				if errors.Is(err, syscall.EAGAIN) {
					break
				}
				if err != nil {
					c.closeWithError(err)
					return
				}
				if n < len(buffer) {
					break
				}
			}
			if atomic.AddInt32(&c.readEvents, -1) == 0 {
				return
			}
		}
	})
}
```

**Comment by lesismal** [comment]
因为ET非ONESHOT会重复触发，所以用了atomic计数，尽量避免当前正在读尚未完成时、再收到读事件导致不必要的重复读取（读不到数据）浪费syscall

**Comment by yicixin** [comment]
的确是我对ET理解有误，感谢解答

**Comment by yicixin** [comment]
已提交pr修复return的问题

**Comment by lesismal** [comment]
好的，合并了，感谢！
