### ISSUE TITLE
Few potential race conditions when dynamically adding/removing conns and shutdown

### ISSUE THREAD

**Issue by vrancurel** [lesismal/nbio#402]
I discovered a few potential race conditions when running with `-race` option:

- Dynamically adding and removing connections to the "epoll" engine due to non-locked access of `connsUnix[]`, the problem is present I think in the other engines too.
- At `(g *Engine) Stop()` when iterating over `connsUnix` (linked to above race)
- Setting the `shutdown` flag at `(p *poller) stop()` which races with `acceptorLoop` test for `shutdown`.

You could see an attempt to fix them in this [branch](https://github.com/vrancurel/nbio/tree/fix_race_in_poller_epoll). Would it be possible to have a clean fix ? Thx

**Comment by lesismal** [comment]
Thanks for your feedback!

For *nix, each num of fd is unique at the same time, so, it's safe for us to visit the connsUnix by fd as index, extra Mutex would be just used for race fixing but not useful and waste more CPU cost.

We tried to disable the warning by `go:norace` but gave up finally.

**Comment by lesismal** [comment]
There are more race conditions, I don't want to avoid them by extra Mutex.
If really need to do it, I think "go:norace" to ignore the warnings is better.
