### ISSUE TITLE
如何增加序列化和反序列化的函数？

### ISSUE THREAD

**Issue by awzhgw** [lesismal/nbio#405]
我的传输body是这样的：

40字节header, 其中header指明了有多少长度的body。。然后再读取body。。

我看示例中，没有这类函数的调用方法？支持吗？

**Comment by lesismal** [comment]
可以用nbio.Conn.SetSession设置你自己的连接对应的结构体，然后OnData接收到数据时自己的结构体实现包括半包缓存、新数据拼接、header和body解析的逻辑
