### ISSUE TITLE
just tested the performance of nbio tcp https on multicore system. it's great! but... how to do h2?

### ISSUE THREAD

**Issue by ouvaa** [lesismal/nbio#408]
am i pushing too hard here? is it possible to do http2 with nbio tls? the https test is perfect. wondering if there's a h2 version i can use.

since i asked for h2, maybe u can also mention about h3 too. is there some hidden ways i can do so that it's not evident?

**Comment by lesismal** [comment]
http2 is not supported by now, it's a ton of work, and I don't have so much time to do it unless I change to a new job and do it full time...

for TCP, I have this repo and here's some benchmark result:
https://github.com/lesismal/go-net-benchmark/issues/1

for Websocket:
https://github.com/lesismal/go-websocket-benchmark

for Http, here, but I didn't spend too much on HTTP benchmark and use old version, if interested, you can do some more:
https://github.com/lesismal/go-http-server-benchmark

for any benchmark repo, please run the test in your own env, my test env may not get the same result as yours.
