### ISSUE TITLE
Retract v1.5.4

### ISSUE THREAD

**Issue by IceflowRE** [lesismal/nbio#417]
You republished v1.5.4 as v1.5.5 due to a critical bug. To prevent people still trying to use `v1.5.4` (which is possible), this should be reflected in the `go.mod` with 

```
retract v1.5.4 // Contains body length parsing bug.
```

More information [retract directive](https://go.dev/ref/mod#go-mod-file-retract).

Edit: Changed message.

**Comment by lesismal** [comment]
Thanks for pointing it out!

I made a commit but I am not familiar with retract, is this correct?
https://github.com/lesismal/nbio/commit/a6684c207ae7ad7a7c43d6aa1e7389e47d215148

I've deleted the v1.5.4 when I publish v1.5.5, but users can still get v1.5.4 by some proxy because of their cache. Does `retract` work for that also?

**Comment by IceflowRE** [comment]
> I've deleted the v1.5.4 when I publish v1.5.5, but users can still get v1.5.4 by some proxy because of their cache. Does `retract` work for that also?

You have deleted the GitHub release, go uses the git tags and the tag `v1.5.4` exists and can/should also not be deleted.

> When a module version is retracted, users will not upgrade to it automatically using [go get](https://go.dev/ref/mod#go-get), [go mod tidy](https://go.dev/ref/mod#go-mod-tidy), or other commands. Builds that depend on retracted versions should continue to work, but users will be notified of retractions when they check for updates with [go list -m -u](https://go.dev/ref/mod#go-list-m) or update a related module with [go get](https://go.dev/ref/mod#go-get).

Also
> The comment may be shown by tools like go get and go list. It will be shown by [gorelease](https://pkg.go.dev/golang.org/x/exp/cmd/gorelease) and [pkg.go.dev](https://pkg.go.dev/) later on, too.

The changes seem fine for me.

**Comment by lesismal** [comment]
As the v1.5.4 has been deleted, can't do more except add this retract.

Updated the comment:
https://github.com/lesismal/nbio/commit/86e2b100052ca8cba3af6cb65a4f097a142d990c

**Comment by IceflowRE** [comment]
Looks good.

**Comment by IceflowRE** [comment]
> As the v1.5.4 has been deleted, can't do more except add this retract.

Just to avoid confusion: The release was deleted, the [tag](https://github.com/lesismal/nbio/releases/tag/v1.5.4) still exists.

**Comment by lesismal** [comment]
New skill +1, thanks a lot! 😄 ❤️
