### ISSUE TITLE
onClose 没有调用

### ISSUE THREAD

**Issue by FJSDS** [lesismal/nbio#422]
![image](https://github.com/lesismal/nbio/assets/10356979/b81387c3-f626-40d3-98cb-cb460a3ec6d8)
![image](https://github.com/lesismal/nbio/assets/10356979/d17ca23a-2600-4bff-a01e-7e7032414940)
websocket.Dialer With TLS 
![image](https://github.com/lesismal/nbio/assets/10356979/ff2abbc9-e1fb-4efd-82fc-011c815ad6a5)

**Comment by lesismal** [comment]
更新到这个试试看:
```sh
go get -u github.com/lesismal/nbio@9aa509c
```
