### ISSUE TITLE
大佬有交流群吗

### ISSUE THREAD

**Issue by Xuzan9396** [lesismal/nbio#433]
现在有个需要支持2w用户的ws连接数，简单的双向通信，这个服务器一般选用什么配置,这个库 4核8g 能支持吗

**Comment by lesismal** [comment]
感谢关注!
2w连接不算太大, 普通业务频率和消耗 4c8g 足够了.
但性能上要看综合消耗, 还包括交互频率, 包体大小, 以及每个消息处理时候的具体业务cpu和io消耗, 所以实际性能是否ok应该以你们模拟业务以及线上运行后的实际消耗来看是否需要提高硬件规格.

**Comment by Xuzan9396** [comment]
如果正式服会启动优化这些参数吗，没有特别大的业务，很小，有点像ping pong的业务，之前我是gorilla/websocket 封装的，但是有个弊端就是就是每次读写启动两个goroutine

**Comment by Xuzan9396** [comment]
然后我有个想问的就是，这些是优化参数吗，一般正式会开启这些吗，我主要是用户量多，但是业务不复杂，ping pong 类似业务，现在用户日活跃有16w，预计使用的人大概1.6w人左右，
sysctl -w net.ipv4.ip_local_port_range="1024 65535"
sysctl -w fs.file-max=2000500
sysctl -w fs.nr_open=2000500
sysctl -w net.nf_conntrack_max=2000500
ulimit -n 2000500
sysctl -w net.ipv4.tcp_mem='131072  262144  524288'
sysctl -w net.ipv4.tcp_rmem='8760  256960  4088000'
sysctl -w net.ipv4.tcp_wmem='8760  256960  4088000'
sysctl -w net.core.rmem_max=16384
sysctl -w net.core.wmem_max=16384
sysctl -w net.core.somaxconn=2048
sysctl -w net.ipv4.tcp_max_syn_backlog=2048
sysctl -w /proc/sys/net/core/netdev_max_backlog=2048
# sysctl -w net.ipv4.tcp_tw_recycle=1 # client nat tcp-handshak problem
sysctl -w net.ipv4.tcp_tw_reuse=1

**Comment by lesismal** [comment]
这些是运维相关的内核优化参数, 我们压测方便一般就这么配置了, 具体的可以搜下相关的帖子了解下
