### ISSUE TITLE
双向的TLS验证通过后，在onWebsocket里，无法获取r.TLS

### ISSUE THREAD

**Issue by ericjing83** [lesismal/nbio#437]
您好，大佬，

目前，我用nbio库已经成功测试了双向TLS握手，而且，在server端证书所属的上一级CA证书何client端证书所属的上一级CA证书分别是两个证书的时候，测试也通过了（我把server端证书对应的ca证书放到了client的根证书信任列表里，同时，把client端证书对应的ca证书放到了server的根证书信任列表里），这个目前没问题。
现在我遇到一个新的问题，golang的云服务需要在建立加密的websocket连接的时候，在标准的TLS双向握手通过的情况下，我自己再进一步对客户端证书进行验证，比如，客户端分为两个类型：普通用户何超级权限用户，我需要在代码里区分这两类用户。这两类用户的客户端证书对应的上一级CA证书是不同的，我把这两类用户的客户端的CA证书都放到了server端的信任列表里：
//start nbio server
	cert, err := tls.X509KeyPair(rsaCertPEM, rsaKeyPEM)
	if err != nil {
		fmt.Println("tls.X509KeyPair failed: ", err)
		return
	}
	cipherSuites := []uint16{
		tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
		tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	}
	pool := x509.NewCertPool()
	addTrust(pool, "/usr/local/certificate/ca_normal.crt")
	addTrust(pool, "/usr/local/certificate/ca_super.crt")

	tlsConfig := &tls.Config{
		ClientCAs:    pool,
		MinVersion:   tls.VersionTLS12, // 设置最低TLS版本为1.2
		MaxVersion:   tls.VersionTLS12, // 设置最高TLS版本为1.2
		CipherSuites: cipherSuites,
		ClientAuth:   tls.RequireAndVerifyClientCert,
		Certificates: []tls.Certificate{cert},
	}
根据，上面的设置（server端代码），这两类客户端都可以和nbio的server端完成标准的双向的TLS握手。但是，标准的TLS握手无法区分通过TLS验证然后创建的conn到底是哪一类客户端。所以，我在server端代码里，想通过这句话来获取客户端证书：

func onWebsocket(w http.ResponseWriter, r *http.Request) {
	// time.Sleep(time.Second * 5)
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		panic(err)
	}
        clientCertificate := r.TLS.PeerCertificates[0] //这句话是我加的
        //后面会根据clientCertificate的issuer进行普通用户和超级用户的区分
	if *print {
		fmt.Println("OnOpen:", conn.RemoteAddr().String())
	}
}
但是，发现运行后报错：r.TLS是空的。请教下大佬，在双向TLS验证通过并且conn成功创建后，如何在server端获取到客户端证书？

**Comment by lesismal** [comment]
感谢关注和使用nbio！

如果是websocket，可以试试这样能否满足你的需求：
```golang
func onWebsocket(w http.ResponseWriter, r *http.Request) {
	wsc, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		// handle err
	}
	tlsConn, ok := wsc.Conn.(*tls.Conn)
	if ok {
		peerCertificates := tlsConn.ConnectionState().PeerCertificates
		// or
		verifiedChains := tlsConn.ConnectionState().VerifiedChains
		// or
		tlsConn.VerifyHostname()
		
		// your verify
	}
}
```

**Comment by lesismal** [comment]
如果只是HTTP，有点麻烦，因为nbio支持了不同IoMod，http请求对应的conn可能是标准库的tls conn也可能是nbio自己的tls conn，所以类型上有点麻烦，我想想怎么处理好些

**Comment by ericjing83** [comment]
您好大佬，

感谢指点。
我测试了下上面的代码，类型断言没有成功。我只要websocket可以拿到客户端证书就够了。

**Comment by ericjing83** [comment]
大佬，
我通过反射，查看了实际的类型，应该是：*nbhttp.Conn。但是，我不知道如何从*nbhttp.Conn拿到客户端证书

**Comment by ericjing83** [comment]
我又测试了下，这样写现在可以了：
nbioConn, ok := conn.Conn.(*nbhttp.Conn)
		if ok {
			tlsConn, ok := nbioConn.Conn.(*tls.Conn)
			if ok {
				peerCertificates := tlsConn.ConnectionState().PeerCertificates
				fmt.Println("issuer is: ", peerCertificates[0].Issuer.String())
			}
		}
貌似问题解决了。

**Comment by lesismal** [comment]
好的，如果不是使用IOModMixed，只是同一个Engine或者标准库的http Server，conn只对应一种，如果涉及多种，可以调试测下不同类型的、看下每一种具体的类型、都做下判断

**Comment by ericjing83** [comment]
大佬，
我生产环境准备始终用这个：IOMod:       nbhttp.IOModNonBlocking
比IOModMixed更稳定，而且，我的性能优化主要针对高负载情况而优化的，低负载时性能过得去就行了，所以这个设置对我来说够了。上面的类型断言对于nbhttp.IOModNonBlocking应该没问题。

**Comment by ericjing83** [comment]
大佬，
我生产环境准备始终用这个：IOMod:       nbhttp.IOModNonBlocking
比IOModMixed更稳定，而且，我的性能优化主要针对高负载情况而优化的，低负载时性能过得去就行了，所以这个设置对我来说够了。上面的类型断言对于nbhttp.IOModNonBlocking目前测试没问题。

**Comment by lesismal** [comment]
好的，感谢分享！
