### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by hugosjoberg** [lesismal/nbio#440]
Hi, I am following the example server here: https://github.com/lesismal/nbio-examples/blob/master/websocket/server/server.go

I have no issues using the server, it's great 👍 However when I kill the server my clients receive a 1006 code instead of a 1000 code.

Is there a way to gracefully shutdown the server?

**Comment by lesismal** [comment]
Thank you for your attention and feedback!

`nbhttp.Engine.Shutdown` closes all the 4th layer(TCP) connections, without WriteClose to the websocket.Conn.
It seems `gorilla/websocket` does the same:
https://github.com/gorilla/websocket/blob/main/conn.go#L344

If we want to send `1000` to every websocket.Conn, you can save the connections yourself in `OnOpen`, and call `websocket.Conn.WriteClose` in a for-loop before calling the shutdown.

BTW, there's no guarantee that the client must receive `1000` even if we have `WriteClose(1000...)`, cause the TCP doesn't promise that. So I suggest we don't depend on the websocket protocol's code, but just handle `close event`.

**Comment by hugosjoberg** [comment]
@lesismal thank you for your quick response, much appreciated 🙂

I'll try your suggestion
