### ISSUE TITLE
can you add a traffic forwarding (traffic relay) example?

### ISSUE THREAD

**Issue by UallenQbit** [lesismal/nbio#441]
can you add a traffic forwarding (traffic relay) example?

**Comment by lesismal** [comment]
Thank you for your attention and feedback to nbio!

I just wrote an example for tcp traffic forward here:
https://github.com/lesismal/nbio-examples/blob/master/traffic_forward_tcp/proxy.go

For other protocols, you can implement them yourself.

**Comment by lesismal** [comment]
for udp, just change the network to "udp":
https://github.com/lesismal/nbio-examples/blob/master/traffic_forward_udp/proxy.go

**Comment by lesismal** [comment]
> thank you for your hard work. I think nbio should provide more examples for proxy, such as http proxy, socks4/5 proxy. The performance of open source http and socks4/5 libraries is not very high. I hope it can be expanded in the proxy direction.

nbio can't beat solutions based on std when there is not a huge number of online connections, std is faster in this scenario.
While when the online is huge, nbio runs better.

**Comment by lesismal** [comment]
It's easy to implement sock4/5's handshake, after handshake, with traffic forward, got the proxy.
You can implement HTTP like other proxys based on std http.Server, they are similar in most of the parts.

**Comment by lesismal** [comment]
Yes, agree with you. But I am a little busy with my current work, implementing and maintaining more repos costs a lot of time.
It's hard for me to do it well unless I have more time or change a job that is not busy and allows me to do that.
