### ISSUE TITLE
谷歌浏览器官方版，通过网页javascript连接nbio服务端，出现1006错误

### ISSUE THREAD

**Issue by ericjing83** [lesismal/nbio#442]
您好，大佬，

最近有个很困扰我的问题。很长时间我还没解决，具体情况如下：
1.我用谷歌浏览器的官方版（接近最新的版本），通过网页javascript连接nbio服务端
2.如果，网页端我用： rwsConnection = new WebSocket(rwsurl,["abcde"]); 就会立刻在连接创建的瞬间出现1006的错误。我初步判断下来，好像是网页拒绝了websocket连接。TLS握手完全没有问题，证书就是普通的证书。（这里的abcde，是在连接成功的时候，发送给nbio，nbio在请求头里的“Sec-WebSocket-Protocol”的key可以得到上面的字符串abcde）
3.如果，网页端，我用：rwsConnection = new WebSocket(rwsurl); 连接在短时间里会成功。但是只会保持1分钟左右。我看这里nbio的设置，是让客户端主动发送心跳给nbio服务端是吧，我想请教下javascript里如何主动发送心跳给nbio，我看看能不能解决问题。

网页端的关键代码如下，除了下面这句话，没有别的特别的代码:
var rwsurl = "wss://www.testcloud.com:8880"
rwsConnection = new WebSocket(rwsurl,["abcde"]); 
rwsConnection.onopen = function (e) {
            console.log('rwsConnection is created.');
        }

服务端代码如下：
package main

import (
	"context"
	"crypto/x509"
	"flag"
	"fmt"
	"github.com/lesismal/llib/std/crypto/tls"
	"github.com/lesismal/nbio/nbhttp"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"

	"github.com/lesismal/nbio/nbhttp/websocket"
)

var (
	addr = flag.String("addr", "0.0.0.0:8880", "http service address")

	hub = Hub{
		broadcast:  make(chan []byte),
		register:   make(chan *websocket.Conn),
		unregister: make(chan *websocket.Conn),
		clients:    make(map[*websocket.Conn]bool),
	}

	upgrader = newUpgrader()
)

func newUpgrader() *websocket.Upgrader {
	u := websocket.NewUpgrader()
	u.CheckOrigin = func(r *http.Request) bool {
		fmt.Println("hi,CheckOrigin")
		return true
	}

	// 服务端主动发心跳检测浪费资源
	// 让客户端发心跳、服务端只要读超时关闭就可以了，这样不白白浪费服务端定时器、更好
	u.KeepaliveTime = 60 * time.Second
	u.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, message []byte) {
		hub.broadcast <- message
	})
	u.OnClose(func(c *websocket.Conn, err error) {
		hub.unregister <- c
	})
	return u
}

func serveWs(w http.ResponseWriter, r *http.Request) {
	fmt.Println("hi calling Upgrade")
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Println(err)
		return
	}
	fmt.Println("Upgraded:", conn.RemoteAddr().String())
	hub.register <- conn
}

// Hub maintains the set of active clients and broadcasts messages to the clients.
type Hub struct {
	// Registered clients.
	clients map[*websocket.Conn]bool

	// Inbound messages from the clients.
	broadcast chan []byte

	// Register requests from the clients.
	register chan *websocket.Conn

	// Unregister requests from clients.
	unregister chan *websocket.Conn
}

func (h *Hub) run() {
	for {
		select {
		case client := <-h.register:
			h.clients[client] = true
		case client := <-h.unregister:
			if _, ok := h.clients[client]; ok {
				delete(h.clients, client)
			}
		case message := <-h.broadcast:
			for conn := range h.clients {
				conn.WriteMessage(websocket.TextMessage, message)
			}
		}
	}
}
func addTrust(pool *x509.CertPool, path string) {
	aCrt, err := ioutil.ReadFile(path)
	if err != nil {
		fmt.Println("ReadFile err:", err)
		return
	}
	pool.AppendCertsFromPEM(aCrt)
}
func main() {
	fmt.Println("hi,greeting from mws!")
	flag.Parse()
	go hub.run()
	cert, err := tls.LoadX509KeyPair("/usr/local/certificate/www.starcloudhardware.com.crt", "/usr/local/certificate/www.starcloudhardware.com.key")
	if err != nil {
		fmt.Println("tls.X509KeyPair failed: ", err)
	}
	cipherSuites := []uint16{
		tls.TLS_AES_256_GCM_SHA384,
	}

	tlsConfig := &tls.Config{
		MinVersion:   tls.VersionTLS13, // 设置最低TLS版本为1.3
		MaxVersion:   tls.VersionTLS13, // 设置最高TLS版本为1.3
		CipherSuites: cipherSuites,
		Certificates: []tls.Certificate{cert},
	}

	mux := &http.ServeMux{}
	mux.HandleFunc("/", serveWs)
	engine := nbhttp.NewEngine(nbhttp.Config{
		Network:                 "tcp",
		AddrsTLS:                []string{*addr},
		TLSConfig:               tlsConfig,
		MaxLoad:                 1000000,
		ReleaseWebsocketPayload: true,
		Handler:                 mux,
		MessageHandlerPoolSize:  10000,
		IOMod:                   nbhttp.IOModNonBlocking,
		// websocket 单帧最大载荷
		MaxWebsocketFramePayloadSize: 1024 * 16, //this is a recommend value from chrome
	})

	err = engine.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}

	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	<-interrupt

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
	defer cancel()
	engine.Shutdown(ctx)
}

**Comment by lesismal** [comment]
麻烦提供个直接能跑的例子, client和server完整能复现的简单例子即可, 我试试

**Comment by ericjing83** [comment]
感谢大佬的指点，
这个问题困扰了我一周多的时间，现在我可能决定绕过这个问题。我经过了很多很多的测试，测试的服务端代码在附件里，具体情况如下：
[main.txt](https://github.com/user-attachments/files/16456442/main.txt)
1.一模一样的golang服务端代码，都是基于nbio的，当我浏览器用谷歌官方版（最新）的时候，只要我在javascript里这样：ws = new websocket(url)，不带任何子协议数据的时候，网页就可以和nbio服务端成功连接。但是，一旦我加了子协议数据，比如，我最简单的测试，ws = new websocket(url, ["abc"])，这样的时候，连接就无法成功，看上去是谷歌浏览器强行终止了websocket连接。
2.一模一样的golang服务端代码，都是基于nbio的，如果我浏览器换成火狐官方版本（最新），无论javascript里是否带子协议数据，比如我这样写：ws = new websocket(url, ["abc"])，网页都可以和nbio成功进行连接。但是火狐浏览器最新版对子协议的数据类型限制在了16进制里。不支持base64格式。
3.一模一样的golang服务端代码，都是基于nbio的，如果我客户端用golang的gorilla client，子协议里带上数据可以和nbio的服务端成功连接。子协议的数据类型可以是任何格式，包括base64。
所以，我觉得，问题出在谷歌浏览器上。如果暂时nbio没有发现问题，我可能先绕过这个问题，避免用谷歌浏览器。或者，用谷歌浏览器的时候，先用不带子协议的代码连接，像这样：ws = new websocket(url)，然后，javascript里的onopen事件触发后，网页端再发送用户的身份验证信息给服务端进行进一步验证。这是一个walk around。

**Comment by lesismal** [comment]
如果能够提供个复现的完整前后端代码我可以试试看

如果是nbio主动关闭的，你用断点调试应该也能找到问题的

**Comment by ericjing83** [comment]
您好，大佬，
这个是可以复现此问题的前后端代码。是一个压缩包，里面有自签名的ca证书，需要谷歌浏览器添加为信任，还包括服务端证书+私钥，服务端代码，网页端代码。谷歌浏览器是最新的官方版。
[复现1006报错的前后端代码.zip](https://github.com/user-attachments/files/16464644/1006.zip)

**Comment by lesismal** [comment]
没有收到github消息提示, 抱歉回复晚了.

好像确实是chrome的问题, nbio里TCP建立连接都没有收到都没到TLS, HTTP, Websocket这些七层协议的阶段, 可能chrome自己就给拦了
