### ISSUE TITLE
请教下大佬，这个库在处理websocket.BinaryMessage时候的性能

### ISSUE THREAD

**Issue by ericjing83** [lesismal/nbio#443]
您好
请教下大佬，在百万级海量请求的场景下，这个库在处理websocket.BinaryMessage时候的性能，相比websocket.TextMessage的性能，是差不多的吗？对于同样的字节长度的信息。

**Comment by lesismal** [comment]
Binary 和 Text 的性能差异主要是 CheckUtf8, 其他基本一样。Text 通常没必要，如果不是历史兼容性原因，建议统一用 Binary

**Comment by ericjing83** [comment]
大佬，
nbio的内存池的性能，不会因为切换到Binary而受影响是吧？
我感觉内存池里是字节切片，应该可以直接存储二进制的数据的。

**Comment by lesismal** [comment]
Binary 和 Text 都是 Buffer ，除了 Text 需要  CheckUtf8, 其他都是对 Buffer 的操作没有性能差别
