### ISSUE TITLE
add example with epoll?

### ISSUE THREAD

**Issue by akshayk-ktk** [lesismal/nbio#448]
Hi,

I was trying out the 1m-websocket connections repo with epoll and saw that it uses gobwas, but the issue there is that a slow connection can block the other connections as you have mentioned.

Apparently this repo solves it via non blocking io, i want to try using this repo with epoll but do not find the example for the same. Is it possible for you to add an example for epoll with nbio?

Thanks

**Comment by lesismal** [comment]
Thanks for your attention to nbio!

For using `epoll` on `linux`, set the `IOMod = IOModNonBlocking` 
```golang
engine := nbhttp.NewEngine(nbhttp.Config{
	Network:                 "tcp",
	Addrs:                   addrs,
	Handler:                 mux,
	IOMod:                   nbhttp.IOModNonBlocking,
	ReleaseWebsocketPayload: true,
})
```

Or just don't set `IOMod`, then `IOModNonBlocking` by default and all the connections will be driven by `epoll`.
```golang
engine := nbhttp.NewEngine(nbhttp.Config{
	Network:                 "tcp",
	Addrs:                   addrs,
	Handler:                 mux,
	// IOMod:                   nbhttp.IOModNonBlocking, // by default
	ReleaseWebsocketPayload: true,
})
```

For `websocket`, here is the benchmark example using `epoll`:
https://github.com/lesismal/go-websocket-benchmark/blob/main/frameworks/nbio_nonblocking/server.go

**Comment by akshayk-ktk** [comment]
Okay, thanks for the info will check it out.
