### ISSUE TITLE
Race condition in engine shutdown

### ISSUE THREAD

**Issue by iclita** [lesismal/nbio#450]
Hi,

I've found a race condition in the engine shutdown flow:
<img width="430" alt="Screenshot 2024-10-11 at 09 28 31" src="https://github.com/user-attachments/assets/a8fc78ba-c865-4498-bfa7-e03deb6683c6">
<img width="530" alt="Screenshot 2024-10-11 at 09 28 15" src="https://github.com/user-attachments/assets/0439f668-3827-45cd-807b-8b6dad5ce951">
<img width="836" alt="Screenshot 2024-10-11 at 09 28 02" src="https://github.com/user-attachments/assets/ee6573d4-ce08-48e4-b91c-021161eb1305">

Can you please have a look?

Thanks a lot

**Comment by lesismal** [comment]
same as https://github.com/lesismal/nbio/issues/449#issuecomment-2406744046
