### ISSUE TITLE
I intentionally wrote a panic handler, but the request never returned. Is this a bug?

### ISSUE THREAD

**Issue by sunvim** [lesismal/nbio#452]
as  the title said,  the code is [blow:
![1](https://github.com/user-attachments/assets/42680ecb-db86-4bb6-b9c2-3f2b73aedfc8)
![2](https://github.com/user-attachments/assets/5367228e-0227-417a-88a3-1834a0662af9)

**Comment by lesismal** [comment]
It's not a bug. nbio is designed at the basic level as net/http.

When we try this:
```golang
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/hello", func(w http.ResponseWriter, req *http.Request) {
		fmt.Fprintf(w, "hello")
	})
	http.HandleFunc("/panic", func(w http.ResponseWriter, req *http.Request) {
		panic(nil)
	})

	http.ListenAndServe(":8080", nil)
}
```
We also can't get the response because of the panic.

But when we use some other frameworks, such as gin:
```golang
package main

import "github.com/gin-gonic/gin"

func main() {
	r := gin.Default()
	r.GET("/hello", func(c *gin.Context) {
		c.String(200, "hello")
	})
	r.GET("/panic", func(c *gin.Context) {
		panic(nil)
	})
	r.Run(":8080")
}
```
We get `500 Internal Server Error`

Whatever, the best way is to use `recover middleware`.
