### ISSUE TITLE
1.2.18版本连接问题咨询

### ISSUE THREAD

**Issue by mowen-gx** [lesismal/nbio#453]
大神们，请教一下，目前使用1.2.18版本，发现一个问题，有时候会发现后端把信息误发到错误的客户端连接上（也就是后端把客户端A的信息发送给了客户端B），这是怎么回事呀？

**Comment by lesismal** [comment]
请提供下复现代码我看下

**Comment by lesismal** [comment]
也先请更新到最新版本吧, 再看下还有问题没

**Comment by mowen-gx** [comment]
偶发的，大概一周出现一次左右，所以目前也没办法复现，原因也无法确定，所以想来咨询一下。再请教一下，从1.2.18升级到最新版本，有兼容性问题需要注意的吗？

**Comment by lesismal** [comment]
应该是兼容的, 只要go get update应该就可以了

**Comment by FJSDS** [comment]
https://github.com/lesismal/nbio/issues/445
 
 答案在这里。升级一下就好了 @lesismal @mowen-gx

**Comment by mowen-gx** [comment]
我研究一下

**Comment by mowen-gx** [comment]
> #445
> 
> 答案在这里。升级一下就好了 @lesismal @mowen-gx

追问一下，是因为多次close导致多个引用指向了相同一块内容，然后请求的Body被覆盖了，导致不同请求拿到了相同的请求内容？ @FJSDS

**Comment by lesismal** [comment]
> > #445
> > 答案在这里。升级一下就好了 @lesismal @mowen-gx
> 
> 追问一下，是因为多次close导致多个引用指向了相同一块内容，然后请求的Body被覆盖了，导致不同请求拿到了相同的请求内容？ @FJSDS

有可能是这个bug导致的, 所以先更新到最新版本试试吧

**Comment by FJSDS** [comment]
> > #445
> > 答案在这里。升级一下就好了 @lesismal @mowen-gx
> 
> 追问一下，是因为多次close导致多个引用指向了相同一块内容，然后请求的Body被覆盖了，导致不同请求拿到了相同的请求内容？ @FJSDS

是的，你检查一下你代码里面是不是用了http, 然后手动调用了 body.Close ,这会导致 ReadCloser 被2次丢入sync.Pool. 因为nbio框架内会主动调用一次body.Close。  这个就会出现你说的消息发错的情况

**Comment by lesismal** [comment]
> 是的，你检查一下你代码里面是不是用了http, 然后手动调用了 body.Close ,这会导致 ReadCloser 被2次丢入sync.Pool. 因为nbio框架内会主动调用一次body.Close。 这个就会出现你说的消息发错的情况

也有可能是之前ws实现的bug, 这中间修改挺大的

**Comment by mowen-gx** [comment]
> > 是的，你检查一下你代码里面是不是用了http, 然后手动调用了 body.Close ,这会导致 ReadCloser 被2次丢入sync.Pool. 因为nbio框架内会主动调用一次body.Close。 这个就会出现你说的消息发错的情况
> 
> 也有可能是之前ws实现的bug, 这中间修改挺大的

@lesismal 有可能一个fd分配给了两个Conn对象的可能吗？

**Comment by mowen-gx** [comment]
确实是这里的问题（已经能复现了），谢谢两位 @FJSDS @lesismal
