### ISSUE TITLE
[]byte 不能进sync.Pool

### ISSUE THREAD

**Issue by FJSDS** [lesismal/nbio#454]
![image](https://github.com/user-attachments/assets/98fdac76-e938-49b2-9eca-eb4bcb491a4a)
![image](https://github.com/user-attachments/assets/6fcbe77e-123f-4c65-b95a-1adfb58a42a6)
![image](https://github.com/user-attachments/assets/00cb4075-37af-44ea-9801-269b33a354f0)

[]byte 不能进sync.Pool 

解决方案如下:

要么取出来的[]byte是地址，然后放回去也是这个地址
要么结构体包装一下。我更倾向这种方案

```
type Bytes struct {
	Data []byte
}

// Pool consists of 32 sync.Pool, representing byte slices of length from 0 to 32 in powers of 2.
type Pool struct {
	pools [32]sync.Pool
}

// Get retrieves a byte slice of the length requested by the caller from pool or allocates a new one.
func (p *Pool) Get(size int) *Bytes {
	if size <= 0 {
		return nil
	}
	if size > math.MaxInt32 {
		return &Bytes{Data: make([]byte, size)}
	}
	idx := index(uint32(size))
	if v := p.pools[idx].Get(); v != nil {
		b := v.(*Bytes)
		b.Data = b.Data[:size]
		return b
	}
	return &Bytes{Data: make([]byte, 1<<idx)[:size]}
}

// Put returns the byte slice to the pool.
func (p *Pool) Put(b *Bytes) {
	size := cap(b.Data)
	if size == 0 || size > math.MaxInt32 {
		return
	}
	idx := index(uint32(size))
	if size != 1<<idx { // this byte slice is not from Pool.Get(), put it into the previous interval of idx
		idx--
	}
	p.pools[idx].Put(b)
}

func index(n uint32) uint32 {
	return uint32(bits.Len32(n - 1))
}
```

**Comment by FJSDS** [comment]
![image](https://github.com/user-attachments/assets/73ce553d-3397-4faf-9670-c221db475c33)
这是我们线上的真实情况。

**Comment by vipcxj** [comment]
图裂

**Comment by vipcxj** [comment]
@FJSDS 顺便问下nbio的websocket有没有自带一个默认的读超时？我客户端如果不主动发个ping，就会超时导致断开~

**Comment by FJSDS** [comment]
> @FJSDS 顺便问下nbio的websocket有没有自带一个默认的读超时？我客户端如果不主动发个ping，就会超时导致断开~

Upgrade的时候设置一下就行了，不过建议客户端开启ping  pong协议

**Comment by lesismal** [comment]
这个 `go tool pprof --alloc_objects` 是统计分配过的对象数量吧, 和当前占用的数量是不一样的

例如同一个pprof heap:

alloc_objects:
<img width="736" alt="image" src="https://github.com/user-attachments/assets/5d6d9b7e-557b-4bd2-aeee-829fccbeb050">

inuse_objects:
<img width="679" alt="image" src="https://github.com/user-attachments/assets/203fd809-759d-44a4-850a-ba19832193ec">

分配过的空间和当前占用的空间则为:
<img width="684" alt="image" src="https://github.com/user-attachments/assets/2568aa51-bcc1-469b-8160-25756bdff3b7">
<img width="657" alt="image" src="https://github.com/user-attachments/assets/2acb00c5-f2aa-4a31-8037-d8baa074d75c">

这个是为了应用层使用方便, mempool 返回给应用层是 []byte, 但 mempool 内部的 sync.Pool 里用的 *[]byte


alloc这个多, 但是也是Free里的栈内存的取[]byte地址的指针, 因为现在Pool就是取放 *[]byte 的, 所以影响应该没那么大:
https://github.com/lesismal/nbio/blob/master/mempool/mempool.go#L40
https://github.com/lesismal/nbio/blob/master/mempool/mempool.go#L100

**Comment by lesismal** [comment]
上一楼用的你的代码:
```golang
package main

import (
	"math/rand"
	"net/http"
	_ "net/http/pprof"

	"github.com/lesismal/nbio/mempool"
)

func main() {
	go func() {
		http.ListenAndServe(":6060", nil)
	}()

	p := mempool.New(1024, 1024*64)
	for {
		b := p.Malloc(rand.Int()%4096 + 1)
		p.Free(b)
	}
}
```

heap文件:

[heap.tar.gz](https://github.com/user-attachments/files/17903218/heap.tar.gz)

**Comment by lesismal** [comment]
最早的时候是直接应用层用的 []byte, 方便, 后来想过改成应用层直接使用 *[]byte 或者 struct, 是可以减少这个少量的分配, 但是涉及到兼容性问题, 有早期用户是自己定制了mempool, 如果改了他们如果升级就会不兼容, 而且用到的地方全要改动一遍, 改动量也比较大

我想想要不要改, 如果改, 可能要发个2.0大版本才好, 1.x的基本都是保持向前兼容了的

**Comment by FJSDS** [comment]
用struct，然后onmessage的时候只传strcut的[]byte，设置了releasepayload=true的就很没分配了，没设置的分配翻倍，但是整个nbio还有其他地方内部在malloc和free，onmessage产生的只占总体的40%，我觉得可以直接改成strcut的，能兼容

**Comment by FJSDS** [comment]
小对象太多对gc影响大，在扫描阶段会耗费大量的cpu时间。我想了很久，真的有必要改。能做到兼容，用struct的方式改，对于没设置bytes回收参数的代码会增加少量gc消耗，但是他们都设置重用，也不在乎这点消耗😓，*[]byte代码可读性太差，写代码的人也麻烦。

**Comment by FJSDS** [comment]
目前我正在优化我们的gateway，如果你不改这里的话，等我优化完，nbio的分配会占到我gateway总分配的90%以上，哈哈。一个是mempool，一个是fork

**Comment by FJSDS** [comment]
我想了一下，整个nbio几乎可以做到接近0分配的情况，明天我研究一下fork那里是啥原因也有大量分配

**Comment by lesismal** [comment]
可以, 改个大版本吧, mempool 不考虑向前兼容了, 但是要花些时间

**Comment by lesismal** [comment]
> 明天我研究一下fork那里是啥原因也有大量分配

fork是指什么, taskpool里的那个?

**Comment by FJSDS** [comment]
> 如果是taskpool里的fork, 可以试试自己简单版本常驻协程替换每次go func()对比下, 缩小chan的cap避免里面积压太多闭包和对应的大量资源
> 
> 你们这个gateway百万连接, 是什么硬件配置的, 现在能跑多少qps啊?

还不知道能上到多少，这么大的量不好压测，只能把分配内存和常住内存的全部优化了，然后压个10万连接看资源消耗，目前也不可能买大机器在那里空跑着，百万只是要求的理想情况。还没那么大的用户量

**Comment by FJSDS** [comment]
![image](https://github.com/user-attachments/assets/fd83dbcc-f200-47de-a81e-688606d19b11)
目前发送和接收总共500万条消息的内存分配情况。
nats 的目前动不了
xid.ID.String 可优化。
reflect.New 是配置文件，常量分配
剩下的全是 nbio的分配了。

目前 mallocgc 还有10%的cpu消耗量

啥时候开始 v2 版本，我这边能参与修改，有时间

**Comment by lesismal** [comment]
先得把 llib 的 tls 也得升级了, 因为涉及之前 mempool 里的 Allocator interface 定义, 而且因为之前是接口, 如果用 struct , 接口定义的返回值变更为 struct, 会导致 import 交叉引用(struct 定义应该在 nbio/mempool 里, 但是nbio import llib, llib 依赖 struct 定义需要 import nbio), 所以还是 *[]byte 吧, 这样主要就是替换, 难度不大, 但涉及的地方有点多, 繁琐

**Comment by FJSDS** [comment]
那改起来就很快了

**Comment by FJSDS** [comment]
![image](https://github.com/user-attachments/assets/11275128-4f30-4091-ae15-05032ab32a1b)


llib那边的有接口依赖。看起比较麻烦了

**Comment by FJSDS** [comment]
提个建议。[]byte 分配最好按照2的倍数分配。这样可以极大减少分配次数。直接按照需要的数量分配可能会导致很多次的Realloc


2的倍数类似这种：
```
var builtinPool Pool

const minCap = 128

type Bytes struct {
	Data []byte
}

// Pool 已2的倍数来区分不同的对象池，实际最小是128字节
type Pool struct {
	pools [32]sync.Pool
}

func GetSample(size int) *Bytes {
	return builtinPool.Get(size)
}

func PutSample(b *Bytes) {
	builtinPool.Put(b)
}

// Get 返回2的倍数的[]byte
func (p *Pool) Get(size int) *Bytes {
	if size > math.MaxInt32 {
		return &Bytes{Data: make([]byte, size)}
	}
	if size < minCap { // 小内存分配太零散了。128字节起步，复用率比较高
		size = minCap
	}
	idx := index(uint32(size))
	if v := p.pools[idx].Get(); v != nil {
		bp := v.(*Bytes)
		bp.Data = bp.Data[:size]
		return bp
	}

	return &Bytes{Data: make([]byte, 1<<idx)[:size]}
}

// Put 回收 Bytes 对象以重用
func (p *Pool) Put(b *Bytes) {
	c := cap(b.Data)
	if c < minCap || c > math.MaxInt32 {
		return
	}
	idx := index(uint32(c))
	if c != 1<<idx { // 不是Get获取的[]byte，放在前一个索引的Pool里面
		idx--
	}
	p.pools[idx].Put(b)
}

func index(n uint32) uint32 {
	return uint32(bits.Len32(n - 1))
}

```

**Comment by FJSDS** [comment]
![image](https://github.com/user-attachments/assets/0152ff6e-df23-40b4-a842-d757984c88e0)

这个 jobList 有吃爆内存的风险，如果在高并发的情况下，数组一直扩容怎么搞，而且还不会释放，举个例子：

每执行完一个job ，然后 Execute(job func()) bool 又往里面加一个。一直这么循环，这个 jobList 会一直变大。高并发的情况下这个真有可能发生。

提个建议，可以用两个buffer来做这个事，还可以减少锁的竞争。

这里有个我个人写的例子：

```
type DoubleBuffQueue struct {
	mu           *sync.Cond
	data         [2][]interface{}
	log          *logger.Logger
	stopped      int32
	over         chan struct{}
	lockOSThread bool
}

func NewDoubleBuffQueue(log *logger.Logger, lockOSThread bool) *DoubleBuffQueue {
	return &DoubleBuffQueue{
		log:          log,
		mu:           sync.NewCond(&sync.Mutex{}),
		lockOSThread: lockOSThread,
		over:         make(chan struct{}),
	}
}

func (this_ *DoubleBuffQueue) PostEventQueue(e interface{}) {
	if atomic.LoadInt32(&this_.stopped) != 0 {
		return
	}
	this_.mu.L.Lock()
	this_.data[0] = append(this_.data[0], e)
	this_.mu.L.Unlock()
	this_.mu.Signal()
}

func (this_ *DoubleBuffQueue) Start(f func(event interface{}), endF ...func()) {
	xf := func(event interface{}) {
		defer safego.Recover(
			func(e interface{}) {
				this_.log.Error("event func panic", zap.Any("panic info", e))
			},
		)
		switch fx := event.(type) {
		case func():
			fx()
		default:
			f(event)
		}
	}
	var rF []func()
	if len(endF) > 0 {
		for _, v := range endF {
			rF = append(rF, func() {
					defer safego.Recover(
						func(e interface{}) {
							this_.log.Error("end func panic", zap.Any("panic info", e))
						},
					)
					v()
				},
			)
		}
	}
	go this_.start(xf, rF...)
}

func (this_ *DoubleBuffQueue) start(f func(event interface{}), endF ...func()) {
	gid := goid.Get()
	defer func() {
		this_.log.Warn("eventloop closed", zap.Int64("gid", gid))
		close(this_.over)
	}()
	this_.log.Warn("EventLoop Run", zap.Int64("gid", gid))
	if this_.lockOSThread {
		runtime.LockOSThread()
		defer runtime.UnlockOSThread()
	}
	for atomic.LoadInt32(&this_.stopped) == 0 {
		this_.mu.L.Lock()
		if len(this_.data[0]) == 0 {
			this_.mu.Wait()
		}
		this_.data[0], this_.data[1] = this_.data[1], this_.data[0]
		this_.mu.L.Unlock()

		for _, v := range this_.data[1] {
			f(v)
		}
		// 可以设置一个最大容量，这个最大容量不是一个限制，只是在一些意外情况下导致data的
		// cap 非常大的时候，把data缩容
		// 比如:
		// if cap(this_.data[1]) > 10240 && cap(this_.data[1]) > len(this_.data[1])*2 { // len < cap/2
		// 	this_.data[1] = make([]interface{}, 0, cap(this_.data[1])/2)
		// 	continue
		// }
		clear(this_.data[1])
		this_.data[1] = this_.data[1][:0]
	}
	for _, v := range this_.data[0] {
		f(v)
	}
	for _, v := range this_.data[1] {
		f(v)
	}
	for _, v := range endF {
		v()
	}
}

func (this_ *DoubleBuffQueue) Stop() {
	atomic.StoreInt32(&this_.stopped, 1)
	this_.mu.Broadcast()
	<-this_.over
}

func (this_ *DoubleBuffQueue) Stopped() bool {
	return atomic.LoadInt32(&this_.stopped) == 1
}
```

**Comment by lesismal** [comment]
2的倍数最早也是这么考虑的但情况不一样，http文本协议的解析没法提前预知剩余长度，一直需要append的情况下用2倍数会造成一直切换index和拷贝，复用率低性能更差，而且这个过程中也可能会过多分配，比如第一次分配了64,后续分别扩展到512、1024才解析完成一个request，这期间要把64和512放回去，实际有效的是最终的1024，但是没办法提前预知最终就是1024

**Comment by lesismal** [comment]
2的倍数最早也是这么考虑的但情况不一样，http文本协议的解析没法提前预知剩余长度，一直需要append的情况下用2倍数会造成一直切换index和拷贝，复用率低性能更差，而且这个过程中也可能会过多分配，比如第一次分配了64,后续分别扩展到512、1024才解析完成一个request，这期间要把64和512放回去，实际有效的是最终的1024，但是没办法提前预知最终就是1024

**Comment by lesismal** [comment]
conn的joblist只是针对单个conn自己，单个conn通常不会有太大，如果有，应用层自己可以加中间件例如超频超流量了然后强行关闭。而且现在各种长连接为主，joblist与连接数量一对一，建立连接和断开不至于超高频到导致joblist成为瓶颈。复用这个slice比list之类的可能更省一点点消耗

**Comment by lesismal** [comment]
*[]byte 的确是不太好改, 因为之前有很多地方是直接 len([]byte) 的, 早上那波修改主要是用 *pbuf 替换了 buf, 但 pbuf 可能为 nil, 之前直接 len(buf) 的地方改成 len(*pbuf) 就有问题了, 要加 nil 判断, 怕改漏掉.

另一个遗憾, 是最早期实现时候没有追求buffer释放与分配的一对一, 也就是严格分配和释放/分配的必须手动释放. 否则直接 cgo 搞个 buffer pool 然后丢给 jemalloc tcmalloc 之类的去做可能更好些. 现在不是严格的分配释放一对一, 有的地方仍然是依赖gc, 就不敢这么用了, 怕漏掉释放会导致 c 里的内存泄漏. 为了避免c里的泄漏, 之前还弄了个玩具, SetFinalizer 的方式, 让漏掉手动释放的地方在被 gc 的时候自动去调用 c 里的释放:
https://github.com/lesismal/noleak
但还是存在风险, 例如短期大量分配并且漏掉释放, 等不到 gc 去 c 里释放就把程序搞崩了, 所以也不适合投入使用

**Comment by lesismal** [comment]
现在这个 jobList 配合通用协程池的方式, 放到其他语言里也都是可以的, 线程池和 fd conn 也能实现负载均衡地去运作, 但是没有什么好的契机再去搞 c/c++ 或者其他语言那些了

**Comment by FJSDS** [comment]
直接上2.0大改一波。哈哈。我这边不急

**Comment by FJSDS** [comment]
> 现在这个 jobList 配合通用协程池的方式, 放到其他语言里也都是可以的, 线程池和 fd conn 也能实现负载均衡地去运作, 但是没有什么好的契机再去搞 c/c++ 或者其他语言那些了

C++有 asio 已经很无敌了，简单易用性能也还不错

**Comment by FJSDS** [comment]
> 直接上2.0大改一波。哈哈。我这边不急

我时不时还是有一些时间可以帮忙搞一下

**Comment by guonaihong** [comment]
asio是不是要进标准库了，昨天好像看到哪个公众号上有提。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月27日(周三) 上午9:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lesismal/nbio] []byte 不能进sync.Pool (Issue #454)




  
现在这个 jobList 配合通用协程池的方式, 放到其他语言里也都是可以的, 线程池和 fd conn 也能实现负载均衡地去运作, 但是没有什么好的契机再去搞 c/c++ 或者其他语言那些了
  
C++有 asio 已经很无敌了，简单易用性能也还不错

**Comment by FJSDS** [comment]
之前不是吵muduo吗？现在换asio了？哈哈，等了好多个3年都还没有标准定下来。还是玩go吧。C++做大项目在中国有点难，对人员要求高，招不到那么多人

**Comment by FJSDS** [comment]
> 之前不是吵muduo吗？现在换asio了？哈哈，等了好多个3年都还没有标准定下来。还是玩go吧。C++做大项目在中国有点难，对人员要求高，招不到那么多人

有C++搞项目的精力，我都可以再多做几个项目出来了。上个项目战斗用C++写。写着写着我一个人在写了，一个人写得吐血都写不完。莫意思，其他人来写C++都是依葫芦画瓢，招人不好招。还是go爽

**Comment by vipcxj** [comment]
c++的坑真滴多，不说别的，绝大多数时间，我的程序就不能正常结束，都是边core dump边结束~ 各种析构问题。c++的全局变量或静态变量因为涉及析构顺序，全是坑~

**Comment by mowen-gx** [comment]
> 初步改了下放这个分支了: https://github.com/lesismal/nbio/tree/mempool_buffer_ptr_opt
> 
> 我还没测试, 先搬砖了, 抽空继续

过来问下，这个有新进展吗？非常关心

**Comment by lesismal** [comment]
> 过来问下，这个有新进展吗？非常关心

这周比较忙, 下周找时间继续

**Comment by lesismal** [comment]
llib里前几天已经改过一些了, 最近两个提交:
https://github.com/lesismal/llib/commits/master/

nbio自己里面的, 需要把 nil 判断的再加上

> alloc tcmalloc 之类的去做可能更好些. 现在不是严格的分配释放一对一, 有的地方仍然是依赖gc, 就不敢这么用了, 怕漏掉释放会导

@FJSDS 
llib需要 `go get -u` 更新一下, 然后能编译能跑, 但是 nil 判断还没加完, 会panic. 我有空了继续加

**Comment by lesismal** [comment]
@FJSDS 

改了一波 nil 判断, 可以更新下 nbio 和 llib 试下:
```sh
go get -u github.com/lesismal/nbio@e50324d50619d5381f0ebf88e8bc41e5b0c5ed2a
go get -u github.com/lesismal/llib@fdcbf6b57f956388972ae61a49db15feb97b7266
```

**Comment by FJSDS** [comment]
不好意思，我这几天也有点忙。忘了看这里，我马上拉下来试试

**Comment by FJSDS** [comment]
首先非常非常感谢作者百忙之中帮忙修改。敬礼！！！

```
   2665189 22.19% 22.19%    2666214 22.20%  github.com/lesismal/nbio/mempool.(*MemPool).Malloc
   1441825 12.01% 34.20%    1441825 12.01%  github.com/rs/xid.ID.String
   1419967 11.82% 46.02%    1419967 11.82%  github.com/lesismal/nbio/taskpool.(*TaskPool).fork
   1228837 10.23% 56.26%    4390994 36.56%  github.com/lesismal/nbio/nbhttp/websocket.(*Conn).handleMessage
   1226551 10.21% 66.47%    1226551 10.21%  github.com/nats-io/nats%2ego.(*Conn).processMsg
   1179657  9.82% 76.29%    2119026 17.65%  github.com/lesismal/nbio/nbhttp/websocket.(*Conn).writeFrame
    933895  7.78% 84.07%    3162157 26.33%  github.com/lesismal/nbio.(*Conn).Execute
    808295  6.73% 90.80%    2228262 18.55%  github.com/lesismal/nbio.(*Conn).execute (inline)

```
github.com/lesismal/nbio/mempool.(*MemPool).Malloc 主要来自 Parse 和 writeFrame 分配的没有被重用到
![image](https://github.com/user-attachments/assets/ceae3494-b55c-44f4-aa34-5fc212ca6e1b)


 github.com/lesismal/nbio/taskpool.(*TaskPool).fork 主要来自闭包和闭包的时候参数的逃逸
![image](https://github.com/user-attachments/assets/0cab6840-0334-40a1-8777-488fd4e5bcd7)

github.com/lesismal/nbio.(*Conn).Execute
github.com/lesismal/nbio.(*Conn).execute (inline)
这两个主要来自闭包和job的逃逸,箭头标注的都会逃逸进堆，job的调用可以写一个函数，把job传进去,defer 也可以写成一个函数直接调用一下就可以了，没必要用闭包
![image](https://github.com/user-attachments/assets/4bf06237-e6bf-430d-9b56-77638e26cdb3)

github.com/lesismal/nbio/nbhttp/websocket.(*Conn).handleMessage 也是里面的闭包造成的

太多闭包看哈有办法优化一下不

**Comment by FJSDS** [comment]
![image](https://github.com/user-attachments/assets/18b6d31e-eebd-42da-b83d-d57fdfa332a1)
这两个地方没改到

**Comment by lesismal** [comment]
> github.com/lesismal/nbio/mempool.(*MemPool).Malloc 主要来自 Parse 和 writeFrame 分配的没有被重用到

mempool不是2^N那种size对齐, 无法保证每次的buffer都是够用的, Parse和writeFrame里可能有很多append, 所以这个不一定是没有被重用, 可能是分配并被放回后, 再次取出来size不够被append导致的

> 主要来自闭包和闭包的时候参数的逃逸

如果是临时变量那些, 因为每次对应的这些临时对象/参数不一样, 即使不是闭包, 放到队列等着异步去调用应该也要逃逸, 这个可以改改试试看

> 这两个地方没改到

"没改到" 是指什么?
sendfile_std 这个是 windows 下面的, 我在 mac vscode 下, 插件提示没用到, windows 主要是做兼容性接口相关的, 功能上不用管它

**Comment by FJSDS** [comment]
![image](https://github.com/user-attachments/assets/6881a191-43a7-4492-b8a0-9330fb25cef2)

**Comment by lesismal** [comment]
> ![image](https://github.com/user-attachments/assets/6881a191-43a7-4492-b8a0-9330fb25cef2)
> 

哦好，晚点改下

**Comment by lesismal** [comment]
@FJSDS  sendfile_std 里的 buffer 改了:  https://github.com/lesismal/nbio/commit/46d8fe4d95e3320dbc42ca53c9dfcea42f0263ca

**Comment by lesismal** [comment]
@FJSDS 
闭包的我试了下benchmark, 不太确定你说的方式是否能有效, 因为不是纯算法cpu消耗, 每次异步并发 runtime 情况不那么一致结果可能不一样, 所以我跑了多组, 分配和执行时间差距都很小, 而且没有哪种固定强于另一种的情况, 每次结果都可能有差别, 有时候闭包略好, 有时候func略好.

不知道我这个测试方法是否能说明问题, 如果有更好的方法可以发下, 我再试试看.

比如这组:
```sh
cpu: Apple M3 Max
# 这两个对比, 闭包性能和分配都好一点
BenchmarkRecoverFunc-14         	     523	   2263071 ns/op	  160192 B/op	   10001 allocs/op
BenchmarkRecoverClosure-14      	     552	   2039175 ns/op	  160171 B/op	   10001 allocs/op

# 这两个对比, 闭包性能好一点, 分配略弱一点
BenchmarkGoFunc-14       	     627	   2052048 ns/op	  160018 B/op	   10001 allocs/op
BenchmarkGoClosure-14    	     520	   2026070 ns/op	  160019 B/op	   10001 allocs/op
```

再比如这组:
```sh
cpu: Apple M3 Max
# 这两个对比, 闭包性能差一点, 分配好一点
BenchmarkRecoverFunc-14       	     541	   2066726 ns/op	  160355 B/op	   10001 allocs/op
BenchmarkRecoverClosure-14    	     612	   2068146 ns/op	  160221 B/op	   10001 allocs/op

# 这两个对比, 闭包性能好一点, 分配一样
BenchmarkGoFunc-14            	     610	   1968586 ns/op	  160018 B/op	   10001 allocs/op
BenchmarkGoClosure-14         	     583	   1959762 ns/op	  160018 B/op	   10001 allocs/op
```

代码:
```golang
// Copyright 2020 lesismal. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

package main

import (
	"log"
	"runtime"
	"sync"
	"testing"
	"unsafe"
)

var loopTimes = 10000

func Recover() {
	if err := recover(); err != nil {
		const size = 64 << 10
		buf := make([]byte, size)
		buf = buf[:runtime.Stack(buf, false)]
		log.Printf("execute failed: %v\n%v\n",
			err,
			*(*string)(unsafe.Pointer(&buf)),
		)
	}
}

func BenchmarkRecoverFunc(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := &sync.WaitGroup{}
		for j := 0; j < loopTimes; j++ {
			wg.Add(1)
			go func() {
				defer Recover()
				wg.Done()
			}()
		}
		wg.Wait()
	}
}

func BenchmarkRecoverClosure(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := &sync.WaitGroup{}
		for j := 0; j < loopTimes; j++ {
			wg.Add(1)
			go func() {
				defer func() {
					if err := recover(); err != nil {
						const size = 64 << 10
						buf := make([]byte, size)
						buf = buf[:runtime.Stack(buf, false)]
						log.Printf("execute failed: %v\n%v\n",
							err,
							*(*string)(unsafe.Pointer(&buf)),
						)
					}
				}()
				wg.Done()
			}()
		}
		wg.Wait()
	}
}

func FuncAndRecover(wg *sync.WaitGroup) {
	defer Recover()
	wg.Done()
}

func BenchmarkPoolGoFunc(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := &sync.WaitGroup{}
		for j := 0; j < loopTimes; j++ {
			wg.Add(1)
			go FuncAndRecover(wg)
		}
		wg.Wait()
	}
}

func BenchmarkPoolGoClosure(b *testing.B) {
	b.ReportAllocs()
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		wg := &sync.WaitGroup{}
		for j := 0; j < loopTimes; j++ {
			wg.Add(1)
			go func() {
				defer func() {
					if err := recover(); err != nil {
						const size = 64 << 10
						buf := make([]byte, size)
						buf = buf[:runtime.Stack(buf, false)]
						log.Printf("execute failed: %v\n%v\n",
							err,
							*(*string)(unsafe.Pointer(&buf)),
						)
					}
				}()
				wg.Done()
			}()
		}
		wg.Wait()
	}
}
```

**Comment by lesismal** [comment]
另外, pprof 别只看分配过的数量和size, 也看下正在使用中的, 看 gc 压力最好是 `GODEBUG=gctrace=1  go run test.go` 看下实际的压力如何

协程池这块, 毕竟并发度的size和异步queue的size都是可控的, 例如并发度1-10w, queue size 1-10w, 总共影响的数量是2-20w, 相比于标准库阻塞方式的Conn, 1M连接数就对应1M并发数量级的了, 对应的变量/对象数量也主要是跟这两种数量级对应的. 而协程池比如2-20w这种量级, 因为单个 job 执行完就可以被 gc 了, 所以同时存在的 gc 压力应该也没有 1M 数量级那么大.

而且并发度的size和queue的size都是我们自己可设置的, 如果不是大量耗时久的任务, 甚至并发度和queue size都可以更低, 因为任务快则协程很快就归还被复用了, 我本地做普通的echo压测百万连接的时候实际最高协程数量也只有几千

**Comment by FJSDS** [comment]
我有点麻了。是否分配到堆上还是要再研究研究，我下午写点示例测一测。我这么改之后分配总量更多了。。。。。。
```
func (c *Conn) Execute(job func()) bool {
	c.mux.Lock()
	if c.closed {
		c.mux.Unlock()
		return false
	}

	isHead := (len(c.jobList) == 0)
	c.jobList = append(c.jobList, job)
	c.mux.Unlock()

	// If there's no job running, run Engine.Execute to run this job
	// and new jobs appended before this head job is done.
	if isHead {
		c.execute()
	}
	return true
}

// MustExecute implements a similar function as Execute did,
// but will still execute or push the job to the
// back of the job list no matter whether Conn has been closed,
// it guarantees the job to be executed.
// This is used to handle the close event in nbio/nbhttp.
//
//go:norace
func (c *Conn) MustExecute(job func()) {
	c.mux.Lock()
	isHead := (len(c.jobList) == 0)
	c.jobList = append(c.jobList, job)
	c.mux.Unlock()

	// If there's no job running, run Engine.Execute to run this job
	// and new jobs appended before this head job is done.
	if isHead {
		c.execute()
	}
}

//go:norace
func (c *Conn) execute() {
	c.p.g.Execute(
		c.do,  /// 这里产生更多分配了。why? 下午写例子直接gcflags 看看为什么
	)
}

func (c *Conn) do() {
	i := 0
	var job func()
	for {
		c.mux.Lock()
		if len(c.jobList) == i {
			// reuse the slice
			c.jobList = c.jobList[0:0]
			c.mux.Unlock()
			return
		}
		// get next job
		job = c.jobList[i]
		// set nil to release the job and gc
		c.jobList[i] = nil
		c.mux.Unlock()
		i++
		func() {
			defer func() {
				if err := recover(); err != nil {
					const size = 64 << 10
					buf := make([]byte, size)
					buf = buf[:runtime.Stack(buf, false)]
					logging.Error(
						"conn execute failed: %v\n%v\n",
						err,
						*(*string)(unsafe.Pointer(&buf)),
					)
				}
			}()
			job()
		}()
	}
}
```

**Comment by lesismal** [comment]
> 我有点麻了。是否分配到堆上还是要再研究研究，我下午写点示例测一测。我这么改之后分配总量更多了。。。。。。

嗯嗯, 可以多试下

逃逸的本质应该是栈变量涉及异步的才需要, 闭包func/普通func/结构体func应该都是对应go程序的函数表里的地址, func本身的定义和内容应该是类似c程序里的Text/代码段, 相当于常量, 所以func的定义本身不应该有逃逸, 逃逸的应该只是那些需要被异步用到的变量/对象

**Comment by FJSDS** [comment]
> > 我有点麻了。是否分配到堆上还是要再研究研究，我下午写点示例测一测。我这么改之后分配总量更多了。。。。。。
> 
> 嗯嗯, 可以多试下
> 
> 逃逸的本质应该是栈变量涉及异步的才需要, 闭包func/普通func/结构体func应该都是对应go程序的函数表里的地址, func本身的定义和内容应该是类似c程序里的Text/代码段, 相当于常量, 所以func的定义本身不应该有逃逸, 逃逸的应该只是那些需要被异步用到的变量/对象


这玩意儿有点无解啊。 传成员函数，一样会分配，我想大概率代码变成了下面这样。本来成员函数展开实例自己就只是第一个参数

具体是不是这样得去分析go编译之后的代码了，我看他的汇编这里直接就有 call runtime.newobjects 的调用

先不纠结这里了
```
func (c *Conn) execute() {
	c.p.g.Execute(
		func(){
                    Conn-do-fm(c)
                }
	)
}
```

**Comment by FJSDS** [comment]
目前这个优化暂时告一段落吧。感谢作者辛苦付出

**Comment by lesismal** [comment]
> 目前这个优化暂时告一段落吧。感谢作者辛苦付出

感谢提出优质issue和分析，让我有机会进一步优化，提前祝大家新年快乐！
