### ISSUE TITLE
Request: websocket over tls example. 

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#5]
I need a run websocket framing on top of tls. I may get around to trying to implement in the next few days if I get some free time, but if you know how to implement quickly, that would be great.

Cheers.

**Comment by lesismal** [comment]
thanks for your feedback, already done, plz refer to the new examples:

https://github.com/lesismal/nbio#websocket-tls-examples

**Comment by acgreek** [comment]
thank you

**Comment by lesismal** [comment]
btw, if the application layer needs to rely on the execution order of messages, please execute directly or use customed goroutine pool to replace **svr.MessageHandlerExecutor** here:

https://github.com/lesismal/nbio/blob/master/examples/websocket_tls/server/server.go#L27

**Comment by lesismal** [comment]
> thank you

so welcome!
