### ISSUE TITLE
Feature request. Websocket compression

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#57]

**Comment by lesismal** [comment]
I do not want to support permessage-deflate before, because it's easy to be implemented by the application layer and not all ws clients support it and the server could decide to not compress.
But since you have proposed it, we make it on the road map.

**Comment by lesismal** [comment]
have implemented decompress for the server in a new branch:
https://github.com/lesismal/nbio/commit/9e4b46f185b7c0092724f0c931418314a920b3b7

examples: [server](https://github.com/lesismal/nbio/blob/compress/examples/websocket/server/server.go#L24), [client](https://github.com/lesismal/nbio/blob/compress/examples/websocket/client/client.go#L24)

I'll go on after some rest

**Comment by acgreek** [comment]
I ran auto_bahn against it. There are a few failures to work through but
good start.

**Comment by lesismal** [comment]
> I ran auto_bahn against it. There are a few failures to work through but good start.
>

Done with all the compression, and the newest Autobahn WebSocket Testsuite report:
https://lesismal.github.io/nbio/websocket

It cost 2 hours on my laptop, such a long run, my laptop has a fever 😂 ......

Please try it yourself and enjoy it 😄 .

**Comment by acgreek** [comment]
Thanks. I can't today but will check it out over the next few days. Next thing we need to do is a performance comparison between the most popular golang websocket apis. I can get this  done over the next few days. We also need to track and increase code coverage.

**Comment by lesismal** [comment]
> Next thing we need to do is a performance comparison between the most popular golang websocket apis
>
we may focus on some points:
1. the memory reduction in high concurrency service
2. not limited to a simple echo service, hard to explain, it's kind of about the cross-goroutine memory management in nbio, same buffer reuse in the same goroutine for each connection, and the different scheduling cost for different frameworks. for a low concurrency service, nbio runs no better than std, even worse than std.
