### ISSUE TITLE
can not reconnect on the tls websocket example 

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#7]
when I have the server running in another shell 

```
$ go run .
2021/05/13 17:11:43 connecting to wss://localhost:8888/wss
2021/05/13 17:11:43 write: hello world
2021/05/13 17:11:43 read : hello world
2021/05/13 17:11:44 write: hello world
2021/05/13 17:11:44 read : hello world
2021/05/13 17:11:45 write: hello world
2021/05/13 17:11:45 read : hello world
2021/05/13 17:11:46 write: hello world
2021/05/13 17:11:46 read : hello world
^Csignal: interrupt
$ go run .
2021/05/13 17:11:49 connecting to wss://localhost:8888/wss
2021/05/13 17:11:49 dial:EOF
exit status 1
$ go run .
2021/05/13 17:11:51 connecting to wss://localhost:8888/wss
2021/05/13 17:11:51 dial:EOF
exit status 1
```

the server is still running the in the other shell

I am on a mac if that helps

**Comment by acgreek** [comment]
Same issue with non-tls example

**Comment by acgreek** [comment]
and http client server

**Comment by acgreek** [comment]
same with echo example 
```
021/05/13 17:21:36.068 [INF] Gopher[NB] start
2021/05/13 17:21:36.073 [INF] success
$ go run  .
2021/05/13 17:21:37.866 [INF] Gopher[NB] start
2021/05/13 17:21:38.868 [ERR] timeout
$ go run  .
2021/05/13 17:21:40.715 [INF] Gopher[NB] start
2021/05/13 17:21:41.715 [ERR] timeout

```

**Comment by lesismal** [comment]
I’m working on it, but it will take some time because I don’t have a Mac Env. 

maybe it's caused by deadlock of kqueue event queue's mutex:
https://github.com/lesismal/nbio/blob/master/poller_kqueue.go#L93
https://github.com/lesismal/nbio/blob/master/poller_kqueue.go#L100
https://github.com/lesismal/nbio/blob/master/poller_kqueue.go#L107

you can debug your code on linux, it should work fine.

**Comment by lesismal** [comment]
strange， got erros here：

https://github.com/lesismal/nbio/runs/2581297246?check_suite_focus=true

```sh
2021/05/14 05:08:57.360 [INF] accept 000: 16, &{49376 [127 0 0 1] {0 0 0 [0 0 0 0] [0 0 0 0 0 0 0 0]}}, <nil>
2021/05/14 05:08:57.360 [INF] accept 000: 17, &{49377 [127 0 0 1] {0 0 0 [0 0 0 0] [0 0 0 0 0 0 0 0]}}, <nil>
2021/05/14 05:08:57.361 [INF] accept 000: 15, &{49378 [127 0 0 1] {0 0 0 [0 0 0 0] [0 0 0 0 0 0 0 0]}}, <nil>
2021/05/14 05:08:57.361 [ERR] accept failed 222: bad file descriptor
2021/05/14 05:08:57.361 [INF] accept 000: 15, &{49379 [127 0 0 1] {0 0 0 [0 0 0 0] [0 0 0 0 0 0 0 0]}}, <nil>
2021/05/14 05:08:57.361 [ERR] accept failed 333: bad file descriptor
2021/05/14 05:08:57.361 [INF] accept 000: 15, &{49380 [127 0 0 1] {0 0 0 [0 0 0 0] [0 0 0 0 0 0 0 0]}}, <nil>
2021/05/14 05:08:57.361 [INF] accept 000: 22, &{49381 [127 0 0 1] {0 0 0 [0 0 0 0] [0 0 0 0 0 0 0 0]}}, <nil>
2021/05/14 05:08:57.361 [INF] accept 000: 24, &{49382 [127 0 0 1] {0 0 0 [0 0 0 0] [0 0 0 0 0 0 0 0]}}, <nil>
```

I may try to use std's listener instead of syscall.Accept

**Comment by lesismal** [comment]
I replaced the syscall.Aceppt with std's listener.Accept， I test the result by github action, it seems a little better than before, but still not sure whether the problem has been solved, please update and try again.

**Comment by acgreek** [comment]
sorry no, getting same results with version 965217f

**Comment by acgreek** [comment]
running the echo server in a docker container works

**Comment by lesismal** [comment]
> running the echo server in a docker container works

is it ok on linux?

**Comment by lesismal** [comment]
because most of the high concurrency service running on linux, I'm considering remove kqueue and use std instead as windows did.

**Comment by acgreek** [comment]
I'm fine with that, I just use my mac for rapid development for deployment to linux

**Comment by lesismal** [comment]
> I'm fine with that, I just use my mac for rapid development for deployment to linux

maybe more people use mac, removing kqueue helps debugging.
it's really difficult for me to debug for mac env by github action, and I don't wanna a mac because of games on windows :joy:

**Comment by lesismal** [comment]
please try with the newest version: https://github.com/lesismal/nbio/commit/f00824e08202c229630b305d5049db1eed888438

**Comment by acgreek** [comment]
sorry, same behavior

**Comment by lesismal** [comment]
could you provide some error logs?

**Comment by acgreek** [comment]
this via the websocket tls example on my macbook

```
$ go run .
2021/05/17 09:34:19 connecting to wss://localhost:8888/wss
2021/05/17 09:34:19 read : hello world
2021/05/17 09:34:19 read : hello world
2021/05/17 09:34:19 read : hello world
2021/05/17 09:34:19 read : hello world
2021/05/17 09:34:19 read : hello world
^Csignal: interrupt
$ go run .
2021/05/17 09:34:25 connecting to wss://localhost:8888/wss
2021/05/17 09:34:25 dial:read tcp 127.0.0.1:56992->127.0.0.1:8888: read: connection reset by peer
exit status 1
$ git log -1
commit 9e6c7c15aa4dc32c41a014383c87046a7ed8c5cd (HEAD)
Author: lesismal <40462947+lesismal@users.noreply.github.com>
Date:   Sun May 16 22:18:06 2021 +0800

    - tls: disable sendfile
    - change default read buffer size to 2k
```

**Comment by lesismal** [comment]
I have annotated bsd and use std instead, will try to fix this problem when I get a mac someday.

**Comment by acgreek** [comment]
I walked it via the debugger. On the second accept, Setting the connection to nonblocking fails 

/usr/local/go/src/internal/poll/sys_cloexec.go:31

```
	if err = syscall.SetNonblock(ns, true); err != nil {
		CloseFunc(ns)
		return -1, nil, "setnonblock", err
	}
```

the first time this code is executed, connection succeeds with ns value '27'. The next time, ns is '28'  and err is returned 

```
2021/05/17 15:05:21.832 [ERR] Poller[NB_LISTENER_0] Accept failed: accept tcp [::]:8888: setnonblock: bad file descriptor, exit...
2021/05/17 15:05:21 dial:EOF
```

**Comment by acgreek** [comment]
I think I found the problem. You have an infinite loop on func (p *poller) deleteEvent(fd int) , you trigger the readWriteLoop to call c.closeWithError(err), which then again calls func (p *poller) deleteEvent(fd int)

**Comment by acgreek** [comment]
created PR with solution

**Comment by lesismal** [comment]
nice job, thank you so much!
