### ISSUE TITLE
Concurrency issues with NewServerTLS()

### ISSUE THREAD

**Issue by mehrvarz** [lesismal/nbio#70]
In some cases my server may want to disconnect an existing websocket connection. It is a case that does not show up in any of your examples. Imagine you would like to do the following [here](https://github.com/lesismal/nbio/blob/3e0fa5b5ac75d820fe2c4106fc473a0d61ba8946/examples/websocket_1m/server/server.go#L33) 
```
if qps==1000 {
    wsConn.Close()
}

```
If I do something like this, the connection will get closed - the client will receive an onClose event. But wsConn.Close() then hangs. Any idea what could be causing this?

**Comment by lesismal** [comment]
> In some cases my server may want to disconnect an existing websocket connection. It is a case that does not show up in any of your examples. Imagine you would like to do the following [here](https://github.com/lesismal/nbio/blob/3e0fa5b5ac75d820fe2c4106fc473a0d61ba8946/examples/websocket_1m/server/server.go#L33)
> 
> ```
> if qps==1000 {
>     wsConn.Close()
> }
> ```
> 
> If I do something like this, the connection will get closed - the client will receive an onClose event. But wsConn.Close() then hangs. Any idea what could be causing this?

I tried with log in the server like this:
```golang
println("---- close 111")
wsConn.Close()
println("---- close 222")
```
output:
```sh
---- close 111
---- close 222
```

it does not hang up.

would you please provide a full example to reproduce that? I guess there may be a deadlock in your OnClose handler.

**Comment by acgreek** [comment]
Sorry, we'll look into this. Can you please provide the OS you ran this code on?

**Comment by lesismal** [comment]
> you please provide the OS you r

I tried on windows and linux, it runs fine. do you reproduce it on macos?

**Comment by mehrvarz** [comment]
> I guess there may be a deadlock in your OnClose handler.

Sounds very reasonable. However, I see one case where everything works right:

```
wsConn.Close() ...
OnClose
wsConn.Close() done

```
And another, where wsConn.Close() does not return. And here OnClose is also not called:

```
wsConn.Close() ...

```
I'm running Linux with Go 1.16.6. - A quick question. Can you think of cases, where it would make sense to shield calls to conn.WriteMessage() with a mutex? Or would this never really make sense? Thank you.

**Comment by lesismal** [comment]
> And another, where wsConn.Close() does not return. And here OnClose is also not called:

Please provide the code that can reproduce this case.

> I'm running Linux with Go 1.16.6. - A quick question. Can you think of cases, where it would make sense to shield calls to conn.WriteMessage() with a mutex? Or would this never really make sense? Thank you.

Concurrency writes in multi goroutines need that mutex.
Although we can handle all the messages by pushing them into a chan then consume them in another goroutine, but we don't want to limit users to this style only. We want to provide the basic safe implementation, the users decide how to use it.

**Comment by mehrvarz** [comment]
The problem appears to occur with nbhttp.NewServerTLS() only. When I use nbhttp.NewServer() with nginx in front as tls proxy, everything is working fine. I use the same websocket handler (serveWs) for both servers. And I use the same client, only with a different port number. - In other words, the code in my websocket handler does not run correctly when run with nbhttp.NewServerTLS().

```
if *wsPort>0 {
	wsAddr := fmt.Sprintf(":%d", *wsPort)
	mux := &http.ServeMux{}
	mux.HandleFunc("/ws", serveWs)
	svr := nbhttp.NewServer(nbhttp.Config{
		Network: "tcp",
		Addrs: []string{wsAddr},
		MaxLoad: 1000000,
		ReleaseWebsocketPayload: true,
	}, mux, nil)
	err = svr.Start()
	// taking care off errors
	defer svr.Stop()
}
if *wssPort>0 {
	cer, err := tls.LoadX509KeyPair("fullchain.pem", "privkey.pem")
	// taking care off errors
	tlsConfig := &tls.Config{Certificates: []tls.Certificate{cer}}
	tlsConfig.BuildNameToCertificate()
	wssAddr := fmt.Sprintf(":%d", *wssPort)
	mux := &http.ServeMux{}
	mux.HandleFunc("/ws", serveWs)
	svrs := nbhttp.NewServerTLS(nbhttp.Config{
		Network: "tcp",
		Addrs: []string{wssAddr},
		MaxLoad: 1000000,
		ReleaseWebsocketPayload: true,
	}, mux, nil, tlsConfig)
	err = svrs.Start()
	// taking care off errors
	defer svrs.Stop()
}
```

Btw, I wasn't able to try out this performance improving thing. I think I couldn't find ParserExecutor.

```
// to improve performance
//parserPool := taskpool.NewFixedPool(runtime.NumCPU()*4, 1024)
//svrs.ParserExecutor = parserPool.GoByIndex
```

**Comment by lesismal** [comment]
> ParserExecutor

Which version are you using? Please update to the latest version of [nbio](https://github.com/lesismal/nbio) and [llib](https://github.com/lesismal/nbio), which is currently v1.1.5 and  v1.0.8. 

We have fixed some llib bugs about tls. If you are using an older version, you may be affected by this bug.

Due to recent optimization considerations that concurrency consistency and performance improvement are not obvious, server.ParserExecutor is no longer supported.

So, please try with the latest versions and tell us whether it works.

**Comment by mehrvarz** [comment]
> Which version are you using?

The issue occurs with NewServerTLS() in v1.1.5 and v1.0.8.

**Comment by lesismal** [comment]
> > Which version are you using?
> 
> The issue occurs with NewServerTLS() in v1.1.5 and v1.0.8.

The latest version has not support server.ParserExecutor.

If you are sure about the version is the latest, would you please provide the full example to reproduce this issue?

**Comment by lesismal** [comment]
> > Which version are you using?
> 
> The issue occurs with NewServerTLS() in v1.1.5 and v1.0.8.

I reproduced this bug with a tls server, and have fixed it, for more details:
https://github.com/lesismal/llib/pull/8

Please update to nbio v1.1.7 and llib 1.0.9 to check is it working fine.

Thank you for your feedback :heart::heart::heart:.

**Comment by mehrvarz** [comment]
> The latest version has not support server.ParserExecutor.

I have never used ParserExecutor. It is unrealted to the described issue.

> I'll check it with tls example.

I will try to provide you with a small example that will expose the issue. I think the key is to use a dedicated client, that will echo data back to your echo server... 

```
wsConn.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
	// echo
	c.WriteMessage(messageType, data)
	if *print {
		fmt.Println("OnMessage:", messageType, string(data))
	}
	c.SetReadDeadline(time.Now().Add(nbhttp.DefaultKeepaliveTime))
})

```
... so that you get some fast data exchange going. Make the client emulate many parallel sessions and make the server do "surprising" things every X loops, like closing a channel, etc. Activate ping/pong in the background. Run this with and without TLS. This should expose the issue quickly.

**Comment by mehrvarz** [comment]
> I reproduced this bug with a tls server, and have fixed it, for more details:
> [lesismal/llib#8](https://github.com/lesismal/llib/pull/8)
> 
> Please update to nbio v1.1.7 and llib 1.0.9 to check is it working fine.
> 
> Thank you for your feedback .

That was quick. Trying it out right now...

**Comment by lesismal** [comment]
> > The latest version has not support server.ParserExecutor.
> 
> I have never used ParserExecutor. It is unrealted to the described issue.
> 

Because you mentioned svr.ParserExecutor, I just want to make sure the version you were using, the svr.ParserExecutor does not matter with this issue if you are sure about the version.

> That was quick. Trying it out right now...
>

OK, waiting for your information.

**Comment by mehrvarz** [comment]
Problem is gone. Thank you very much. Well done!!
I have a related questions. Maybe two. Would you mind if I ask them below?

**Comment by lesismal** [comment]
> Problem is gone. Thank you very much. Well done!!
> 

You are welcome!

> I have a related questions. Maybe two. Would you mind if I ask them below?
>

Welcome to communicate, just talk about it.

**Comment by mehrvarz** [comment]
Thank you. First a little background: I am using a benchmark tool to simulate connecting users. This tool looks at the duration it takes for a single connect sequence to complete (xhr + ws-upgrade + 1st ws-message exchange = 3 roundtrips) and it generates more new clients based on that number (or less). The tool tries to _not_ kill the server, but to find the "sweatspot" for number of new users per second. ATM I get sustained ~500 cps without TLS, and ~80 cps over TLS. This is on a fairly small box. But the actual numbers don't matter so much. What matters is how the numbers change, when some performance optimization is applied.

Q1: Did you ever consider implementing a zero-copy upgrader? I think it can improve performance noticeably. I am however not sure if it makes a lot of difference if TLS is used. Q2: Do you see room for faster TLS?

**Comment by lesismal** [comment]
> Q1: Did you ever consider implementing a zero-copy upgrader? I think it can improve performance noticeably. I am however not sure if it makes a lot of difference if TLS is used.
>

First of all, we need to clarify your definition of zero copy:
1. between kernel and user space
2. between tcp layer and TLS layer and http layer

If you mean 1 and to implement poller with MSG_ZEROCOPY, it's more difficult to implement, and it may not guarantee higher performance in general scenarios, because of its cost for page mapping and lock or other operations in kernel when data size is small.

If you mean 2, and not considering the compatibility of std, we can implement the parser like fasthttp: it get the http request's fieldes from the raw read buffer's sub buffer, no need to convert sub buffer's to new strings or new buffers. But there are still other problems for poller framework, because when we read data and get a request, we usually need to handle it in another goroutine, else if there are io or other things we do may blocked, the poller goroutine would be blocked and then, the service would become slow. So, if we want to implement zero-copy and must pass the request to another goroutine, we must use different buffers for reading each request, hard to decide the size of the buffer and hard to manage the life cycle of the buffer which would lead to a lower performance in a general business.

In addition, for TLS, the most time cost is the RTT of multiple data exchanges during the handshake, rather than the data copy. And even if it is not zero copy, the amount of data is not too large for both TLS and NON-TLS during upgrade, the improvement that zero copy can bring may not be much.

I may do some research for MSG_ZEROCOPY, if you like to do that together, pr is so welcomed!

**Comment by lesismal** [comment]
> Q2: Do you see room for faster TLS?
>

I copied go1.6 std's TLS code and modify it to support non-blocking, some of std's code is a little bit performance unfriendly, It still has some room for improvement, but is too complicated, and it may even need to implement from zero to get a larger performance improvement, I currently don't have so much energy to do that. 
But I am still taking time to optimize the performance of http/websocket based on pprof.

**Comment by lesismal** [comment]
BTW, compared with golang std:

If the number of connections is not so large and they are all CPU-consuming requests, std does not need to switch goroutines when processing one or more consecutive messages on a connection, and the logic of synchronous parsing is simpler, and the response time of poller framework has no advantage. 
If many requests are IO-consuming, the goroutine of std will also be scheduled because of IO, then the performance advantage of poller framework may be relatively improved.

The main advantages of poller framework are:
1. Save a lot of memory when high concurrency
2. Save scheduling costs when the number of goroutines is large

So, if the number of connections is large, we get both better performance and stability.
The poler framework enables hardware of the same specification to serve a larger number of connections.

**Comment by mehrvarz** [comment]
> 1. Save a lot of memory when high concurrency

Can confirm! My server consumes 20 - 40 bytes per user (bytes!), depending on how you want to count it. I am a little afraid of mentioning it bc these numbers look wrong :o)

Does 500 vs 80 transactions per second over TLS not shock you? I mean the relative difference, not the abs numbers. I seem to be unable to get much over 80, even though my server is only at 30-40% cpu load. Does TLS blow up traffic volume and/or the # of roundtrips 6 fold?

One thing I just noticed: I can use any go library for the websocket client and I can do websocket in JS in Chrome browser without any issues. However, when I try to use the same JS-client in Firefox, I get this on the server: "Upgrade err=websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header" I have not checked the headers yet. Will do that next.

**Comment by lesismal** [comment]
> Can confirm! My server consumes 20 - 40 bytes per user (bytes!), depending on how you want to count it. I am a little afraid of mentioning it bc these numbers look wrong :o)

poller framework reduces the memory of the goroutine stack, but not the size of your application layer's buffer.

> Does 500 vs 80 transactions per second over TLS not shock you? I mean the relative difference, not the abs numbers. I seem to be unable to get much over 80, even though my server is only at 30-40% cpu load. 
>

More poller may help to improve TLS handshake but that's not a promise. For example:
```golang
svr := nbhttp.NewServer(nbhttp.Config{
	Network: "tcp",
	Addrs:   addrs,
	NPoller: runtime.NumCPU() * 2, // or other num you want to test
}, router, nil)
```

> Does TLS blow up traffic volume and/or the # of roundtrips 6 fold?
>

Only the handshake makes more RTT, there will be only encryption-related cost but not RTT aftter handshake, so we can still get 100k-1200k QPS here(and you should notice that both the server and the client are on the same VM in my test, if there's only the server in this VM, the server would performance a higher QPS):
https://github.com/lesismal/nbio/pull/62#issuecomment-881221338

**Comment by lesismal** [comment]
> One thing I just noticed: I can use any go library for the websocket client and I can do websocket in JS in Chrome browser without any issues. However, when I try to use the same JS-client in Firefox, I get this on the server: "Upgrade err=websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header" I have not checked the headers yet. Will do that next.
> 
> Edit: Maybe FF wants it to be all lowercase?
> 
> https://github.com/lesismal/nbio/blob/3e0fa5b5ac75d820fe2c4106fc473a0d61ba8946/nbhttp/websocket/upgrader.go#L143

It seems no problem with uppercase:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/101

And gorillia/websocket use uppercase too:
https://github.com/gorilla/websocket/blob/master/server.go#L217

**Comment by mehrvarz** [comment]
> It seems no problem with uppercase:

Sorry, I got it wrong. I thought FF is complaining about nbio. But it is nbio complaining about FF. So nbio thinks there is something wrong with the user agent and it is putting out this err msg. Do you have a JS websocket client to test with?

**Comment by mehrvarz** [comment]
> we can still get 100k-1200k QPS here(and you should notice that both the server and the client are on the same VM in my test, if there's only the server in this VM, the server would performance a higher QPS):

My numbers are between to servers in different cities. Different story.

**Comment by lesismal** [comment]
> > It seems no problem with uppercase:
> 
> Sorry, I got it wrong. I thought FF is complaining about nbio. But it is nbio complaining about FF. So nbio thinks there is something wrong with the user agent and it is putting out this err msg. Do you have a JS websocket client to test with?

it seems like a header parsing bug, I'm working on it.

**Comment by lesismal** [comment]
> Do you have a JS websocket client to test with?

reproduced and fixed it : https://github.com/lesismal/nbio/commit/b874deea3dd2d6edd25db76fe3bda2e49cceeda3

please try with v1.1.8

**Comment by mehrvarz** [comment]
> please try with v1.1.8

The browsers are working fine now. You really have full control of it :fireworks:

**Comment by lesismal** [comment]
> > please try with v1.1.8
> 
> The browsers are working fine now. You really have full control of it 🎆

Thank you! It's my pleasure!
