### ISSUE TITLE
Issue running a websocket server on Mac osX 11.2.3

### ISSUE THREAD

**Issue by nicoroy2561** [lesismal/nbio#76]
When I try running a server with the default configuration (copied the code from the many examples you provided), the following is printed to the console on my mac:

```
2021/08/04 23:52:24.632 [INF] Gopher[NB] start listen on: [":8001"]
2021/08/04 23:52:24.632 [ERR] Poller[NB_LISTENER_0] Accept failed: accept tcp [::]:8001: use of closed network connection, exit...
```

..and the server is effectively not active / can't be reached. I tried also using different ports, specifying "localhost" and so on.
Any idea on what might be going wrong here?

**Comment by lesismal** [comment]
> ```
> 2021/08/04 23:52:24.632 [ERR] Poller[NB_LISTENER_0] Accept failed: accept tcp [::]:8001: use of closed network connection, exit...
> ```

Usually, we get this log when the server Stop/Shutdown.

svr.Start() is not a blocking interface{}, please make sure not Stop/Shutdown your server before you really want.
Or please provide your server's code, we'll check it.

**Comment by nicoroy2561** [comment]
Oh, silly me.
Now I realise why you put a loop after every instance - my bad. 
Sorry for the silly question and thank you for your help :)

**Comment by lesismal** [comment]
> Oh, silly me.
> Now I realise why you put a loop after every instance - my bad.
> Sorry for the silly question and thank you for your help :)

You are welcome! :smile:
