### ISSUE TITLE
is websocket.Conn.SetSession goroutine safe

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#77]
If I call websocket.Conn.SetSession() in the websocket.Upgrade.openHandler, is that guarantied to be safe; IE websocket.Update.onMessageHandler will not be called until after the openHandler completes such that if in onMessagHandler I call websocket.Conn.Session() I don't worry have to worry about it not being set yet?

It would be nice if such contracts were clearly documented in function header comments. I use VSCode, and the code completion provides the function header comments in the completion popup box so that if the comments stated it, I wouldn't have to review the code.

Please consider going through the code and adding more description to functions; their expected use case and any special consideration/protections/contracts. 
<img width="578" alt="Screen Shot 2021-08-05 at 9 41 40 AM" src="https://user-images.githubusercontent.com/1256210/128360256-61901709-9c0f-4353-ba8c-f0fa9334db9f.png">

**Comment by lesismal** [comment]
It should be safe by v1.1.21, more details: https://github.com/lesismal/nbio/issues/75#issuecomment-893184802

Now the http upgrade message and all websocket messages of the same connection are handled one-by-one.

You can add a `sleep` and logs like this to check it:
```golang
u.conn = newConn(u, conn, nbc.Hash(), false, subprotocol, compress)
u.Server = parser.Server
u.conn.Server = parser.Server

time.Sleep(time.Second)
fmt.Println("--- 111 before onOpenHandler")

if u.openHandler != nil {
	u.openHandler(u.conn)
}
```

and
```golang
u.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
	// echo
	fmt.Println("--- 222 OnMessage:", messageType, string(data), len(data))
	c.WriteMessage(messageType, data)
})
```

I get output like this:
```sh
# go run ./server
2021/08/05 22:06:16.902 [INF] Gopher[NB] start listen on: [":8888"]
--- 111 before onOpenHandler
OnOpen: [::1]:41778
--- 222 OnMessage: 1 hello 5 // the first websocket message will not be passed to the onMessagHandler until the http handler for upgrade is over
--- 222 OnMessage: 1 hello 5
--- 222 OnMessage: 1 hello 5
--- 222 OnMessage: 1 hello 5
--- 222 OnMessage: 1 hello 5
--- 222 OnMessage: 1 hello 5
--- 222 OnMessage: 1 hello 5
OnClose: [::1]:41778 <nil>
```

**Comment by lesismal** [comment]
> It would be nice if such contracts were clearly documented in function header comments. I use VSCode, and the code completion provides the function header comments in the completion popup box so that if the comments stated it, I wouldn't have to review the code.

Upgrader.OnOpen is not a must.
We can still do the init things in the http upgrade handler like this:
```golang
func onWebsocket(w http.ResponseWriter, r *http.Request) {
	upgrader := newUpgrader()
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		panic(err)
	}
	wsConn := conn.(*websocket.Conn)
	wsConn.SetReadDeadline(time.Time{})

        endpointConn := endpoint.New(...)

	fmt.Println("OnOpen:", wsConn.RemoteAddr().String())
}
```

Since most people are accustomed to the synchronous code sequence scheme of the go standard library, explaining too much about the asynchronous execute order will make more people confused.
And most important, It’s a little difficult for me to make this clear in English :joy:. Would you like to help to make some comments? I can explain the logic that you want to know.
