### ISSUE TITLE
autobahn tests failures

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#78]
seeing a lot of crashes on the autobahn test suite

```
[nbio-autobahn]: Running test case ID 9.4.4 for agent non-tls from peer tcp4:127.0.0.1:9998
[nbio-server]:   2021/08/10 12:37:47.210 [ERR] taskpool call failed: runtime error: invalid memory address or nil pointer dereference
[nbio-server]:   goroutine 7 [running]:
[nbio-server]:   github.com/lesismal/nbio/taskpool.call.func1()
[nbio-server]:          /go/src/github.com/lesismal/nbio/taskpool/caller.go:19 +0xc7
[nbio-server]:   panic(0x6bfaa0, 0x8ec800)
[nbio-server]:          /usr/local/go/src/runtime/panic.go:965 +0x1b9
[nbio-server]:   github.com/lesismal/nbio/nbhttp/websocket.(*Conn).writeFrame(0x0, 0x102, 0xc004243000, 0x1000, 0x1000, 0x0, 0x766d60, 0xc00004ace0)
[nbio-server]:          /go/src/github.com/lesismal/nbio/nbhttp/websocket/conn.go:318 +0x192
[nbio-server]:   github.com/lesismal/nbio/nbhttp/websocket.(*Conn).WriteFrame(...)
[nbio-server]:          /go/src/github.com/lesismal/nbio/nbhttp/websocket/conn.go:274
[nbio-server]:   github.com/lesismal/nbio/examples/websocket/server_autobahn.newUpgrader.func1(0x0, 0x460002, 0xc004243000, 0x1000, 0x1000)
[nbio-server]:          /go/src/github.com/lesismal/nbio/examples/websocket/server_autobahn/server.go:23 +0x88
[nbio-server]:   github.com/lesismal/nbio/nbhttp/websocket.newConn.func6(0x0, 0x50002, 0xc004243000, 0x1000, 0x1000)
[nbio-server]:          /go/src/github.com/lesismal/nbio/nbhttp/websocket/conn.go:409 +0x6d
[nbio-server]:   github.com/lesismal/nbio/nbhttp/websocket.(*Upgrader).handleDataFrame.func1()
[nbio-server]:          /go/src/github.com/lesismal/nbio/nbhttp/websocket/upgrader.go:408 +0x6d
[nbio-server]:   github.com/lesismal/nbio/nbhttp.(*Parser).Execute.func1()
[nbio-server]:          /go/src/github.com/lesismal/nbio/nbhttp/parser.go:120 +0x62
[nbio-server]:   github.com/lesismal/nbio/taskpool.call(0xc003082048)
[nbio-server]:          /go/src/github.com/lesismal/nbio/taskpool/caller.go:23 +0x5d
[nbio-server]:   github.com/lesismal/nbio/taskpool.(*fixedRunner).taskLoop(0xc000056300)
[nbio-server]:          /go/src/github.com/lesismal/nbio/taskpool/fixedpool.go:41 +0x16d
[nbio-server]:   created by github.com/lesismal/nbio/taskpool.NewFixedPool
[nbio-server]:          /go/src/github.com/lesismal/nbio/taskpool/fixedpool.go:125 +0x167
[nbio-server]:   
[nbio-server]:   
```

**Comment by acgreek** [comment]
with your latest changes, I am no longer seeing the crash but I am seeing a few test failures on the tls

**Comment by acgreek** [comment]
also some tests are failing

**Comment by lesismal** [comment]
try the latest

**Comment by acgreek** [comment]
I had same problem pushing to github earlier

**Comment by lesismal** [comment]
seems still some failure with the latest, gonna sleep, I'll continue with it next Asia day time.

**Comment by acgreek** [comment]
yeah slightly better, not seeing the panics but the message corruption is still an issue

I suggest we make autobahn a requirement before tagging for release

**Comment by lesismal** [comment]
> yeah slightly better, not seeing the panics but the message corruption is still an issue

seem like the Upgrader.Read bug, about data frame handler and different opcode type.

> I suggest we make autobahn a requirement before tagging for release

good idea! let's make it.

**Comment by acgreek** [comment]
it appear that the last version where the all the 5.* tests pass is 1.1.2 git hash 6d0ce8f

**Comment by acgreek** [comment]
yeah, all tests [1-9].* pass at that revision

**Comment by acgreek** [comment]
I kept nbio at tag v1.1.2 but updated llib to the latest and all tests pass. Our problem code is likely all in nbio

**Comment by lesismal** [comment]
I run the autobahn and it passed all the tests.
The major problem for the previous version is about the Ping/Pong/Close messages that we handle the messages with the read buffer directly but do not make a copy, so if the next frame come before we have finished the handler logic, and cover the old data of the buffer, the buffer becomes dirty, then something went wrong. These lines which make a copy for the body fixed the failures of autobahn:
https://github.com/lesismal/nbio/blob/master/nbhttp/websocket/upgrader.go#L333

And I also did some other details optimization, more details: https://github.com/lesismal/nbio/commit/f403ab639da82757475eb041c4ff61d671db7076

Please try the master branch with the latest commit, if you pass all the tests too, we'll publish a new version.

**Comment by acgreek** [comment]
Thanks so much. I'm probably not going to get around to looking at this until next Monday so if you got 100% tests passing, i'm ok with cutting another release.

**Comment by lesismal** [comment]
> Thanks so much. I'm probably not going to get around to looking at this until next Monday so if you got 100% tests passing, i'm ok with cutting another release.

Ok, I am also busying on [arpc](https://github.com/lesismal/arpc) and some [benchmark things](https://github.com/cloudwego/kitex-benchmark) about it.

I'm not hurrying to release the latest, let's do it a few days later.

**Comment by acgreek** [comment]
all tests pass, thank you
