### ISSUE TITLE
frequent disconnects when more than one connection 

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#8]
I'm using the websocket over tls on linux and it appears to work ok when the server only has one client connected, but with more than one I am seeing, read timeout errors on the server 

 OnClose: 172.20.0.1:62684 read timeout

all clients are performing the same transaction. Every half a second they send a message to the server than the server responds with acknowledgment

**Comment by lesismal** [comment]
would you please provide the full code, I'll try it

**Comment by acgreek** [comment]
I provided a pull request

**Comment by acgreek** [comment]
did it reproduce for you?

**Comment by lesismal** [comment]
> did it reproduce for you?

yes I do. it's because we need to reset the readdeadline when we recv a new websocket message.

and there's another problem for tls that I ignored before:
```txt
nbhttp and nbio.Conn use mempool by default, but llib does not use mempool. when nbio.Conn passes data to llib/tls and then to websocket, the memory becomes dirty. 
```
I will temporarily ban mempool to ensure that the memory is clean in data flow.

I'll pr later.

**Comment by acgreek** [comment]
> > did it reproduce for you?
> 
> yes I do. it's because we need to reset the readdeadline when we recv a new websocket message.

Why is the ReadDeadline only a problem when there is more than one connection?

> 
> and there's another problem for tls that I ignored before:
> 
> ```
> nbhttp and nbio.Conn use mempool by default, but llib does not use mempool. when nbio.Conn passes data to llib/tls and then to websocket, the memory becomes dirty. 
> ```
> 
> I will temporarily ban mempool to ensure that the memory is clean in data flow.
> 
> I'll pr later.

**Comment by lesismal** [comment]
you should get the timeout errors when the c/s running for 120s, because the server SetReadDeadline to 120s by default onopen:
https://github.com/lesismal/nbio/blob/master/nbhttp/server.go#L41
https://github.com/lesismal/nbio/blob/master/nbhttp/server.go#L306
https://github.com/lesismal/nbio/blob/master/nbhttp/server.go#L396

reset it on each websocket message, then solve it:
https://github.com/lesismal/nbio/blob/master/examples/websocket_tls/server/server.go#L33

now I have run the new example for more than 5 minutes and it does not stop.

please try again

**Comment by acgreek** [comment]
works so far, thank you. This module is exactly what I need. I suggest you add some unit tests. If I get some free time, I'll try to help

**Comment by lesismal** [comment]
> Why is the ReadDeadline only a problem when there is more than one connection?

one connection would also be timeout if you wait for enouth time.

it doesn’t seem to be triggered precisely by the timeout arg, but has a certain error range, I'm not sure about it by now, have to sleep and will check it again the next Asia daytime.

**Comment by lesismal** [comment]
> works so far, thank you. This module is exactly what I need. I suggest you add some unit tests. If I get some free time, I'll try to help

Already did some unit test [here](https://github.com/lesismal/nbio/blob/master/nbio_test.go), but as you said, it's really not enough.
There are too many critical points that are very difficult to write unitest, and there was only myself maintaining this repo. http 1.x, tls, and websocket has cost me a lot of time, and it is very difficult to debug the mac env every time :joy:.
There is plan to support http 2.0 before, but websocket is sufficient 
 enough for the protocol interaction of api type. And as a static resource server, the single connection of 2.0 is really a performance regression, so I don’t plan to support http 2.0 any more.

That’s great news for me if you have time to help,  I really hope and appreciate it, thank you for your support!

**Comment by lesismal** [comment]
> it doesn’t seem to be triggered precisely by the timeout arg, but has a certain error range, I'm not sure about it by now, have to sleep and will check it again the next Asia daytime.

timer runs fine
