### ISSUE TITLE
Is it possible to set Headers on client-side before Websocket is established?

### ISSUE THREAD

**Issue by tigrannajaryan** [lesismal/nbio#80]
Hi, thank you for this great library.

I need to set an "Authorization" header on the client side when the client dials to the server (establishes the HTTP connection). I checked the examples and searched the docs but cannot seem to find a way to do it.

Is there any way to do it?

Just for reference to illustrate the point here is how the client side header can be set with Gorilla for example:
```go
import "github.com/gorilla/websocket"

// ...

func connect() error {
	header := http.Header{}
	header["Authorization"] = []string{"myauthstring"}

	var resp *http.Response
	dialer := *websocket.DefaultDialer
	c.conn, resp, err = dialer.Dial("http://example.com/mywebsocketpath", header)
	if err != nil {
		if resp != nil {
			fmt.Printf("Server responded with status=%v\n", resp.Status)
		}
		return err
	}
}
```

I am looking for the equivalent capability in nbio.

Note: on the server side I am already able to check the value of the header this way and it works fine with nbio:
```go
import "github.com/lesismal/nbio/nbhttp/websocket"

// ...

// somewhere in my init func:
mux := &http.ServeMux{}
mux.HandleFunc("/mywebsocketpath", srv.wsHandler)

// and here is the handler
func myWsHandler(w http.ResponseWriter, r *http.Request) {

	auth := r.Header["Authorization"]
	// check auth header here.

	upgrader := websocket.NewUpgrader()
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Fatal("WS Server upgrade:", err)
	}
        // use websocket conn here.
}
```

**Comment by lesismal** [comment]
Thank you for your feedback!

### 1. Do you mean setting the response header? 

Now we can do it like this as gorilla/websocket does:
```golang
func myWsHandler(w http.ResponseWriter, r *http.Request) {
	auth := r.Header["Authorization"]
	// check auth header here.

        responseHeaders = http.Header{}
        responseHeaders.Add(key, value)

	upgrader := websocket.NewUpgrader()
	conn, err := upgrader.Upgrade(w, r, responseHeaders)
	if err != nil {
		log.Fatal("WS Server upgrade:", err)
	}
        // use websocket conn here.
}
```

Maybe we'll support to response the Writer header as below, but seems no necessory compared with the way of gorilla/websocket:
```golang
func myWsHandler(w http.ResponseWriter, r *http.Request) {
	auth := r.Header["Authorization"]
	// check auth header here.

        w.Header().Add(key, value) // this header will be encoded during Upgrade

	upgrader := websocket.NewUpgrader()
	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Fatal("WS Server upgrade:", err)
	}
}
```

### 2. Or Do you mean HTTP-client on nbio? 
We have not support HTTP-Client on nbio. Usually, the net/http should be enough, and it's difficult to implement the HTTP-CLient on nbio because of the things about connection pool and reconnecting. And it would cost another long term to make it running stable.

**Comment by tigrannajaryan** [comment]
Thanks for quick response.

I mean HTTP request headers on client side.

I may be misunderstanding something, but I thought this example shows how to create client WebSocket using nbio: https://github.com/lesismal/nbio/blob/master/examples/echo/client/client.go

If that is true then I wonder if it is possible to send HTTP request headers before the connection is upgraded to WebSocket.

**Comment by lesismal** [comment]
> Thanks for quick response.
> 
You are welcome!

> I mean HTTP request headers on client side.
> 
> I may be misunderstanding something, but I thought this example shows how to create client WebSocket using nbio: https://github.com/lesismal/nbio/blob/master/examples/echo/client/client.go
> 
This is not a websocket example, it's only a tcp echo example.

> If that is true then I wonder if it is possible to send HTTP request headers before the connection is upgraded to WebSocket.

So you mean a nbio-websocket client?
We haven't supported that yet but may put it on the plan. Would you please share what you want to use it for?

**Comment by tigrannajaryan** [comment]
>This is not a websocket example, it's only a tcp echo example.

@lesismal OK, thanks, I misunderstood then. 

>So you mean a nbio-websocket client?
>We haven't supported that yet but may put it on the plan. Would you please share what you want to use it for?

Yes, I mean a nbio-websocket client. I am implementing a system where I need both a client and a server in one process (think WebSocket proxy that needs to receive a large number of websocket connecitons, do some processing then send all data via an outgoing websocket connection to a different system) and I wanted to use nbio both for client and server functionality. No problem, I will use gorilla for the client portion for now, I just did not want to use 2 different WebSocket libraries in one Go process. I am still planning to use nbio for the server-side since I need to be able to handle a very large number of incoming connections.

**Comment by tigrannajaryan** [comment]
I will close this for now since there is nothing to do here (other than perhaps think if you would like to add Websocket client capabilties to nbio in the future).

**Comment by tigrannajaryan** [comment]
Thank you again for looking.

**Comment by lesismal** [comment]
> I will close this for now since there is nothing to do here (other than perhaps think if you would like to add Websocket client capabilities to nbio in the future).

I also spent lots of time for [arpc](https://github.com/lesismal/arpc) these two weeks.
nbio-websocket-client souds like a good feature, I will evaluate its difficulty and may make a plan after some tidy job about arpc.

Thank you again for this feature issue!

**Comment by lesismal** [comment]
Hi @tigrannajaryan, a new version that supports HTTP Client and Websocket Dialer/Client has been published already:

https://github.com/lesismal/nbio/releases/tag/v1.2.4

Welcome to try it and feedback if possible! 😄

**Comment by tigrannajaryan** [comment]
@lesismal thanks a lot for adding it. Unfortunately I already implemented the client portion using ws gorilla and no longer have an immediate need to use nbio for client side, so I will not be able to try it right now.

However, I will keep in mind that nbio now has ws client capabilities when I need it next time. :-)

Thank you again for looking into this.

**Comment by lesismal** [comment]
> Unfortunately I already implemented the client portion using ws gorilla and no longer have an immediate need to use nbio for client side, so I will not be able to try it right now.

That's all right, and welcome to try it in the future! 😄 

You are welcome!
Also thank you for this issue, It reminds me to add this feature. 😄
