### ISSUE TITLE
Minimal websocket example

### ISSUE THREAD

**Issue by hellochenwang** [lesismal/nbio#88]
Hi,

I'm trying to write a minimal websocket example but I can't seem to get it working.

Here's the code:
```
package main

import (
	"net"
	"net/http"

	"github.com/lesismal/nbio/nbhttp/websocket"
)

func main() {
	var wsHandler WSHandler
	server := &http.Server{Addr: "0.0.0.0:8081", Handler: wsHandler}

	ln, err := net.Listen("tcp", "0.0.0.0:8081")
	if err != nil {
		panic(err)
	}

	err = server.Serve(ln)
	if err != nil {
		panic(err)
	}
}

type WSHandler struct {
}

func (h WSHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	defer func() {
		if err := recover(); err != nil {
			println(err)
		}
	}()

	upgrader := websocket.NewUpgrader()
	upgrader.CheckOrigin = func(r *http.Request) bool {
		return true
	}

	conn, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		println(err)
		return
	}
	wsConn := conn.(*websocket.Conn)
	// wsConn.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
	// 	// echo
	// 	c.WriteMessage(messageType, data)
	// })
	wsConn.OnClose(func(c *websocket.Conn, err error) {
		println("OnClose")
	})
	println("OnOpen")
}
```

When I try to establish a connection, it prints:
```
2021/09/03 02:01:37 http: response.WriteHeader on hijacked connection from github.com/lesismal/nbio/nbhttp/websocket.(*Upgrader).returnError (upgrader.go:517)
2021/09/03 02:01:37 http: response.Write on hijacked connection from fmt.Fprintln (print.go:265)
(0xa5cfc0,0xc000142f30)
```

Also, the following code gives error message "wsConn.OnMessage undefined (type *websocket.Conn has no field or method OnMessage)"
```
	wsConn.OnMessage(func(c *websocket.Conn, messageType websocket.MessageType, data []byte) {
		// echo
		c.WriteMessage(messageType, data)
	})
```

**Comment by lesismal** [comment]
`nbio/nbhttp/websocket` does not support std's `net/http server`.

It is designed for nbio(poller with async io interface, support async-streaming-parsing).

Here is websocket server example:
https://github.com/lesismal/nbio/blob/master/examples/websocket/server/server.go

More examples:
https://github.com/lesismal/nbio/tree/master/examples

**Comment by lesismal** [comment]
All the WebSocket frameworks based on std need to serve each connection with one or more goroutines, which would cost lots of goroutines when there are lots of connections, problems about mem/gc/schedule/stw comes with the huge number of goroutines.

nbio is designed to solve the problems of 100k/1000k, so we implemented async-io and streaming parsing, which means we can't keep it fully compatable with std.

**Comment by hellochenwang** [comment]
It makes sense. Thanks very much for the answer. I am able to run your sample server.

**Comment by lesismal** [comment]
> It makes sense. Thanks very much for the answer. I am able to run your sample server.

You are welcome!:smile:
