### ISSUE TITLE
I want to write proxy server like shadowsockslibev,low memory use 6~7MB? 

### ISSUE THREAD

**Issue by leekey1** [lesismal/nbio#91]
source:

import (
	"fmt"

	"github.com/lesismal/nbio"
	"strconv"
)

type niosess struct {
	isserver bool
	step int
	parterconn *nbio.Conn
}

func closeConn(c *nbio.Conn){

	if session := c.Session(); session != nil {

		sess := session.(*niosess)
		fmt.Println("RemoteAddr ",c.RemoteAddr(),sess.isserver)

		if sess.isserver {
			if sess.parterconn != nil {
				sess.parterconn.SetSession(nil)
				sess.parterconn.Close()
			}

			c.SetSession(nil)
			c.Close()
		} else {
			fmt.Println("is remote close")
			closeConn(sess.parterconn)
		}

	}else{
		fmt.Println("non sess close")
		c.Close()
	}
}

func Startserver(){

	g := nbio.NewGopher(nbio.Config{
		Network:            "tcp",
		Addrs:              []string{":8888"},
		MaxWriteBufferSize: 4 * 1024,
		ReadBufferSize:2048,
		NPoller:1,
		MinConnCacheSize:128,
		Backlog:128,
	})

	//isClient := true

	g.OnOpen(func(c *nbio.Conn)  {
		fmt.Println("OnOpen:", c.RemoteAddr().String())
		if session := c.Session(); session != nil {
			// remote open

		} else{ // server
			sess := &niosess{
				isserver:true,
			}
			c.SetSession(sess)
		}
	})

	g.OnClose(func(c *nbio.Conn, err error){
		fmt.Println("OnClose:", c.RemoteAddr().String())
		closeConn(c)
	})

	g.OnData(func(c *nbio.Conn, data []byte) {
		//	c.Write(append([]byte{}, data...))

		if session := c.Session(); session != nil {

			sess := session.(*niosess)
			if sess.isserver {

				fmt.Println("isserver len",len(data),sess.step)

				if sess.step == 0 {
					resp := []byte{5,0}
					c.Write(resp)
					sess.step = 1
				} else if sess.step == 1 {
					data[1] = 0
					nr := len(data)
					hostb := data[3:nr-2]
					portb := data[nr-2:nr]

					isIp := data[3] == 1

					host := ""
					if !isIp {
						host = string(hostb[1:])
					} else{
						host = fmt.Sprintf("%d.%d.%d.%d", hostb[1], hostb[2],hostb[3],hostb[4])
					}

					p := int(portb[0]) * 256 + int(portb[1])

					addr := host+":"+strconv.Itoa(p)
					fmt.Println("host:port",host+":"+strconv.Itoa(p))

				        nbConn, err := nbio.Dial("tcp", addr )
				        if err != nil {
					        fmt.Println("Dial failed: ", err)
					        closeConn(c)
					        return
				        }
        
				        remotesess := &niosess{
					        isserver:false,
					        parterconn:c,
					        step: 5,
				        }
        
				        sess.parterconn = nbConn
				        nbConn.SetSession(remotesess)
				        c.SetSession(sess)
        
				        g.AddConn(nbConn)

					c.Write(data)
					sess.step = 2

				} else {
					if sess.parterconn != nil {
						sess.parterconn.Write(data)
					} else{
						closeConn(c)
					}
				}

			}else{ // is remote

				fmt.Println("remote len",len(data))

				if sess.parterconn != nil {
					sess.parterconn.Write(data)
				} else {
					fmt.Println("parterconn nil")
					closeConn(c)
				}

			}

		} else {
			fmt.Println("non sess recv",data)
		}

	})

	err := g.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}
	defer g.Stop()

	g.Wait()

}

this code use memory over 12MB. how to upgrade to use low memory?

**Comment by lesismal** [comment]
Please provide a full example including client, then I could try it.

**Comment by leekey1** [comment]
### Env

`go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/anjung-geun/Library/Caches/go-build"
GOENV="/Users/anjung-geun/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/anjung-geun/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/anjung-geun/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tr/hfh08tqj59l_zzzv3xznxkfw0000gn/T/go-build2743322910=/tmp/go-build -gno-record-gcc-switches -fno-common"`


### sever.go
// GO111MODULE=off go run server.go

`package main



  import (
	  "fmt"
	  "github.com/lesismal/nbio"
	  "strconv"
  )
  
  
  type niosess struct {
	  isserver bool
	  step int
	  parterconn *nbio.Conn
	  sdata []byte
  }

func closeConn(c *nbio.Conn){

	if session := c.Session(); session != nil {

		sess := session.(*niosess)
		fmt.Println("RemoteAddr ",c.RemoteAddr(),sess.isserver)

		if sess.isserver {
			if sess.parterconn != nil {
				sess.parterconn.SetSession(nil)
				sess.parterconn.Close()
			}

			c.SetSession(nil)
			c.Close()
		} else {
			fmt.Println("is remote close")
			closeConn(sess.parterconn)
		}

	}else{
		fmt.Println("non sess close")
		c.Close()
	}
}

func isRemotetls() bool {
	return false
}

func Startserver(){


	g := nbio.NewGopher(nbio.Config{
		Network:            "tcp",
		Addrs:              []string{":8888"},
		MaxWriteBufferSize: 4 * 1024,
		ReadBufferSize:2048,
		NPoller:1,
		MinConnCacheSize:128,
		Backlog:128,
	})

	//isClient := true

	g.OnOpen(func(c *nbio.Conn)  {
		fmt.Println("OnOpen:", c.RemoteAddr().String())
		if c.Session() == nil {
			// server
			sess := &niosess{
				isserver:true,
			}
			c.SetSession(sess)
		}
	})

	g.OnClose(func(c *nbio.Conn, err error){
		fmt.Println("OnClose:", c.RemoteAddr().String())
		closeConn(c)
	})


	g.OnData(func(c *nbio.Conn, data []byte) {
		//	c.Write(append([]byte{}, data...))

		if session := c.Session(); session != nil {

			sess := session.(*niosess)
			if sess.isserver {

				fmt.Println("isserver len",len(data),sess.step)

				if sess.step == 0 {
					resp := []byte{5,0}
					c.Write(resp)
					sess.step = 1
				} else if sess.step == 1 {
					data[1] = 0
					nr := len(data)
					hostb := data[3:nr-2]
					portb := data[nr-2:nr]

					isIp := data[3] == 1

					host := ""
					if !isIp {
						host = string(hostb[1:])
					} else{
						host = fmt.Sprintf("%d.%d.%d.%d", hostb[1], hostb[2],hostb[3],hostb[4])
					}

					p := int(portb[0]) * 256 + int(portb[1])


					addr := host+":"+strconv.Itoa(p)
					fmt.Println("host:port",host+":"+strconv.Itoa(p))

					nbConn, err := nbio.Dial("tcp", addr )
					if err != nil {
						fmt.Println("Dial failed: ", err)
						closeConn(c)
						return
					}

					remotesess := &niosess{
						isserver:false,
						parterconn:c,
						step: 5,
					}

					sess.parterconn = nbConn
					nbConn.SetSession(remotesess)
					c.SetSession(sess)

					g.AddConn(nbConn)

					c.Write(data)
					sess.step = 2




				} else {
					if sess.parterconn != nil {
						sess.parterconn.Write(data)
					} else{
						closeConn(c)
					}
				}


			}else{ // is remote

				fmt.Println("remote len",len(data))

				if sess.parterconn != nil {
					sess.parterconn.Write(data)
				} else {
					fmt.Println("parterconn nil")
					closeConn(c)
				}

			}

		} else {
			fmt.Println("non sess recv",data)
		}


	})

	err := g.Start()
	if err != nil {
		fmt.Printf("nbio.Start failed: %v\n", err)
		return
	}
	defer g.Stop()

	g.Wait()


}



func main(){
	Startserver()
}`

### client.go
// GO111MODULE=off go run client.go

`package main

import (
	"golang.org/x/net/proxy"
	"github.com/eycorsican/go-tun2socks/core"
	"fmt"
	"net"
	"time"
	"math"
	"sync/atomic"
)

// GO111MODULE=off go run client.go
func main()  {

	var ok uint64 = 0
	var fail uint64 = 0
	var total uint64 = 0
	host := "qq.com"

	iprecords, _:= net.LookupIP(host)

	ip := iprecords[0]

	addr := fmt.Sprintf("%s:443",ip)


	buf := make([]byte, 4*1024)

	ch := make(chan string)

	for i := 0; i < 300; i++ {
		go func() {
			for i := 0; i < 300; i++ {
				dialer, err := proxy.SOCKS5("tcp", core.ParseTCPAddr("127.0.0.1", 8888).String(), nil, nil)
				if err != nil {
				//	fmt.Println("proxy socks5 err", err)
					atomic.AddUint64(&fail, 1)
					fmt.Println("total ", total, "ok:", ok, "fail:", fail)
					continue
				}

				c, err := dialer.Dial("tcp", addr)
				if err != nil {
				//	fmt.Println("proxy socks5 Dial err", err)
					fmt.Println("total ", total, "ok:", ok, "fail:", fail)
					atomic.AddUint64(&fail, 1)
					continue
				}

				bytes := []byte("GET / HTTP/1.1\r\nHost: baidu.com\r\n\r\n")

				_, err = c.Write(bytes)
				if err != nil {
					atomic.AddUint64(&fail, 1)
					fmt.Println("total ", total, "ok:", ok, "fail:", fail)
					c.Close()
					continue
				}
				_, err = c.Read(buf)
				if err != nil {
					atomic.AddUint64(&fail, 1)
					fmt.Println("total ", total, "ok:", ok, "fail:", fail)
					c.Close()
					continue
				} else {
					//fmt.Println("buf",n,buf[0:n])
					c.Close()
				}
				atomic.AddUint64(&ok, 1)
				atomic.AddUint64(&total, 1)

				fmt.Println("total ", total, "ok:", ok, "fail:", fail)
				if total == 300 * 300 {
					ch <- "down"
				}
				//time.Sleep(time.Millisecond * 200)
			}

		}()

	}


	for {
		select {
		case <-ch:
			fmt.Println("final total ", total, "ok:", ok, "fail:", fail)
			return
		default:
			time.Sleep(time.Duration(math.MaxInt64))
		}
	}







}
`
memory image capture with 'Mac Activity Monitor'

<img width="774" alt="Screen Shot 2021-09-18 at 12 25 53 PM" src="https://user-images.githubusercontent.com/12266176/133872432-8af469b0-5619-4bdb-95bc-166e91bb00d6.png">

**Comment by lesismal** [comment]
I'll try it.

BTW, if you reply with markdown would be better.

**Comment by lesismal** [comment]
I tried your example on ubuntu:

![image](https://user-images.githubusercontent.com/40462947/133873407-dd4b75a5-9cb1-449c-a177-244d8b662c2c.png)

nbio is mainly used on Linux, there are no promises for mac. You can try on Linux.

**Comment by lesismal** [comment]
Shall we close this issue?

**Comment by leekey1** [comment]
thank your answer..
