### ISSUE TITLE
autobahn tests failures

### ISSUE THREAD

**Issue by acgreek** [lesismal/nbio#94]
9.* tests appear to timeout

**Comment by lesismal** [comment]
try latest: https://github.com/lesismal/nbio/releases/tag/v1.2.3

**Comment by lesismal** [comment]
strange, `&syscall.EpollEvent{Fd: int32(fd), Events: epollEventsRead}` performs different with `&syscall.EpollEvent{Fd: int32(fd), Events: uint32(epollEventsRead | p.g.epollMod)}`, but `p.g.epollMod` is 0.

**Comment by acgreek** [comment]
fixed
